### ISSUE TITLE
Normalize spaces name before creating the the folder

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10118]
We need to normalize the spaces name before we create the folder.
To long name or names with illegal characters would cause issue.

**Comment by fmoc** [comment]
We should indeed sanitize (and potentially truncate) the strings locally.

**Comment by phil-davis** [comment]
And any algorithm that maps some "string about the space" (space name or whatever) to "local folder name"  has to result in either:
- unique folder name for each space, or
- some folder hierarchy that makes sure each local path to a space is unique

And the generated local paths, naming, needs to be understandable by ordinary users when they are opening the folders in the file explorer of their local operating ssystem.

**Comment by fmoc** [comment]
> unique folder name for each space

Collisions are already detected and resolved by appending numbers, e.g., `(1)`, `(2)`. This is going to remain for now, since the only (globally unique (well reasonably unique)) identifier we have is some sort of UUID. We need to use some user-friendly description (I try to avoid the term identifier since it might imply some uniqueness).

The server folks suggested to initialize the sync folder names with a (possibly upcoming) user-assignable server alias that is itself initialized with the original space name.
