### ISSUE TITLE
[QA] Missing features in Wizard

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10266]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Some features are missing in the new wizard 3.0
Rewrite of the wizard: https://github.com/owncloud/client/issues/9249

### Steps to reproduce the issue

1. Click Add a new account
2. Add a server address
3. Log in
4. Check the sync options available

### Screenshots

<img width="749" alt="Screenshot 2022-11-11 at 11 22 35" src="https://user-images.githubusercontent.com/49001702/201322245-0e2d651d-2882-4cee-ab7d-c41400ab55b2.png">

### Expected behavior

The features in wizard 2.11 are the same as in wizard 3.0

### Actual behavior

Option to Ask for confirmation and Choose what to sync are missing in the new wizard 3.0
Tested in mac 3.0.0 beta1

**Comment by TheOneRing** [comment]
Its moved to the manual setup. We start the folder wizard now if a manual setup was requested.

**Comment by michaelstingl** [comment]
Removed from Wizard, because folder limit and external storage are global settings, and not "per account". Can be solved with (1) choosing manual setup, then (2) configure in Settings, then (3) add folder sync connections where those settings are applied.
![CleanShot 2022-11-11 at 11 42 34@2x](https://user-images.githubusercontent.com/214010/201324538-bef6a3c5-afb8-4b83-8865-c0179b273415.png) | ![CleanShot 2022-11-11 at 11 42 29@2x](https://user-images.githubusercontent.com/214010/201324565-26a8e81e-f631-4a43-8e55-552dafdfcd76.png) | ![CleanShot 2022-11-11 at 11 42 47@2x](https://user-images.githubusercontent.com/214010/201324569-a8dff8dd-90bf-4f3f-b1f4-0b7983c873f0.png)
-- | -- | --
2.11.1 account setup | 3.0 advanced options | 3.0 global settings

Needs doc update

**Comment by fmoc** [comment]
Wrong status assigned, this should be closed as wontfix.

**Comment by jnweiger** [comment]
Needs at least documentation.
Better solution would be to add a hint to the UI, how to reach the global settings.

**Comment by fmoc** [comment]
We could add another label within the advanced settings on the final wizard page which hints to the "new" location. Please open an issue for this.

**Comment by michaelstingl** [comment]
Docs issue:
- https://github.com/owncloud/docs-client-desktop/issues/321
