### ISSUE TITLE
[QA] Linux AppImage update causes a crash

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10552]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Linux AppImage update causes a crash

### Steps to reproduce the issue

Update from qa-3.2.0.10260-x86_64.AppImage to qa-3.2.1.10301-rc1-x86_64.AppImage

### Screenshots

No screenshot

### Expected behavior

Successful update

### Actual behavior

Crash without a crash number

**Comment by fmoc** [comment]
The crash is within libappimageupdate/libzsync2/cpr. We seem to have received some Sentry reports, too:

- https://owncloud.sentry.io/issues/3948475832/
- https://owncloud.sentry.io/issues/3937788005/

Most of the [issues found by a querying for `cpr`](https://owncloud.sentry.io/issues/?project=79001&query=is%3Aunresolved+cpr&referrer=issue-list&statsPeriod=14d) are related to this problem.

This is a dependency issue and might be fixed by updating. I'll try to find out why we are crashing.

**Comment by michaelstingl** [comment]
@fmoc workaround available? Or RC2 with a fix?

**Comment by HanaGemela** [comment]
Update from owncloud 3.0.0 to 3.2.1 rc2 works on Ubuntu 22.04
