### ISSUE TITLE
request for enterprise use: possibility to manually recover locally deleted files

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#1069]
Hello,

For enterprise use of owncloud I think it is mandatory to make sure that data is _NEVER_ lost. The backup and trashbin concept on the server may not always prevent this if a file is lost before reaching the server - consider for example: https://github.com/owncloud/mirall/issues/1014

No matter what we will do, there will always be a way of running into a problem with a similar effect - data loss on the client.

I understand that there was a discussion about using local OS trashbin already on the list owncloud@kde.org and here: https://github.com/owncloud/mirall/issues/528

I understand that proper integration with OS trashbin is maybe complex and I am not asking for this.

However, independently of OS trashbin, I would consider an option of moving files to a local trash directory in the local sync folder - as an extra security protection to allow a user to restore a file completely manually. This directory would need to be cleaned up periodically.

**Comment by MTRichards** [comment]
Just had a request on this so wanted to bring it back up front for feature requests.

**Comment by MTRichards** [comment]
@danimo @dragotin what do you think these days about this request? It gets complex across filesystems and OSes, for example...

**Comment by michaelstingl** [comment]
@moscicki If I delete a local file, that has been never fully transferred to the server, and it is not in the OS trashbin for any reason, how can it be transferred to a local `oC_trashbin` folder? As I understood, ownCloud client can only react after the delete event happened on the file system. Otherwise the ownCloud client would need to create something like a hidden shadow-copy at the moment the file gets added to the local sync folder. But there are 3rd party solutions or even features in modern OS that can do this much better.

**Comment by ogoffart** [comment]
There is now an hidden option to move the file to the trash bin.  (since 2.5 i think) 

`moveToTrash` as decribed in https://doc.owncloud.org/desktop/2.5/advancedusage.html
