### ISSUE TITLE
Username field is garbled, cannot edit the contents, so cannot login

### ISSUE THREAD

**Issue by flatpack** [owncloud/client#10856]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I installed the Owncloud client on my Ubuntu 22.04 linux desktop, following the advice [here](https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/).

I started the owncloud client for the first time and filled in my server url and my username,password credentials.

The client starts and the Login Required dialog appears.  The Username field does not contain my Username (it looks like a random string of alphanumeric+hyphen characters). It is greyed out so cannot be edited. Adding my password does not work (the username in the text box is wrong and cannot be changed)

Attempting to login using the Account button also leads to the Login Required dialog and the same problem.

Since I cannot login to the server, I cannot use owncloud to sync files, as intended.

### Expected behavior

I expected that entering my login details would allow me to login to the server via the owncloud client, and that files would sync automatically (as they do on my other devices).

### Steps to reproduce the issue

1. Install owncloud client on a new install of Lubuntu 22.04.2 as per the recommended instructions [here](https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/).
2. Start owncloud desktop app as normal.
3. Fill in the owncloud server url and user credentials.
4. Check if you can log in OK.

### Screenshots

![screenShot2](https://github.com/owncloud/client/assets/4448472/26b3ea55-21b0-43fb-a61b-d5e18e38b60b)

### Logs

N/A

### Client version number

ownCloud 4.0.0.10896 [74fef3](https://github.com/owncloud/client/commit/74fef3a70c2c7bb95598574e31d30bcade9a4eb6)
Libraries Qt 5.15.2, OpenSSL 3.0.2 15 Mar 2022
Using virtual files plugin: suffix
ubuntu-5.19.0-41-generic

### Desktop environment (Linux only)

Linux DESKTOP 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Client package version and origin (Linux only)

Installed from https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/ via apt package manager: sudo apt install owncloud-client

### Server information

N/A

**Comment by maxdwit** [comment]
Verified with ubuntu 22.04 using owncloud-client=4.0.0+oc-1089 from repositories. 
Same behaviour. After completing the Wizard above mentioned screenshot with another authentication request pops up.
Can't be discarded, any entry there is just ignored.

**Comment by michaelstingl** [comment]
> Verified with ubuntu 22.04 using owncloud-client=4.0.0+oc-1089 from repositories.

@maxdwit Provided information isn't sufficient to solve the problem. Please share logs, including HTTP requests and responses or a test account.

You could upload here:
- https://cloud.owncloud.com/index.php/s/FkrXKsDFPNGYZwm

Internal link for the team:
-  https://cloud.owncloud.com/index.php/f/6008303

More information how to capture log files:
- https://doc.owncloud.com/desktop/4.0/appendices/troubleshooting.html#obtaining-the-desktop-app-log-file

**Comment by maxdwit** [comment]
@michaelstingl  please provide an email for direct contact. Can provide access tomorrow in the morning.

**Comment by dahlecr** [comment]
I am experiencing the same problem and can provide additional information. The problem only occurs when using a LDAP user, in my case Owncloud is configured using Active Directory as authentication source.

As shown in the OP's screenshot, the login prompt with the username is grayed out, containing a long string. It's the same string which is listed as username for Active Directory users. The LDAP user authentication plugin however is configured, to use samaccountname as login username, not the UID string. Since username is grayed out (you cannot change it) there is no way to login for you. This appears to be a bug with the Desktop Client, since the client persists using the string listed as username.

`{"reqId":"46f5a601-4391-42dd-8893-a26e2d9c8479","level":2,"time":"2023-05-25T19:54:25+00:00","remoteAddr":"203.0.113.2","user":"--","app":"core","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Login failed: '69A910FA-375F-4B77-885B-49EF42538845' (Remote IP: '203.0.113.2')"}`

**Comment by stefanost67** [comment]
I can confirm I experience the same problem.

**Comment by TheOneRing** [comment]
We where able to reproduce the error.
We plan to release a fix with 4.1 soonish.

**Comment by HanaGemela** [comment]
Passed in ownCloud 4.1.0.11119-daily20230531
