### ISSUE TITLE
Sync Mac OS (HFS+) Extended Attributes

### ISSUE THREAD

**Issue by tsunagari** [owncloud/client#1159]
Labels (previus mac os versions) or tags (Mac os Mavericks) shoud be sync so all computer can retrive files by labels or tags.
![capture decran 2013-11-13 a 19 25 32](https://f.cloud.github.com/assets/5272830/1534143/08b392b2-4c91-11e3-9e65-6cfa66a182fe.png)
![capture decran 2013-11-13 a 19 26 05](https://f.cloud.github.com/assets/5272830/1534146/1aa09236-4c91-11e3-864b-10c358071128.png)

**Comment by sehlen** [comment]
I am interested in this feature as well and I might do some work on it. I had a look at the codebase but since I didn't find any overview documents on how the sync client works, I found it hard to get started. I can see two possible solutions: 

1. probably super simple but might not be wanted and might not scale very well: you can use xattr to write metadata to a file:
```
  xattr -lrx . > .metadata
```
then sync the file and use xattr to set the metadata again.
(You have to extract the values from the file/db and set it file-by-file).
One could have one central file/db or one per directory or so. 
A diff would reveal the metadata changes that have to be applied. 

2. probably better: set the extended attributes in the same way as the other metadata directly while syncing, if possible. 

3. A combination of the two is also possible, I guess. E.g. use the xattr mechanism but use the csync db that already exists (if that's what's currently being used to record the sync state).

Can someone of the developers maybe give me short intro how the repo is structured and how the sync client works to get me started? Did I miss any documentation that is already available?

**Comment by moscicki** [comment]
This is an important feature, especially for Mac users.

Could we please start by specifying the protocol extensions needed for this feature?
C.f. https://github.com/owncloud/client/issues/3199

**Comment by brunoc68** [comment]
I am migrating a Mac user from Dropbox to Owncloud.
Actually we noticed this issue ; if not solved, we will have to stay with Dropbox.
Very simple : some software - like Sage in our case - uses extended attributes with their files. If these attributes are not kept, the files are synchronized but become totally unusable with the software.
Concerning the debate bug vs feature, either Owncloud supports MacOS users and it is a bug, or it is a feature and you can not continue to state that Owncloud supports MacOS.

**Comment by fablarosa** [comment]
Brunoc68 is definitely right, ownCloud should sync extended attributes.

**Comment by progmem64** [comment]
+1, but i think its never going to happen since the issue was opened 4 years ago, a shame

**Comment by guruz** [comment]
FYI this is what Dropbox syncs: https://help.dropbox.com/en-us/installs-integrations/sync-uploads/extended-attributes

**Comment by vkoechli** [comment]
Any news on this? I use owncloud to sync directories between my Macs and this destroys, in addition to any custom icons, all Finder aliases, as the alias property is stored in com.apple.FinderInfo extended attribute. So I figure syncing extended attributes would be really important for a lot of users.

**Comment by DeepDiver1975** [comment]
Requires change on server side. Will not happen on server(s) and as a result not in the client -> close
