### ISSUE TITLE
Link to "Report an issue"

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#1251]
Many applications have a "Report an issue" button.
It would be convenient with a "Report an issue" link in the about section in the General tab pointing to https://github.com/owncloud/mirall/issues

**Comment by pascalBokBok** [comment]
There is a "Built from git revision xxx" that can be clicked in the general tab. Having a "Public reported issues" link could also be there :smile:

**Comment by pascalBokBok** [comment]
If the "Report bug" button includes the version information in the resulting url then I think my friend @guruz would be happy :-)
Example: https://github.com/owncloud/client/issues/new?title=MyNewBugreport&body=VersionXYZ

**Comment by guruz** [comment]
@pascalBokBok Indeed :-D

**Comment by Kawohl** [comment]
@guruz what is the way to go here?
Just start with a clickable link under: "Built from git revision"? As a start or should we go completely with a branding option? (I could use a hint or two then, to point me to the configs ;-) )

**Comment by guruz** [comment]
Yes, you can make a clickable link :)
Instead of a branding option, you could check if the theme name is "ownCloud" as I doubt other OEM partners want this link.
Our idea is now to direct users first to central.owncloud.org instead of github.
You could just append your link text to the label from C++ side

**Comment by SamuAlfageme** [comment]
👍
