### ISSUE TITLE
Connection Error notice does not vanish until status window is reopened

### ISSUE THREAD

**Issue by butonic** [owncloud/client#1565]
In the status window the client correctly updates the server connection status ui elements when the client loses the connection and when he reconnects.

When the connection is lost a notification is shown aboe the list of server connections. that message should disappear as well when the client has reconnected. Everything is workin in the background but the user has to close and reopen the dialog to make the notice go away.

**Comment by dragotin** [comment]
@lmaestro can you pls. verify this with current version? Thx.

**Comment by lmaestro** [comment]
It is fixed in version 1.8.0-nightly20150122 (build 1912) when the connection is lost, the setting window shows:
![screen shot 2015-01-22 at 1 28 53 pm](https://cloud.githubusercontent.com/assets/4689430/5855701/6953873e-a23b-11e4-88d2-f83e62757a31.png) 
And then when the connection is back:
![screen shot 2015-01-22 at 1 30 41 pm](https://cloud.githubusercontent.com/assets/4689430/5855721/a91e6956-a23b-11e4-9cea-58236ab7fcd4.png)
![screen shot 2015-01-22 at 1 31 49 pm](https://cloud.githubusercontent.com/assets/4689430/5855723/ac7d4cca-a23b-11e4-894a-e5a9a2b12865.png)
