### ISSUE TITLE
System Proxy not always detected

### ISSUE THREAD

**Issue by unclejamal3000** [owncloud/client#1645]
### Expected behaviour
Proxy should be used if one is configured in system.

![2014-03-28 14_35_35-owncloud](https://cloud.githubusercontent.com/assets/6795043/2629505/2ec879bc-be39-11e3-97cf-1516233e0416.png)

### Actual behaviour
ownCloud Client does not always detects the system proxy (no static configuration -> automatic recognition and configuration script is used on my workstation). These settings are deployed with the Windows AD group policy and can not be changed permanently. 
I didn't find a way to reproduce it but sometimes the client tries to connects directly to the OC server. Sometimes it helps to restart the client, sometimes I have to remove the check box for automatic recognition in the Internet Explorer settings.

![2014-03-28 14_34_00-einstellungen fr lokales netzwerk](https://cloud.githubusercontent.com/assets/6795043/2629508/47a3d5f8-be39-11e3-9655-7af2ba0e1f72.png)

Browser access (IE, Firefox, Chrome) is working all the time. So I will exclude the possibility of a general system misconfiguration.

### Steps to reproduce
I don't know.

### Client configuration
Client version:
1.5.3 (build 2523)
Operating system:
Windows 7 SP1 x64
OS language:
English

### Logs
I don't see proxy related data in the log file.

**Comment by danimo** [comment]
Ok, there are two different issues here:

1. System proxy settings are not respected at all on Ubuntu: This is a Qt issue (the distro needs to provide packages with Qt using libproxy). I am not sure if this feature is available for Qt 4, but some distros have chosen to backport it. Ideally, they should migrate to Qt 5. This is tracked in https://github.com/owncloud/client/issues/2486.

2. Is a Windows-specific bug: Because Proxy auto-detection can take quite a long time, the result gets cached locally. This is tracked in https://github.com/owncloud/client/issues/2695.

This this bug is a duplicate, and mixing both issues, I'll cose it. Please track the respective dedicated reports.
