### ISSUE TITLE
Specify what chars are not syncable in the error message

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#1733]
Try and sync a file name containing a colon, for example "Re: some email.eml".
The sync client will show the message: "File contains invalid characters that can not be synced cross platform".

It would be good to improve that error message to show a list of unsupported characters as a hint for the user.

This was requested here: https://github.com/owncloud/core/issues/8217

CC @ferdiga

**Comment by Dianafg76** [comment]
@PVince81 Any news about this?

**Comment by PVince81** [comment]
No

**Comment by brevilo** [comment]
It would be even better to point out clearly that "can not be synced cross platform" actually means no sync at all, regardless of the platforms used. "Cross platform" in that context is meant as an explanation, not a condition.

Thanks.

**Comment by ferdiga** [comment]
### Steps to reproduce
1. install owncloud client on ubuntu 15.04
2. define external local file on server
3. sync desktop

### Expected behaviour
the sync should 
- report a better error message (which file and character)

I checked the directory structure with the following py script which does nto return an error


# -*- coding: utf-8 -*-
import os
import sys

#walk_dir = "/home/strakosch"
walk_dir = "/home"
#walk_dir = "/var/www/owncloud_data"

for root, subdirs, files in os.walk(walk_dir):
#    print root
    string=root
    try:
        string.decode('utf-8')
#        print "string is UTF-8, length %d bytes" % len(string)
    except UnicodeError:
        print "string is not UTF-8"

    chars = set(':?*”><|') # invalid chars
    if any((c in chars) for c in string):
        print('Found in %s' % (string))

        

### Actual behaviour
Tell us what happens instead (IP changed addres)

{"reqId":"Gkx3Su3Exi0UmBHxImU1","remoteAddr":"1.1.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 File name contains at least one invalid character\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\InvalidPath\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/custompropertiesbackend.php(100): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('strakosch\\\/home\\\/...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropertyStorage\\\/Plugin.php(86): OC\\\\Connector\\\\Sabre\\\\CustomPropertiesBackend->propFind('strakosch\\\/home\\\/...', Object(Sabre\\\\DAV\\\\PropFind))\\n#2 [internal function]: Sabre\\\\DAV\\\\PropertyStorage\\\\Plugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\File))\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1016): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(936): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OC\\\\Connector\\\\Sabre\\\\File))\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('strakosch\\\/home\\\/...', Array, 1)\\n#7 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":112}","level":4,"time":"2015-11-26T21:26:33+00:00"}


### Server configuration
**Operating system**:
Debian 8
**Web server:**
apache2                               2.4.10-10+deb8u1
**Database:**
mariadb-server                        10.0.22-0+deb8u1

**PHP version:**
php5                                  5.6.14+dfsg-0+deb8u1 
**ownCloud version:** (see ownCloud admin page)
8.2.1
**Updated from an older ownCloud or fresh install:**
updated from 8.1.1
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - documents: 0.11.0
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - files_w2g: 0.8.1.0
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - updater: 0.6
Disabled:

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
-- public keyword is unknown in 8.2.1

{                                                                                                                                                                                                                                                                        
    "system": {                                                                                                                                                                                                                                                          
        "instanceid": "ocde8d3204fb",                                                                                                                                                                                                                                    
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                 
        "datadirectory": "\/var\/www\/owncloud_data",                                                                                                                                                                                                                    
        "dbtype": "mysql",                                                                                                                                                                                                                                               
        "version": "8.2.1.4",                                                                                                                                                                                                                                            
        "dbname": "owncloud",                                                                                                                                                                                                                                            
        "dbhost": "localhost",                                                                                                                                                                                                                                           
        "dbtableprefix": "oc_",                                                                                                                                                                                                                                          
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                       
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                                                                                                                                                                                                                   
        "installed": true,                                                                                                                                                                                                                                               
        "enable_previews": true,                                                                                                                                                                                                                                         
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 3,
        "share_folder": "\/Shared",
        "trusted_domains": [
            "service.chricar.at"
        ],
        "mail_from_address": "xenon",
        "mail_domain": "strakosch.at",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "false"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
local, Google Drive
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Chrome current
**Operating system:**
Ubuntu 15.04
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ferdiga** [comment]
see the error message of the desktop client
![bad request](https://cloud.githubusercontent.com/assets/6248560/11431063/8e5374a2-9490-11e5-813a-07887808519d.jpg)

**Comment by ogoffart** [comment]
https://github.com/owncloud/client/pull/5449

**Comment by SamuAlfageme** [comment]
[Full MS death-char list](https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx) is now explained in the `Activity` section:

![screenshot 2017-02-15 14 02 13](https://cloud.githubusercontent.com/assets/2644445/22975532/62c4bb00-f387-11e6-88fe-b009c7e972d6.png)
