### ISSUE TITLE
In »Activity«, keep errors at the top

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#1745]
Currently when you have errors, it’s very hard to find them in the activity feed because they could be buried down below.

Instead, errors should always be very first in the list. There should ideally be 3 sections (similar to the mobile clients):

* Errors
* In progress
* History (or different word)

In that order, because errors are the most important and probably need user action.

@dragotin @danimo @MTRichards

**Comment by dragotin** [comment]
I don't think it makes sense to clutter the sync protocol with "errors", or rather say "information about not synced files", on top because many users are using the list to verify their sync activity.

The most information that lines up as "information about not synced files" is about why files where ignored from the sync. Ignorings are often intentional and annoy people if these are displayed above their sync progress. OTOH we can not remove the list of ignored files and other problems completely as people sometimes need it to verify their settings. The list should be available, but not prominent.

I think the implementation in #4083 nicely builds that. Closing this.

**Comment by jancborchardt** [comment]
> many users are using the list to verify their sync activity.

An _assumption_ of how people use the current design (which needs to be improved) has little to do with how we need to change it.

What you said above seems to assume that most ownCloud users like to »verify their settings«. However a normal person just wants to sync files, and if there are issues like illegal characters they should be informed of that in one simple activity list.
