### ISSUE TITLE
Not using native tab design on OS X 10.10

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#1847]
Not native:
![screen shot 2014-06-04 at 20 31 23](https://cloud.githubusercontent.com/assets/878997/3178063/6e7c5258-ec16-11e3-91ac-4f6075e59801.png)

Native:
![screen shot 2014-06-04 at 20 31 43](https://cloud.githubusercontent.com/assets/878997/3178065/7b5524be-ec16-11e3-9b2c-40244c2a2e90.png)
![screen shot 2014-06-04 at 20 31 31](https://cloud.githubusercontent.com/assets/878997/3178064/7b54fe12-ec16-11e3-80de-5a1f5d5f22a0.png)

**Comment by guruz** [comment]
Depends https://github.com/owncloud/client/issues/2699

**Comment by shadone** [comment]
Doh, I didn't even see that I was mentioned here, sorry guys for not replying (bad email filtering on my side).

Yeah, Qt 5.4 makes it look slightly better, but still far from native. In my opinion "somebody" should make a native ownCloud client for OS X (I started doing it myself multiple times but never got to any usable state due to lack of time).

Since Qt 5.4 is binary compatible you could just download it and replace the frameworks (in the Frameworks folder; and don't forget the plugins folder too) in the owncloud application bundle.

**Comment by guruz** [comment]
@LukasReschke Can you try a recent nightly and check if it uses Qt 5.4 (should be in the log somewhere). Does it look better?

**Comment by LukasReschke** [comment]
Yep.
