### ISSUE TITLE
Be able to detect file updates (for upload) even if mtime didn't change

### ISSUE THREAD

**Issue by Lattenfrosch** [owncloud/client#1891]
Environment: Windows Sync client 1.5.4 (build 2686)

Let's say I have a TrueCrypt volume saved in OwnCloud. When the content of the volume changes and it is unmounted, only the hash sum of the file changes but the timestamp is preserved.

Now it seems that the sync client does not recognizes this hash sum change and would never update this file on the server.

I moved from Dropbox to OwnCloud and the Dropbox client could handle this. Would be a knockout criterion for me if this would not work anymore with OwnCloud...

Is this a known issue?
Any ideas how to solve it?

TIA

**Comment by ogoffart** [comment]
Since 1.8 we also check if the size is changed.

**Comment by guruz** [comment]
... 1.8 nightly builds can be found at http://download.owncloud.com/desktop/daily/

**Comment by dragotin** [comment]
@Lattenfrosch mind to test with a more recent client version, as we added the size check?

**Comment by guruz** [comment]
Please test with 2.0 beta, coming out in some days.

**Comment by phil-davis** [comment]
I did this with TrueCrypt at one time - set TrueCrypt to open and work in fixed size containers and not update any file meta-data (time stamps...). Then I stopped doing it because lots of backup tools... do not realize that the file has changed. Those TrueCrypt settings are for people who want extra security from someone watching their system for files that change - a TrueCrypt file can just look like some big binary blob that never has it time stamp changed or file size changed.
As @ssieb says, for this you need some file system notification event that you can receive to know that something happened. Then I guess you need to do some hash of the file content and compare to the server to see if there is any different content. Because the creation/modification dates and the file size will all be unchanged.
And to catch this in general then when ownCloud client starts up it would have to recalculate hashes of every file and compare to the server in case content had changed during "off-time" without it knowing.
I am just documenting here since I am a TrueCrypt user and have played with this stuff. Probably a lot of code and CPU and I/O and network traffic needed to always be guaranteed of good sync for this type of stuff.
