### ISSUE TITLE
Global Pause-Option

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#1971]
Is was wondering if it would be possible to implement something like a Global Pause-Button. At the moment it is possible to pause syncing for single Folders. The motivation behind this request is, that I sometimes tether my notebook with my phone an I don't want owncloud to sync during this time.

I know that I also could quit owncloud and restart it when I'm back on a "normal" connection, but having such a pause option would be quite handy. Maybe this Global Pause-Option could be configurable, like:

Pause for: 10min, 15min, 30min ... "resume manually"

Edit (@danimo): The implementation should also contain a possiblity to pause/unpause from the command line as to hook it up to scripts, see https://github.com/owncloud/client/issues/2760.

**Comment by te-online** [comment]
+1 for this enhancement. Might not be too hard to implement, as there already is an option to pause every single account.
If you regularly work while being on mobile data plan, you don't want owncloud to sync big stuff. My solution for now is to quit owncloud for that time, but than I often forget to start it again afterwards.
An option to only sync files under 2 megabyte or so would be awesome, but maybe overkill.

**Comment by danimo** [comment]
Feel free to continue on the branch I pushed (some code that I had lying around half-baked and ported to master now. The following is missing:

- [ ] Blessing of the approach by @jancborchardt 
- [ ] Some kind of reflection of a global pause state in the settings/status dialog
- [ ] Persistence of the pause state across restart

Who wants to pick this up?

**Comment by danimo** [comment]
This is how it currently looks:

![image](https://cloud.githubusercontent.com/assets/1315934/5791092/79268ee2-9eba-11e4-9e0f-4433ec13c55c.png)

**Comment by te-online** [comment]
Looks great. I might try to look into it to see what I can do by end of next week.

**Comment by danimo** [comment]
@te-online Also, the local pause option should maybe be renamed to Enable/Disable again, so it's not too confusing.

**Comment by jancborchardt** [comment]
@danimo can you show a screenshot of both states – when it’s paused and when it’s running?

**Comment by danimo** [comment]
@jancborchardt No, I don't have a build of that branch at hand. if it's running it shows whatever state there is as an icon, and the checkmark in front of "Pause syncing" goes away.

**Comment by jancborchardt** [comment]
Ok, that seems to be the best solution. If we would change it to »Syncing paused« it would create confusion as how to unpause.

**Comment by jancborchardt** [comment]
(I’d still prefer the »Pause« button on the same line as the Syncing / Up to date, but I know that’s probably not possible cross-platform. ;)

**Comment by te-online** [comment]
Sorry, it seems I don't have any time to look into this at the moment. It might be a one-liner, but I'd have to set up the whole development environment, because I didn't work on the client so far. When there's more freetime, I will be happy to have a look at it. 

In the meantime, everybody feel free to implement it. :-)

> (I’d still prefer the »Pause« button on the same line as the Syncing / Up to date, but I know that’s probably not possible cross-platform. ;)

Even if it was possible, I don't see any space there. There are advantages of having it on a single line. It's always accessible, no matter what syncing state is being displayed.

**Comment by danimo** [comment]
Related: https://github.com/owncloud/client/issues/2760

**Comment by guruz** [comment]
For the record, DropBox:

![dropbox](https://cloud.githubusercontent.com/assets/959327/7492780/c2f2c3f6-f3fb-11e4-85ae-f7a0e333b46a.jpg)

OneDrive:

![onedrive](https://cloud.githubusercontent.com/assets/959327/7492782/c87ead44-f3fb-11e4-8d24-eb29cb07b833.jpg)

(it even has the ```Sync now``` proposed in #2158)

**Comment by guruz** [comment]
@dragotin mentions in https://github.com/owncloud/client/issues/3185#issuecomment-99068126
>  In the light of multi account however, global probably means by account.

IMHO we can still do it globally and have it pause all accounts.

**Comment by danimo** [comment]
I have started on a global pause option, not sure where the PR went, but there is a https://github.com/owncloud/client/tree/global_pause branch.

**Comment by guruz** [comment]
Even more relevant now given that we have multi-account support..

**Comment by martin-rueegg** [comment]
+1 for the global option

use cases:
- since ssl transport gets interpreted as real-time traffic, it blocks everything else. yes, i'm aware of the bwlimit, yet i want to set the upload bwlimit to let's say 80% of the line's capacity (otherwise i will never upload my 100GB!). this is usually enough for http GETs [and DNS requests in the first place] to go through and the download is not the problem. yet, getting an incoming VoIP-call requires me to reduce the load on the line, thus a global (not per-accound) pause.
- same when on the road with my notebook. yes, i can quit the owncloud client, but then i have to remember to restart it. seeing the "paused" icon in the tray helps me to remember.

(client: Version 2.1.0 (build 5683). Windows.)

**Comment by Kawohl** [comment]
Is this done and can be closed? 
![screen shot 2016-10-11 at 14 54 25](https://cloud.githubusercontent.com/assets/12275313/19270916/ab0b9c36-8fc2-11e6-9600-4df5e2c9f8d0.png)

**Comment by dragotin** [comment]
Obviously....

**Comment by martin-rueegg** [comment]
Fantastic! Thanks.
