### ISSUE TITLE
Plasma 5 tray icon startup error

### ISSUE THREAD

**Issue by mcorteel** [owncloud/client#2023]
### Expected behaviour
The desktop client should appear in plasma5's new system tray.

### Actual behaviour
It does not.

### Steps to reproduce
1. Start ownCloud with KDE 5
2. A popup appears telling you that it cannot find a system tray.
3. The client does not work.

### Client configuration
Client version: 1.6.2

Operating system: GNU/Linux, openSuSE 13.1

### Comments
As of plasma 5, the system tray has been modified and the client keeps poping up at startup to indicate that it cannot find any.
[This blog post](http://blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/) contains some information about the new systray (I don't know if it can help).
Anyway, it would be great to have ownCloud working with plasma again!
Thanks for all the hard work, ownCloud rocks!

**Comment by jospoortvliet** [comment]
@wadtech hmmm might be a debian weirdness or something else that's missing... or a mismatch in Qt versions etc

**Comment by tomtana** [comment]
Hey, I am running kUbuntu 14.04 and I had exactly the same problem. 
The sni-qt fix worked for my, thanks for the hint !

**Comment by atroxix** [comment]
For me the issue still appears in OpenSUSE 13.2 and even though I have sni-qt installed.

Selection of packages installed:
sni-qt 0.2.6-3.1.3
libowncloudsync0 1.7.1-1.1
owncloud-client 1.7.1-1.1
plasma-framework 5.6.0-42.2
plasma5-desktop 5.1.0-4.3

**Comment by jospoortvliet** [comment]
@atroxix make sure you have the 32bit AND 64 bit package installed. From there on - it really should work... It gives a warning but will otherwise show up and work just fine.

**Comment by atroxix** [comment]
Yes, actually the system tray icon works, but just the warning appears. Does not matter whether I have 32-bit sni-qt installed or not.

**Comment by PVince81** [comment]
Works for me with:
plasma5-workspace-5.1.95-35.4.x86_64
sni-qt-0.2.6-4.1.x86_64

on openSUSE Factory.

The tray icon appears. However I also get a warning at system startup that the systray isn't there.
But if I start the sync client later, the warning doesn't appear.

I guess it's probably because sni-qt / KDE hasn't fully initialized at the time where the sync client tries to add itself (race condition).

**Comment by perezmeyer** [comment]
The problem with sni-qt and Qt4 in Debian is that it requires a patch to Qt4. Due to the time it was created it had no chances to be included upstream, so we are (so far) ignoring it.

As we can't convince Qt's upstream to include it, the real solution here is to port the system tray to Qt5, which is something that should be considered at some point.

**Comment by CRCinAU** [comment]
I wonder what the deal is with this at the moment?

Fedora 22 & KDE5 show the tray icon, and it works perfectly - however I still get a prompt from owncloud-client that the system tray is not available.

Is this now just an annoying if condition getting in the way?

**Comment by ogoffart** [comment]
@CRCinAU What Qt version are you using?  Is it possible that it is because owncloud starts before plasma?

**Comment by guruz** [comment]
Can this issue be closed?
Does this work with newer Qt or newer Plasma?

**Comment by perezmeyer** [comment]
The problem only happens on Plasma 5 if Qt4 is not patched with an unnoficial patch in order to make sni-qt to work (which last time I checked was dead upstream, although I've been told that might change).

Another way to solve this is to port the system tray icon to Qt5 (if that hasn't happened already).

**Comment by ogoffart** [comment]
Yes, the owncloud client has been ported to Qt5 and Qt5 is recommanded if you are runing plasma 5.

**Comment by ogoffart** [comment]
do you use the official package from owncloud, the ditro packages, or something you compiled yourself?

**Comment by ckamm** [comment]
Like @perezmeyer says, it seems that the problem only still appears with an unpatched Qt4. We're unlikely to be able to address that.

**Comment by kugel-** [comment]
I'm on plasma 5.6 and qt 5.6, yet the tray icon is missing.
