### ISSUE TITLE
NTLM or Kerberos support

### ISSUE THREAD

**Issue by smidt** [owncloud/client#2111]
It would be nice to get NTLM or Kerberos support for the client.

**Comment by dragotin** [comment]
pushed out to at least 2.4.0

**Comment by Zombie-Ryushu** [comment]
Another up vote for GSSAPI based Kerberos Authentication. It should be coded such that both the Desktop Sync Client, and FireFox with support, can use GSSAPI Kerberos.

**Comment by butonic** [comment]
Some terminology: [ADFS 2.0 (and 3.0) supports multiple authentication *types*](http://social.technet.microsoft.com/wiki/contents/articles/1600.ad-fs-2-0-how-to-change-the-local-authentication-type.aspx):

1. _**Integrated Windows authentication (IWA)**_ - can utilize Kerberos or NTLM authentication. You should always prefer Kerberos authentication over NTLM and configure the appropriate service principal name (SPN) for the AD FS 2.0 service account so that Kerberos can be used. Credential collection can happen in two ways depending on how your browser is configured:
  1. _automatic logon with current user name and  password_ - used when AD FS 2.0 URL is in IE Intranet Zone or another IE Zone which is configured to automatically logon with current user name and password
  2. _Browser-based HTTP 401 authentication prompt_ - used when credentials cannot be automatically supplied to the 401 challenge for credentials
2. _**Forms-based authentication (FBA)**_ - A forms-based .aspx page is presented to the user containing username and password fields. This page is fully customizable so that you can add new sign-in logic or page customizations (logos, style sheet, etc.)
3. _**Transport layer security client authentication**_ - a.k.a. Client certificate authentication or Smart Card authentication. The credential is supplied by selecting an appropriate client authentication certificate.
4. _**Basic authentication**_ - The web browser displays a credential prompt and the credentials supplied are sent across the network. The advantage of Basic authentication is that it is part of the Hypertext Transfer Protocol (HTTP) specification, and is supported by most browsers. [...]

Currently, the desktop client only supports FBA and Basic authentication (correct me if I am wrong). In ADFS scenarios this requires [adding "Gecko" to the list of WIA supported user agents](https://blog.kloud.com.au/2014/11/06/implementing-adfs-v3-0-forms-authentication-in-mixed-environments/).

With 9.1 the server supports 2FA and AFAIK the plan is to always use a browser based login for all clients (desktop and mobile) to aquire a device specific token.

Since the client will always open a browser window additional authentication types remain an important feature. Actuall, looking at the above list of authentication types there are two tasks:

- [ ] support WIA in the form of
  1. Kerberos (Requested by Default in ADFS scenarios) or
  2. NTLM (less secure)
- [ ] client certificates, tracked in https://github.com/owncloud/client/issues/69

@guruz what type exists in the branch mentioned in https://github.com/owncloud/client/issues/2111#issuecomment-53543982
@danimo what is the status of NTLM? I only found http://doc.qt.io/qt-5/qauthenticator.html#ntlm-version-2 Doesn't that mean we can support IWA via NTLMv2? Debugging ADFS and mod_shib reveals that ADFS will request Kerberos auth by sending the `WWW-Authenticate: Negotiate` header. I never saw `WWW-Authenticate: NTLM` :( Answering myself ... *we kind of need kerberos*: https://community.dynamics.com/crm/f/117/t/165603 
Also https://codereview.qt-project.org/#/c/91285/ has been merged.

**Comment by guruz** [comment]
About NTLM Qt side: https://codereview.qt-project.org/#/c/91285/ was a fix for proxy authorization. Web server auth (Your ```WWW-Authenticate```) should already work? 

NTLM server side: Just googled https://gist.github.com/JosefJezek/5748211 by @JosefJezek

Kerberos Qt side: Yeah I guess we'd need https://bugreports.qt.io/browse/QTBUG-1538 .. (@peter-ha and @richmoore might know more

About Kerberos server side: This might be an interesting comment for the server side: https://github.com/owncloud/core/issues/10682#issuecomment-226495676 (not sure if this can integrate with Windows, maybe via Samba?).


FYI @ChristophWurst about 2factor comments.

**Comment by Zombie-Ryushu** [comment]
Kerberos is a tiny bit complicated with Apache, FireFox, Samba, and Linux. In the past, Kerberos has been a stand in for Negotiate Authentication for Apache and FireFox. As long as DNS was working right, you could use MIT or Heimdal Kerberos to use Negotiate Authentication in place of Basic Authentication. It was actually Apache and FireFox doing the Authentication, and passing the results on to whatever Nagios/eGroupware/OwnCloud wanted. In FireFox, the server had to be listed as a Trusted URI.

This broke the typical Forms based Login page these applications normally used. If the Kerberos Authentication failed, the server could deny Authentication completely, or fall back to Basic Authentication, it couldn't route back  to Forms based Auth.

**Comment by ogoffart** [comment]
We have upgraded version of Qt now, maybe this should work.  Please re-open if this still does not work with recent version of the client and and this is still something we need.
