### ISSUE TITLE
Shibboleth authentication window in sync-client don't fit the web display.

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#2285]
### Expected behavior 
The login text fits on the authentication window

### Actual behavior
The login text is to wide and have to scroll left and right.

### Steps to reproduce it:
I put some images how it see now and how it should be:
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2285

### Possible solution?

I'm not expert, but maybe in [shibbolethwebview.cpp](https://github.com/owncloud/mirall/blob/e5471d8318a7063f726a8df1abc6a7c7d1648f9a/src/libsync/creds/shibboleth/shibbolethwebview.cpp)

adding something like "Expanding":
```
    <widget class="QWebView" name="webView">
       <property name="sizePolicy">
        <sizepolicy hsizetype="Expanding" vsizetype="Expanding">
         <horstretch>0</horstretch>
         <verstretch>0</verstretch>
        </sizepolicy>
       </property>
       <property name="url">
```
ref: http://stackoverflow.com/questions/12223774/how-can-i-create-a-properly-sizing-qwebview

Is that possible? @dragotin @danimo

**Comment by danimo** [comment]
@cdamken The web is content-follows-browser size, not the other way around. The new default size is 900x700 the first time, and the dialog remembers its geometry now.

@michaelstingl I tested adding the full URL, and it's too long in case of IdPs due to the insanely long parameters. I added "(%host)" now and hope that's sufficient.

I'd very much prefer not to add more theming options here, but find a pragmatic solution. Please confirm that this solves the issue.

**Comment by lmaestro** [comment]
I have tested in version 1.8-nightly20150218 build 2033 and it is fixed.
