### ISSUE TITLE
owncloudcmd cannot control its own settings. owncloud GUI needed here.

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#2294]
E.g. The tranfer speed of owncloudcmd is affected by the rate limiting from the gui client. There should be a command line setting to override this.
And/or print out the settings used at startup. Possibly it is a file that users can edit themselves?

**Comment by benmichael** [comment]
Sorry for waking up an ancient request, but I'd also like to see this implemented.  I have a headless server, and am doing a huge upload.  Being in South Africa, the internet is poor at best, so while owncloudcmd is running it chews up all the bandwidth and I cannot do anything else online.

As a side note, why can't owncloudcmd run as a daemon?  Surely you shouldn't need a GUI to run a daemon?  I have several hundred gigabytes, stored in owncloud, and the sync check alone takes a few minutes.

**Comment by nokia001** [comment]
Yes me too.

**Comment by boltronics** [comment]
I'm running Debian Jessie at my workplace desktop, and the ownCloud devs removed the option to control bandwidth because apparently Qt shipped in Jessie is too old. That makes ownCloud almost unusable when uploading due to it consuming all of my limited bandwidth. Worse still, there appears to be no way to manually fix this via command line settings.

I don't care if I have a GUI or not - I just need the bandwidth control settings back. If I can control this via the command line (or even a documented configuration option!), I'll take it.

**Comment by SamuAlfageme** [comment]
Hey @boltronics regarding:

> ownCloud devs removed the option to control bandwidth because apparently Qt shipped in Jessie is too old.

We have an old issue where @guruz explains why this happened https://github.com/owncloud/client/issues/4334#issuecomment-168999312 -> https://github.com/owncloud/client/blob/master/ChangeLog#L180-L182: 

> version 2.1 (release 2015-12-03)
> ... 
> * Removed libneon-based propagator. As a consequence, The client can no longer provide bandwith limiting on Linux-distributions where it is using Qt < 5.4

To solve this issue, you can install our brand new Qt 5.6.2-based packages from https://github.com/owncloud/client/issues/5470#issuecomment-301756093, e.g.

https://software.opensuse.org//download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client

That been said, just tried with those on Ubuntu 16.04 and the flags for the cmd client work as expected: 

```
$ owncloudcmd --help
[...]
﻿﻿  --uplimit [n]          Limit the upload speed of files to n KB/s
  --downlimit [n]        Limit the download speed of files to n KB/s


$ owncloudcmd --uplimit 50 local_sync_folder https://<your-server>/
[...]
```

... You can check the network usage from the process with `nethogs`,`nettop` or a similar tool.

I understand running the client always with the flag can be a pain in ass, you can always +1 this issue to support developing this feature.

**Comment by boltronics** [comment]
Hi @SamuAlfageme. Thanks. I still don't understand why all support provided by the library was removed, given it was providing such important functionality. Even if the new way is better in some manner, it's not if the result is that some users will be forced to go a long time without functionality they were previously depending on. 

Thanks for the suggestion. I'm actually running Jessie because I do want to ensure I'm running stable software - it's for my work machine after all. Hence, I'm quite reluctant to install nightly packages. With the official stable version (2.3.2), those `--uplimit` and `--downlimit` options don't exist.

Looks like my best bet for now is to look into `mod_bandwidth`. At least Stretch is just around the corner, so I might re-evaluate my options at that time.

**Comment by DominicMe** [comment]
+1 I really don't understand how a cloud storage app does not have an option to run headless. I am forced to script a timer that runs every 60 seconds to try to replicate a GUI like daemon. Lack of bandwith control makes it even worse, if I add a large file my internet simply dies. Why not just add "-limit" option to the command line client?

**Comment by DominicMe** [comment]
@SamuAlfageme I am on 2.3.3 which is the latest in fedora repo and dont see bandwith limit options, since what version are these option available?

**Comment by SamuAlfageme** [comment]
@DominicMe they should indeed be available from 2.3.3 on, in all platforms (since the reason behind removing the `libneon` propagator was incompatibility with Qt versions < 5.4, and all distro's dependency versions are aligned after https://github.com/owncloud/client/issues/5470) 

However https://github.com/owncloud/client/pull/5707 never made it to 2.3 branch, so you can start using it in version 2.4 of the client (currently in alpha version: https://owncloud.org/changelog/desktop/) - i'd say it's not that big of a deal for a backport (i.e. no more 2.3 releases, right? @guruz )

Thanks for pointing it out.

**Comment by DominicMe** [comment]
@SamuAlfageme Thanks for the explanation. It would be great if it was updated as compiling from source is a bit of a pain when compared to installing from Ferora's offiial repos. I would also rather not run alpha release just to get bandwith limiting.

**Comment by guruz** [comment]
@DominicMe Please expect a 2.4 beta1 around next week or in two.

**Comment by guruz** [comment]
@DominicMe Did you try 2.4 beta1?
https://owncloud.org/changelog/desktop/

**Comment by DominicMe** [comment]
@guruz Beta is not available on Fedora or even Arch AUR. Might try to install manually at some point, but not now.

**Comment by michaelstingl** [comment]
@DominicMe Please check the links in the changelog. Beta for Fedora 24, 25, 26 is available.

**Comment by DominicMe** [comment]
@michaelstingl You are right, but after adding the repo it still installs the older version 2.3.3

**Comment by michaelstingl** [comment]
@DominicMe Good catch! Please open a new issue about it.

**Comment by ogoffart** [comment]
As said before, the upload, download limit can be configured with command line arguments.

There are still things that cannot be configured.
But ideally, the owncloudcmd should not depend on the config from the client. https://github.com/owncloud/client/issues/6213

**Comment by ogoffart** [comment]
owncloudcmd has almost no more dependency with the config files.

**Comment by jnweiger** [comment]
For the records:
With the 2.5.0 the command line client has all the options to cover the requests mentioned above:

<pre>
owncloudcmd - command line ownCloud client tool

Usage: owncloudcmd [OPTION] <source_dir> <server_url>

A proxy can either be set manually using --httpproxy.
Otherwise, the setting from a configured sync client will be used.

Options:
  --silent, -s           Don't be so verbose
  --httpproxy [proxy]    Specify a http proxy to use.
                         Proxy is http://server:port
  --trust                Trust the SSL certification.
  --exclude [file]       Exclude list file
  --unsyncedfolders [file]    File containing the list of unsynced remote folders (selective sync)
  --user, -u [name]      Use [name] as the login name
  --password, -p [pass]  Use [pass] as password
  -n                     Use netrc (5) for login
  --non-interactive      Do not block execution with interaction
  --nonshib              Use Non Shibboleth WebDAV authentication
  --davpath [path]       Custom themed dav path, overrides --nonshib
  --max-sync-retries [n] Retries maximum n times (default to 3)
  --uplimit [n]          Limit the upload speed of files to n KB/s
  --downlimit [n]        Limit the download speed of files to n KB/s
  -h                     Sync hidden files,do not ignore them
  --version, -v          Display version and exit
  --logdebug             More verbose logging
</pre>
