### ISSUE TITLE
Selective sync settings and configuration

### ISSUE THREAD

**Issue by gig13** [owncloud/client#2311]
The selective sync feature seems to default to selecting and syncing any newly shared content unless you turn off the entire /Shared directory. If you turn it off and then only check the box for one item in there, then all new items will sync automatically. Do you know if there's a way to reverse the behavior, instead of sync everything unless specifically told otherwise, only sync the items that have been specifically checked in the selective sync dialog? Also, will there be a way a user to provide a default selection for the selective sync feature at build time?

@MTRichards @dragotin

**Comment by gig13** [comment]
@MTRichards @karlitschek @scolebrook 
This is being asked for again. I have more information, but here is the general summary.

"We'd like to have the option to not sync new content. A checkbox in the selective sync dialog that is checked by default (current behavior) would toggle between everything syncs until you uncheck it and nothing syncs until you check it. Having the ability to specify whether this box is checked or unchecked by default with a build option would be great.

As one use case for this feature, one of the primary teams driving ownCloud in our organization is our video production team. Many members of this team are scattered all around the world and they need to get video back to the office for post-production. SMB/FTP are poor choices as the internet connections in many parts of the world are not great. They currently use drop box because of its implementation of chunked uploads. They want to replace Dropbox in their workflow with ownCloud. "

**Comment by MTRichards** [comment]
Yup. It is in the backlog for the desktop client, and the current thinking is to set a limit on when the user is prompted if they want to have the folders syncing. For example, that limit could be 50MB. Any new root folder added to ownCloud as a share for that user would be prompted to say yes or no to the sync, and then selective sync would be set based on the answer.

Step 1 though is to solve this in the initial setup of the client, then to add a step two solution as described here^.

**Comment by scolebrook** [comment]
@MTRichards Our use case also includes external storage, not just shared content. And that storage is definitely going to be altered outside of ownCloud. I see this approach resulting in a user choosing to be constantly prompted about new content that others have created or just setting that limit high to avoid the prompts and have their hard drive and bandwidth consumed with stuff they don't need.

Perhaps if you uncheck a folder, all new content within that folder defaults to being unchecked even though siblings are checked. Eg. All my folders are checked except for an SMB external storage mount. I uncheck it but check a folder within it. Someone creates a folder in that share on the server (a sibling to the one folder that I've checked). It inherits it's sync status from it's parent and is not synced. But since all the rest of my content is synced, if I create a new directory at the root of my account on my Mac, my PC will set it's sync status to it's parent and sync it. This approach would effectively allow setting the default for children on a per directory basis.

Currently sync status matches siblings not the parent. If the parent is unchecked but a single sibling is checked, then a new sibling is checked also. If all siblings are unchecked then a new one is also unchecked.

If I keep throwing ideas around I'm sure I'll come up with something that is great for us and suits no one else :smile: !

**Comment by MTRichards** [comment]
Interesting idea @scolebrook I like it, have to think through it a bit.

So two options on whether something is synced automatically:
1) size based (not if bigger than x)
2) selective sync based (if the root is selected to be synced)

Problem there is all newly added shares would be synced by default, so we need a case to handle that too. Say when you mount a new sharepoint on initial setup, or when the scope of deployment increases.

**Comment by dragotin** [comment]
To solve these problems, I wished we could make more use of the fact that we can handle more than one sync connection of specific folders from the server. Instead of syncing the whole server and reduce the set of data involved by selective sync, it might be more clever to just set up a couple of sync connections for specific folders.

I understand that this is not what users are used to (yet), but maybe we can "under the hood" combine the two technologies?

**Comment by scolebrook** [comment]
We are having new shares "land" in /Shared still so that we have the ability to quickly set users up to not sync any newly shared content. They can then move it where they want and if it's out of /Shared it'll sync. But that doesn't help with our SMB storage setup.

Our initial solution was to have one folder set to sync all but /Shared with selective sync and then have another folder that would sync some things in /Shared. But with the SMB storage scenario one of our teams wants, that doesn't solve the problem either.

Getting the default for new content from it's parent rather than it's siblings would probably meet all our needs if we combine it with multiple folder configurations.

**Comment by MTRichards** [comment]
We need to look at this for Desktop Client 1.9. Not saying it is in, but I am saying it should be considered.

**Comment by bcg-didi** [comment]
@MTRichards 
> The selective sync is implemented as a white list.

That's what the user interface suggests (at least that was my perception). However under the hood the implementation seems to be blacklist based:
```
$ cat ~/.local/share/data/ownCloud/folders/bc-cloud 
[bc-cloud]
localPath=/home/didi/bcg/cloud
targetPath=/
backend=owncloud
connection=ownCloud
blackList=archive/, design/Assets/
```

In our case, the reasons for using the selective sync feature are:
- not enough space for everything on some Computers with SSD
- avoid wasting bandwidth (since there's no LAN sync yet)

The current behaviour of automatically syncing new folders makes that much more difficult then it would be with a whitelist based approach.

**Comment by MTRichards** [comment]
We are working on it, to be honest. There is a lot of discussion about how of course...but we are working on it.

**Comment by ogoffart** [comment]
New issue: https://github.com/owncloud/client/issues/3148
