### ISSUE TITLE
1.7.0-beta4: discovering the folder excluded from sync

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2387]
I excluded the entire kernel directory from sync (in order to remedy the endless error loop #2386).

However the client keeps on "discovering" this very large tree and only at the end it says that it ignores it.
It should be entirely excluded from consideration.

It does local discovery quite often which is a problem on its own -- without any activity in the local folder do you expect to trigger periodic scan of the entire tree?

**Comment by martin-rueegg** [comment]
as a user, i actually agree with @moscicki in that i understand an "un-selected" folder to be the same as an "ignored" folder.
suggested behaviour:
- [x] checked folder: synchronized (obviously!)
- [ ] unchecked folder: ignored.
- when unchecking a folder, the user is asked, if the files should be kept (nothing done, except adding the folder to the ignore-list) or deleted (deleted immediately). maybe a bloody are-you-really-sure dialog would avoid some catastrophe.

(client: Version 2.1.0 (build 5683). Windows.)

**Comment by martin-rueegg** [comment]
after reading part of #2502, i realize that as of version 2 it is obviously already the case, that local files are not deleted, but when i watch the status the ignored folder still gets listed during the discovery phase ...

**Comment by michaelstingl** [comment]
@guruz @ckamm Related to https://github.com/owncloud/enterprise/issues/1965 ?

**Comment by ckamm** [comment]
@michaelstingl I don't think so. The issue here is that selective-sync-ignoring and pattern-ignoring are different. Selective-sync-ignored trees will be removed locally if up-to-date, and will also continue to be locally-discovered.

I agree that the behavior can be confusing and the distinction isn't obvious. Changing any of this is made complicated by backwards-compatibility considerations.

Maybe we should have three states "Completely ignored" / "Remove local if up-to-date" / "Synced" somehow, but extra choice is confusing as well. Or "Remove local if up-to-date" should become "Completely ignored" after everything that could be removed was removed - but then there may be subtle behavior differences...

**Comment by moscicki** [comment]
What about only two states: synchronized and not synchronized. The use-case for deleting local files sound more like an "archive on the server" which is an *action* and not a state. 

Therefore, I think it would make more sense to have a button called "Archive" that a user would be free to activate or not. That Archive action would result in local deletion of files which are known to the client (and clean -- not modified locally) and the directory switching to "not synchronized" state. BTW. It looks impossible to me to avoid race conditions in general to assure that deletions do not destroy locally modified data. Hence, it should be done explicitly by the user when he knows it is "safe".

Merely choosing "not synchronize" would not delete anything and keep the local tree intact. Flipping back-and-forth between synchronized and "not synchronized" should not result in any state change in the directory (assuming that all files are clean). Flipping to "synchronized" should be equivalent to "first-time" sync such as adding new sync-folder pair: changed files result in conflict and files removed on both ends are transferred (and not deleted).  It would result in a directory scan to retrieve the local and remote state of the directory. Flipping to "not synchronized" would not require a file scan (but possibly a cleanup of the syncdb to remove the entries no longer synchronized).

This is a very clear semantics and covers most of use-cases and avoids unexpected behaviour (from our experience 50% of users do not expect the local files to be deleted).

**Comment by ckamm** [comment]
I mostly agree with what @moscicki is saying.

Local cleanup as an action makes sense. It's what I was suggesting above about removing locally once and then switching to ignoring completely.

@moscicki What do you mean by "it seems impossible to avoid race conditions...". The situation shouldn't differ at all from a remote removal propagating downwards - if that is reasonably safe, then the archive action should be reasonably safe. 

I think a straightforward way of adding this UI-wise would be in the selective sync interface: You deselect a couple of folders and have the option of ticking a "Clean up fully synchronized local data" checkbox that's near the Apply/Cancel buttons. In essence the existing "local data will be removed!" warning would become an option.

@ogoffart Thoughts?

**Comment by ogoffart** [comment]
The "choose what to sync" feature (aka selective sync)  was based on the equivalent drop box feature which is removing the files. It took long discussion back at the owncloud conference some years ago untill we came to the current behavior. (which I also agree is probably not optimal) The problem is that we are trying to work with many different use cases, and there is in fact several ways to achieve similar things:

1. add multiple different folders
2. edit the ignore list 
3. selective sync

**Comment by michaelstingl** [comment]
Adding @pmaier1 to the show…

**Comment by ogoffart** [comment]
Closing old issue.
This is the expected behavior of "choose what to sync".
