### ISSUE TITLE
[Windows] Make overlay icons work in root folder

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2455]
- [x] Revert 5c5a89c1a4169a1cdaac6fba710668266e713881
- [x] Merge https://github.com/owncloud/mirall/pull/2454
- [x] Rebuild windows dll's and fast forward sub-repo

**Comment by danimo** [comment]
176413d3121a73b06e0761026b930a8ff18d1dfc reverts 5c5a89c1a4169a1cdaac6fba710668266e713881. What's now left is a rebuilding the windows extension

**Comment by danimo** [comment]
Extension has been rebuilt and is part of recent builds.

**Comment by lmaestro** [comment]
It doesn't work in version 1.8.0-nightly20150202 (build 4670).

![screen shot 2015-02-02 at 1 21 20 pm](https://cloud.githubusercontent.com/assets/4689430/6000490/bc0b5550-aade-11e4-8148-e576c8925e64.png)

**Comment by jturcotte** [comment]
Seems to work well for me. Does it never work at all? Or is there some situations where it does work and others not?

**Comment by lmaestro** [comment]
I tested in Windows 8 version 1.8.0-nightly (build 4714) an it doesn't work. 

![captura1](https://cloud.githubusercontent.com/assets/4689430/6170493/5f705814-b2d5-11e4-8fab-2d3d97949dca.jpg)

**Comment by jturcotte** [comment]
Thanks, seems like the issue is still there then.
Trying to find out how to reproduce the issue, could you please tell:

1) Does it work for other files inside the directory (not just the root folder)?
2) Do you also see the issue if you place the TEST-OWNCLOUD somewhere else than Desktop? Like in C:\TEST-OWNCLOUD?
3) Is there any situation where you would see the root folder icon? If you restart Windows, or if you press F5?

**Comment by lmaestro** [comment]
I have tested and :
1) Yes overlay icons work inside the root folder
2) I Tried to locate it in different locations and no one works 
3) I restarted and it didn't work and the same if I press F5.

**Comment by lmaestro** [comment]
It works fine in version 1.8-nightly (buil 4740)
