### ISSUE TITLE
[OS X] [1.7.0] High CPU usage

### ISSUE THREAD

**Issue by mcnesium** [owncloud/client#2479]
After upgrading to v1.7.0 I experience the owncloud process to constantly consume between 10 and 50% of the CPU, even though there are no files to sync. This is on C2D/2,2GHz OSX Lion and I have 14 sync folders set up.

**Comment by qnxor** [comment]
Another report. I also just instaled 1.7.1.1655 on Yosemite 10.10.2 on a MBP Late 2013. The CPU I have is i7-4850HQ. In activity monitor I can see the owncloud process spike to 25% (so 100% of one core) every 1 minute or so when it's idle. It also goes to 8-15% more frequently (every 15-20 seconds) and stays there for 2-3 seconds.

I have only 3 folders and 4 files (fresh ownCloud installation) with one of them being an encrypted folder with external storage (Dropbox).

Compared to the Dropbox desktop client, where I have more than 20,000 files, after about 10 minutes of idle, the owncloud process is has spent more than 5x CPU time than the dropbox process. This factor increases with time. The dropbox client does a big CPU spike at the start checking my huge database, but then is really virtually idle.

I tested the above after quitting Finder completely. I'll do the above `ps` test soon, as well as running it in the terminal and recording the logging.

Nonetheless, this looks abnormal and is affecting the time when on battery.

**Comment by guruz** [comment]
@qnxor We're about to release 1.8 beta2 today or tomorrow. Would be nice to see your results with that. (if there is nothing to sync a CPU spike should only happen at startup and then every 2h with 1.8)

**Comment by qnxor** [comment]
@guruz That sounds great, many thanks for replying. I was going to compile it for MacOSX but you just saved me some precious time. 

#2783 mentions 1.8.0 beta2 as "released" but the downloads page links to beta1. Is that an error or the binary is not actually ready?

**Comment by mcnesium** [comment]
@qnxor the beta2 binary can be downloaded [here](https://download.owncloud.com/desktop/daily/ownCloud-1.8.0.2077beta2.pkg)

**Comment by qnxor** [comment]
@mcnesium I installed 1.8 beta2 and little changed in my case. I still see cpu spikes and high usages more frequenctly than expected. CPU time was 02m04s for owncloud,  compared to 00m19s for dropbox ... both idle, started at the same time, after 2h. Dropbox handles over 20,000 files, while owncloud only 4 files.

I'll run the `ps` test and terminal logging and post again.

**Comment by qnxor** [comment]
Could it be an issue related to my apache config (etag, gzip compression, etc)? Any particular things you'd recommand I try to enable/disable on the server to debug this?

**Comment by guruz** [comment]
```* Compare etag with previous etag: last: ""54f7dca18ee8f"" , received: ""54f7dcdd84d36""```
This means on the server side something changed, that's why another sync is scheduled.
Which server version do you use?
Is there anything special about the sync folder you have configured (shared folder, external storage, ...) ?

**Comment by guruz** [comment]
> with one of them being an encrypted folder with external storage (Dropbox).

@qnxor Can you look at the complete log output and say which folder is always re-scheduled and synced? Is it all three folders or only that one?

**Comment by qnxor** [comment]
> Can you look at the complete log output and say which folder is always re-scheduled and synced? Is it all three folders or only that one?

The complete log consists of repeated blocks of the text I posted here: https://dl.dropbox.com/s/ovw1czxlk3pe2k4/oc1.log ... all of this repeats every 60 seconds. 

Note how is it says `slotEtagPollTimeTimeout` and `slotRunEtagJob: * Trying to check "ownCloud" for changes via Etag check. (time since last sync: 53 s)`. It looks there is a timeout of 53 s which triggers regular checks.

But that aside, the fact that the etags are different doesn't look right (see log): `03-05 04:35:32:250 0x7f91d0614440 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""54f7dca18ee8f"" , received: ""54f7dcdd84d36""`

> Just check for the message `OCC::FolderMan::slotScheduleSync: Schedule folder "???" to sync!`

See the log I posted, line 11: `OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag` (that's the main and only folder in MacOSX that the desktop client syncs)

> Is there anything special about the sync folder you have configured (shared folder, external storage, ...) ?

Like I said previously, one of the folders (the one called `Dropbox-Enc` you see in the log) is on Dropbox, via the external storage plugin and is also encrypted by ownCloud via the encryption plugin. Inside that folder there is only one file (ArcSin.pdf). All other folders are the default ones that owncloud created itself. All this is in the log.

> Can you check the owncloud.log on the server for possible errors/warnings?

Good call! There is an error related to external_storage: `{"reqId":"9f70682ab4c7c24aa2c687dd5d288529","remoteAddr":"86.132.105.113","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-05T04:35:37+00:00"}`

But that can't be true ... the external storage sync with the Dropbox-Enc folder works just fine. I just copied another file in "Dropbox-Enc" and it was sync'ed just fine to Dropbox, and I can also see it in the web interface. Something else must be going on.

> Which server version do you use?

I'm using Ubuntu 14.04.2 with Apache 2.4.12 and PHP 5.5 (both from this PPA: https://launchpad.net/~ondrej/+archive/ubuntu/apache2).

The enabled apache modules are: `access_compat actions alias auth_basic auth_digest authn_core authn_file authz_core authz_groupfile authz_host authz_user autoindex cgi cgid dav dav_fs deflate dir env expires filter headers mime mpm_prefork negotiation php5 reqtimeout rewrite setenvif socache_shmcb ssl status`

The enabled php5 modules are:
```
# grep extension= /etc/php5/apache2/conf.d/*
/etc/php5/apache2/conf.d/05-opcache.ini:zend_extension=opcache.so
/etc/php5/apache2/conf.d/10-pdo.ini:extension=pdo.so
/etc/php5/apache2/conf.d/20-curl.ini:extension=curl.so
/etc/php5/apache2/conf.d/20-gd.ini:extension=gd.so
/etc/php5/apache2/conf.d/20-intl.ini:extension=intl.so
/etc/php5/apache2/conf.d/20-json.ini:extension=json.so
/etc/php5/apache2/conf.d/20-mcrypt.ini:extension=mcrypt.so
/etc/php5/apache2/conf.d/20-mysqli.ini:extension=mysqli.so
/etc/php5/apache2/conf.d/20-mysql.ini:extension=mysql.so
/etc/php5/apache2/conf.d/20-pdo_mysql.ini:extension=pdo_mysql.so
/etc/php5/apache2/conf.d/20-pdo_pgsql.ini:extension=pdo_pgsql.so
/etc/php5/apache2/conf.d/20-pdo_sqlite.ini:extension=pdo_sqlite.so
/etc/php5/apache2/conf.d/20-pgsql.ini:extension=pgsql.so
/etc/php5/apache2/conf.d/20-readline.ini:extension=readline.so
/etc/php5/apache2/conf.d/20-sqlite3.ini:extension=sqlite3.so
```

The apache host conf for the site that owncloud is running under is:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>

    ServerAdmin admins@DOMAIN.COM
    ServerName  DOMAIN.COM
    ServerAlias www.DOMAIN.COM

    DocumentRoot        /var/www/DOMAIN.COM
    UseCanonicalName    Off

    <Directory /var/www/DOMAIN.COM>
        Options FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/ssl_error.log
    LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    SSLEngine on
    SSLCertificateKeyFile    /etc/ssl/private/DOMAIN.COM.key
    ## Apache 2.4 complains about using two directives for this
    #SSLCertificateFile       /etc/ssl/certs/DOMAIN.COM.pem
    #SSLCertificateChainFile  /etc/ssl/certs/DOMAIN.COM.ca-bundle
    ## Just cat the above two files into one file, the one below
    SSLCertificateFile       /etc/ssl/certs/DOMAIN.COM.full.crt

</VirtualHost>
</IfModule>
```

The apache owncloud.conf and .htaccess are the default ones, I have not modified them:

```
# cat /etc/apache2/conf-enabled/owncloud.conf
Alias /owncloud "/var/www/owncloud/"
<Directory "/var/www/owncloud">
    Options +FollowSymLinks
    AllowOverride All
</Directory>
```

```
# cat /var/www/owncloud/.htaccess
# Version: 8.0.0
<IfModule mod_fcgid.c>
<IfModule mod_setenvif.c>
<IfModule mod_headers.c>
SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
</IfModule>
</IfModule>
</IfModule>
<IfModule mod_php5.c>
php_value upload_max_filesize 513M
php_value post_max_size 513M
php_value memory_limit 512M
php_value mbstring.func_overload 0
php_value always_populate_raw_post_data -1
<IfModule mod_env.c>
  SetEnv htaccessWorking true
</IfModule>
</IfModule>
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
RewriteRule ^\.well-known/carddav /remote.php/carddav/ [R]
RewriteRule ^\.well-known/caldav /remote.php/caldav/ [R]
RewriteRule ^apps/calendar/caldav\.php remote.php/caldav/ [QSA,L]
RewriteRule ^apps/contacts/carddav\.php remote.php/carddav/ [QSA,L]
RewriteRule ^remote/(.*) remote.php [QSA,L]
RewriteRule ^(build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
RewriteRule ^(\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
</IfModule>
<IfModule mod_mime.c>
AddType image/svg+xml svg svgz
AddEncoding gzip svgz
</IfModule>
<IfModule mod_dir.c>
DirectoryIndex index.php index.html
</IfModule>
AddDefaultCharset utf-8
Options -Indexes
<IfModule pagespeed_module>
        ModPagespeed Off
</IfModule>
<IfModule mod_headers.c>
  <FilesMatch "\.(css|js)$">
    Header set Cache-Control "max-age=7200, public"
  </FilesMatch>
</IfModule>
```

**Comment by guruz** [comment]
@qnxor We had a misunderstanding here, you wrote "I have only 3 folders and 4 files" and I thought you mean you had 3 sync folders in the client setup, but actually you have 1 sync folder set up.

Can you do me a favor and paste the log of maybe 4 consecutive syncs? I'd need to know exactly how the ETags change.

I have a suspicion already:
The Dropbox-Enc is shown as ```INSTRUCTION_NONE``` even though:
```
03-05 04:35:34:961 0x7f91d4176a58 csync_walker: directory: ownclouds://DOMAIN.COM/owncloud/remote.php/webdav/Dropbox-Enc [file_id=00000056oc9opkh40b3h]
03-05 04:35:34:961 0x7f91d4176a58 _csync_detect_update: Database entry found, compare: 1425530075 <-> 1425530015, etag: 54f7dcdbafb72 <-> 54f7dc9fa2d08, inode: 0 <-> 19337491, size: 0 <-> 0, perms: RMDNVCK <-> RMDNVCK
03-05 04:35:34:961 0x7f91d4176a58 _csync_detect_update: file: Dropbox-Enc, instruction: INSTRUCTION_EVAL <<=
```
You see ^^ the ETag of ```Dropbox-Enc``` is different.

However then recursing into the remote ```Dropbox-Enc```:
```
03-05 04:35:37:733 0x7f91d4176a58 csync_walker: file: ownclouds://DOMAIN.COM/owncloud/remote.php/webdav/Dropbox-Enc/ArcSin.pdf [file_id=00000057oc9opkh40b3h size=90651]
03-05 04:35:37:733 0x7f91d4176a58 _csync_detect_update: Database entry found, compare: 1425438714 <-> 1425438714, etag: 54f67800aad03 <-> 54f67800aad03, inode: 0 <-> 19337492, size: 90651 <-> 0, perms: RMW <-> RMW
03-05 04:35:37:733 0x7f91d4176a58 _csync_detect_update: file: Dropbox-Enc/ArcSin.pdf, instruction: INSTRUCTION_NONE <<=
```
Here you see the file inside has the same ETag and didn't actually change.

CC @PVince81 @schiesbn  What is the cause here regarding the broken ETag? The DropBox plugin? The encryption?

**Comment by PVince81** [comment]
Do I understand it well that the steps to reproduce are as follows:
1) Upload a file "test.txt" to "Dropbox-Enc" using the Web UI
2) Wait for the sync client to sync it down
3) Edit the file using the web UI (or upload+overwrite using the web UI)
4) Wait for the sync client to sync it down

But it never syncs it down because the file or folder etag did not change ?

**Comment by PVince81** [comment]
Possibly related: https://github.com/owncloud/core/issues/11628 (@guruz told me this was about etag changing constantly without reason)

**Comment by qnxor** [comment]
@guruz Here's a full (sanitized) log of 5 minutes from the moment the desktop client starts: https://dl.dropbox.com/s/ntla2jgkp7p3mck/oc3.log

I now have bigger problems. I added a file to "Dropbox-Enc" to test if it syncs. It does. But if I delete it using Finder, the owncloud client puts it back after 5-10 seconds! Here's a full log of me starting owncloud, then deleting a file from the "Dropbox-Enc" subfolder: https://dl.dropbox.com/s/h6i17n2810uti0c/oc4.log

Deleting a file from another subfolder, or from the main folder, does not bring it back.

It feels like one or more components are flaky (encryption plugin, external storage plugin, desktop client). I don't feel safe using it for my regular work.

> Do I understand it well that the steps to reproduce are as follows:
> 1) Upload a file "test.txt" to "Dropbox-Enc" using the Web UI
> 2) Wait for the sync client to sync it down
> 3) Edit the file using the web UI (or upload+overwrite using the web UI)
> 4) Wait for the sync client to sync it down
>
> But it never syncs it down because the file or folder etag did not change ?

Not quite. Everything is sync'ed correctly. The problem is that the desktop client appears to continuously attempt to sync the folder when it should not.

What I did was as follows
- fresh install and created another admin user
- activated the external storage and encryption plugins
- at dropbox.com I created an app restricted to a single folder and got the API key and passcode
- in the owncloud interface I created a Dropbox external storage using the API key and passcode provided by Dropbox ... this is the sub-folder called "Dropbox-Enc" we were speaking of
- added a file to the Dropbox-Enc folder
- the desktop client (at least the MacOSX one) constantly syncs every 60 seconds, causing CPU spikes, see log and my reports in my previous posts here.

However now I have bigger problems (see above).

**Comment by PVince81** [comment]
@qnxor when you talk about file operations (like deleting), are you doing these:
1) in the ownCloud web UI ?
or
2) locally with the ownCloud sync client ?
or
3) with the Dropbox client ? (or the Dropbox web UI)

Encryption should work fine. The problem is most likely with the Dropbox storage (it has known issues...)

**Comment by qnxor** [comment]
@PVince81 like I said, I deleted it using Finder from the `Dropbox-Enc` subfolder (which a subfolder of the owncloud folder that is set to sync).

**Comment by guruz** [comment]
@qnxor Yes, the Dropbox storage plugin is probably the root cause of this. Could you submit an issue inside the core repo and from there also link to this issue here? 

For all others: If you continue to have issues with > 1.8.0 beta2 please create a new bug inside this repo here.

**Comment by qnxor** [comment]
I'll copy/paste my posts above (I lack the time to write a new report)
