### ISSUE TITLE
Force HTTPS: server replied: Forbidden

### ISSUE THREAD

**Issue by manuelmoroni** [owncloud/client#2556]
"|0|....|INST_NEW|Down|1416076936|54679e88312dd|25680|00000154ocfa666bb1c5|6|The item is not synced because of previous errors: Error downloading https://.........com/remote.php/webdav/...... - server replied: Forbidden|0|0|0|||INST_NONE|"

it seems the problem is in the https protocol. with the http the problem seems solved

switching between http and https i found the problem. long story short i point out my tests:
1- https with "force https" option enabled on the admin panel -> sync fail!
2- http with "force https" option disabled on the admin panel -> sync success!
3- https with "force https" option disabled on the admin panel -> sync success!
==> the bug seems to be on the "force https" option enabled.

right now i'm forcing https through .htaccess configuration

**Comment by Melele** [comment]
Is there progress on this topic ? I have the same problem here, I setup with http and switched to https later.. Already posted on the owncloud forum http://forum.owncloud.org/viewtopic.php?f=29&t=25760&p=77078#p77078

**Comment by manuelmoroni** [comment]
no news for me sorry.....
keep me posted.

i used the workaround of forcing https via .htaccess  file.

2015-01-12 10:41 GMT+01:00 Melele <notifications@github.com>:

**Comment by Melele** [comment]
Mine works after new installation of 7.04:
What I did:
1. upgrade all relevant folders to php 5.4 
2. setup webinstallation
3. for my package I cannot use php_value and options, so I disabled # those in the config.php
otherwise I always got an error at step 3 of the installation.
4. Had to reset my database password before finishing
5. was able to finish installation
6.I changed config.php again like in http://blog.lewumpy.de/2013/03/owncloud-mit-ssl-proxy-betreiben/ but not .htaccess to put in ssl proxy as I cannot use a certificate in my package.
7.I was able to check the box "enforce https" without any errors on the administration site.
8. I didn't use my subdomain link, but the normal directory for all the entries.

Desktop Client and Browser work fine now, no more Error like in the headline.
I hope this helps others too.

**Comment by manuelmoroni** [comment]
THX a lot. If i'll decide to upgrade i'll take your advice. (Hoping i won't
need all your steps)
Il 12/gen/2015 20:38 "Melele" <notifications@github.com> ha scritto:

**Comment by jackbravo** [comment]
I have this issue too. I don't see the option to "enforce https" on the administration site (I'm guessing you guys refer to /owncloud/index.php/settings/admin right?).

**Comment by jackbravo** [comment]
Ok, seems like this is an issue with the owncloud-client and the new encryption in owncloud 8.1: https://github.com/owncloud/client/issues/3448
