### ISSUE TITLE
Local sync problems to windows client. Local file name clash

### ISSUE THREAD

**Issue by walters199** [owncloud/client#2574]
If i add to files in my webclient like
test.txt and
TEST.txt

I get an error syncing this to my windows machine ( Can not download because of local file name clash!)
Maybe the best solution is to prevent this in the online client because Windows doesn`t care about uppercase letters or not. This is giving us a lot of support problems. 

We have owncloud 7.2 with mysql database, debian based.
Using client 1.7.0

**Comment by ogoffart** [comment]
Yes, you cannot sync files that have diferent case on windows, that is a known limitation of Windows.

But the web interface and linux allow you that. There is no need to restrict it there just because it does not work with windows.  The sync client will just show you an error which you can fix by renaming the file in the web interface.
