### ISSUE TITLE
Shibboleth-403-error not shown via sync-client

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#2607]
Users login via Shibboleth, but it is only allowed for users that have the right attribute. Users that don't have the attribute will get a 403-error page.

The problem is that, when an user tries to login via the sync-client, he will never see the 403-error. So the user is completely unaware "what is wrong".

Can the sync-client "understand" when there is no access granted after a successfull shibboleth login.

@dragotin @danimo 

00002241

**Comment by cdamken** [comment]
@MorrisJobke: @danimo made some modifications that helps for now, but the solution will be probably in 1.7.2 or 1.8. it was not possible for 1.7.1

**Comment by danimo** [comment]
> Improve user experience (currently the wizard at this point assumes that HTTPS is broken/misconfigured and asks the user if he wants to try HTTP only. There are some things we can do to make that guess more correct.

This one just landed in master.

**Comment by craigpg** [comment]
Here's what you see in the setup wizard after authenticating when you don't have proper permissions:

![image](https://cloud.githubusercontent.com/assets/160667/5651116/bc1795f2-9672-11e4-8ceb-b1f0c1d03595.png)


Since this is not a client-specific error condition, the user will run into the permissions issue when trying to access their ownCloud via the browser.  At least in this particular case, when going through the browser they get a much more useful error page:

![image](https://cloud.githubusercontent.com/assets/160667/5651160/17ff8a1e-9673-11e4-985a-fe7e0a022011.png)

We should enhance the "Error downloading..." message in the wizard to suggest the user try to access the service directly in the browser and provide them the link to click on.  For example, "To ensure you have proper access, please try accessing the service directly in your browser: https://.../files"

**Comment by danimo** [comment]
@michaelstingl Does what Craig proposes sound ok to you?

**Comment by danimo** [comment]
@michaelstingl ping?

**Comment by cdamken** [comment]
@danimo That solution sounds good to me :+1:

**Comment by michaelstingl** [comment]
@danimo is @craigpg 's proposition "To ensure you have proper access, please try accessing the service directly in your browser: https://.../files" in master yet?

**Comment by danimo** [comment]
@michaelstingl No, I will tackle this in the next days.

**Comment by danimo** [comment]
@michaelstingl This is what it looks like now: ![image](https://cloud.githubusercontent.com/assets/1315934/5935630/2d2aa138-a6dd-11e4-9c1f-25fdfe001a8b.png)

**Comment by danimo** [comment]
@craigpg Is the wording ok?

**Comment by danimo** [comment]
Commit 524f04f34eb990d68b7b64010243cad2b1db3c24 is the final part

**Comment by danimo** [comment]
will be in the next build

**Comment by craigpg** [comment]
:+1:  on the wording.

**Comment by lmaestro** [comment]
It works fine in the version 1.8.0-nightly20150129(build 1951)
