### ISSUE TITLE
Add support for selective sync to owncloudcmd

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/client#2632]
Add support for selective sync to owncloudcmd - this would be a huge help for test automation.

**Comment by dragotin** [comment]
@ogoffart thinks it should be doable for the next release :-)

**Comment by ogoffart** [comment]
I'm having a hard time to find a good name for the option:

What I came up to:

```
owncloudcmd --unsyncedfolder  /tmp/selectivesync.txt
```

Where selectivesync.txt contains the list of unchecked items.

Any better name?

**Comment by moscicki** [comment]
```
--selective-sync
```
?
;-)

**Comment by ogoffart** [comment]
"selective sync" is more like an internal name that is not supposed to be user visible.  But maybe owncloudcmd is sufficently internal that it is a good option name.

**Comment by jnfrmarks** [comment]
@ogoffart 

I was also thinking --selective-sync.

I actually don't know a lot about the feature and assumed it allowed the user to sync a specific file or directory under their root owncloud directory.  I will read up on the feature later today and can make another suggestion then.

**Comment by ogoffart** [comment]
In 1.8 there is an option:

```
  --unsyncedfolders [file]    File containing the list of unsynced folder (selective sync)
```

**Comment by lmaestro** [comment]
Included:
owncloudcmd - command line ownCloud client tool

Usage: owncloudcmd [OPTION] <source_dir> <server_url>

A proxy can either be set manually using --httpproxy.
Otherwise, the setting from a configured sync client will be used.

Options:
  --silent, -s           Don't be so verbose
  --httpproxy [proxy]    Specify a http proxy to use.
                         Proxy is http://server:port
  --trust                Trust the SSL certification.
  --exclude [file]       Exclude list file
  --unsyncedfolders [file]    File containing the list of unsynced folder (selective sync)
  --user, -u [name]      Use [name] as the login name
  --password, -p [pass]  Use [pass] as password
  -n                     Use netrc (5) for login
  --non-interactive      Do not block execution with interaction
  --version, -v          Display version and exit
