### ISSUE TITLE
Win Client hangs(?) after upgrade

### ISSUE THREAD

**Issue by McOc** [owncloud/client#2651]
As suggested by tflidd in the OC forum, I am creating an issue here.
The following is the original post from 
https://forum.owncloud.org/viewtopic.php?f=14&t=25550

-----------------

Hi,

I just upgraded from
Client 1.6.4 to 1.7.1
and
Server 7.0.0 to 7.0.4

Server looks fine, I am able to log in. All seems fine.
On the Client side, things are different.
After startup, client went through all directories of the first sync set (my music files) and says for each directory sthg like "discovering <folder name>". This time, consuming some CPU also on the server. After the last folder, it seems to hang: no local disc interaction, GUI not usable, local CPU and local RAM constantly on the same one level. Currently it is running for 1h roughly.

The manual does not say sthg like this (at least in the searched areas ;)

Any clues?

Thanks,
McOc

**Comment by rotdrop** [comment]
Hi there,

I have a similar issue (Linux client) when trying to sync with an OC server which has external OC storages mounted.

Setup on server:

- one owncloud server for our symphony orchestra
- one private oc server for myself
- the private server mounts a shared folder from the orchestra server
- the servers are just working fine; somewhat slow, but the shared external storage can be accessed just fine, also downloading of files through the web-interface just works

However, the sync client just goes through an endless loop of "discovery" with messages "Discovering BlahBlah" where "BlahBlah" is either an existing remote folder, or even the name of the _local_ folder where the stuff should be stored locally.

The sync client is 1.7.1 and just worked fine before mounting the remote storages on the server. I'm not posting the client log because it is empty (after the point when the remote storage was mounted on the server). Is there a debug switch or something for the client?

Maybe it is mere slowness?

Best,

Claus

**Comment by guruz** [comment]
Can you guys try a nightly build of 1.8? (remember to have backups..)
We use a new method/network code for discovering remote directories there, I think it could fix the issue.

**Comment by geez0x1** [comment]
Sorry I don't really have the time (especially to recover if things do not go as planned) do try a nightly right now; when is 1.8 due? (I can't seem to find a planned release date anywhere)

**Comment by guruz** [comment]
1.8rc1 is out.

**Comment by guruz** [comment]
Please comment if this still happens with one of the1.8 nightly builds:
http://download.owncloud.com/desktop/daily/
