### ISSUE TITLE
Settings dialog top navigation looks strange in OS’s other than OS X

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#2711]
For OS X the top navigation in the settings dialog is ok. For other operating systems, having it to the left looked much better. There is just no good widget to make it look nice on top.

It will also be way better for the multi-account feature so we can have the accounts listed.

 cc @danimo @dragotin

**Comment by danimo** [comment]
@jancborchardt on the contrary: This way we have a consistent design, and can make the accounts go on the right side. As to "there is no good widget to make it look nice": Thunderbird does the same, but I agree it looks better because they have a) more items and b) our icons are too monotone and lack detail to be scaled up. I think we should rather work on providing better icons and tweak the widget than providing different layouts.

**Comment by dragotin** [comment]
I agree to jan tbh. We agreed long time ago that we line up the different accounts underneath (or above) the tabs for General, Activity and Network.

Activity could also be somehow removed, as it is account related and maybe moved to each account view.

**Comment by guruz** [comment]
Please re-evaluate

**Comment by jancborchardt** [comment]
We have to fix some details, but in general now with the polishing during 2.0 it was much improved! :)
