### ISSUE TITLE
Weird thing with Dropbox

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/client#2737]
### Expected behaviour

I add a dropbox account in my owncloud account to be able to have access to these files directly.
So everything works fine, the installation has been easy but I I saw that my client delete the folder then everyfile and few minutes later restart to download every files..
Don't understand why.
Nothing has changed from my side.
So I send you the log file from yesterday filtered to you to be able to see what's is going on with the server. 
### Actual behaviour

Clienet should not delete the folder and restart download

### Steps to reproduce
1)	add a dropbox account in my owncloud account to be able to have access to these files directly. 
2)	Install was fine
3)     	

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend:

### Client configuration
Client version:

Operating system:

OS language:

Installation path of client:

### Logs

Logs can be found at s3 under github-issues/2737

**Comment by guruz** [comment]
@LukasReschke can help with the DropBox-storage-backend.. ;-)

**Comment by LukasReschke** [comment]
Just saying that those `Client configuration` and `Server configuration` fields are there for a reason…

**Comment by danimo** [comment]
I guess what Lukas is trying to say: We need some more information

**Comment by MorrisJobke** [comment]
@icewind1991 Could this be caused by an problem with a short outage of the connection to dropbox and later being able to connect to dropbox again?

**Comment by MorrisJobke** [comment]
o.O No please don't create milestones for me. Assigned is enough

**Comment by LukasReschke** [comment]
@guruz When can we expect mirall in the "morrisjobke" release?

**Comment by MorrisJobke** [comment]
I can't setup dropbox and test due to https://github.com/owncloud/core/issues/13698 :(

**Comment by MorrisJobke** [comment]
What I tried:

* setup Dropbox external storage
* put some test files in
* setup a sync client and sync everything down
* sync some files up to the Dropbox folder via client
* cut the connection to dropbox setting `api.dropbox.com` and `api-content.dropbox.com` to `127.0.0.1`
     * sync client still works
     * you can browse also the dropbox folder in the web UI - it just says: "storage full: insufficient storage", but the files are still listed
* I added a file to the sync client dropbox folder
* same error message like in the web UI:
![dropbox-down](https://cloud.githubusercontent.com/assets/245432/5916520/75294258-a612-11e4-94c8-45e56f3188e2.png)

I tested this on todays stable7 owncloud/core@80560e7

I guess this is not limited to dropbox but rather to the storage handling in core I guess. Maybe this is just caused by the slowness of the dropbox external storage and a race condition can be met easier. But this is just a wild guess.

As long as we didn't know more exact steps, logs and environment details, we can do nothing.

**Comment by danimo** [comment]
@iliyasbasir Please open a server ticket about this issue then.
