### ISSUE TITLE
[Feature] Client-side file encryption

### ISSUE THREAD

**Issue by lasselasse** [owncloud/client#275]
Please add the capability for client-side file encryption to the sync client: All files transferred to/from the server are encrypted/decrypted on the fly using a password given by the user. This would be an optional per-sync setting in the client. (I envision a cute padlock symbol to mark entries that have this feature turned on.) 

If we accept that file/folder names are _not_ encrypted (the user needs to be warned about this!), the implementation should be fairly easy since there only needs to be encryption/decryption added to the upload/download streaming of the file data. File metadata is not affected and thus the update detection does not need to be changed. Also, the user would only need to be prompted for the password when file data is actually transferred.

Since most cloud storage does not support client-side encryption, this would be a quite unique feature ownCloud!

**Comment by scheppi2610** [comment]
@jancborchert:
Dear jan, may I once again ask if your opinion on this topic might have changed? I want to use oc in my enterprise environment and i would really like to have an encryption module integrated into the client seamlessly.
I agree that this would break the webinterface partly. But this is depending on the modularity of the integration.
From my point if view there are two possible solutions:
a) one accepts that a truely secure filestorage cannot be accessed without supplying your private key some way, so you need a local verification by an app excluding a webinterface, or
b) you add an option to the settings to encrypt only all contents of one specific folder which could combine acessibility and security.
Any other ideas welcome.
I have opened a budget in my company to solve this issue, though i do not have any connection to developers. That's why this is my startingpoint.

Rgds, scheppi

**Comment by dragotin** [comment]
Just contribute: #4327
