### ISSUE TITLE
Updated bundled sqlite3

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2750]
We bundle 3.8.6 1d5b3aadeaf6f0cfb49aa97176588bbbaee6c3c3
Current version is 3.8.8.1 https://sqlite.org/changes.html

@ckamm Can you also check the changelog, maybe it has a chance to fix https://github.com/owncloud/client/issues/2701#issuecomment-71799379

**Comment by guruz** [comment]
@danimo @dragotin @ogoffart The discussion would also be if we switch Linux to the bundled one.. https://github.com/owncloud/client/issues/2492

**Comment by ckamm** [comment]
I updated our bundled version to 3.8.8.1 but didn't see anything relating to #2701 in the changelog. I think switching to the bundled sqlite version on linux would make sense. The performance difference to older versions seems to be enormous.

**Comment by dragotin** [comment]
Using a bundled version under Linux is dangerous because there are so many linux distros out there and there might be other components involved that use the systems sqlite, for example Webkit.

I am fine with adding an alternative, ie. if cmake has not found the sqlite devel files, it falls back on the bundled one, IF somebody has prooved that it works with Webkit.

**Comment by guruz** [comment]
I'm closing this issue then, there is no good solution as we're too afraid of symbol clashes etc..

This unfortunately means that users of older Linux distributions might see the client as slower than it needs to be with the newer versions.

**Comment by rullzer** [comment]
Bundling on linux is always a tricky thing. I personally am not a big fan of bundled versions. For the same reason I am not a fan of static linking. If a bug is found in sqlite then all of a sudden I have to remember to upgrade 2 places.

So I would suggest just bundle it. But make it so that the user can chose to use the system version. And just print a warning if the old version is used.

**Comment by guruz** [comment]
@rullzer Do you find an easy way to tell cmake that a certain version is recommended but not requirted? Maybe it can auto-print a notice.
