### ISSUE TITLE
[Enhancement] Add button to edit sync-exclude.lst

### ISSUE THREAD

**Issue by Morganlej** [owncloud/client#2816]
Why
1) The button immediately give a hint about how to manage the greyed out list. (i never saw the helping instruction that pops up after a couple seconds hovering over the list, so i even started a forum thread about how to manipulate it... - probably other experience the same difficulty)

2)  Much easier access than to remember what the popup say and type it.

So, put a [Edit system defaults] button somewhere in that dialog, picture in http://doc.owncloud.org/desktop/1.7/navigating.html#using-the-ignored-files-editor

Possibly it is technically easier to open the systems default file browser on the correct folder, and then the user can se the file and open using preferred editor.

Also: i presume this is changing defaults for all users on the system?
Add that to a descriptive text. (the hovering text today do not say)
Or maybe even we should discuss if the settings should be per user and not per system?
-so the sync-exclude.lst should be in users home folder instead, and if not existing fall back to system...

**Comment by matteoipri** [comment]
Hi,
I also wanted to edit the default sync exclude list.
I think that the default sync exclude list should be user editable and a per user setting.
Since some of the excluded patterns are due to (possible) limitations of the server and its security, I think the best way would be let the server tell the client what patterns are excluded server side and these should not be user editable, while other default patterns (that are obviously useful to the majority of users) should be user editable.
That's my 2 cents.

**Comment by ogoffart** [comment]
The default list is not meant to be edited
