### ISSUE TITLE
Performance and sync issues

### ISSUE THREAD

**Issue by shoeper** [owncloud/client#2825]
Problems:
- Client only uses 25% CPU (server not even 25% and hard drives are no issue, too)
- client syncs files being already on the server and the client on setup
- client gives wrong error messages: e.g. if a folder is deleted while its sceduled for sync client says 500 internal server error but the client shouldn't have send any request regarding that (non existing) folder to the server.

Aftereffects:
- Client is not as fast as it could be (only 30MB/s instead of possible 60<MB/s (via samba I get 100<MB/s - I don't expect that from owncloud but a better client would make possible more speed))
- Client hangs and download speed indicator is wrong (shows e.g. 11MB/s instead of >30MB/s)
- Files already being on client and server are downloaded again (requiring very much time > 1TB of data)

**Comment by danimo** [comment]
Please open one issue per problem that you are observing. Otherwise its impossible to track in a meaningful way:

1. The bottleneck here is the server, not the client. That said we are working with the server team to increase parallelism for 1.8/8.0.
2. We need more information to track that down. Please open a new ticket, and fill in the template provided in the contribution guidelines linked from there.
3. I'm pretty sure this is not a wrong error message (the client doesn't produce any on its own), but we need to have more debugging information. Instructions for 2 apply here, too.

**Comment by shoeper** [comment]
The bottleneck for a lagging client and wrong speed information is definetly not server related. But ok I'm going to create new issues later on.

**Comment by danimo** [comment]
@shoeper Oh, I skipped the line. yes the speedindicator is buggy, and there should already be an issue.
