### ISSUE TITLE
On authentication failure do not pop up Password dialog

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2848]
If the client during normal operation suddenly gets an authentication error, it should not immediately pop up the password dialog (modal) but show a user notification in the  tray and go into the logged-off mode.

It could even try a couple of times to relogin using the same credentials, because it might be that the user backend was offline temporarily.

This enhancement request was derived from https://github.com/owncloud/client/issues/2615

**Comment by MTRichards** [comment]
Would also be good to do it in such a way that 3 failed attempts because of a password change (90 day password change policy for example) don't lock the user out of the directory.

**Comment by MTRichards** [comment]
Is this really 1.8.1 bug fix planned @dragotin ? Or is that just a placeholder?

**Comment by dragotin** [comment]
@MTRichards do you think it is ok to try "silenty" three times and if this fails, come up with the password dialog, because the password probably has changed on server side?

And yes, that is for 1.8.1 if you agree.

**Comment by MTRichards** [comment]
In general yes.  Sometimes this locks the user ldap account though, if set often three is the threshold for locking. Is two tries possible?

**Comment by MTRichards** [comment]
Of maybe a pause before trying again so the server can restart?

**Comment by guruz** [comment]
See also discussion on https://github.com/owncloud/client/issues/2879#issuecomment-79066670

**Comment by MTRichards** [comment]
@dragotin @danimo Planned still for 1.8.1?

**Comment by dragotin** [comment]
@ckamm I think you worked in that corner recently, do you think there can be a solution for 1.8.1? I think we should include it.

**Comment by ckamm** [comment]
@dragotin @MTRichards I'll look at it. I'd be very unhappy about accidentally locking accounts by retrying. Can we somehow determine whether retrying a failing auth has side effects?

**Comment by jcfischer** [comment]
3 tries is probably not enough (if the client retries every n seconds, that allows a window of 3*n). I would imagine a "ease off" period of a few minutes to be sensible.


We have now implemented several LDAP servers behind a load balancer and setup a backup ldap server in the admin UI of oC so hopefully this problem is solved for us by throwing more infrastructure at it.

**Comment by guruz** [comment]
@dragotin @ckamm  Why not show the dialogue and pre-fill it with the old/current password as suggested by @blizzz in https://github.com/owncloud/client/issues/2879#issuecomment-79225505

**Comment by ckamm** [comment]
It's unclear whether we should do this, see discussion in #2186

**Comment by ckamm** [comment]
We talked about this issue in detail. The outcome was that we could handle the temporary authentication failure much better if the server told us that the auth backend is down, instead of replying with a generic auth failure message.

We did discuss workarounds where we
* normally don't send the Authorization header along with the session cookie
* upon auth failure retry with the same session cookie for a while (guessing that maybe it's a temporary failure)
* eventually retry with the user credentials (dangerous because of account lockouts #2186)
* and only if that fails ask the user for his password

**Comment by guruz** [comment]
@DeepDiver1975 @blizzz @LukasReschke FYI ^^

**Comment by ckamm** [comment]
We haven't committed to implementing the workaround. It's definitely not in scope for 1.8.1. If we can get a more verbose auth error from the server this could be relevant for 1.9.

**Comment by ckamm** [comment]
Starting with server version 8.1 an unavailable auth backend will result in a 500 error, see owncloud/core#17192.

**Comment by ckamm** [comment]
As per owncloud/core#17192 the server has been adjusted to return 503 in this case.

**Comment by ckamm** [comment]
And with that server change, no further client modification is necessary: The 503 reply will change the account state to "Service unavailable" and not trigger a credential reset.

Test notes:
* Needs a recent server. master will do, the change is also in the process of being backported to 8.1, see https://github.com/owncloud/core/pull/17266
* Simulate the LDAP auth backend being unavailable by switching off the LDAP server

**Comment by Dianafg76** [comment]
@ckamm I tested this issue, and working fine
Many thanks, :-)
Desktop v  ownCloud-2.0.0.2538-nightly20150715.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1.0","edition":""}
