### ISSUE TITLE
[ownBrander] [Just one folder] If the folder name includes special characters, a new folder is created

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#2936]
STEPS:
1.- Select to sync just one folder
2.- The folder name includes special characters, such as: "üla üla"
3.- Generate the client
4.- After installing it, check that a new folder is created: "Ã¼la Ã¼la"

EXPECTED BEHAVIOR:
The define folder, is the sync one

SERVER:
{"installed":true,"maintenance":false,"version":"8.1.0.0","versionstring":"8.1 pre alpha","edition":""}

CLIENT:
1.7.1

**Comment by guruz** [comment]
> 3.- Generate the client

Is this an ownbrander / custom theme issue?

**Comment by rperezb** [comment]
Yes, this is a custom theme issue

**Comment by Dianafg76** [comment]
@guruz The same thing happens
STEPS:
1.- Select to sync just one folder
2.- The folder name includes special characters, such as: "üla üla"
3.- Generate the client
4.- After installing it, check that a new folder is created: "Ã¼la Ã¼la"

EXPECTED BEHAVIOR:
The define folder, is the sync one

SERVER: {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Desktop v: ownCloud-2.1.0.2924-nightly20151201.pkg

**Comment by dragotin** [comment]
Moving to next minor rel.

**Comment by danimo** [comment]
@rperezb This is an ownBrander bug: The String that OB creates needs to be wrapped in `QString::fromUtf8()`

**Comment by rperezb** [comment]
Done, thx
Reference: https://github.com/owncloud/ownbrander/issues/500
