### ISSUE TITLE
Schedule Quota job only when Settings dialog is displayed or Tray menu is clicked?

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2951]
I think @ogoffart had suggested this some days ago.

CC @PVince81 who had been wondering about request amounts.

**Comment by strugee** [comment]
Clarifying question - you mean that the client would only run a sync when Settings is open or the tray menu is clicked?

**Comment by PVince81** [comment]
No, that wouldn't make sense. The sync job would always run as before.

It's just that additionally to that, there is another job which only purpose is to update the quota information. Instead of reading the quota from the server often, it would only read it when the dialog is open, which makes sense if the quota value isn't used for anything else than displaying it.

**Comment by ogoffart** [comment]
https://github.com/owncloud/client/pull/3378
