### ISSUE TITLE
409 Conflict on file deletion

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#2955]
When I delete a file locally, it doesn't get deleted from the ownloud. The comment that appears in the Activity tab of the client says "409 Conflict". In fact, the file disappears from the cloud (that is, it gets moved into "Deleted files" on ownCloud) only when I erase it permanently from the Recycle Bin on my computer.

It seems like a bug to me... or is it supposed to work like this? My client version is 1.7.0. 

No proxy configuration
oC6.0.6

### LOGs

For the test, I did the following: copied a file (bookmarks.html) into my local drive, then deleted it and then emptied the recycle bin.
I am sending you the two F12 log output files:

- "log1": after deleting the file locally
- "log2": after emptying the Recycle bin

S3-ownCloud\Shared\owncloud\support\github-issues\client\2955

@MorrisJobke 

00002611

**Comment by dragotin** [comment]
Both logfiles are exactly the same. 

But I think here is what happens: The user syncs the entire path d:\, the whole partition. The partition has it's own trashbin which is also synced, even though it is not an ordinary dir. The client detects the file ```bookmarks.html``` as renamed, probably into the trashbin.

The solution to this is: We will add the Trashbin directory name to the blacklist so that it does not traverse into.

**Comment by cdamken** [comment]
@dragotin could you add the Recycled directory to the default ignore list?

Thank you in advance :+1:

**Comment by danimo** [comment]
The name is `$Recycled.Bin`.

**Comment by dragotin** [comment]
@cdamken would be great if you could test that with 1.8.0 and close the issue if it works. Thx.

**Comment by guruz** [comment]
> The user syncs the entire path d:\, the whole partition. The partition has it's own trashbin which is also synced, even though it is not an ordinary dir.

This could have also been fixed by implementing https://github.com/owncloud/client/issues/2086

**Comment by cdamken** [comment]
### Thanks guys!
