### ISSUE TITLE
automatic update - sparkle feed problem?

### ISSUE THREAD

**Issue by tessus** [owncloud/client#3000]
It's been almost a week since 1.8.0 has been released, but for some reason https://updates.owncloud.com/client/?version=1.7.1.1655&platform=macos&oem=ownCloud&sparkle=true is empty.

Is there a problem with the feed?

**Comment by danimo** [comment]
Everything is fine. We do not push the update immediately in case there are any difficulties that show right after release.

**Comment by tessus** [comment]
Thanks for the info. Just out of curiosity: what's the timeframe of the delay?
Don't you think that 3 days would be enough?

Also, I don't quite understand the delay at all. If people see the update on
the web site, it is more than likey they will update manually right away.

**Comment by danimo** [comment]
In the last releases, we've been waiting a bit more than a week. From experience it takes about that much time to qualify if a release has any major issues or now (i.e. see if it's isolated issues, etc).

**Comment by tessus** [comment]
@danimo it's has been 2 weeks and there's still no update in the feed. to be exact the feed states the following: Please come back later. 

I'm pretty sure that people don't trust this update system anymore. The last 4 times I've updated manually, and so has everyone else I know who uses the ownCloud client.

**Comment by danimo** [comment]
@tessus It's not 'reliable' as we had to throttle downloads due to high load. As a consequence, only every 10th user received an update notification. We'll lift this limit this week, and we'll continue to work on automatically easing out the limits. Additionally, we're also looking into deploying more download servers or using a CDN.

**Comment by cheesecracker** [comment]
What is the mechanism on this "automatic" update?  Does the server push the update notification to EVERY connected client *at the same time*?  Or does the server provide update only to clients which ask for notification?  Instead of giving every 10th user the notification, can't you "spread" the notification among a longer period?

**Comment by danimo** [comment]
No, the clients poll. Once at startup at the moment, future version will poll more often, see #3044. I'll close this report, since the work should be done over there.

**Comment by cheesecracker** [comment]
OK thanks.  Then what did you mean by "only every 10th user received an update notification"?  That means for every 10 polls, only one of them (the 10th one?) receives the notification that update is available?
If that's the case, I understand why some clients *never* get update.  If this limit is lifted for version 1.8, then it's OK.
