### ISSUE TITLE
Progress in settings: Reduce update interval of remaining time

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/client#3014]
There is no need to update the remaining time 10 times per second (or even much), because you cannot read it then, because it alwas changes. 2 update sper second should be fully enough.

cc @guruz

**Comment by guruz** [comment]
This (maybe) took a big amount of CPU on @nickvergessen 's machine.

**Comment by ckamm** [comment]
Note that my refactoring in #2328 already introduces a 1s timer for updating the estimates. I don't think it changes the mechanism with which the estimates are pushed to the ui though, so it'll likely be also with each transmissionProgress() emission.

**Comment by ckamm** [comment]
I'll check if I can do this for 1.8.1 in a way that doesn't gratuitously conflict with the refactoring.

**Comment by ckamm** [comment]
I did the change in ffd6c62, but at least on linux not many progress updates get skipped.

**Comment by ckamm** [comment]
I'm not happy with this kind of fix, since it may skip interesting updates. There's also a second slot connected to the progress info update that'd need throttling. We also fixed other bugs that had a much stronger performance impact. We'll revisit this once progress reporting has been further overhauled.

**Comment by ogoffart** [comment]
Closing old issue. 
The progress impl has changed a bit since that time, and nobody is complaining anymore it is too frequent.
