### ISSUE TITLE
Updater: Check for Updates per day, not (only) per restart

### ISSUE THREAD

**Issue by danimo** [owncloud/client#3044]
Right now, people that never restart their system might not get notifications about new version in time. This is a must on Windows, and an "if-possible" on Mac OS X.

### Acceptance criteria

- [x] Notification about new version must happen (passive, but visible)
- [x] Tested on Windows
- [x] Tested on Mac OS (if possible)

**Comment by danimo** [comment]
Proposal: Once we have downloaded an update, modify the color in the system tray and/or add a "Update & Restart" item in the menu.

**Comment by enoch85** [comment]
:+1: Finally! Thank you @danimo

**Comment by dragotin** [comment]
Not in the scope of a bugfix release.

**Comment by moscicki** [comment]
@dragotin: could we get this please in 1.8.2? I think this is a real problem because many users almost never restart their computers and we have no way of quickly pushing new releases onto them. I don't think it is a hard thing to implement, is it? It looks to me critical for larger service operations.

**Comment by dragotin** [comment]
https://github.com/owncloud/client/pull/3344

**Comment by dragotin** [comment]
@owncloud/desktop-developers pls review #3344

**Comment by danimo** [comment]
@dragotin Do you want to drive this task?

**Comment by dragotin** [comment]
It's in master now.

**Comment by Dianafg76** [comment]
@danimo I tested this issue, and If I reboot my system ( Windows computer ) my system does not receive notification of a new version in time. But if I turn off the computer and if I turn on, my system receives notification of a new version in time. In Windows.
I Desktop v1.8.2 (build 5171 ) installed , if restart or shut down the computer , ask me "is available a new version of the client program ownCloud " . Customer owncloud 1.8.4 (build 5267 ) can be downloaded .....

**Comment by dragotin** [comment]
@Dianafg76 as I said, the new updater functionality of regular updates is only existing in the 2.0.0 nightly builds. So it does not make sense to test anything older than 2.0.0 nightlies.

What sounds like a feasible test is to let a nightly client run for a longer time through a proxy, ie. mitmproxy. Check there if it connects to the update server regularly. Since the default update frequency is quite high, you should set the paramter ```updateCheckInterval``` in the config file to lets say 300001 (note the one at the end). That makes it check every fife minutes.

**Comment by Dianafg76** [comment]
@dragotin Ok, sorry

**Comment by ogoffart** [comment]
I assume this is fixed.
