### ISSUE TITLE
Linux client uses insecure storage for password

### ISSUE THREAD

**Issue by jamincollins** [owncloud/client#3060]
I recently looked into how the ownCloud client was storing user passwords and found that it was using the Gnome Keyring Daemon.  The Gnome Keyring Daemon is not a secure storage location, this has been discuss off and on for a while now:

http://mdeslaur.blogspot.com/2009/11/gnome-keyring.html
https://mail.gnome.org/archives/gnome-keyring-list/2010-December/msg00013.html

**Comment by danimo** [comment]
Please file this issue against https://github.com/frankosterfeld/qtkeychain, the library that we use. That said, we came from _actually_ storing the file in plain text, which opens other attack vectors. We are not going to roll our own security here.

**Comment by mhogomchungu** [comment]
There is another library called lxqt_wallet[1] that tries to solve the identified problem.

The library gives a consistent API[2] for gnome's keyring,kde kwallet and an internal storage system that solves the mentioned problem.

With the internal storage system,each application maintains its own secrets and one application can not read another application secrets simply because the other application has its secrets unlocked.

I created this library precisely because i did not like the behavior the OP complained about.

[1] https://github.com/mhogomchungu/lxqt_wallet

[2] https://github.com/mhogomchungu/lxqt_wallet/blob/master/frontend/lxqt_wallet.h
