### ISSUE TITLE
Missing monochrome icon

### ISSUE THREAD

**Issue by monreal** [owncloud/client#3069]
Mirall 1.7.1 (configured to use monochrome icons) shows a color icon in certain situations:

![owncloud-bw-icon](https://cloud.githubusercontent.com/assets/54005/6992549/bda031de-dad5-11e4-8981-28512ea7d844.png)

**Comment by danimo** [comment]
Can you elaborate on the exact situations? Can you reproduce with 1.8 still?

**Comment by monreal** [comment]
Wow, I did not notice 1.8 was out already... will have to try that.

I got this icon last when a local file changed during sync. It is also shown when some files are not synced because of some previous errors I think.

**Comment by danimo** [comment]
How did you make the icons appear on top in the first place (assuming this is GNOME 3)?

**Comment by monreal** [comment]
Right, this is GNOME 3 with the Topicons extension. It just embeds the classic tray there.

**Comment by guruz** [comment]
@monreal Did you try 1.8? :)

**Comment by monreal** [comment]
@guruz sadly no, it will have to wait until I get my new PC running this weekend

**Comment by guruz** [comment]
@jospoortvliet @danimo Is this related to the discussion you had this morning on IRC?

**Comment by jospoortvliet** [comment]
@guruz no, its not, but I know what is wrong ;-)

Looking at the icons we have, there simply aren't as many monochrome as color icons. For example, state-warning is missing, which is why @monreal sees the color icon.

compare https://github.com/owncloud/client/tree/master/theme/colored
vs 
https://github.com/owncloud/client/tree/master/theme/white

(part of the difference is of course that the colored theme has hiDPI versions and the white one doesn't)

**Comment by guruz** [comment]
@jancborchardt Is Achim on Github? Can we ping him for this?

**Comment by jancborchardt** [comment]
@guruz no, he doesn’t use Github. Mail him: mail at geissel dash informationsdesign dot de

**Comment by danimo** [comment]
I've mailed him. Let's see.

**Comment by danimo** [comment]
Please check with next nightly build

**Comment by Dianafg76** [comment]
I tested this issue, and the monochrome icons looks OK
Desktop v ownCloud-2.0.2.2714-nightly20150915.pkg 
Closed

**Comment by MorrisJobke** [comment]
With this change it's really hard to spot the actual state of the ownCloud client. Because it is only a little tray icon and every state has a circle under the cloud: You need to check the icon quite hard: cross in cycle, checkmark in cycle, sync in cycle, i in cycle ... all of them look very similar and are very hard to distinguish. cc @owncloud/designers

**Comment by MorrisJobke** [comment]
See for example https://github.com/owncloud/client/commit/2f20c15824bf1e92b9672b6398bed92da97c7896#diff-adc6b7c6ec9a9a0508eee08371cc1425

**Comment by jancborchardt** [comment]
@danimo @guruz I thought you mailed Achim to use the previous more clear icons?

**Comment by dragotin** [comment]
@jancborchardt neither @danimo nor @guruz has time to care about this. Can you please do it, or we have to stay with what we have. Thanks.

**Comment by guruz** [comment]
Even better would be if we could at-mention him on github
