### ISSUE TITLE
commit 03e23da6a319f0608747d7fb3ce287d47704b550 makes the ownCloud settings dialog show up on login on XFCE and Cinnamon

### ISSUE THREAD

**Issue by xuhdev** [owncloud/client#3070]
The commit 03e23da6a319f0608747d7fb3ce287d47704b550 makes the ownCloud settings dialog show up on login if the "Launch on System Startup" is checked on Linux.

Expected result: the client should silently start up.

Reproduce: Check "Launch on System Startup"; Log out and log in again.

**Comment by ogoffart** [comment]
I believe that it is because owncloud is started twice.  Once because xfce restores the sessions perhaps,  and once because of the auto-start shortcut that we install.

It would be nice to know which one is started fist.  Depending on that we can look into the option on how to solve that. 
Possibly we could add a special option to the auto-start shortcut not to show the window.
Or we could add a command line option in the desktop shortcut to actually show the window (because that's what user wants when the click on the shortcut on windows)
Or we could check if we can play with QSessionManager or QApplication::isSessionRestored

**Comment by xuhdev** [comment]
I actually have disabled my session restore for both my cinnamon and xfce. I can find an autostart file in ~/.config/autostart , but seems no more autostart configuration.

**Comment by xuhdev** [comment]
I've found that I've also set owncloud in my xfce session auto startup option. After the owncloud item in xfce autostartup option was unchecked, this issue was resolved.

Yes, it seems to be caused by starting up twice. It does not affect me any more, but I would still like to help if you want to get this fixed in some situations.

**Comment by dragotin** [comment]
I saw that with KDE as well on Chemnitzer Linuxtage. Client was started twice when it was in the autostart section, and popped up the dialog as a result. Not sure what we can do about that tough.

**Comment by FuturePilot** [comment]
Happens on KDE as well. I guess it makes sense that it's getting started twice as KDE is restoring it from the previous session as I don't quit the client when I log off.

**Comment by guruz** [comment]
Possibly fixed with the commit above for 2.0, please test..
