### ISSUE TITLE
Mac OS: temperature problem

### ISSUE THREAD

**Issue by martinbaeumler** [owncloud/client#3098]
Mac OS client laptop heats very strong. Unit: 1.4 GHz Intel Core 2 Duo with 2 GB of RAM running Yosemite 10:10 heats up within 2 minutes in which the ownCloud client uploads files. Cooler starts getting very loud. The close all other apps has no effect on the situation.

Any further information needed? Let me know what I can deliver to help.

**Comment by danimo** [comment]
See https://doc.owncloud.org/desktop/1.8/troubleshooting.html, we need the log file, also:

* How many files are you going to sync?
* Is this the initial sync?

**Comment by martinbaeumler** [comment]
- I started with about 130 files and added another 13.000 while the sync was in progress. 
- yes, this is the initial sync.

**Comment by martinbaeumler** [comment]
- problem was already there when I started with the 130

**Comment by guruz** [comment]
> Any further information needed? 

Which version of the client?

**Comment by VincentvgNn** [comment]
@martinbaeumler 
In a test I had client version 1.8.0 running on Win XP and it was unusable due to the high processor load. Since I installed ownCloud-1.8.0.4938-nightly20150411 it's running fine again.
So try to install the latest version from http://download.owncloud.com/desktop/daily/?C=M;O=D
I use the client in combination with server 8.0.2.

**Comment by guruz** [comment]
@martinbaeumler Have you managed to try again with a more recent build? Maybe of 2.0 even?

http://download.owncloud.com/desktop/daily/
