### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by fduraibi** [owncloud/client#3146]
Is there any plan on supporting http2?
Since I believe it will help increase the performance specially when syncing many small files over SSL.

Based on this https://github.com/owncloud/core/issues/15715 it seems that the server is ready (just enable http2 in the webserver like apache or nginx).

**Comment by danimo** [comment]
We will have HTTP 2.0 support through Qt, as we rely on its networking stack. They will probably evolve this out of the existing SPDY support.

@guruz I could not find an upstream issue in the Qt bug tracker. Is there one?

**Comment by guruz** [comment]
I had started to investigate SPDY (and modified Qt a bit to support the SPDY versions that nginx speaks) but then stopped because the current problem is the server booting up the huge PHP app/dependencies. So SPDY would not improve anything until the server gets slimmer there.

https://github.com/owncloud/core/issues/12001#issuecomment-62161489

CC @peter-ha

**Comment by peter-ha** [comment]
This is the upstream issue: https://bugreports.qt.io/browse/QTBUG-44522

HTTP/2 evolved out of the SPDY standard; there are 2 building blocks needed on top of modifying the current SPDY implementation:
* ALPN TLS extension instead of NPN
* the new compression scheme

**Comment by guruz** [comment]
Timur Pocheptsov from the Qt Company is working on it :-)

https://codereview.qt-project.org/#/c/145762/

**Comment by guruz** [comment]
https://blogs.dropbox.com/tech/2016/05/enabling-http2-for-dropbox-web-services-experiences-and-observations/
"Increased POST request latency due to the specific HTTP/2 implementation in Nginx 1.9.15." FYI @dragotin 

SSL stuff:
https://ma.ttias.be/day-google-chrome-disables-http2-nearly-everyone-may-31st-2016/

**Comment by dragotin** [comment]
Pushed out to at least 2.4.0

**Comment by mightyBroccoli** [comment]
Are there any news regarding this topic? It would be REALLY nice to have the feature in the near future as more and more servers are able to connect via http2

**Comment by ogoffart** [comment]
pull request: https://github.com/owncloud/client/pull/5659

**Comment by ogoffart** [comment]
Closing this issue,  the progress can be still tracked on the pull request: 
https://github.com/owncloud/client/pull/5659

**Comment by guruz** [comment]
macOS package, please test https://download.owncloud.com/desktop/testing/ownCloud-qt5.10.1-2.4.2.951124.pkg

**Comment by guruz** [comment]
Better macOS package here, the other one might be broken on some OS:
https://download.owncloud.com/desktop/testing/ownCloud-qt5.10.1-2.4.2.951824.pkg

**Comment by guruz** [comment]
Has anyone seen issues with HTTP2 in 2.6.0 similar as in https://github.com/owncloud/client/issues/7610 ?
