### ISSUE TITLE
Please add support for client certificates in desktop client

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/client#3181]
To improve security, i have added SSLVerifyClient to apache configuration. The access is working great on browsers (imported the client certificate on firefox and chrome), but this setup appears to break desktop client. Would it be possible add an option to import a client certificate on the desktop client ?

**Comment by Jas2Ma** [comment]
owncloud-client is using operating system certificates.
Which OS do you use?

**Comment by jsalatiel** [comment]
Server - Ubuntu 14.04Desktop - Linux

**Comment by Jas2Ma** [comment]
I'm sorry. I think I misunderstood you in the first place. You use client-certificates to authenticate users? Your problem is not a self signed server certificate?

**Comment by jsalatiel** [comment]
I use client certificates to be able to reach my https://server/owncloud location, and there it prompts for the username/password as usual.

**Comment by Jas2Ma** [comment]
I can't help you with that. You will have to wait for a developer to give his two cents.


But I can't imagine, that they will spend much effort on client certificates integration, since you need a system to deploy your client certificates to users. And without this system all the share functions of owncloud will be useless.

**Comment by LukasReschke** [comment]
Please search for existing issues before opening news ones. Thanks.

Duplicate of https://github.com/owncloud/client/issues/69
