### ISSUE TITLE
Can't select the new Folder for Sync

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3190]
### Steps to reproduce
1. Open your ownCloud desktop client 
2. Select to sync all your data in a folder called  'ownCloud'
3. Select to "Add Folder..." 
4. Click on "Choose.."
5. Select the local folder on your computer to Sync, for example "Sync folder3"
6. Press "Open", and next press "Continue"
7. Click on "Create folder", create it on the root, called it "test"
8.  Select test

### Expected behaviour
You should be able to add the Folder

### Actual behaviour
A warning appears, and you can't continue:
![screen shot 2015-05-05 at 09 23 59](https://cloud.githubusercontent.com/assets/12032058/7468413/8b431e9a-f308-11e4-9978-8fac8d5ffb2f.png)

###Version Desktop
Version 1.8.1.2326-nightly20150504 MAC

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}
Checked with a server with permanent redirection
LDAP and Encryption enable

**Comment by guruz** [comment]
I think this is a artificial limitation that had been discussed before with @jancborchardt and @MTRichards 
Maybe it should be lifted

**Comment by jancborchardt** [comment]
This is not artificial. The problem is:
1. You have your whole server root synced with your local »ownCloud« folder
2. You add a local folder outside of the »ownCloud« folder to sync with your server
3. First question: Where should it go? I assume the root folder.
4. Second question: Will it then be synced down into the local »ownCloud« folder again, hence duplicating it?

Even if it would technically be doable (put the folder in the root, but don’t sync it down _again_), it would be confusing as on the server the one folder is on the same root level but on the computer it is somewhere completely different.
(Now when all your folders are picked via the »Add folder« dialog that is different, because everything is all over the place.)

**Comment by danimo** [comment]
We could solve this by allowing the same user/server on multi accounts, but allow different folder pairs. If we really want to, that is.

**Comment by jancborchardt** [comment]
@danimo that sounds like a crazy and absolutely undiscoverable workaround though.

**Comment by jancborchardt** [comment]
Also – I would say no, we do not want to support this. For reasons stated above.

@MTRichards please chime in.

**Comment by dragotin** [comment]
.o0( popcorn )

**Comment by dragotin** [comment]
I think the "Add folder" button should be disabled if the user syncs the entire ownCloud to a local dir. We want to reduce complexity.

**Comment by MTRichards** [comment]
This is interesting because I ran into the same thing yesterday. We mixed two capabilities, the sync all with selective sync, and the sync whatever folders you want. I understand the overall point, if you sync the root folder on one machine, you can't sync other folders on that machine - it just doesn't work. And this is by design.

That said, I like @dragotin 's solutions on how to mix - if you sync the entire root folder on that client, you can't pick a new folder to sync (except on a second ownCloud account of course).

**Comment by guruz** [comment]
> .o0( popcorn )


![img_20150505_145845](https://cloud.githubusercontent.com/assets/959327/7472915/687f0d86-f337-11e4-8dd7-0272c03624ac.jpg)

**Comment by guruz** [comment]
> I understand the overall point, if you sync the root folder on one machine, you can't sync other folders on that machine - it just doesn't work. And this is by design.

See also https://github.com/owncloud/client/issues/1122 ... Not sure if good design.

**Comment by jancborchardt** [comment]
> I think the "Add folder" button should be disabled if the user syncs the entire ownCloud to a local dir. We want to reduce complexity.

This sounds like a good solution first, but makes it not very clear _why_ it is available but disabled. Remember this is the default state. So instead showing that notice in the »Add folder« dialog is definitely better than just disabling it.

**Comment by MTRichards** [comment]
Sure, I would do both - disable the button and explain why - the current warning is for the purpose of explaining. Problem is it is already well into the "add a folder" dialog when you get the warning, so you want to do something and just can't, and that is frustrating.

Perhaps just a "You are already syncing all server folders with this client." if you mouse over the disabled button, something like that?

**Comment by MTRichards** [comment]
Also the same as: https://github.com/owncloud/client/issues/2147

**Comment by jancborchardt** [comment]
@MTRichards ok, that’s a good solution. @dragotin if a title / hover like that works, then let’s do it.

**Comment by MTRichards** [comment]
>See also #1122 ... Not sure if good design.
Suggestions welcome :stuck_out_tongue_closed_eyes: 

We tried this with syncing all files, then a lower level folder called clientsync, then we tried it with syncing the whole tree again by default. Then we added selective sync to each syncing pair. Bottom line, there is no good default solution for everyone, just the best default solution for most. Right now, the default syncs all, and then advanced users can remove that and sync more of a one to one relationship. Any ideas on a better approach are welcome...

Anything I could come up with is just so convoluted and complex.

**Comment by dragotin** [comment]
ok, TODO: 
- [ ] If the entire ownCloud is synced, disable the *Add folder...* button
- [ ] if the *Add folder...* button is disabled, add a mouse-over text saying *"You are already syncing all server folders with this client."* Maybe add the local folder name to that message.
