### ISSUE TITLE
[Sharing link] Error code 404: with Folder (special characters)

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3193]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new folder, called a/a
4. Right click on the folder a/a
5. Select share with ownCloud

### Expected behaviour
You should notice that the folder is not synchronized to have special characters

### Actual behaviour
Is appears "OCS API error code:404". 
![screen shot 2015-05-05 at 10 19 28](https://cloud.githubusercontent.com/assets/12032058/7469131/56191942-f310-11e4-81af-bf5f29a30d8c.png)

###Version Desktop
Version 1.8.1.2326-nightly20150504 MAC

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}
Checked with a server with permanent redirection
LDAP and Encryption enable

Logs DESKTOP:

**Comment by rullzer** [comment]
It is because of the ":". Currently that char is blacklisted. So if you create a directory with a ":" it does not get synced and thus it can't be shared.

But this shows that we should somehow check for the item to be properly uploaded.

Other dirs with special chars work fine over here.
If you find a case that does not include a ":" please reopen.
