### ISSUE TITLE
Filenames containing ":" not synced?

### ISSUE THREAD

**Issue by cathalgarvey** [owncloud/client#3203]
Hi, just an observation here: my wife and I share files through Owncloud, and just discovered that files containing a colon character (`:`) do no sync correctly. I'm assuming this is a client error but might equally be server; her client indicated the file was synchronised successfully, but the file did not appear in the browser-client file list nor was is synchronised to my machine successfully (no mention of it in the network activity dialogue, in contrast to hers).

So...something funky afoot there. We changed the filenames, and sync proceeded as expected.

**Comment by ckamm** [comment]
@cathalgarvey Currently ownCloud will only sync files with names that are directly representable on all platforms. See #854 for an older bug report and https://github.com/owncloud/core/wiki/Cross-Platform-File-Handling for future development discussion.

**Comment by moscicki** [comment]
@dragotin, @ckamm, @MTRichards : now that the owncloud windows server is gone (as per announcement on owncloud.org) -- is there any problem to allow to sync these characters between two linux or mac clients? Current way of handling this is larger problem than people generally think because we have evidence than many users do not notice that these files are not synced. Ultimately these leads to data loss because users are convinced that all of their files are safe on the server while it is not a case.
I think all characters that are allowed on the server platform should be syncable (the easiest is to ignore these files on client platforms with restricted character set). This means that a Windows client will never try to download such a filename. I think that's a very simple and reasonable solution (avoiding any filename translation mess).

**Comment by Cyrille37** [comment]
Hi,
Another idea to avoid loosing no geek users : if a user write a incompatible filename in the sync folder, owncloud client open a popup that ask to the user to confirm the renaming of the file with the rights replacement chars.

**Comment by moscicki** [comment]
@Cyrille37: the problem is what if a user copied 500 filenames like this into a sync folder. Would you like to get this dialog box 500 times?

**Comment by cathalgarvey** [comment]
I'd at least like to be notified if a file will fail to sync; a message 
in the activity pane, or (in Gnome3, which adds nice tag-icons to 
files!) a little warning icon on a failed-to-sync file?

My problem was the silent failure, I understand that filename 
conventions suck. Failures should not be silent, I should be told if a 
file I share with another user will fail to synchronise.. or even 
back-up! What if I'd come complaining about a failed back-up and file 
integrity loss, and the answer was "we just don't warn the user about 
failed uploads"?

On 06/05/15 10:19, moscicki wrote:
> @Cyrille37 <https://github.com/Cyrille37>: the problem is what if a user
> copied 500 filenames like this into a sync folder. Would you like to get
> this dialog box 500 times?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/3203#issuecomment-99394093>.
>

-- 
Scientific Director, IndieBio Irish Programme
  Now running in Cork, Ireland May->July
  Learn more at http://eu.indie.bio and follow along!
Twitter:  @onetruecathal
Phone: +353876363185
miniLock: JjmYYngs7akLZUjkvFkuYdsZ3PyPHSZRBKNm6qTYKZfAM
peerio.com: cathalgarvey

**Comment by brevilo** [comment]
Same here. I just can't use ownCloud (Mac Client, Linux Server) until this is fixed...
