### ISSUE TITLE
client 1.8.0 windows - login timeout?

### ISSUE THREAD

**Issue by ngarafol** [owncloud/client#3209]
Hi,

Is it normal for owncloud client to ask for login credentials once per day? I am using shibboleth, so could it be due to shibboleth timeout? Default was 8h, so I upped it to 12h. But still should not be an issue since client is getting status.php every minute or so?
OC version used is 7.0.4.

Regards,
Nikola

**Comment by ckamm** [comment]
@ngarafol You should only be asked for your credentials again when your session cookie expires. Since we do an authed ping every 30 seconds, it should not usually expire while the client is running.

If this happens regularly to you and you don't believe it's a server issue, you could run the client with --logfile mylog.txt (see https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly) and then send the log or relevant parts to me once it happens again.

Note that if you're syncing a lot of data, the log file can become huge. Also note that it contains your server adress and file names, which may be sensitive data. (maybe test this with a fresh user)

**Comment by ngarafol** [comment]
Did not manage to set logging yet. Another question though: Is it normal that autentication window shows every time owncloud client application is run (first start only) and on every windows restart/bootup?

**Comment by ckamm** [comment]
@ngarafol The duration for which session cookies stay valid depends on the server. Usually it's longer than a day though. You are saying you observe this behavior?

* Boot computer
* Start OC client - enter password
* quit client, wait 5 min
* restart OC client - no password needed
* reboot computer
* start client - password required

If so, that'd indicate that it's not a server issue and I'd appreciate a log file for that last start of the owncloud client.
