### ISSUE TITLE
Usage over quota not properly represented by tray icon

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/client#3223]
When a user exceed his quota, there’s only a little red cross on the application in the systray and, for few seconds, a pop-up asking to look in the logs.
Our end-users won’t ever take care of theses advices, by far too small and insignificant. More problematic : after a few minutes, the little red cross disappears and the green « v » is again on the application. This green sign should means « everything is correct and all your files are sync with the server »… which is not…

Ref #1139 for the better quota reached representation in the tray area.

cc @jancborchardt

**Comment by jancborchardt** [comment]
> More problematic : after a few minutes, the little red cross disappears and the green « v » is again on the application.

This is the real problem. Once you are over quota, the red cross should not disappear until you are under it again.

**Comment by jancborchardt** [comment]
@dragotin this actually seems like a bug, not an enhancement.

**Comment by phil-davis** [comment]
I have searched about this for a while. It was also happening in https://github.com/owncloud/client/issues/725 back in 2013 and that was closed.
On 2.0 beta/nightly anything up to 17 Aug 2015 there is the same behaviour as I see in 1.8.4.
When I add a file to the client-side folders that will cause the server-side to go over quota, the client simply starts trying to upload the file. Some seconds later it gets "connection closed". The cycle goes on forever every 30 seconds or so.
In 1.8.4 I at least see a message in the log about "OCC::CheckQuotaJob created for". But in 2.0 log I do not even see this.
It would be really nice to give an "out of quota" message rather than just "connection closed". At the moment the user has to notice that they are close to quota and then surmise that quota is the problem.
I see this is for 2.0.1-next - I am happy to help if there is anything useful I can do towards this.

**Comment by dragotin** [comment]
@phil-davis the "connection closed" problem was a different thing.

In 2.0.1 you see an (soft error) message that tells you that a file could not be uploaded because the quota was exceeded. It is true that the red cross is only shown for a short time span, indicating that there is an error. But this goes away, as the problem is blacklisted. That is exactly what the blacklist is for and how it is designed: If there is a problem with an individual file (other files may still fit and be uploaded properly) it blacklists it to not annoy the user with the error. Note, that this is only for problems with individual files, and also that the client tries again later. That works as designed. 

What is missing is a more visible warning if the quota is above 80 percent.

**Comment by olivierche** [comment]
Hi,
Sorry to write here if it's not the right place as this bug is closed since 10 Sep 2015 and was for Milestone 2.0.2 but it seems that there's still no permanent visible "red cross" on systray when users are over quota (with 2.2 client version and 9.1.1 server)
Is it planned for a next ownCloud client version ?
