### ISSUE TITLE
[OS X] Copied link has bogus Pasted-Contact.vcf

### ISSUE THREAD

**Issue by scansec** [owncloud/client#3300]
Hello,

When using the copy share-link in the client, and pasting into another program (ex mail-client), it paste the content as a object called: Pasted-Contact.vcf, instead of a text-link

**Comment by scansec** [comment]
Using client 1.8.1 build 2335

**Comment by dragotin** [comment]
hmm, I am not sure if I understand correctly. Please try to explain a bit more in detail what you are doing and expecting. Thanks

**Comment by razyr** [comment]
When creating a link from the Mac OwnCloud client, select the "Copy Link" button and paste that link into an email.  The expected behaviour is that a hyperlink would be pasted from the clipboard.  What you get is a vcard contact as shown in the first image below.

![owncloud-link-bug-1](https://cloud.githubusercontent.com/assets/8116645/8159055/2ae14fec-1331-11e5-81ef-3f2acce73722.jpg)

Testing this further by looking at the received email, the "link" is presented as a vcard, consistent with what the Mac mail client showed above.  If you click the vcard, it downloads into your Contacts.   What we would expect is for the link to be displayed as hypertext and clicking that link would take you to the Owncloud instance to download the file.

![owncloud-link-bug-2](https://cloud.githubusercontent.com/assets/8116645/8159057/2e40e1de-1331-11e5-946b-7591c60d5b54.jpg)

**Comment by razyr** [comment]
More info on the above.

If you paste the copied link into an application such as TextEdit, you get the expected URL.  You can then copy/paste that URL from TextEdit into Mac Mail and you get the expected behaviour of a clickable link.

It seems as if this is a QT bug where the UTI isn't being set correctly by QClipboard::setText().   Other apps such as SlickEdit have had the same problem reported.  https://community.slickedit.com/index.php?topic=10962.0.   

UTI docs are here:   https://developer.apple.com/library/mac/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE

Docs on how UTI is implemented by OSX pasteboards is here:  https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/PasteboardGuide106/Articles/pbConcepts.html

**Comment by zocker22** [comment]
@razyr is right. I examined the clipboard with [ClipboardViewer](http://www.markdouma.com/developer/ClipboardViewer.zip) and found out, that when I copy a plain text from another application than it is only stored in the cliboard-spaces "public.utf8-plain-text" and "NSStringPBoardType". Which is absolutely enough.
<img width="546" alt="bildschirmfoto 2015-10-15 um 16 25 34" src="https://cloud.githubusercontent.com/assets/1318984/10516698/d4af01e4-7359-11e5-8592-512f5d079ded.png">

But when I copy the link via owncloud-client (rightclick ...) than the link is stored in 10 different clipboard-spaces. One of them (I guess the problematic one) is called public.vcard. So whenever I paste my clipboard into another application, it is up to the application to decide which clipboard space to use. Apple Mail apperently chooses "public.vcard" or "Apple VCard pasteboard type". (See attached image)
<img width="392" alt="bildschirmfoto 2015-10-15 um 16 24 49" src="https://cloud.githubusercontent.com/assets/1318984/10516699/d9e1933e-7359-11e5-9873-c89e21d0d441.png">

There must be a way to copy the string into only the plain-text section...

**Comment by razyr** [comment]
I think the "Needs Info" label could have been removed on this ticket back in June.   Not much more we can document as users, but as it stands this functionality is essentially broken for Mac users.

**Comment by Dianafg76** [comment]
@guruz, I tested this issue, and now:
The steps:
1. Select the Copy link with a vcard contact
2. Paste into the email, now I see the URL:
![screen shot 2015-10-22 at 09 27 17](https://cloud.githubusercontent.com/assets/12032058/10659316/33a34c4c-789f-11e5-8c90-e72ec0e62611.png)
3. Send the e-mail, when you open the e-mail, you see the URL:
![screen shot 2015-10-22 at 09 29 06](https://cloud.githubusercontent.com/assets/12032058/10659360/74f5ff8c-789f-11e5-8ec5-dadac6ffba7a.png)
4. If you click on the URL, I see this:
![screen shot 2015-10-22 at 09 30 23](https://cloud.githubusercontent.com/assets/12032058/10659379/a1d0ced8-789f-11e5-93d9-61af32765bb7.png)
5. If you download the .vcf, I see this:
![screen shot 2015-10-22 at 09 32 18](https://cloud.githubusercontent.com/assets/12032058/10659513/acdd4cb0-78a0-11e5-86a4-ab959c42cf0d.png)

@guruz, my question is: This is correct?, Thanks

I tested this issue with:
Desktop v ownCloud-2.1.0.2821-nightly20151022.pkg  
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by szujak** [comment]
It is a bug reported in QT today https://bugreports.qt.io/browse/QTBUG-48953 maybe it help you

**Comment by guruz** [comment]
@szujak It's worked around in our nightly builds. Feel free to try (but they contain quite some untested code, so as usual be cautious and have backups..)

http://download.owncloud.com/desktop/daily/

**Comment by guruz** [comment]
Nobody reported back, but I'm assuming this is fixed now in the builds mentioned above

**Comment by srhuddle** [comment]
I'm seeing this same behavior with Mojave (10.14.3), Mail.App and Microsoft Remote Desktop -- Ctrl-C copy from MRD pastes as a VCF in Mail.app.

**Comment by michaelstingl** [comment]
@srhuddle Please open a new issue with the relevant information (steps to reproduce, version etc).
