### ISSUE TITLE
1.8.2rc1 stuck in discovery state (and eventually Operation Cancelled)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3309]
The 1.8.2rc1 client on Linux got stuck in the discovery state (blue icon) and eventually after several minutes it came back with Operation Cancelled. I am not clear if this is a race condition or a shaky wireless network that I was on.

![image](https://cloud.githubusercontent.com/assets/621965/8018956/86c06c8c-0c36-11e5-8b3c-2150cb528606.png)

Here is the process sample. Why is there CSync_Neon thread? I though Neon-based code was not used anymore in 1.8?

![image](https://cloud.githubusercontent.com/assets/621965/8018982/dc619c6e-0c37-11e5-90a0-1ca035fbf601.png)

![image](https://cloud.githubusercontent.com/assets/621965/8018983/fe758072-0c37-11e5-8259-15aa83e8093b.png)

![image](https://cloud.githubusercontent.com/assets/621965/8018992/3e89b4f8-0c38-11e5-93c4-6b157a95d9b6.png)

**Comment by dragotin** [comment]
IMHO that is what it looks like in flacky network environments, @guruz what do you think?

The thread name is indeed confusing, I changed it with commit fc2ceb88fb978c53c6207beb96ca5ff9a176bc2a . It's true that neon is not longer used IF the client is built against Qt 5.4 or newer, otherwise Neon is still needed for the bandwidth limitation.

**Comment by guruz** [comment]
Yes, looks like a flacky network connection..

**Comment by moscicki** [comment]
OK. Nothing to worry about then.
