### ISSUE TITLE
Upload of many Files really slow

### ISSUE THREAD

**Issue by myzinsky** [owncloud/client#331]
### Expected behaviour

Upload of a lot of MP3 Files (4GB) should be fast.
### Actual behaviour

Upload Only 6 Files (ca 40mb) in 4 hours!
### Server configuration

Operating system: Debian Stable

Web server: Apache2

Database: Mysql

PHP version: PHP Version 5.3.3-7+squeeze14

ownCloud version:  4.5.6 
### Client configuration

Client version: 1.2

Operating system: Debian Unstable

OS language: German

Installation path of client: /usr/bin/owncloud
### Logs

ownclouds://xxx/Blue Moon
02-12 14:18:20:533 oc_module: owncloud_stat ownclouds://xxx/Blue Moon called
02-12 14:18:20:678 oc_module: Simple propfind result code 207.
02-12 14:18:20:678 oc_module: Server Date from HTTP header value: Tue, 12 Feb 2013 13:18:20 GMT
02-12 14:18:20:679 oc_module: Ok: Time delta remained (almost) the same: 0.
02-12 14:18:20:679 oc_module: => Errno after fetch resource list for ownclouds://xxx/Blue Moon: 0
02-12 14:18:20:679 oc_module: Working on file Blue Moon
02-12 14:18:20:679 oc_module:   :> Subtracting 0 from modtime 1360675100
02-12 14:18:20:679 oc_module: STAT result from propfind: Blue Moon, mtime: 1360675100
02-12 14:18:20:679 oc_module: Directory of file to open exists.
02-12 14:18:20:679 oc_module: PUT request on //xxx/Blue%20Moon/Robben%20Ford%20-%20My%20Everything.mp3!
02-12 14:18:20:679 oc_module: Sendfile handling request type PUT.
02-12 14:18:20:679 oc_module: Put file size: 6858752, variable sizeof: 8

This is an example, it waits a really loooong time :( (Paths shortened with xxx)
#### Web server error log

<b>Deprecated</b>:  Directive 'register_long_arrays' is deprecated in PHP 5.3 and greater in <b>Unknown</b> on line <b>0</b><br />

There is a lot of this stuff, but i'm not shure if this is realted to owncloud
#### ownCloud log (data/owncloud.log)

{"app":"media","message":"error reading title tag in '\/var\/www\/owncloud\/xxx.mp3'","level":2,"time":1360575380}### Expected behaviour
Upload of a lot of MP3 Files (4GB) should be fast.

**Comment by modernmediagrp** [comment]
@sargelavoie - hey can you message me on how you got leny running on your BA NAS?

**Comment by sargelavoie** [comment]
@modernmediagrp - I have followed these [instructions](http://www.noerenberg.de/hajo/pub/seagate-blackarmor-nas.txt). However, I do not use owncloud anymore. I use syncthing running on a raspberry pi which is connected to my nas through nfs.

**Comment by danger89** [comment]
This issue ist still not solved!!

**Comment by knowlecules** [comment]
+1, I'm experiencing the same slowness.

**Comment by danger89** [comment]
So what's the next step :S?

**Comment by Croydon** [comment]
Still a big issue if one is uploading many small files. I got a remaining time displayed in MONTHS.

**Comment by scolebrook** [comment]
It's helpful to provide data to quantify what slow means in your situation and what your configuration is. For me, a folder of 1000 small files totaling 19MB takes a little under 6 minutes to sync. I've run this test with ownCloud client 1.8.4 and 2.0.2 against server 8.1.3. Server side is two load balanced apache 2.2 boxes running a memcache instance on each. PHP sessions are in memcache using memcached with data written to the memcache instance on both servers. The database is a 3 node Percona Cluster behind a load balancer. Storage is a NAS that is connected to the web servers by smb mounted in the file system. The network links between all the VMs we use is 10Gbps, internet pipe is 100Mbps and my pipe was 20Mbps.

During these tests I saw a db query rate of about 3k/sec. Before and after was about 2k/sec indicating that this sync operation resulted in 1k queries/s. I didn't see abnormal cpu load on the db nodes or web servers. There was also no unusual iowait levels on the web servers and network traffic was no where near capacity. I'm not sure if the speed of this transfer is a result of latency at one point or another. Given the lack of load anywhere I suspect so. Perhaps increased parallelism by transferring more files at once would make better use of the server and network capacity available.

Since server capabilities vary, and may vary from one hour to the next, parallelism would need to be dynamic. And how should the client determine when to increase the number of simultaneous uploads or decrease them? Not as easy as it sounds.

**Comment by lordadamson** [comment]
I have that and I don't know how to fix it :(

**Comment by moscicki** [comment]
This crippled performance is mainly the server issue. Meaning software
running on the server and resulting in insane sql activity (and insane php
overheads). I guess this is major milestone for owncloud 9 server release
but I would suggest you check with owncloud server developers to be sure.
If you happen to use sqlite on the server I would suggest you do not and
switch to mysql for instance.

On Sun, Nov 15, 2015 at 11:00 AM, Adam Zahran <notifications@github.com>
wrote:

> I have that and I don't know how to fix it :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/331#issuecomment-156796953>.
>



-- 
---
Best regards,
Kuba

**Comment by danger89** [comment]
@moscicki Can you proof this behavior?

**Comment by moscicki** [comment]
Yes: with a C++ webdav server things are much faster.

On Mon, Nov 16, 2015 at 2:50 PM, Melroy van den Berg <
notifications@github.com> wrote:

> @moscicki <https://github.com/moscicki> Can you proof this behavior?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/331#issuecomment-157031677>.
>



-- 
---
Best regards,
Kuba

**Comment by danger89** [comment]
WebDav is a HTTP protocol and has nothing to do with MySQL.

**Comment by scolebrook** [comment]
@danger89 ownCloud isn't just webDAV. Try running it without a database of some kind. SQLite is a low performance database backend. If you want speed, use MySQL. If you have more than one person or sync client using ownCloud at the same time. SQLite is really only good as a data store for a single application which is why the sync client uses it for the journal.

You can see the point @moscicki makes from the stats I supplied further up this thread. While I was uploading a folder of about 1000 small files there was a query rate increase of approximately 1000 queries a second. This lasted for a 6 minute period. That's an average of about 360 queries to upload each file. Now there's folder structure in there to consider too. It had to discover that directories didn't exist, make them and so on. But 300+ queries is a massive amount for a single file. With the network round trip between the web and database servers running at about 0.8ms (there's a load balancer in there too) a very large percentage of the 6 minutes for my test is clearly network latency due to the massive amount of communication to the db.

This has been an area of continuous improvement with each major version. But it's clear that there still room for more.

**Comment by aronovgj** [comment]
It is still innodb_flush_log_at_trx_commit on the server side. set it to 0 or 2.

**Comment by aronovgj** [comment]
Also nobody could explain to me what this means:
"Beware that it means that the actual IO flush is only done every one second and no more at each commit (see [1]), you may lose data so don't use this for critical systems"

What can be lost during this second and can this corrupt my files if mysql has a properly working recovery?

**Comment by scolebrook** [comment]
@aronovgj By setting innodb_flush_log_at_trx_commit to 0 you are turning off MySQL's properly working recovery mechanism and relying solely on the capabilities of your storage backend (battery protected write cache, etc). Better have some good power management in place.

Setting it to 2 results in the log being written for every write query but the other write operations happening once a second at most. This is not ACID compliant unless you're in a galera cluster where the cluster as a whole is still ACID compliant.

There is only a marginal performance improvement between 2 and 1. 1 is where everything is flushed to disk for every write query and is the only option that is ACID compliant for a stand alone MySQL server.

But 0 doesn't change the results of the test I described above. While there is less disk io on our database nodes, it takes the same time to sync the same folder. This reinforces my opinion that in my case, the time is a function of network latency. The latency is very, very small in our environment, about as small as you can possibly make it, but there are literally hundreds of queries for each file and it really adds up.

I have no idea what the content of all these queries is but I think it's a pretty safe bet that many of them are selects for exactly the same information over and over again by different parts of the code. It would be good if that information could be cached to avoid hitting the db over and over.

**Comment by RealRancor** [comment]
> now we need to catch up on server side. Please track in the mentioned server bugs.

from https://github.com/owncloud/client/issues/331#issuecomment-41292972

**Comment by danger89** [comment]
If it's a server side issue, indeed we need to take a look at the 'core' issues instead. Give this issue more credits for example:
https://github.com/owncloud/core/issues/20967

**Comment by Croydon** [comment]
14.329 files, 557 directories, 91,8 MB
and it runned for serveral days multiple hours. I can't even say exactly how long.
However, it's obviously a problem with small files.

**Comment by aronovgj** [comment]
@scolebrook Although setting  `innodb_flush_log_at_trx_commit = 2` may not be ACID compliant I strongly disagree that the performance improvement is marginal compared to setting it to 1, reducing HDD load from 100% to about 5% and reducing the sync time from several months to a few hours.
Had about 70000 files, about 30gb altogether but also a lot of small files which took several seconds per file.

**Comment by scolebrook** [comment]
@aronovgj You aren't seeing the difference between 1 and 2 specifically. You're seeing how the requirements of the two impact storage that is constrained on iops. 2 does an append write to the log for every write type query. A very quick and simple write operation. Even slow storage can accomplish it quickly. It then writes the actual tables once per second these are insert type writes are take significantly longer than an append as some data needs to be re-arranged. Grouping these operations together and writing once a second allows for significant optimization. 1 on the other hand doesn't allow that optimization because there is no grouping of work.

If you have battery backup for your systems such that you're satisfied that the risk of data loss is sufficiently mitigated, 2 will give better performance. The level of performance difference between 2 and 1 will be a function of how slow the storage is. Where storage isn't the bottle neck, the difference, while still obvious, is not that significant. Changing os level settings or other settings in MySQL can have a bigger impact. This is our situation. Network latency is the primary constraint for us with our storage never getting above 10% utilization for any configuration in MySQL.

We actually run with 0 which is an order of magnitude faster than 2 because our infrastructure is backed up and protected to the extent where the it'd require the loss of the data center to lose that one second of data between writes. In that event we'd be falling back to our most recent offsite tape which would be at least 24 hours old. And that is exactly the same level of risk for using either 1 or 2 because loss of the data center includes loss of the disks.

Each situation is different. Knowing the details about these options is important to make sure your configuration is appropriate for your environment and your needs. Everything in IT is a compromise in one way or another.

Something else that will improve performance is spending some time tuning io at the operating system level. Our MySQL nodes are virtualized so we use the noop scheduler and let our storage environment do the optimization of write operations to it's disks rather than have Linux spend time optimizing only to have the storage backend re-optimize the MySQL traffic together with the traffic from other systems. For hardware servers it's probably best to measure performance with your workload and try cfq and deadline to find the right one for your situation.

At the end of the day, the issue is the number of queries that are required. 300+ per file must be far more than what is actually needed. If this can be optimized further as it has in previous versions, then it improves network and disk use.

**Comment by aronovgj** [comment]
Thanks for the clarification @scolebrook. So seems like we are talking about different problems in different environments. I have a home server with two HDDs, one of which is only for backups every six hours. And I actually can live with data loss of up to six hours. However I'd rather live without the risk and with proper writing speeds. I haven't found another solution for this until now.

**Comment by RealRancor** [comment]
Instead of discussing this here in the client tracker you can also have a look at the core issue tracker as already suggested twice. If the amount of sql queries can be reduced maybe the change of innodb_flush_log_at_trx_commit is not needed at all.

**Comment by scolebrook** [comment]
@aronovgj Sounds like you're making informed decisions to suit your needs and your equipment. Excellent.

@RealRancor is right. Talking about tuning MySQL or other things doesn't get the job of improving ownCloud done. It's helpful information but it's still a workaround.

**Comment by TheManOfTheMAn** [comment]
I am using Owncloud 8.2 on a Ubuntu 14.4.3 LTS Virtual set up including MySql and I also faced this issue.

I can confirm that this is caused mainly due the Database overhead for each new file what will be uploaded to the server. While tweaking cache and lock with APCu and Redis just gave me a very little improvement an also tweeking Php, Apache and MySql configs did not make a big difference.

But it was absolutely clear as I moved the MySql-Database from the HDDs to a SSD in my Sytstem.
Upload time per file took in about 10 to 15 seconds in minimum (even for very small files).
After SSD for MySql its in about 1 second in minimum.

So this problem just really counts if you shift many little files (as mentioned before). Because the database overhead takes much more time than the physical upload and storing time on the local disk.

While the new desktop sync client performs multiple uploads and this in combination with the SSDs gave the upload speed a push so that is somehow acceptable now. But since we need to use webdav a lot there the upload speed is still a pain in the ass for a large amount of little files.

Because most webdav mounts juste upload each file one by one, same problem while deleting folders. Deleting each file one after the other. This was absolutely unusable with 15 to 20 seconds per file and is still very bad with 1 to 2 seconds per file in minimum.

Well the problem for us is, that we need to use webdav because we can not sync our whole external owncloud storage to the mainly used apple airs with very few disk space. So that people can work with it we use cyberduck mounting the webdav. Download, dir listing, upload of large files, everything is perfect. Except the problem with small files.

So a possible solution would be a dramatical increase of database action going along with every uploaded file. Maybe it would be better to move as much actions to a regularly working crone job and to improve the mysql overhead.

Another possibility would be to expand the desktop client to use to mehtods: Folder sync. like DropBox and just a file browser with multi upload ability without local syncing somehow like the apple or android app. So that you see all your files remotly and that you could edit them directly without the need of syncing and much faster than webdav.

Or is there a possibility to make webdav faster?

**Comment by butonic** [comment]
Have a look at https://www.percona.com/blog/2013/09/20/innodb-performance-optimization-basics-updated/ especially innodb_flush_log_at_trx_commit if you can live with loosing 2 seconds of transactions (IMO like a failed upload on power outage). Roughly speaking, setting it to 2 will only cause data loss when the OS crashes. Setting it to 0 will make you loose data when mysql crashes. You decide. Would be interesting to see how the performance changes in your case. Let us know!

**Comment by TheManOfTheMAn** [comment]
Well thanks for the tip. I was scared of setting it to 2 as I just downgrade from replication mode of the database to periodical dumps. But to be honest the replication was not primary targeted to Owncloud but to a resource database what is hardly used but where data lose would be terrible, but that is not related to this discussion.

Just to inform you: Yes I moved away from replication master slave mode due performance issues way before I tested the sql performance and posted the comment above :) – but anyway I might could live with the standard OS I/O cache (innodb_flush_log_at_trx_commit = 2) update time if you can answer me one question:

If a users is uploading files into hes Owncloud private place, or if the system admin is moving files just right to a users Owncloud "files" folder, will Owncloud detected the changes and set all necessary DB entries or will this cause problems in some circumstances?

 I know that the cron checks external drives for changes periodically and that there is a config setting to activate file system changes in general.

The point is, I do daily backups of the MySql-database. So even if there is a bad crash and corruption, it would be okay if all uploaded files get clean redetceted  after importing an older DB dump while the files are physically present. If yes, I would try to move to "2" in this case :)

**Comment by jospoortvliet** [comment]
@TheManOfTheMAn have you tried it since then? Would be interesting to hear if this helped, if it did, it is something we could document.

**Comment by guruz** [comment]
FYI, the 2.2 client will try to do more parallelism for small files. This will at least help to use the network better even if the server could become more the bottleneck.. 
You can try with a nightly build from this morning.. http://download.owncloud.com/desktop/daily/
(3rd of March)

**Comment by TheManOfTheMAn** [comment]
**WARNING**
Pardon me for my late answer!

I would **NOT RECOMMEND** setting  the innodb_flush_log_at_trx_commit  to 2.

I tested it and there was very less up to no increase in the speed performance while uploading files.
So there might be a little or no effort at all, depending on your system, using  innodb_flush_log_at_trx_commit = 2 but a total increase of system instability.

Just one day after I set it to 2 my system got a hard rested by an admin (should'nt happen normally but just imaging a power outage. However the Owncloud database was corrupted and it was not possible to repair or restore it. Even if there was 3 o'Clock at night with no user operations running on the database, it was enough for completely corrupting it. So we could get it back to work dropping all tables and pushing an database backup to the server!

So to be clear:  innodb_flush_log_at_trx_commit = 2 will not only cause a little loose of data if the system went down unexpected or crashes for some reasons. It will possibly corrupt your database and leave it unusable at all. So in my opinion this isn’t a valid option at all and it won't give you a significant performance increase!

My final solution:  I moved the database on SSDs to get a acceptable upload speed.

**Comment by aronovgj** [comment]
I did some hard restards to my system having it set to 2 and nothing happened. But that is finally a proper answer to my question. I wanted to know what *can* happen.

**Comment by mckaygerhard** [comment]
my 50c apport:

i have some instalations used for backup and, noted that those with postgres dont have so many problems like those with mysql, i'm not a mysql-like user due i think its a poor database and in those instalations that have mysql with owncloud i must restart the database to property get working afeter that kind of problems
