### ISSUE TITLE
Silently fails to sync files with nlinks > 1, gives green checkmark even though files weren't synced.

### ISSUE THREAD

**Issue by jgoerzen** [owncloud/client#3391]
Hello,

I got a nasty surprise recently -- I moved a large directory tree into a directory that OwnCloud syncs.  After a little while, the OwnCloud icon on my desktop gave me a green checkmark.  And before long, the same happened on another PC syncing up with there.  A few days later, I copied it off to a different location on PC B, and then removed it from PC A.  I later discovered I was missing some files; subsequent investigation showed that these are ones that were hardlinked to other locations on PC A.  Looking at the log, it shows that these files were skipped, but no comment or reason why.

It has already been shown (for instance, in #2557, and #530) that hardlinks will not be synced.  However:

1) The UI is presenting feedback suggesting the directory is completely synced, when in fact it's not;

2) The UI is not making it clear WHY these hard-linked files are skipped;

3) This is occurring even when there are no other links to the files within the tree OwnCloud is syncing.

As someone that makes extensive use of cp -rl, this is pretty darn troublesome for me.  Even if the comments in #2143 are accurate (it does seem odd, since a disappearance of an inode reference in one directory and appearance of the same in another should make move logic possible), still if OwnCloud is going to not sync my files, I need to know about it.

  The fact that I am given the green checkmark when some files were not synced, even though they didn't match my exclusion pattern, is the bug here.

**Comment by phil-davis** [comment]
Just now code is being committed that will sync files in the ownCloud folder tree that are hard links e.g.:
https://github.com/owncloud/client/commit/575ca50aacc67cdbf0803c885806f31d5d1aad42
and this issue is also related to interrelations between hardlinks and dual-boot Windows/Linux... but has some good comments about how syncing of hard links will end up as separate files on the server if both hard link entries are in the ownCloud folder tree:
https://github.com/owncloud/client/issues/3241
If files that are hard links are the only case of "unknowingly ignored files" that are not synced even though the green checkmark is showing, then this issue should be solved by the current commits that will sync hard links.

**Comment by jgoerzen** [comment]
That would be excellent.  It does indeed sound that way.

**Comment by ogoffart** [comment]
owncloud client 2.0 will sync hard links

**Comment by Dianafg76** [comment]
I tested this issue, and it is working fine, many thanks ;-)
Desktop v ownCloud-2.0.0.5252-nightly20150707-setup.exe
