### ISSUE TITLE
Unnecessary tooltip in settings dialog navigation, duplicates text

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3405]
See:
![capture du 2015-07-03 22-56-09](https://cloud.githubusercontent.com/assets/925062/8504748/185843e4-21d7-11e5-8bd7-fd5b4b7d07ae.png)
There’s not really a reason to duplicate that text. It does however look very strange when the tooltip comes up when you just have your cursor over the entries for a tad longer.

**Comment by ogoffart** [comment]
The problem is that Qt forces a tooltip on toolbar buttons. So it's hard to change that.

We could eather patch Qt so that it does not put a tooltip on toolbutton that already have the same text.  Or we could try to hacks our way with event filter and such to avoid the tooltips.  Or we could set sensible tooltips. Or we could ignore the problem.

**Comment by jancborchardt** [comment]
Ok, then we ignore it. :D
