### ISSUE TITLE
Do not traverse the whole local file tree when using file system notifications

### ISSUE THREAD

**Issue by fefrei** [owncloud/client#3408]
### Expected behaviour
When changing a single, small file in a synced directory, ownCloud should pick up the change automatically, only check this file, and quickly upload it.

### Actual behaviour
After changing the file, ownCloud reacts within seconds, and shows `Discovering '<folder>'`. By looking at `<folder>`, it is clear that the client is re-scanning unrelated parts of the synced folder, possibly the whole folder. For a synced folder with >10.000 files, this means that on my machine, the client fully utilizes one CPU for about 20 seconds whenever a file is changes. Combine this with a text editor that auto-saves quite regularly, and you get a hot laptop and poor battery life simply by editing a text file.

### Steps to reproduce
1. Have a large folder synced to ownCloud.
2. Write to a single file.
3. Observe CPU utilization.

### Server configuration
Operating system: Raspbian

Web server: Apache/2.2.22 (Debian)

Database: mysql  Ver 14.14 Distrib 5.5.43

PHP version: PHP 5.4.41-0+deb7u1

ownCloud version: 8.0.4

Storage backend: local disk

### Client configuration
Client version: 1.8.3

Operating system: Windows 8.1 x64

OS language: English (US), Region: Germany

Installation path of client: `"C:\Program Files (x86)\ownCloud\owncloud.exe"`

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
[Here](https://secure.fefrei.de/paste/?859780143e2c599f#d/6sIuVDURgvzG6Dip0oJZaPRMdhsuaoIu1Ph50ZhJU=) is the log created by changing a single file - `C:\Users\Felix\ownCloud\Studium\P2\CS\project.thy`.
2. Web server error log:
No entries related to this.

3. ownCloud log (data/owncloud.log):
I have no idea what log this is referring to.

**Comment by guruz** [comment]
Hi, we're currently working on a few things that could improve the situation there on Windows.
Would you be willing to test a nightly build as soon as it is ready?

CC @dragotin https://github.com/owncloud/client/issues/880

**Comment by fefrei** [comment]
Sure! Just tell when when a nightly is available, and what feedback you need (or whether a simple "still 20 seconds" / "way faster") suffices.

**Comment by guruz** [comment]
We have an un-QAed nightly build of 2.x available http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5264-nightly20150713-setup.exe

However I suggest to only try this if you have backups..

**Comment by fefrei** [comment]
I'm currently syncing a copy of my full dataset to a test account with this nightly build, installed on Windows 10. This might take a day or two, I'll report back when it is done.

**Comment by guruz** [comment]
@fefrei Thanks. So this is the same machine and same dataset, right?
So it is possible to compare with the "20 sec"?

**Comment by fefrei** [comment]
It is the same dataset and the same machine, but a different OS (I didn't want to mess with my install on my production OK).

**Comment by fefrei** [comment]
After a slow initial sync (which was bound by resources on the server-side), I can finally tell you:

It's still as slow as before. Changing a small text file causes a roughly 20-second-rescan which checks unrelated folders. I can literally hear that I saved the file because the fan spins up.

**Comment by guruz** [comment]
Thanks, that's interesting to know. 

So the switch from the POSIX ```opendir/readdir``` to ```FindFirstFile/FindNextFile``` did not help yet @dragotin 
But there's still some room for improvement, please stay tuned..

**Comment by fefrei** [comment]
Just let me know if you want me to test another build. Further tests should also be faster, since I won't have to wait for my poor Raspberry Pi to add tens of thousands of database entries...

**Comment by dragotin** [comment]
The problem is that for every sync run, the client traverses the local file set which indeed consumes some cycles. This done to re-setup the internal data structure of the local file tree.

A solution would be to keep the internal data structure permanently and just add the changes delivered by the file system notifications to it. Another alternative would be to re-construct the local file tree structure from the sync journal. 

All that requires very reliable file system notifications. In the past we were not convinced we can rely on them, so that's why we did not yet consider this change.

**Comment by fefrei** [comment]
I believe that e.g. Dropbox does it like this, and they don't seem to have large issues with this.
You could also consider traversing all files only if some reasonable amount of time has passed since the last sync run - preventing the client from using one CPU core all the time.

**Comment by massimoi** [comment]
+1 for this bug, on my system onwcloud get almost unusable with CPU over 50% all the time and the fan spinning like mad.... Also explorer seems to be affected by hi-cpu when owncloud client is running.

(Dropbox or OneDrive do not have the same problem).
Thanks
Massimo

**Comment by zephyrus00jp** [comment]
Hi, I am the reporter of #3001.
I did not notice that it was closed, and I am sorry that I posted to #3001 a few times.

Anyway, I will post my findings to this issue. For the several months I have monitored
the I/O volume of owncloud client under Windows by using task manager (yes, that program which is invoked by control-alt-del key combination.
When we open the "process" tab of task manager, we will see the CPU, memory usage, etc.
We can add I/O volume, etc. by the menu "Display" -> column selection.
I have monitored cumulative I/O read bytes (octets) in this manner,
and found that owncloud does probably close to x 5 - x 25  more input than dropbox.
(This is after normalizing the read by the amount of files under owncloud and dropbox.
That is, if owncloud stores 8 times as much files as dropbox, I can tolerate 8 times as many byte reads. So in this case, the read bytes for owncloud is divided by 8 and compared with owncloud's I/O.

Even after normalilzation, owncloud reads x 5 - x 25 times as many octets than dropbox. 

Maybe my original title of #3001 could have been misleading. I was referring to the amount of read
rather than the number of read system calls. But in the end, it is the same thing.
My PC does too excessive I/O due to owncloud and as some posters here note
it feels very sluggish when this happens. My PC is desktop with wall power and so
I don't realize the power consumption issue, but it must be tough on notebook users.

I think if callback/notifier for file modification works, and I think it ought to work in Windows 7 and up,
we should use it for efficiency reasons.
At least dropbox doesn't have to read so many bytes: I suspect that some unnecessary hash value creation for non-changed files or unnecessary generation of hash value for black-listed files (and never uploaded to the server) occurs due to an incorrect placement of proper checks before such heavy input is done for each file during directory traverse. Just a suspicion, though.

TIA

**Comment by fefrei** [comment]
This is clearly related. I haven't noticed the IO that much (thanks to a SSD), but the full re-scan is the cause for both: It reads a lot of data that the CPU processes.
Thanks for sharing these observations - both parts clearly need to change.

**Comment by robert128** [comment]
I agree this is a big problem and limits the usage of ownCloud.  I tried putting over 150,000 files under ownCloud control, and it just took too long to sync a single file - minutes of scanning.  I eventually moved the files to a differnet location.  And for anyone who writes code, ownCloud will constantly scan because there are always saves and compiles, and you end up with a machine that is really taxed doing simple stuff.

**Comment by guruz** [comment]
@robert128 I'd say ```git``` is a better candidate if you want to synchronize code.

**Comment by guruz** [comment]
@dragotin @MTRichards Let's try this for 2.1 .. ?

@dragotin and @ckamm had some ideas about keeping the tree in memory or in the DB and only react to file system watch notifications.. https://github.com/owncloud/client/issues/2297

**Comment by MTRichards** [comment]
@guruz ok.

**Comment by guruz** [comment]
Leads to https://github.com/owncloud/client/issues/2297

**Comment by wadedugas** [comment]
Since the issue I opened for this behavior on a MacBook was closed, please make sure this issue is updated to include OS X.

Is the client using FSEvents on OS X?

**Comment by guruz** [comment]
@wadedugas Yep #2297 mentions that

> On Mac: We don't get notifications for changes our own process caused, so a single run should be enough. We may be able to hook into the filesystem change journal to even skip that.

:-)

https://github.com/owncloud/client/blob/master/src/gui/folderwatcher_mac.cpp
