### ISSUE TITLE
"choose what to sync" should not delete local folders

### ISSUE THREAD

**Issue by shopps** [owncloud/client#3424]
### Client configuration
Client version: 1.9
Operating system: Windows
OS language: english

I was told to post this here rather than the mailing list, but it doesn't fit the bug reporting template. It doesn't seem to be a bug, it seems to be a poor design choice.

Original message:
Hi, I love this app and thanks for creating it.

I have one major problem with the desktop sync client in windows. The current behavior is to delete files from the local drive if they are unchecked in the "Choose what folders to sync" dialog. This is wrong.

There are no other cloud storage apps that behave in this way, and I'm flabbergasted why this was the approach taken. The sync app should never delete files from the local drive, unless that option is specifically enabled by the user, and it should default to disabled should that option be created. Unchecking a folder in the sync list should cause that folder to be ignored completely by the app, and nothing else.

This is a crippling mistake in design. I'll use my business as an example. I have a top folder called "Business Files", and underneath that folder are a number of mission critical folders "Contracts", "Media Assets", "Works in Progress". I want to backup and distribute the contracts and assets to the cloud, but works in progress are short-term, and involve large files not suitable to be synchronized 24/7. So I need a way to ignore the "works in progress" folder. I should not be forced to re-order the folder structure to work-around what is a design flaw in the sync client.

Other than that, thanks for a great app, and I hope this issue gets patched.

**Comment by scolebrook** [comment]
We actually really like this design. It makes it one action to remove content from a local machine without removing it from the account. To me, stopping sync and then having a copy on the server and different copy on one or more local systems that conflict with each other would seem to be a far worse design. If/when a user then wants to re-sync something, they have some work to do to resolve conflicts between server and local versions.

In your case, it sounds like you need to use the folders feature rather than selective sync. Setup folder pairings for your ownCloud/Business Files/{Contracts|Media|Assets|Works in Progress} folders. Pause Works in Progress. Sync it when you want to or not at all. No structure re-ordering on either side, one button sync control for Works in Progress (less than selective sync).

**Comment by shopps** [comment]
Perhaps I misunderstand what you mean by folder pairings, are you 
suggesting I set up a seperate sync folder for each subfolder of the 
business tree? If I add another depth of subfolders to the scenario that 
wouldn't solve it. Perhaps I want /FolderA/FolderB/FolderC/ all synched 
but not FolderB.1 or FolderB.4, but I do want FolderB.3.. etc.

If you really like having your cloud app automatically deleting stuff on 
your local drive which should be the master record, then that should be 
a feature which is disabled by default and requires enabling. As I 
stated, there are no other apps which behave this way, yours is the only 
one. Therefore it is not intuitive, and is likely to cause problems for 
people.

I hate the feature. I understand I'm just one person, but I'm sure there 
are other people who simply want a means to ignore certain folders. 
Commercial cloud apps have that feature. I am going to stick with 
ownCloud for now because I want to have full control and encryption of 
my data. What's the point of having control if you hand over the 
destructive keys to the app?

In my humble opinion as a computer geek, an ignore folders feature 
should come first, an auto-delete or complex sync options feature should 
be secondary. Because of this feature I am forced to structure my 
folders a certain way to work-around the sync app. Ugly.

I might be misinterpreting what you mean by the folders feature, I 
apologize if so, I am new to using this app. But if I understand 
correctly that is already what I'm using, in this case I've got one 
folder for personal things, and one folder for business things, each has 
many subfolders. It makes no sense to transfer large & temporary files 
to the server when I've got to pay for bandwidth.

---
Steven Hopps || shopps@pridetechdesign.com
424-888-0443 || http://www.pridetechdesign.com

= Ask about my Security Tune-Up & 24/7 Server Monitoring! =

**Comment by scolebrook** [comment]
There is already an ignore folders/files feature (but you have to type in the folder name/path rather than check a pretty box). But I guess we're looking at this from two entirely different perspectives. You're looking at your local computer as the master the server, all other synced computers and all copies of shared content as the copy. We're looking as the server as the master with everything not on the server as the copy. Deleting content from the master is always a bad idea but deleting a copy rather than forking a new version tree is generally a good idea.

Generally in all sync scenarios (and even non-synced file servers) the server side copy is considered authoritative and local copies are considered to be just that, copies. There's obviously some reason why you're looking at this the other way. I'd be interested in understanding why.

**Comment by shopps** [comment]
I'm not sure one approach is necessarily better than another, and I see 
merit in yours. My experience is mostly with Dropbox, Copy.com, and 
Google Drive. They give priority to the client side.

In my case, I have a local file-server, and multiple workstations. The 
workstations use mapped drives to access files on the local file-server, 
and the local file-server uses ownCloud to back up files to a remote 
file-server. I use cloud storage in this case primarily as a means of 
cheap offsite backups, but I also take advantage of the mobile apps and 
the ease of retrieving files thru the web interface. This saves me 
resources on the workstations since only the local file-server has to 
run the sync app. I understand I could do this with rsync, but if I 
travel I can activate the app on my laptop as-needed. Plus, automatic 
encryption is nice (and the reason I made the jump).

Keepass (keepass.info) has a feature with it's synchronization which 
lets you choose whether to give priority to the remote file or the local 
file, that might be a good option.

I will browse the docs for the ignore feature you mentioned, I don't 
mind typing in folder names, I've only got to set it up once I presume.

---
Steven Hopps || shopps@pridetechdesign.com
424-888-0443 || http://www.pridetechdesign.com

= Ask about my Security Tune-Up & 24/7 Server Monitoring! =

**Comment by scolebrook** [comment]
Yes, you will only need to setup ignore rules once. See https://doc.owncloud.org/desktop/1.8/navigating.html#editing-ignored-files

Even when I use dropbox, because I sync multiple computers, the server copy is authoritative for me and the clients (my computers) are the copy. If I delete something on one computer I expect it to sync that action to the server and because the server is authoritative I expect that action to be pushed to all other synced computers rather than any of them push that file back to the server. Basically if there's ever a difference between a computer and the dropbox server, I expect the dropbox server to win. So does dropbox. I expect ownCloud to be no different.

I thought you might be doing backups. I always caution people about how sync services such as ownCloud are not designed to be a backup solution on their own. Forgive me if you've heard this warning before and already considered the implications. Perhaps it will benefit someone else who hasn't. If you have file system corruption and a file is damaged, that change which you won't be aware of until it's too late, will be synced to the server. If someone accidentally deletes something and doesn't know it, then that action is synced and the file will disappear from the ownCloud trash after 30 days. I would only use a sync service as part of a broader backup strategy.

For cloud backups I like Crashplan. If you're using your own storage, the software is free. If you want to use their storage it's around $5/mth for one computer for unlimited storage with unlimited versions. There are a number of companies offering very cheap and solid cloud backup solutions similar to them. I use their service personally so that's the only one I can speak about with any experience. But if you decide to look in that area research the field. Crashplan may or may not be right for you.

Back to the issue at hand though. You do make a very good point about the limited warning for the impending deletion of local content. That should probably be a little louder. A checkbox to set whether the local content is deleted or not would be good. It's default value should be configurable in a theme as well as whether it appears at all (so a company can make sure that their default is never over ridden). I guess it would be up to ownCloud to determine what these values would be for their version but it would give an admin the ability to override them and compile their own clients with their own settings if they wish.

**Comment by shopps** [comment]
Thanks for the tip regarding corruption, I had not thought of that.. I 
will implement a traditional weekly backup plan in addition.

The cloud backup plan is mostly in case of a sudden catastrophic failure 
of the file server, so that I can quickly recover my work on one of my 
other machines.

---
Steven Hopps || shopps@pridetechdesign.com
424-888-0443 || http://www.pridetechdesign.com

= Ask about my Security Tune-Up & 24/7 Server Monitoring! =

**Comment by ogoffart** [comment]
> There are no other cloud storage apps that behave in this way, and I'm flabbergasted why this was the approach taken

We inspired ourselfs on the equivalent feature in DropBox while designing the selective sync. Dopbox does exactly that (deletes the folder you unselect)

**Comment by moscicki** [comment]
> Even when I use dropbox, because I sync multiple computers, the server copy is authoritative for me and the clients (my computers) are the copy. If I delete something on one computer I expect it to sync that action to the server and because the server is authoritative I expect that action to be pushed to all other synced computers rather than any of them push that file back to the server. Basically if there's ever a difference between a computer and the dropbox server, I expect the dropbox server to win. So does dropbox. I expect ownCloud to be no different.
> 
With one big difference currently: for Dropbox conflict files are detected on the server, so even your locally modified file is uploaded (and safe!) on the server. For owncloud, conflict files are detected on the client, and your latest locally modified content is renamed to *_conflict* which is not uploaded to the server (and the only copy of this content is only stored locally and thus not safe. 

This is a "safety leak" in the current owncloud system.

kuba

--

**Comment by scolebrook** [comment]
@moscicki Thanks for that. Good to know and I agree. An end user will have the expectation that everything is synced including conflict files simply because they are in their local sync folder. I'm not sure what implications there may be for simply uploading the conflict file though. What would happen for a shared folder where multiple people have conflict files? Can we be sure that the locally created file names will be unique so they can all co-exist together.

**Comment by jancborchardt** [comment]
@shopps as @ogoffart already said: Dropbox does it exactly like this. »There are no other cloud storage apps that behave in this way« is not true.
