### ISSUE TITLE
Misleading "Syncing all files in your account with" ...

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#3430]
In the accounts list it says "Syncing all in your account with "...
![image](https://cloud.githubusercontent.com/assets/639487/8594922/0d94ff42-2646-11e5-865a-eb10258a87cf.png)
It's misleading in two ways: 
* It's indicating that a sync is happening right now (although it might not).
* In my case not _all_ files are synced - only some folders.

**Comment by phil-davis** [comment]
It could just say:
"Synced files in your account with"
as once the green tick is there, then the sync is action completed/past.
Leaving out "all" avoids any implied promise of "all" - because actually there are various "tmp/hidden" files that are never synced (but I guess they are not on the server to be synced) and you might have explicitly told it not to sync some folders...
Or the word "all" could be specified only if the client has no excluded files/folders.

**Comment by pascalBokBok** [comment]
Perhaps simpler "Using folder X"

**Comment by jancborchardt** [comment]
Honestly here only 2 pieces of information are important:
* the server (already shows that above)
* the local folder

So here I would only show the folder name (without the technical /home/user/ prefix). And the »ownCloud« alias is not needed. cc @ogoffart ref #783

**Comment by moscicki** [comment]
@jancborchardt : about /home/user/: let me disagree. We have sophisticated users who sync folders other than /home/user/owncloud and also who sync multiple sync folder pairs. In both cases it is a vital piece of information where is your local sync folder located.

I would agree with removing "all" because it is confusing and not needed, indeed.

**Comment by jancborchardt** [comment]
> We have sophisticated users who sync folders other than /home/user/owncloud and also who sync multiple sync folder pairs.

Of course in the case when it’s a different path than the default `home/user`, as well as multiple folders, the full path can be shown. But for the default setup it is not needed.

**Comment by pascalBokBok** [comment]
So how about replacing 
"Syncing all files in your account with 
/home/username/owncloud" 
with
"Local folder /home/username/owncloud"

?

**Comment by phil-davis** [comment]
Just a note that in the recent nightly builds it now says:
"Syncing selected files in your account with"...
There is currently no logic to changed between "selected" and "all" depending if only some folders are selected or if all folders are selected for sync. I guess when "all" folders are "selected" then it is still true that it is "Syncing selected file".
Anyway, words that do not even mention "selected" or "all" will avoid that issue altogether.

**Comment by jancborchardt** [comment]
Yeah, maybe it’s best to just say:

> Local folder: ownCloud
> (space for the loading bar)

(Please remove the `/home/username/` technical part – it’s not necessary unless the folder is not in the home directory.)

@guruz @ogoffart ok?

**Comment by guruz** [comment]
Done aa6c09d9425246a9e35430402aaae2f14d95b022
