### ISSUE TITLE
Auto-shutdown upon sync

### ISSUE THREAD

**Issue by JakeCowton** [owncloud/client#3494]
Leaving my PC running overnight to sync my large files is a waste of electricity.

It would be great to have an "Auto-shutdown" feature to send the shutdown command (or log off, restart etc,) Once the synchronisation has completed.

**Comment by danimo** [comment]
Thank you for your request.

ownCloud Client is designed for continuous syncing, rather than being a one-time sync tool that 'completed'. Thus, your request isn't really implementable. Note that even though it might
intuitively sound simple to define a "sync run", but it's not, because there is no way to be sure
that _everything_ has been synched in the common case (suppose e.g. someone else is still uploading data while your client syncs).

Another possibility is to use the `owncloudcmd` binary, which implements a one-time sync,
and combine it with a script that shuts down the machine.

Thus I'm closing this request.
