### ISSUE TITLE
Keyboard accessibility of setup wizard

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3508]
Pressing enter to confirm a field in the wizard does not jump to the next step.
For example when you put in the URL or username and password, it’s expected that pressing enter works as confirmation. That’s the usual way forms / log in functions like these work.

(Also, tabbing to the »Next« and other buttons below is not possible.)

This happened with latest stable on OS X.

**Comment by ogoffart** [comment]
Qt is following the OS X look and feel. This is how every other wizard behave on OS X.
@jturcotte: can you confirm?

**Comment by jturcotte** [comment]
Qt disables it explicitly on OS X: http://code.woboq.org/qt5/qtbase/src/widgets/dialogs/qwizard.cpp.html#1420

You also can't press enter in standard "Assistants" (that they call them) to go to the next screen. But you should be able to tab to the Next button if you activate it in your settings: http://superuser.com/a/473145/27750

**Comment by jancborchardt** [comment]
Strange, any idea why it’s auto-disabled? It came up when I watched a friend install ownCloud and the desktop client and it was a small but annoying bug.

**Comment by jturcotte** [comment]
It annoyed me a lot at the beginning too. It's disabled because that's how OS X does it across its interface, for consistency. As to why Apple chose this I don't know, maybe it thought that users wouldn't expect the enter key in an edit field to have an impact on the whole dialog, that might have been decided years before the web made this a common thing (just speculating).

There are some dialogs in XCode, etc. that do allow the enter key, so I wouldn't be against over-rulling the consistency in this case if it's not too difficult.

**Comment by jancborchardt** [comment]
If it’s not too difficult then it would indeed be cool to have the enter key work in the wizard at least for the steps with input fields (URL input and credentials screen).

**Comment by hodyroff** [comment]
Client behaves like the platform defaults. Sounds perfect for me. Please reopen with arguments if you disagree.
