### ISSUE TITLE
F12 Log is not the same as the ownCloud client log

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#3518]
We are getting some requests for making the ownCloud client log acheived via F12 the same as the whole ownCloud log.

Apparently when there is an issue, it is very hard to completely diagnose it without the client log, but this log is hard to tell people how to get running properly. Or rather, it is hard to get them to provide. It it were tied to F12, that would make it a lot easier to debug and diagnose.

Thoughts?

@cdamken 

00003489

**Comment by danimo** [comment]
@MTRichards Can you explain what you mean by "the whole client log?"

**Comment by MTRichards** [comment]
Translating from a customer comment, but pressing F12 doesn't seem to provide as much info as launching with --logfile enabled at the command line.

**Comment by danimo** [comment]
Doubtful, it's the exact same output. The only difference is that F12 only starts to show the output starting from the moment the window opens.

**Comment by MTRichards** [comment]
Ok, then consider this confirmed.
@cdamken please communicate this to the customer and get further clarification.

**Comment by cdamken** [comment]
@danimo The  explanation is easy: Once we notice a problem occurs with the client, we actually ask to get logs pressing F12, at that time all the problems already happened and most of them are not possible to reproduce again.

The customer wrote:
>When one of our end-user has problem with the synchronization, we usually ask for the log file. Now we found out that the standard client log with F12 is not as good as the logs created when starting the client with the —log-dir option.

>Could you add a feature where that log could be triggered from the client as it is a bit a hassle to explain the user how to start the client with that better log option. 

IMHO, could be an option where the last 2 or 3 syncs could be saved automatically and/or rotated if needed (Maybe zipped). Where the end-user (that most of the time doesn't know how to get, save the log file or reproduce the problem) could extract in an easy way (probably in the Activity or General Tab).


That way we can provide the logs from the beginning of the sync

**Comment by cdamken** [comment]
@MTRichards @danimo Do you need more information from the customer?

**Comment by MTRichards** [comment]
No, I think it is clear now what is missing - they want a rolling sync log. Problem is, this will not solve their problem. So while I understand their request, I am not sure that I can solve it. 

For example, let's assume I keep a log for the last day. It will be large enough, but ok - we have a log. Then, let's assume that I notice I lost a file, and want the log to deal with it. If I am lucky, the issue happened in the last day. If not, the log is gone - and this will be continually a problem if we set the time to a week, or a month. 

Not sure how to actually solve the problem of getting a log file for a problem after the fact, without logging everything for the last 30 days, which gets really really big and then is even harder to dig through for analysis of the problem. So I am leaving it here to try and come up with an idea of how to help here.

**Comment by cdamken** [comment]
@dragotin  I still see ```Needs info``` Is it something I have to ask?

**Comment by ogoffart** [comment]
there is the `--logdir`  option that does exactly that.

**Comment by cdamken** [comment]
@ogoffart 
> there is the --logdir option that does exactly that.

the clients does not start with --logdir as default. that make hard to reproduce it again when they don't know exactly how it happened.

@MTRichards 
> . So I am leaving it here to try and come up with an idea of how to help here.

Could we Zip the logs per hour or day? and defined by default to keep them 1 week probably and could be incremented or reduced in the configuration of the client..

**Comment by dragotin** [comment]
Use `--logdir /log/directory`. That will create one log per sync run, and the dir will grow huge. But to solve that the customer can set up any automatic deletion such as
```
find . -type f -mtime +30 -delete
```
driven by cron.

Remember that the F12-log is purely a developers log, hardly useful for most usecases. If we want better diagnose tools, we need to think about that.

**Comment by cdamken** [comment]
I have to go back to the point: This is a feature request from the customer:
https://github.com/owncloud/client/issues/3518#issuecomment-126325037

We ask to the customers to provide us Log files when they have a problem. at the same time they ask to the end users the same thing.

By default is not ```--logdir``` and they can't reproduce the error again.

This enhancement is __to help the developers to improve the product__, is not for the end user. Sometimes pressing F12 Is too late.

**Comment by thetrial** [comment]
In above mentioned reference »Client Logfile (Window) on Mac« I had written this:

*****
I would suggest, that there is a dedicated button in the client to open a logwindow. F12 usually defaults to Exposé on most (?) Mac systems. Or, at least there should be a possibility to make an own shortcut. Usually one can create shortcuts per application via OSX system preferences, but due to the Client app does not have an own menue, this does not work.

As an alternative I would (symbolic) link the main log to where logfiles usually ar located on a Mac system to read it via the console. But I have not understand if there is a main log per default or not.

For now I have to quit the client so I can start it via cli. To restart a running instance (as mentioned) does not work here. It would be nice to make it possible to acces a main log. And if this does not exist, maybe to –once– adjust that, so it gets created. Maybe via ini/pref-file.

Another idea would be to integrate to log window itself into the client, maybe?
*****

So, after I’ve read this issue here I’m not quite sure if this log exists per se or is invoked by a (e. g.) F12 keystroke. If usually and per default NO log exists, okay. IF it exists, it would be nice to move or link it to an appropriate place for logs (OSX behaves like unix or linux in this case). But my main problem is, F12 usually is preoccupied under OSX with a function (Exposé). So could it be made that way one could assign an own shortcut for that? Via perferences or even via ini-File preference (as advanced setting)? I cannot use F12. Maybe I could assign another Fx, or something like shift-alt-XYZ, etc.

**Comment by michaelstingl** [comment]
@thetrial F12 is usually used for "Show Dashboard" by default in Mac OS X. This could be re-configured in System Preferences > Keyboard > Shortcuts > Mission Control

**Comment by thetrial** [comment]
For technical reasons I cannot change F12 on these machines. That’s the reason why I want to have the ability to change the fix assignation in the OC client.

**Comment by ogoffart** [comment]
I suggest just to create a shortcur with  `--logdir /log/directory  --logexpire 1`
(`--logexpire 1` removes the files after one hours)

Not that generating the log slows down the sync quite a lot.

**Comment by cdamken** [comment]
@ogoffart @MTRichards Can be set somehow by default or activate over the UI?

The end-user will not restart the client and start it over the CLI

**Comment by michaelstingl** [comment]
I like @ogoffart 's solution. Sysadmins easily can create a shortcut on the end-users machine.

Logging always in the background to have logs from the past when hitting F12 is a performance issue. Adding an option in the GUI to enable background-logging, also captures only the future errors, and the issue must be reproducible to solve it.
