### ISSUE TITLE
Owncloud Client repeatedly Syncing files

### ISSUE THREAD

**Issue by RobertBrown3** [owncloud/client#3530]
As I am typing this, I am watching the Owncloud Client on my Windows 8 Desktop. I have a number of selected folders that I am keeping in sync, and the client is performing syncs over and over again.

I am not making changes to any of these files. I am, however, getting repeated notifications that various files are being updated.

Checking the activity log, I am seeing several files being copied over and over again. Clearly, for some reason, the client is not detecting that the updates are not necessary.

This is clearly a bug. Wile it looks like just an annoyance, in reality the repeated copying could create problems on my disk.

Please fix this...

**Comment by phil-davis** [comment]
The devs here are sure to need more info on this. Server and client ownCloud versions, OS... Copy of the log. Use the standard template to make sure you give all the relevant info: https://github.com/owncloud/client/blob/master/issue_template.md

**Comment by dragotin** [comment]
@PVince81 wasn't there a case with changing ETags still open?

**Comment by sivabizruntime** [comment]
Operating system: Windows 7

Web server: apache2

PHP version: 5

ownCloud version: 8.1

Client configuration

Client version: 1.8.4


Log File details:


08-20 11:58:39:458 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 11:58:39:463 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1394 s)
08-20 11:58:39:476 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 11:58:39:477 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 11:58:42:673 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 11:58:42:674 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 11:58:43:586 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 11:58:43:586 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 11:58:43:591 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 11:58:48:585 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:58:48:585 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:58:48:585 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 11:58:52:508 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:58:52:508 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:58:52:508 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0
08-20 11:58:57:572 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://example.com" + "/"
08-20 11:59:06:740 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:06:740 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:06:740 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 11:59:09:475 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 11:59:09:475 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1424 s)
08-20 11:59:09:476 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 11:59:09:477 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 11:59:13:739 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 11:59:13:739 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 11:59:13:743 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 11:59:14:685 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 11:59:14:685 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 11:59:23:741 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:23:741 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:23:741 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 11:59:31:737 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://example.com" + "/"
08-20 11:59:39:490 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 11:59:39:490 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1454 s)
08-20 11:59:39:491 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 11:59:39:491 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 11:59:43:483 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 11:59:43:484 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 11:59:43:486 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 11:59:46:698 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 11:59:46:698 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 11:59:55:724 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:55:724 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 11:59:55:724 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 12:00:06:027 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://example.com" + "/"
08-20 12:00:09:506 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 12:00:09:507 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1484 s)
08-20 12:00:09:509 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 12:00:09:510 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 12:00:14:147 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 12:00:14:148 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 12:00:14:152 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 12:00:15:233 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:15:233 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:15:233 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 12:00:18:710 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 12:00:18:711 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 12:00:27:707 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:27:707 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:27:707 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0
08-20 12:00:39:522 0x7b8ab0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("OwnCloud")
08-20 12:00:39:523 0x7b8ab0 OCC::Folder::slotRunEtagJob: * Trying to check "OwnCloud" for changes via ETag check. (time since last sync: 1514 s)
08-20 12:00:39:524 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "OwnCloud" to check remote ETag
08-20 12:00:39:524 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://example.com" + ""
08-20 12:00:40:086 0x7b8ab0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
08-20 12:00:40:088 0x7b8ab0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

08-20 12:00:40:088 0x7b8ab0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
08-20 12:00:40:506 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://example.com" + "/"
08-20 12:00:43:740 0x7b8ab0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662"" , received: ""55d4902480145""55c9a87fdceed""55b5157cf07db""55d49023d53d6""55ba09c402c8f""55b5157d0a662""
08-20 12:00:43:740 0x7b8ab0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x630ff80)  with name  "OwnCloud"
08-20 12:00:43:743 0x7b8ab0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-20 12:00:48:742 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:48:743 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7531300) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:48:743 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7531300) QObject(0x0)  0 false 3 0
08-20 12:00:50:725 0x7b8ab0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-20 12:00:50:725 0x7b8ab0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://example.com" + "/"
08-20 12:00:59:713 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:59:713 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-20 12:00:59:713 0x75838d8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x9d2b028) QObject(0x0)  0 false 3 0

**Comment by sivabizruntime** [comment]
i am also having the same issue of related this case 3530. and my case was closed 3630. so i shared some information regarding this issue so kindly give me solution for the above said issue...

Thanks in advance....

**Comment by PVince81** [comment]
>wasn't there a case with changing ETags still open?

The only ones I'm aware of are from people using SMB external storages.

**Comment by rawbertp** [comment]
Same problem here. But I think it's only occurring for the SMB storage files.

**Comment by tobybryans** [comment]
Same problem here, and the server is running on filesystem (ie non-SMB) storage. It only seems to happen with shared folders though.

**Comment by guruz** [comment]
Do you guys have any more input on this?
We suspect this is a server issue. Did you try a newer version?

**Comment by ogoffart** [comment]
The attached log in the first comment does not show any download.

Is this problem still hapenning with recent owncloud?  And if yes, please provide a log that does the download.
