### ISSUE TITLE
**HELP** - Sync Client duplicating folders - **HELP**

### ISSUE THREAD

**Issue by davegrenier** [owncloud/client#3553]
Hi,

I was hoping maybe someone here could help me out, I am currently supporting a small business with there owncloud server, and a few days ago a user renamed a folder that is shared with other users, the sync did not seem to go through and now i have a folder with 30GB and a folder with 500mb, then i renamed the folder without spaces on the same users computer hoping it would sync and resolve the issue, now i have 3 folders, one with 10gb, the other with 500mb, and the other with 30gb... WHY!?! the sync takes about 17h to finish and did not seem to finish (i'm assuming).

please someone help me resolve the duplication errors and the mixed folders.

**Comment by danimo** [comment]
Hi, this is a bug tracker, not a support forum. Please try https://forum.owncloud.org. If you narrowed down the problem and it proves to be not a setup issue or a server problem, please report a new issue.

Hint for next time: Instead of `**HELP**`, what really helps you and us to get your problems resolved is a more verbose report as described in https://github.com/owncloud/client/blob/master/CONTRIBUTING.md (which we asked you to read before reporting a new bug).
