### ISSUE TITLE
Clarify notification for updated file

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#3615]
When the file test.txt is updated in my ClientSync folder on a different computer I get a notification:
"ClientSync and 1 other files have been updated"
A better notification would be:
"Updated ClientSync/test.txt"
When multiple files:
"Updated 7 files in ClientSync"

**Comment by guruz** [comment]
@pascalBokBok Your report does not contain any version information.

**Comment by pascalBokBok** [comment]
Using client 1.8.4 against owncloud 8.1.1
I'm using Kubuntu 14.04 with KDE 4.13

As can be seen in #3613, @phil-davis has the same experience with 2.0.0.5393 Windows 10

**Comment by danimo** [comment]
>When the file test.txt is updated in my ClientSync folder on a different computer I get a notification:
>"ClientSync and 1 other files have been updated"
>A better notification would be:
>"Updated ClientSync/test.txt"
>When multiple files:
>"Updated 7 files in ClientSync"

No. That's not the same meaning! The real bug is that ownCloud at this point is not aware of whether it is dealing with files or directories. The idea behind that display was that it would show "File1 and n other files have been updated", but File1 is almost certainly a directory these days. So the correct fix is to make the code aware of the differences between files and directories, instead of considering both as 'synched items'.

**Comment by pascalBokBok** [comment]
@danimo The sync acivity log seems to be able to make the distinction. Can't you just use the same event filter in notifications?

**Comment by pascalBokBok** [comment]
I just wanted to say that the message is the same in client 2.0.0 as described in the issue.

**Comment by ogoffart** [comment]
It should be fixed in 2.0.2 by commit db8f958

**Comment by Dianafg76** [comment]
I tested this issue, and for my is working OK
Desktop v ownCloud-2.1.0.2833-nightly20151028.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed
