### ISSUE TITLE
Slow sync of large amount of files

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#3637]
I just tried to upload 100,000 4KB files to owncloud (via LAN) with the sync client.
After 40 min it had uploaded 5,705. That's too slow. To compare, scp transferred all in 9 minutes.
In the owncloud server the two CPUs were maxed out with Apache 90% of the time and then a bit of postgres.

Owncloud 8.1.1 and sync client 1.8.4 on Kubuntu 14.04

Reproduce:
```sh
mkdir manyFiles
cd manyFiles
dd if=/dev/urandom of=splitMe bs=4K count=100000
split -b 4096 -a 10 splitMe
rm splitMe
cd ..
```
and move the folder manyFiles into your owncloud folder.

**Comment by ogoffart** [comment]
Hi, this is a known issue. There are "inneficiencies" on the owncloud server. that makes upload of many small files slower than it could be.

There are some tricks already to improve performences in playing with the settings. And the core team is also working to improve the performences. (see documentation)

I am closing this issue because we are aware of it and it does not help to have that in the client bug tracker.

**Comment by ogoffart** [comment]
see for example this issue on the core bug tracker:  https://github.com/owncloud/core/issues/7072 )
