### ISSUE TITLE
Desktop Client: Wrong Credentials, Mobile Client works.

### ISSUE THREAD

**Issue by Loris1123** [owncloud/client#3648]
I'm running Owncloud in a Docker container. 
Port 443 of the Container is forwarded to localhost:5001.

Then I created a reverse proxy with Nginx. This is the configuration:

    location /owncloud {
                proxy_pass https://127.0.0.1:5001/owncloud;
                proxy_redirect  https://127.0.0.1:5001/owncloud /owncloud;
                proxy_set_header          Host            $host;
                proxy_set_header          X-Real-IP       $remote_addr;
                proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;

    }

When I access https://my-server-ip/owncloud I can see the loginpage and everything works perfektly.
But when I want to configure the Desktop app (Linux and Windows) it says "Wrong credentials"
The mobile client for android works.

**Comment by guruz** [comment]
Did you try running the Linux client with "```owncloud --logfile - ```" ?

**Comment by Loris1123** [comment]
No I haven't. But here is an interesting part of the log:

    08-19 16:49:01:822 Setup-Log:  "Versuche zu ownCloud an https://SERVER-IP/owncloud zu verbinden..." 
    08-19 16:49:01:822 !!! Mirall::ValidateDavAuthJob created for  QUrl( "https://SERVER-IP/owncloud" )  querying "" 
    08-19 16:49:02:657 void Mirall::AbstractNetworkJob::slotFinished() 202 "Error downloading   https://SERVER-IP/owncloud/remote.php/webdav/ - server replied: Forbidden" 
    08-19 16:49:04:851 Current Wizard page changed to  -1 


So maybe it could be a Serverproblem instead one of the client. But I'm still wondering why the android client is working.

**Comment by Loris1123** [comment]
I think this is no problem with the container. Maybe it is a problem with nginx.   
I just installed owncloud direclty on my server. 
For nginx configuration I used the official documentation:
https://doc.owncloud.org/server/8.0/admin_manual/installation/nginx_configuration.html

I still can't login with the Desktop Client. But the Mobile Client works.

**Comment by zeorin** [comment]
+1

I'm running Ubuntu 15.04 with OwnCloud Desktop client version `1.7.0~beta1+really1.6.4+dfsg-1`, which comes from the `http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_15.04/` repo. My server is a Debian 7 server, running owncloud 8.1.1.3, from the `http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/` repo.

I just updated OwnCloud on my server and then the problem arised.

My desktop system says it's at the latest version (even after an `apt-get update`), but the [site](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) says that 1.8.4 is the latest version.

That's strange... So after trying some different things I figured out that the repository is now `http://download.opensuse.org/repositories/isv:/ownCloud:/`**`desktop`**`/xUbuntu_15.04/` instead of `http://download.opensuse.org/repositories/isv:/ownCloud:/`**`community`**`/xUbuntu_15.04/`.

So I changed the line in `/etc/apt/sources.list.d/owncloud-client.list`, ran `apt-get update` and then fired up Synaptic, which indicated that I had a broken package. I clicked on "Fix broken packages", "Mark all upgrades" and "Apply", restarted the desktop sync client, and presto, no error this time, logged in successfully.

Good luck.

**Comment by Loris1123** [comment]
Correct, it was a version-problem! 
I had used 1.7 of the client from the official ubuntu repositories. With version 2 from opensuse repos it works.
Thank you.

**Comment by ikenaga** [comment]
I solved the issue by correcting owner to folder. When I installed the folder was created as root.

**Comment by apelvis** [comment]
Had a similar issue on Debian Jessie -> solved by using the client in backports, the one in Jessie proper was too old to connect.
