### ISSUE TITLE
Quota shows wrong value

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#3652]
### Expected behaviour
Quota should be the same as it is displayed on the Personal page.

### Actual behaviour
I have 1GB Quota but in the Client it says it would be 12 GB. That's because another user shared a folder, that contains 11GB, with me. The Clients adds the size of shared folders from other users to my quota.

### Server configuration
Operating system: Ubuntu 14.04.3

Web server: Apache/2.4.7

Database: mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

PHP version: 5.5.9-1ubuntu4.11

ownCloud version: 8.1.1

### Client configuration
Client version: 2.0.0git (build 2642)

Operating system: OSX 10.10.5

OS language: en-US

Installation path of client: /Applications

**Comment by PVince81** [comment]
The values returned for "quota-used-bytes" by a PROPFIND on the root are the total sizes of all the folders inside the root, regardless of sharing status. It looks like it's the same values as "oc:size".

Do we want to change the semantics of this and have PROPFIND not return the actual size of a folder but only the occupied size counted in the quota of the current user ?
This means that for a received shared folder the "quota-used-bytes" would always be zero while "oc:size" would be the real folder size.

The IETF says:
"DAV:quota-used-bytes : value in octets representing the amount of disk space used by this resource – including its files and sub-collections but NOT its autonomous sub-collections. ".

Also interesting:
"Since there are many factors that affect the storage used by a set
      of resources, including automatic compression, the size of
      associated metadata, and server-inserted content (such as that
      created by PHP code) in the on-the-wire representation of
      resources, clients are advised to not depend on the value of DAV:
      quota-used-bytes being the sum of the DAV:getcontentlength
      properties for resources contained by a collection."

and
" Additionally, because there may be a number of distinct but
      overlapping sets of resources for which a DAV:quota-used-bytes is
      maintained (Section 4), there may be no correlation between the
      size of the resources in a collection and DAV:quota-used-bytes.
      For example a server that implements user-based quotas, DAV:quota-
      used-bytes usually will be the same for a collection and it's
      members."

From https://tools.ietf.org/html/draft-ietf-webdav-quota-07#section-7

So if we go the "user-based quota" route, we could have the "quota-used-bytes" have the same value everywhere instead of computing a special value based on sharing status.
I believe the sync client only cares about "quota-used-bytes" on the root folder anyway ?

@DeepDiver1975 what do you think ?

**Comment by scolebrook** [comment]
We've just upgraded from 7 to 8.1.3 and are seeing this behavior. This is a significant change for users who are used to having the client tell them their quota total and their usage of that quota. Now they see three numbers that vary constantly and are rather useless from a user perspective. An end user doesn't care about how much storage is taken up on the nebulous black box referred to as "the server". They care about how much stuff they've got in their account and more importantly, how much more stuff can they fit in there.

If a user has 10 GB account but has 500GB of data shared with them, their account could be almost entirely empty from a quota perspective but the usage percentage is very high at 98%. And then they are removed from that share and it's at 0%. Then they are added to other shares. The graph is completely useless and the constantly changing use and total numbers, while still allowing the calculation of available storage, are confusing due to the constant change.

And it's completely inconsistent with what is observed in the web interface which shows what the client used to show, storage used not including shared content, total quota and percentage used.

And of course, this significant user experience change is not documented anywhere to at least give admins a heads up about the mass of post upgrade support tickets they'll get. Our upgrade is 12 hours old and I've gotten one on the weekend. Really looking forward to Monday!

**Comment by gig13** [comment]
@bboule 
Please check

**Comment by gig13** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
@karlitschek @cmonteroluque @MTRichards I guess this discussion needs a decision. Also the approach of having one quota everywhere and only the "your files count against the used space" makes sense.

**Comment by phil-davis** [comment]
Actually a user has (potentially) many quotas that they can have used part of. e.g.:
- User1 own folders and files (that they might have also shared with others, even giving write access so other users can fill the quota of User1...)
- User2 has shared some folder with User1 with write access - that folder has some size of the files in it, and User2 has some total quota, and the remaining quota that User1 can consume in the User2 folder is not just an easy subtraction. It is the remaining quota for User2 taking into account all the files and folders that User2 has, not just what is shared with User1.
- User3 has shared some folder with User1 read-only. Same quota calculation issue here, but in this case the care-factor is lower, because User1 cannot add/change files so they will not care too much too know about the remaining quota of User3.
And so on.

A place where only a single quota is shown should probably just show the quota of the actual user, the quota used so far by files owned by that user, and the simple difference giving the remaining quota.

**Comment by MTRichards** [comment]
Is the question whether to do this or not?:
>Do we want to change the semantics of this and have PROPFIND not return the actual size of a folder but only the occupied size counted in the quota of the current user ?
This means that for a received shared folder the "quota-used-bytes" would always be zero while "oc:size" would be the real folder size.

I think this approach makes sense.

I think the quota should be the amount of disk space used not including sharing. It should be consistent with the web and mobile, and not change. I don't think that the client has to do anything differently, we just need to use the property to return that number...

**Comment by gig13** [comment]
@MorrisJobke @MTRichards 

>And it's completely inconsistent with what is observed in the web interface which shows what the client used to show, storage used not including shared content, total quota and percentage used.

>And of course, this significant user experience change is not documented anywhere to at least give admins a heads up about the mass of post upgrade support tickets they'll get

What is the feedback to customers? Do we have an explanation on how this changed, and what are the next steps for correcting or improving?

**Comment by MorrisJobke** [comment]
> Do we have an explanation on how this changed

On the server side nothing has changed for versions. On the client side the critical changes has been reverted some time ago and everything should be same as before.

**Comment by tflidd** [comment]
I just checked the new 2.1.0rc1 client, and the quota-message is quite confusing:
I have 
* main storage 2.8 MB/5 GB (shown in web interface)
* external local storage 21 GB/31 GB (on external usb drive)
* client shows 21 GB/26 GB

Either you only consider the quota on the personal main storage which would be (like in the webinterface):
2.8 MB/5 GB
or you consider all storages which would be:
21 GB/36 GB

**Comment by gig13** [comment]
@bboule @MorrisJobke 

The only number that matters is the size of the content they own and the size of their quota, exactly as shown in the web interface. The graphical representation of those two numbers clearly demonstrates the only thing that matters to end users there.

i think we are in agreement with @MTRichards 
> I think the quota should be the amount of disk space used not including sharing. It should be consistent with the web and mobile, and not change. I don't think that the client has to do anything differently, we just need to use the property to return that number...

Can we get this set for a milestone?

**Comment by PVince81** [comment]
> We've just upgraded from 7 to 8.1.3 and are seeing this behavior.

Note that the quota behavior was not changed on the server since OC 6, so not sure if the client is doing something differently or if a server bug sneaked in.

**Comment by gig13** [comment]
@PVince81 
Another instance of this occurring with 8.2.2 (upgraded from 8.0.x).
Client version is 2.1.0 and using the official client CentOS repo (Linux).
php version  5.5.30

Client reports 261GB in use (incorrect)
Client shows actual use of "Home" folder at 486GB (correct)
Web reports quota as 1MB (correct)

The "Home" folder is mounted using the LDAP Home plugin. It is a Windows network home directory mounted via SMB on the ownCloud server. We provide a small quota on the ownCloud server because the client otherwise would error when attempting to sync or add files to the Home folder. The Home folder has it's own quota managed through Windows.

Prior to the upgrade to 8.2.x, the client correctly showed 1MB of quota. Since I was running client 2.1.0 prior to the upgrade, this seems like a server side issue.

Syncing still works fine, so this mainly a cosmetic issue, but it is still very confusing.

**Comment by gig13** [comment]
@bboule 
Do you know of other instances where this is also occurring? At least 3 separate instances reported in this case so far.

**Comment by butonic** [comment]
To correctly handle quota we would have to expose the mount points and their free space / quota.

**Comment by MorrisJobke** [comment]
> To correctly handle quota we would have to expose the mount points and their free space / quota.

cc @icewind1991 @DeepDiver1975

**Comment by butonic** [comment]
ping @icewind1991 @DeepDiver1975

**Comment by PVince81** [comment]
So far it looks like the mount points do not tell us free space:
```xml
  <d:response>
    <d:href>/owncloud/remote.php/files/sftp/</d:href>
    <d:propstat>
      <d:prop>
        <oc:size>7176722</oc:size>
        <d:quota-used-bytes>7176722</d:quota-used-bytes>
        <d:quota-available-bytes>-2</d:quota-available-bytes>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/owncloud/remote.php/files/smb/</d:href>
    <d:propstat>
      <d:prop>
        <oc:size>133974803</oc:size>
        <d:quota-used-bytes>133974803</d:quota-used-bytes>
        <d:quota-available-bytes>-2</d:quota-available-bytes>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
```

Might need to implement this for all storage implementations where it makes sense / where it is possible.

**Comment by PVince81** [comment]
Read: might need a specific solution/implementation for every external storage type to grab the remote free size, if the API permits.

I checked phpseclib but didn't see any method that would allow the SFTP storage to retrieve the free space.
@icewind1991 how about the SMB one ?

**Comment by butonic** [comment]
There are external storages that cannot report the free space ([FileInfo::SPACE_UNKNOWN](https://github.com/owncloud/core/blob/c5a200c4198de951dabdd3f783ade655b8ea6434/lib/public/files/fileinfo.php#L52)) and some that deliberatly tell you they provide unlimited space ([FileInfo::SPACE_UNLIMITED](https://github.com/owncloud/core/blob/c5a200c4198de951dabdd3f783ade655b8ea6434/lib/public/files/fileinfo.php#L57))

In both cases we can only try an upload and need to handle failures correctly. We as in web, desktop and mobile clients.

**Comment by gig13** [comment]
@bboule @PVince81  Any milestone for this change?

**Comment by PVince81** [comment]
It depends what change is required.

From the server side, the only change that I see is to find a way for SMB to display the quota from the SMB. But then maybe what we want is actually the quota from LDAP, not from the SMB storage ?

For the client, I'm not sure how the desktop client is supposed to know which folder to use to display the quota. So far it seems to always read the value of the root.

**Comment by PVince81** [comment]
Note that there is an experimental setting to make the quota also count external storage: https://github.com/owncloud/core/blob/master/config/config.sample.php#L1091

But it might break / be wrong when using shares.

**Comment by felixboehm** [comment]
Behaviour on server and client should be at least the same to prevent confusion.

**Comment by MorrisJobke** [comment]
@PVince81 Would it make sense to show the external storages also in the quota list and show: "21 GB used in externalStorage1" for example?

**Comment by MorrisJobke** [comment]
This would at least unify the shown quota on client and server side.

**Comment by PVince81** [comment]
@MorrisJobke that would be nice, but this goes outside the scope of a bugfix and would be a new feature. For the clients it also means it must have a way to retrieve the list of all mount points instead of just somewhat guessing from the file tree. This could be a new API endpoint to get a quota summary.

**Comment by MorrisJobke** [comment]
I will migrate this over to core later.

**Comment by gig13** [comment]
@bboule @MorrisJobke Any milestone set for this?

**Comment by bboule** [comment]
@MorrisJobke can you check with the client team  I am thinking 2.1.2 but we should ask if possible

**Comment by dragotin** [comment]
I am not clear how this concerns the client at all. Please summarize.

**Comment by MorrisJobke** [comment]
> I will migrate this over to core later.

https://github.com/owncloud/core/issues/22254 <- clearly needs to be handled by the server and is an enhancement.

**Comment by gig13** [comment]
@bboule @MorrisJobke What do I communicate back? That were are exploring an enhancement to display different storage quota for possibly 9.1?

**Comment by MorrisJobke** [comment]
> @bboule @MorrisJobke What do I communicate back? That were are exploring an enhancement to display different storage quota for possibly 9.1?

Sounds good.
