### ISSUE TITLE
[2.0rc2] Error Message "Forcing job abort on HTTP connection reset with Qt < 5.4.2"

### ISSUE THREAD

**Issue by zirydy** [owncloud/client#3675]
I would like to report the following issue as I don't see it reported so far. What does this issue of "QT < 5.4.2" suppose to imply in the error log?

### Steps to reproduce
1. Use ownCloud Client to upload a file > 100MB
2. File upload begins
3. The upload completes with error messages.

### Expected behaviour
A file upload should complete without error messages.

### Actual behaviour
**.owncloudsync.log**
#=#=#=# Syncrun started 2015-08-24T21:57:55 until 2015-08-24T21:57:56 (1401 msec)
#=#=#=# Syncrun started 2015-08-24T21:58:42 until 2015-08-24T22:00:49 (127182 msec)
|0|Videos|INST_SYNC|Up|1440446320|55d38c9508dd3|4096||0||0|0|1439927445|55d38c9508dd3|00000101ocggey9e1lvb|INST_NONE|
|0|Videos/test.mp4|INST_NEW|Up|1394559340||216509735||3|Forcing job abort on HTTP connection reset with Qt < 5.4.2.|201|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-08-24T22:01:07 until 2015-08-24T22:03:12 (125138 msec)
|0|Videos|INST_SYNC|Up|1440446320|55d38c9508dd3|4096||0||0|0|1439927445|55d38c9508dd3|00000101ocggey9e1lvb|INST_NONE|
|0|Videos/test.mp4|INST_NEW|Up|1394559340||216509735||3|Forcing job abort on HTTP connection reset with Qt < 5.4.2.|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-08-24T22:04:12 until 2015-08-24T22:23:34 (1161793 msec)
|0|Videos|INST_SYNC|Up|1440446320|55d38c9508dd3|4096||0||0|0|1439927445|55d38c9508dd3|00000101ocggey9e1lvb|INST_NONE|
|0|Videos/test.mp4|INST_NEW|Up|1394559340||216509735||3|Forcing job abort on HTTP connection reset with Qt < 5.4.2.|201|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-08-24T22:24:34 until 2015-08-24T22:26:30 (116016 msec)
|0|Videos|INST_SYNC|Up|1440446320|55d38c9508dd3|4096||0||0|0|1439927445|55d38c9508dd3|00000101ocggey9e1lvb|INST_NONE|
|0|Videos/test.mp4|INST_NEW|Up|1394559340||216509735||1|Unknown error|0|0|0|||INST_NONE|

### Configuration
**ownCloud Client**:
Happens with 2.0rc2, 2.0rc1, 1.8.4

**Database:**
MySQL

**PHP version:**
5.5

**ownCloud version:**
8.1.1

**Comment by guruz** [comment]
Which Qt version do you use? Which OS? Which distro?
Can you enable HTTP Keep alive (with a high number of requests and timeout) on your webserver?

**Comment by zirydy** [comment]
I'm using Ubuntu 15.04 and have Qt 5.4.1 installed (the current version in the Ubuntu repository). I'm not hosting my own server so I'm afraid I don't have the privilege to enable HTTP Keep.

**Comment by astucieux** [comment]
Client Activity MSG: "Forcing job abort on HTTP connection reset with Qt < 5.4.2.3,3 MB"
I'm regularly getting this same issue with my domestic ownCloud 8.1.1 server and client R2.0.0 system.
The OC server is running on my recently built AMD Athlon5350 (4 core) tweaked to 2.2Ghz with 16MB RAM and an ample SSD. The OS is Mint 17.1 LTS (Ubuntu 14.02 Trusty) and up to date. This Linux release is shipped with Apache2 5.5.9 and MySQL Ver:14.14 Distrib 5.5.44
Just the ownCloud DATA component is NFS mounted on a QNAP NAS RAID5 dedicated Share.
Previously I was running ownCloud 6 on a QNAP TS221 NAS (single CPU) and it took around 19hrs to upload my initial cloud folders. Horrendously slow! Hence I built the dedicated 4 core server (with AES support) to speed things up, and it did. The same folders uploaded in under 8 minutes! This was using ownCloud 8.0 and client 1.8 but it wasn't all joy. The client ran into a selection of issues that appeared to be file locking problems and sometimes trying to reload a file that had milliseconds earlier been uploaded. A messy problem that left .name~random hidden files in the local OC folder to be cleaned up.
The client 1.8 was running on a Mint 17.1 desktop machine (4 core) Gigabit LAN.
When OC 8.1.1 was released I upgraded and also deployed the new Redis 2.2.7 extension for "Transactional File Locking" (shows as ACTIVE on Admin Server Status). This has made an improvement because now the car-crash of the client reloading a file that's just been uploaded has stopped. Now I only observe the "Forcing job abort on HTTP....." on the client activity log and at the next client scan interval the aborted file upload is correctly picked-up and into the server cloud.
BTW: the ownCloud client runs as a HTTPS account session and the OC "File Locking" app is enabled.
The client download sync to my other Linux machines+laptops works perfectly on this rig. It's the multiple file uploads (especially JPG's) that comes a cropper.

**Comment by astucieux** [comment]
Follow Up Observation:
I have noticed that I always get this message "Forcing job abort on HTTP connection reset with Qt < 5.4.2.3,3 MB" when I first fire-up+log onto my Linux desktop and I copy/move my first batch of files or subfolder into the local ownCloud-Client sync location. The message can appear on the first, and second; up to 3 files and they all appear to be eventually uploaded after all the others have be processed. For the remainder of my desktop activity, any additional files copied/moved to the sync folder get uploaded without any objections. No further alert messages.... 
BUT: if I quit the ownCloud-client and restart it, the first lot of files it tries to upload will generate the "Forcing job abort on HTTP connection reset with Qt < 5.4.2.3,3 MB" message again! What is this message trying to tell me? It's supposed to be using a secure HTTPS (443) port connection anyway.

**Comment by guruz** [comment]
Please use a recent Qt version.

**Comment by ghiamar** [comment]
Hi! it's happening to me with Ubuntu 15.10 and OwnCLoud Sync 2.1.1, the file I'm attempting to upload is just 12mb zip!

My server is using OC 9 and PHP 7 with APCu 5.1.3

**Forcing job abort on HTTP connection reset with Qt < 5.4.2**

Thanks in advise!

**Comment by guruz** [comment]
@ghiamar You can see the Qt version in the ownCloud client settings dialog. Are you on Qt 4.x still?
If you switch bandwidth limiting to "automtic" does it work then?
You should also configure your server to use keep-alive. https://doc.owncloud.org/server/8.0/admin_manual/configuration_server/performance_tuning.html#keepalive-should-be-configured-with-sensible-defaults

**Comment by ghiamar** [comment]
Thanks @guruz! I set ny apache conf to 

> KeepAlive On
> KeepAliveTimeout 100
> MaxKeepAliveRequests 200
> HostnameLookups Off

Now OC client reduced time from days to 3 hours. Will try later the stress test package and let you know.

My server is using OC 9 and PHP 7 FPM with APCu 5.1.3
