### ISSUE TITLE
Remote Deploy for ownCloud

### ISSUE THREAD

**Issue by arogarth** [owncloud/client#3678]
Hi,

is there a way to remote deploy the oc client? 

Thx

**Comment by guruz** [comment]
What does this mean?

**Comment by stonerl** [comment]
@guruz I think what he wants to know is how to deploy the client from a server to client PCs.

@arogarth It depends on what you intend to do. I assume you intend to install the Client on Windows PCs. ownCloud uses the [NSIS-Installer] (http://nsis.sourceforge.net/). The NSIS Installer only allows you to use a few options for unattended installation.

http://unattended.sourceforge.net/installers.php

By using these command line options you install owncloud without user interaction.

```
owncloud-setup.exe /S /D="C:\Programs\ownCloud\"
```

But you need a general solution for Software Deployment. In case you have an AD-Server running this could be achieved by scripts. But usually when you use an AD you should feed it with msi-packages. Another solution I used a couple of years is [OPSI] (http://uib.de/en/opsi/about-opsi/). This can handle all sorts of installers.

**Comment by danimo** [comment]
There is also an unsupported (and meanwhile abandoned) MSI wrapper that would allow AD deployment: https://github.com/pennmanor/wix-wrapper. Anyway, the request for a native MSI installer is documented in https://github.com/owncloud/client/issues/860, and since this is an issue tracker, not a support forum, I'll close this issue as a duplicate.

**Comment by arogarth** [comment]
Hi,
I want to deploy ownCloud with Kaspersy Enterprise. The WiX-Wrapper doesnt work, but the flag /S work fine. Thank you very much!
