### ISSUE TITLE
[2.0.0] [Windows] 0 byte with Windows' symbolic linked files

### ISSUE THREAD

**Issue by RalfWW** [owncloud/client#3705]
Hi,

having a symbolic link in to a file, the file gat uploaded to OC but with 0 byte.

We had that in the past but it worked with version 1.8.x

Gruss

Ralf

**Comment by guruz** [comment]
We need more info on this. Where does the link point to? Is it inside the same sync directory?
How did it "work" in the past?

**Comment by ogoffart** [comment]
Please us the issue template: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

**Comment by RalfWW** [comment]
### Expected behaviour
The goal (outside of the sync-directory), a symbolic link points to, should be synced.
Example:
.../syncdir/myfile.zip   --is a symlink_to_---> .../Desktop/myfile.zip

### Actual behaviour
A file with 0 byte and the name of the symlink is synced to owncloud.

It is working with symlinks to directorys. All included files in the goal dir are uploaded correctly.

I checked it with Version 1.8.3.5213: same behaviour.
I had in mind that I checked it successfully with a “former” version… :-/


### Steps to reproduce
1. Create a symlink to a file i.e. on your desktop
2. I'm using "Ling Shell Extention" for that under WIN 7 Prof. on NFS-Drive
3.

### Server configuration
Operating system:
Hosting on domain factory
Web server:

Database: MYSQL 5

PHP version: 5.6

ownCloud version: 8.1.1

Storage backend:

### Client configuration
Client version: 2.0.0

Operating system: Win 7 Prof SP1

OS language: German

Installation path of client: "C:\Program Files (x86)\ownCloud"

**Comment by phil-davis** [comment]
For the record, here are my results using the various types of file symbolic link in Windows.
Create a symbolic link, a hard link and a junction point in the ownCloud sync tree to some file outside the ownCloud sync tree:
```
D:\INF>mklink D:\INF\Banke-Office1.jpg D:\Personal\Photos\Banke-Office1.jpg
symbolic link created for D:\INF\Banke-Office1.jpg <<===>> D:\Personal\Photos\Banke-Office1.jpg

D:\INF>mklink /H D:\INF\Banke-Office1H.jpg D:\Personal\Photos\Banke-Office1.jpg
Hardlink created for D:\INF\Banke-Office1H.jpg <<===>> D:\Personal\Photos\Banke-Office1.jpg

D:\INF>mklink /J D:\INF\Banke-Office1J.jpg D:\Personal\Photos\Banke-Office1.jpg
Junction created for D:\INF\Banke-Office1J.jpg <<===>> D:\Personal\Photos\Banke-Office1.jpg

D:\INF>dir b*
 Volume in drive D is Data
 Volume Serial Number is 3A98-CDC5

 Directory of D:\INF

08/31/2015  02:17 PM    <SYMLINK>      Banke-Office1.jpg [D:\Personal\Photos\Banke-Office1.jpg]
06/25/2015  01:15 PM           609,424 Banke-Office1H.jpg
08/31/2015  02:18 PM    <JUNCTION>     Banke-Office1J.jpg [D:\Personal\Photos\Banke-Office1.jpg]
               2 File(s)        609,424 bytes
               1 Dir(s)  45,593,227,264 bytes free
```
The hard link looks just like a real file in the "dir" listing. The others show their link type.
On the ownCloud server GUI:
![banke-office1](https://cloud.githubusercontent.com/assets/1535615/9575079/70e11ef8-4fec-11e5-9e4b-3e1214dabf23.png)
On the client activity:
![banke-office1-activity](https://cloud.githubusercontent.com/assets/1535615/9575090/7f3937c4-4fec-11e5-81ea-02084a04102d.png)
The file that is a hard link gets to the ownCloud server correctly - that is expected because hard links really do look just like real file entries in folders.
The file that is a symbolic link gets to ownCloud, but is 0 bytes - I guess something could be done to make that better, which is the topic of this issue report.
The file that is a junction point gets an "Access is denied" in the activity log. Note that this place on my ownCloud server happens to be an external storage to a Windows Server file share, the access denied might be reflecting back from the Windows Server that will not let a Junction Point be created. I will investigate that, but actually maybe ownCloud client should ignore junction points???

**Comment by phil-davis** [comment]
I tried the same thing to a "native" ownCloud server 8.0 out on the internet and got the same results, including the "access is denied" for the Junction Point - actually I thought that Junction Points have to be directories, so I am surprised that Windows lets me create a Junction Point that points to a file.

**Comment by phil-davis** [comment]
Making a directory symbolic link or junction point works fine - the files inside the "pointed-to" folder get synced up to the ownCloud server. So that is all fine with directories.
```
mklink /D
mklink /D /J
```

**Comment by guruz** [comment]
Since it also doesn't work with an old version we probably never supported it.
(So it's also not a regression of 2.0's new discovery Windows vio code by @dragotin )

**Comment by ogoffart** [comment]
Closing old issue. PLease reopen if this is still the case in recent version.
