### ISSUE TITLE
another minor message edit

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3745]
@jancborchardt:

What about "Remove sync" instead of "Remove folder". We are not really removing folder, are we?

![image](https://cloud.githubusercontent.com/assets/621965/9676600/849300da-52ce-11e5-9433-7d9f033de94d.png)

**Comment by phil-davis** [comment]
:+1:

**Comment by guruz** [comment]
@jancborchardt ...also we should probably not use "Delete" for the account button and "Remove" for the folder button?

**Comment by phil-davis** [comment]
Perhaps "Remove sync connection"?
IMHO the word "folder" should not be there, because to mere mortals that means what it says, an actual folder. The actual folder is not removed by this action, it remains behind on the client in whatever state it was in when the sync connection was removed.
But of course the length of text in menu items like this is also a consideration/tradeoff - after translation to German the words will all be twice as long and it will fill the screen :)

**Comment by jancborchardt** [comment]
»Remove sync« sounds good. Also the »Remove« instead of »Delete« for an account. cc @guruz 

@jnweiger sure it’s complicated, but we have to show it in a simple way.

**Comment by danimo** [comment]
Renamed the button (needs relocation, but that's another issues) and the action.

![image](https://cloud.githubusercontent.com/assets/1315934/9776742/eb275878-575b-11e5-82dd-c92dc15ddec6.png)

**Comment by carlaschroder** [comment]
But I thought removing the sync also removed the local folder?

**Comment by carlaschroder** [comment]
So it behaved like Delete.

**Comment by carlaschroder** [comment]
I fired up a test instance and clicked 'Remove Folder', and a nice message appeared explaining 'Do you really want to stop syncing with the folder ownCloud? (my local sync folder). Note: this will not delete files'. While removing folders from selective sync does delete them, and a nice message appears explaining this. It's a bit confusing, though the messages are helpful. I'm fine with 'Remove sync' and will update the docs.

**Comment by Dianafg76** [comment]
I tested this issue, and the name for the button is "Remove sync"
Desktop v ownCloud-2.0.2.2713-nightly20150914.pkg  
Closed
