### ISSUE TITLE
When upgrading of Windows client 2.0 to 2.0.1 sync folders were lost

### ISSUE THREAD

**Issue by tangix** [owncloud/client#3747]
Was prompted this morning to update my Windows Desktop Sync Client to 2.0.1 (build 5445) running on Windows 8.1 64-bit. After the update was installed all configured folders were lost and had to be re-added manually.

**Comment by RalfWW** [comment]
Same on my side with WIN 7 Prof SP1 German 64bit.

**Comment by phil-davis** [comment]
My Windows 10 Pro 32 bit English (US) upgraded fine.

**Comment by tangix** [comment]
Should probably add that I am running Swedish Windows 8.1. Folder-names issue?

**Comment by guruz** [comment]
@tangix Did your sync folder name (or any parent folder) contain ø å etc?
@RalfWW or similar?

Were the configured folders gone or the configured folders and the account (URL etc) ?

**Comment by tangix** [comment]
@guruz Yes, in Swedish the path is "C:\Användare\msa.TANGIX\owncloud" (C:\Users\msa.TANGIX\ownCloud in Englisg when copying pasting).

**Comment by RalfWW** [comment]
The 2 accounts are still there.

I was able to re-adding the sync-folder at one account only Server is a 8.1.1 fresh installation

But the other account is "working" but the listing of the available folders is not working. Server is a updated 8.1.1
I found out, that the connection to a remote WEBDAV-Server is not working.
After removing that definition (with path at /root) listing is working again.

@guruz There are no spezial characters in the root folder's names.

**Comment by tangix** [comment]
From my old config-file in C:\Users\msa.TANGIX\AppData\Local\ownCloud\owncloud.cfg.aE9772 I see that it is in fact the English version of the path used, but with standard slash:
[Accounts]
0\Folders\ownCloud\localPath=C:/Users/msa.TANGIX/ownCloud/

But after re-adding the synched folder I see in the new owncloud.cfg the path is escaped with double back-slash.
0\Folders\ownCloud\localPath=C:\\Users\\msa.TANGIX\\ownCloud

**Comment by Siedlerchr** [comment]
I also have the same problem win 7 SP1 x64 German, and none of my paths contains any umlauts, but they contain spaces. But the two remaining folders also contain White spaces.
And the files in the remaining folders also contain Umlauts.

**Comment by ckamm** [comment]
This is odd because there's only a single-line diff between 2.0.0 and 2.0.1 - and it's an unrelated wizard fix. Are you sure you were updating from the official 2.0.0 release to the 2.0.1 release?

**Comment by Siedlerchr** [comment]
@ckamm  Yes,  yesterday I got the notification and today I did the auto-update. 
My prev version was : ownCloud-2.0.0.5423 and now my version is 2.01.5446

**Comment by vkimball** [comment]
Same thing happened to me on two different Windows PCs.  One XP and the other Windows 7.  Didn't happen on Mac or Ubuntu Linux updates.

**Comment by mikaelfrykholm** [comment]
The difference seems to be that the folders to sync is now in owncloud.cfg instead of folders/*
```
0\Folders\ownCloud\localPath=/home/mikael/ownCloud
0\Folders\ownCloud\targetPath=/ronin
0\Folders\ownCloud\paused=false
0\Folders\ownCloud\ignoreHiddenFiles=true
```

folders/ownCloud
```
[ownCloud]
localPath=/home/mikael/ownCloud
targetPath=/ronin
backend=owncloud
connection=ownCloud
```

**Comment by skimpax** [comment]
Idem for me: synced directory configuration was lost after upgrade to 2.0.1_5446 (was in official 2.0.0).
Did the upgrade just by clicking OK on upgrade notification.
Client on Win 7 Pro / 64bits / French

**Comment by tangix** [comment]
Just upgraded my other systems running Windows 7 64-bit and Win 8.1 64-bit, both running English OS versions. No problems at all, all settings kept.

**Comment by tjharman** [comment]
Windows 7 64-bit
Lost all folders on upgrade.

**Comment by dubsflyt** [comment]
I have also yesterday seen this same problem on 2.0.0, the only thing the user had done was rebooted the machine (some windows updates installed at the same time) and subsequently the sync folder config was wiped.

I have also seen it from every user who upgraded to 2.0.1 but only the one user on 2.0.0

**Comment by phil-davis** [comment]
This happened to me only on my home laptop. It did an auto-update from 2.0.0 to 2.0.1 on Windows 10 and prompted me for admin priv... When ownCloud started again the account was there but no sync folder. I had to add the sync folder again.
On other systems I have done manual updates using the full downloaded installer and had no problem.
Is this problem only happening when the update is done with the auto-updater?

**Comment by guruz** [comment]
@phil-davis Interesting theory... but then i would have guessed the config-losing to be all or nothing, not keeping the sync URL

**Comment by Siedlerchr** [comment]
Interestingly on my Win7 32bit notebook, upgrading from 1.84 to 2.01 via autoupdate worked with no problems. All folders intact.

**Comment by dragotin** [comment]
Can you guys check the old place where the folders resided ($HOME/.local/share/data/owncloud/folders for Unixoids) and paste the file names of the files residing there to this report?

**Comment by Siedlerchr** [comment]
@dragotin 
In Windows it's placed under: C:\Users\<UserName>\AppData\Local\ownCloud
```BilderOwnCloud
FSR
LaTex
Rechnungen
UNI
Verwaltungsgedoens
WS1516 - Bacheloarbeit
```

Notebook:
```
BWL_WPR
DataMiningPythonStuff
FSR
LaTex
ownCloud
Rechnungen
Verwaltungsgedoens
```

**Comment by phil-davis** [comment]
My home laptop Windows 10 just has a file called "ownCloud" in C:\Users\Davis\AppData\Local\ownCloud\folders
That file contains:
```[ownCloud]
localPath=F:/Davis-ownCloud/
targetPath=/
backend=owncloud
connection=ownCloud
```
The thing is that I have already added back the same folder sync connection again as was there previously. So good evidence of what happened is probably gone for me.
Note that F: is a partition on the internal hard drive (after C:, D: an HP recovery partition and E: the DVD drive). So F: is always available.

**Comment by individual-it** [comment]
for me in $HOME/.local/share/data/ownCloud/folders there is only one file called "owCloud"

content:
````
[ownCloud]
localPath=/home/xxxxx/OwnCloud/
targetPath=/
backend=owncloud
connection=ownCloud
blackList=@Invalid()
````
but before loosing the connections I had like 5 or 6 connections set up

**Comment by skimpax** [comment]
As said in mly prior comment, configuration lost after upgrade.
Locations of my configuration: C:\Users\chris\AppData\Local\ownCloud
Folders present in C:\Users\chris\AppData\Local\ownCloud\folders: 

C:\Users\chris\AppData\Local\ownCloud\folders\Christophe :
[Christophe]
localPath=C:\\ZzzData\\Christophe
targetPath=/Christophe
backend=owncloud
connection=ownCloud
blackList=@Invalid()

C:\Users\chris\AppData\Local\ownCloud\folders\Général :
[G%E9n%E9ral]
localPath=C:\\ZzzData\\G\xe9n\xe9ral
targetPath=/G\xe9n\xe9ral
backend=owncloud
connection=ownCloud
blackList=@Invalid()

C:\Users\chris\AppData\Local\ownCloud\folders\Karine :
[Karine]
localPath=C:\\ZzzData\\Karine
targetPath=/Karine
backend=owncloud
connection=ownCloud
blackList=@Invalid()

C:\Users\chris\AppData\Local\ownCloud\folders\Musiques :
[Musiques]
localPath=C:\\Users\\chris\\Music
targetPath=/Musiques
backend=owncloud
connection=ownCloud
blackList=@Invalid()

C:\Users\chris\AppData\Local\ownCloud\folders\Photos :
[Photos]
localPath=C:\\Users\\chris\\Pictures
targetPath=/Photos
backend=owncloud
connection=ownCloud
blackList=@Invalid()

C:\Users\chris\AppData\Local\ownCloud\folders\Pratique:
[Pratique]
localPath=C:\\ZzzData\\Pratique
targetPath=/Pratique
backend=owncloud
connection=ownCloud
blackList=@Invalid()

Update done via auto-update mecanism by clicking on update available notification when poped-up. First time for me I used auto auto-update (always did update by classic downlown/install procedure before).
Issue due to interraction of update/install, with one done in Admin mode but the other in User mode?
Issue due to Locale special characters?  (cf. my character 'é' in one of my folder)
Win 7 Pro / 64bits / French

**Comment by guruz** [comment]
@individual-it Are you implying this also happened on your Linux machine?

**Comment by individual-it** [comment]
@guruz yes, see my first comment on that topic

**Comment by ckamm** [comment]
This may very well be caused by not writing the config file correctly #3820

**Comment by ckamm** [comment]
When the client quits, the account settings are saved to the config file again (Application::slotCleanup). Maybe the configuration was wiped beforehand for some reason, or can't be read properly when that QSettings object sync()s. That'd explain account data being saved in the config file while folder data is missing.

**Comment by ckamm** [comment]
Unfortunately this will happen *again* on the update from 2.0.1 to 2.0.2, because the bug was an unintended side-effect of the shutdown process after launching the updater. :(

**Comment by ckamm** [comment]
@Dianafg76 What's wrong?

**Comment by Dianafg76** [comment]
@ckamm sorry

**Comment by Dianafg76** [comment]
I can't reproduce this issue with Win Server 2008 Enterprise.
@tangix, @RalfWW, @phil-davis Could you try, update from 2.0.1 to 2.0.2, please
Thanks

**Comment by tangix** [comment]
@Dianafg76 : just upgraded from 2.0.1 build 5446 to 2.0.2 build 5464 and my settings survived. No other problems detected.

**Comment by Dianafg76** [comment]
@tangix Many thanks

**Comment by phil-davis** [comment]
I think this problem happened when the auto-updater ran automagically. Whenever I did a manual upgrade it worked fine between any versions.
I have installed 2.0.1 release from scratch on a test machine and set up some folder sync pairs.
Is there a way to trick the 2.0.1 client into finding a 2.0.2 update somewhere?

**Comment by ckamm** [comment]
@phil-davis Yes, this was triggered only when the client started the updater binary and closed itself. 

I think you can trick the client into thinking there's an update by manually adjusting some setting values, but I don't know what combination of settings is necessary exactly.

**Comment by dexternest** [comment]
Am I getting this right, that the issue was closed?
I had the same thing* happening to me today, when I let the owncloud client update itself to the newest version (2.0.2.5569).
But since I'm a newbie here, there might be something I'm not aware of?

*) "There are no sync folders configured"

**Comment by Gizmokid2005** [comment]
I, too, was just hit with this issue when Owncloud auto-updated on Win8.1 x64. The folders are all in C:\Users\Michael\AppData\Local\ownCloud\folders but not configured in the C:\Users\Michael\AppData\Local\ownCloud\owncloud.cfg and the client shows that there are no sync folders configured.

**Comment by dexternest** [comment]
I've opened a new issue, since this had been closed already: #4012

**Comment by gmonkey2** [comment]
Case may have been closed prematurely.  Just upgraded a client from 2.0.1 5546 to 2.0.2 5569 and lost all of my sync data

**Comment by tjharman** [comment]
PEOPLE!! ARGH!
The issue is clear:

IF YOU LET OWNCLOUD UPGRADE FROM 2.0.0/2.0.1 to 2.0.2 BY ITSELF, you will almost certainly lose your sync folders.

THIS IS DUE TO A BUG IN 2.0.0/2.0.1.  It doesn't matter if you later auto-upgrade to 3.8.4 THIS BUG WILL AFFECT YOU IF YOU ARE UPGRADING FROM 2.0.0/2.0.1.

Opening this ticket over and over is pointless.  The issue is fixed in 2.0.2 so that when it upgrades itself, this won't happen.

You can't fix a bug that's already there, deployed to all the 2.0.0/2.0.1 clients.  They have the bug and they trigger it when they upgrade to a newer version.

**Comment by dexternest** [comment]
Ok, THAT is an explanation.
The issue was NOT clear before.
THANKS!

**Comment by dragotin** [comment]
Yes, it is exactly like that, unfortunately. Still no reason to get loud I'd say, but yes, thanks anyway for explaining.

**Comment by GeoSchnitz** [comment]
In that case, what's the best solution to avoid this issue.
Backup the AppData\Local\ownCloud files, deinstall versions 2.0.0/2.0.1, install 2.0.2 and copy back the cfg files and /folder configs?
Does this work because of different configurations-definitions?

**Comment by phil-davis** [comment]
Backup your files - because you should have backup anyway :)
Manually download the 2.0.2 installer. Use that to run the upgrade manually.
That should avoid triggering the problem in 2.0/2.0.1
There should be no need to restore anything from backup.
For me, I never saw this bug on test systems where I had been doing manual installs/upgrades. It was only seen on clients that were allowed to auto-upgrade.
