### ISSUE TITLE
[OS X] No overlay icons anymore - Yosemite -  client ownCloud-2.0.1.2694 

### ISSUE THREAD

**Issue by Claire75** [owncloud/client#3819]
The folder I synchronise is /myname/owncloud , not a system or something "special" one .
I used to have ovelay icons until version 2.0.1 , I do not anymore 

I saw https://github.com/owncloud/client/issues/3680 but they say it's for ~/Library sub-folders 

FOr me, it's for my "standard" folder 

Thanks a lot ...

**Comment by guruz** [comment]
Habe you tried to re-login yourself in OS X?

**Comment by Claire75** [comment]
Yes, I did it more than once .

I fixed it on my mac by
- stopping owncloud client
- removing app 
- removing /Library/Application Support/Owncloud

then reboot
then clean RAM ( sudo purge )
then 
- install ownCloud-1.8.4.2531 : folder's small overlay is back :)
- stop owncloud
- install ownCloud-2.0.0.2666 : icons "dropbox like" is back ( see picture)
- stop owncloud
- install ownCloud-2.0.1.2694 : it's ok 

( I put this answer on the owncloud forum ) 
++ sorry for my english, I'm not a native ... :)

**Comment by jturcotte** [comment]
My guess (copying that info from https://github.com/owncloud/client/issues/2340#issuecomment-135026172):

The extension loading is now handled by OSX directly instead of having to inject the bundle directly in Finder, so you can find the option in [System Preferences / Extensions / Finder] where you should be able to enable the "ownCloud Extensions"

There are some situations where the extension wouldn't be enabled properly on the first install, but normally just enabling it there should make it available again.

**Comment by dragotin** [comment]
So can this be closed as nothing to be fixed? Maybe it's worth an entry in the FAQs.

**Comment by jturcotte** [comment]
I feel quite bad about that behavior, already 2-3 users have reported the issue, and I think that many that aren't actively looking for their missing overlay icons might be suffering from it.

However:
- I'm not even sure if we can do better, I haven't found a way in the documentation. See http://apple.stackexchange.com/q/156023
- We already do the "pluginkit -e use ..." hack in the installer. This might fail if the extension wasn't discovered when we run the command though, but this should not happen anymore if the user upgrades from a version that already had the extension (like from 2.0.0 to 2.0.1 in @Claire75's example). So maybe the bug is only actually an issue when users are installing it for the first time or upgrading from <2.0.

In any case I think that it's probably worth putting an entry in the FAQ that it might be required that they activate the extension manually in System Preferences. This bug doesn't sound like 2.0.2 material, so if we don't close it we should move it to the backlog until we see it as a more severe issue.

**Comment by Claire75** [comment]
I must say that I do any upgrade , so I was in 2.0.0 when I upgraded to 2.0.1.

I "came back" to the 1.8.4 because after the desinstall of 2.0.1 (and remove of /Library/Application Support/Owncloud , and reboot, and purge RAM ) I first try to install 2.0.0 and ... no icons. That's why I turn back to 1.8.4 . 

I don't know if this can help. I just notice that overlay icons are not the same between 1.8.4 ( very tiny one on the folder icon) and 2.0.0 ( a "like dropbox" separate from the folder icon ) .
 
Now everything is ok and works fine for me :) :) :)

**Comment by jturcotte** [comment]
Ok cool, I'll leave the bug open for the FAQ adding task since it's better to enable it through the Extensions settings than going back to 1.8.4 :)

**Comment by guruz** [comment]
What we do in the installer might be more reliable now: 6a9655aab6b0b06dc4085dcb01ff7ef4131100ee 

Let's still keep this Known Issue open until we're at 2.3 ..
