### ISSUE TITLE
Windows Client 2.0.1 (build 5446) syncing whole user folder...

### ISSUE THREAD

**Issue by phillip-hodges-ncc** [owncloud/client#3827]
OK, I'm having an issue with the latest version of the Windows Client 2.0.1 (build 5446). I have set-up several folders to synchronize, Pictures, Music, etc.

I'm having issues with the 'My Documents' sync. Whenever I try selecting "C:\Users\Phillip\Documents" or "My Documents" it starts syncing the whole user folder "C:\Users\Phillip". It doesn't indicate it is doing the whole user folder, however by looking into the the "Documents" folder in the on-line version I can see the music, pictures and downloads, etc.

It is uploading the contents of the "C:\Users\Phillip\Documents" folder and the contents of "C:\Users\Phillip" into the same remote folder "Documents".

I am running v8.1 of the owncloud server and my PC is running Windows 7 Enterprise.

Any help or advice would be great.

Phil

**Comment by phil-davis** [comment]
Welcome, great to see you spell Phillip with double-l.
Are you using selective sync somehow and that causes the files in the parent folder to also be synced - if so read https://github.com/owncloud/client/issues/3632
Otherwise, are there sym links in My Documents that point across to Pictures, Music...?
Actually users have been having trouble getting sync to work at all when there are sym links in My Documents - https://github.com/owncloud/client/issues/3813
But you seem to be having trouble with too much syncing?

Can you show some settings of the various folder sync connections that you have made?
