### ISSUE TITLE
Add option to disable/pause a ownCloud account

### ISSUE THREAD

**Issue by schiesbn** [owncloud/client#3829]
Just an idea but maybe it would be a nice small feature:
If you sync multiple accounts with the clients it can happen that you don't always want to sync all accounts. Therefore it would be nice if the user could disable/enable different ownCloud accounts.

**Comment by guruz** [comment]
You should be able to disable an individual sync folder with the ```...``` button.

Would it help you to have this option also in the tray menu for the whole account instead of the sync folder?

FYI @jancborchardt

**Comment by schiesbn** [comment]
@guruz ah, nice... well hidden feature. :wink:  Putting it in the tray menu sounds like a good idea to me.

Maybe also the name should be different? "pause sync" sounds to me like something you do only for a really short period of time and which gets reseted if you restart the client. I would rather call it "disable account" and "enable account", or something similar. @jancborchardt what do you think?

**Comment by jancborchardt** [comment]
The usecases for pausing/disabling vary, and so does the time. Other apps also call it something like Pause so I would stick with that. :) We have that since some time and haven’t had any complaints so far about it not being understandable.

**Comment by schiesbn** [comment]
I only looked for it now that we have multi-account support. Because I don't want that my devel account syncs all the time but only when I need it. I wouldn't have thought that "pause sync" is what I'm looking for. I looked for a option to enable/disable the account. Anyway, I can live with the name but it would be nice if would be easier to find, like suggested by @guruz

**Comment by michaelstingl** [comment]
I would need a pause button in the tray menu to pause ALL syncing to save my 3G data plan.

00004038

**Comment by michaelstingl** [comment]
Does this interfere with https://github.com/owncloud/client/issues/1971 ?

**Comment by r2evans** [comment]
My vote/suggestion:

I prefer the label of "Pause" to "disable", personally, and since the pause state persists across app restarts (so, if paused when the machine shuts down or reboots, it will be paused when it starts up again), I'm generally happy with its current behavior.

I do like the idea of adding an option to the taskbar, something like this:

![ocpause](https://cloud.githubusercontent.com/assets/5815808/11321219/4547e6e0-906b-11e5-9f47-4708bd22b0a0.png)

**Comment by MTRichards** [comment]
@dragotin @danimo something to consider for 2.2.

**Comment by danimo** [comment]
@MTRichards I'd rather fix the server...

**Comment by MTRichards** [comment]
We already have the pause button, all I want to consider is the request for putting it in the context menu. It is a blue ticket.

**Comment by jancborchardt** [comment]
We try to cram too much in that menu already. I would strongly advise against putting this option in there since we already have it in the main settings window anyway.

At least until we consider redesigning the tray menu to be more focused and flexible than just lines of links: https://github.com/owncloud/client/issues/1748

**Comment by martin-rueegg** [comment]
i could not find any info regarding pausing an account, except for a specific folder - which actually pauses the entire account indeed.
having the option in the drop-down menu of a folder sync definition, rather than in the account drop-down, seems counter-intuitive.

regarding having it in the context menu of the tray icon: yes, it would be great to have it there, which would be much more appreciated than the list of all synchronized local folders (if the menu should be un-cluttered).

**Comment by bboule** [comment]
@cmonteroluque does this require an assignment?

**Comment by cmonteroluque** [comment]
@dragotin heads up

**Comment by ckamm** [comment]
There are now options to pause and unpause all folders in the tray menu. The tray icon also changes now if all folders are paused.

**Comment by michaelstingl** [comment]
@ckamm Great, Thanks! Could you post a screenshot?

**Comment by ckamm** [comment]
@michaelstingl Here you go:
![pause3](https://cloud.githubusercontent.com/assets/833306/13457485/c4fd4734-e068-11e5-997d-d39a4c3ef416.png)

**Comment by guruz** [comment]
Tested and works nicely for me.

@michaelstingl It's in the nightly from this morning

**Comment by martin-rueegg** [comment]
on windows 8.1 with [Version 2.2.0-nightly20160302 (build 5878)](https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5878-nightly20160302-setup.exe), i don't get those menu entries. what do i miss?

**Comment by guruz** [comment]
@martin-rueegg You need to have 2 accounts configured to get the one on the left in the screenshot. The one in the right you should get.

Please check the settings dialog if you are really really using that version, it shows the version somewhere.

**Comment by martin-rueegg** [comment]
thanks, @guruz, i did a fresh install (uninstalled 2.1.1) and also checked the version string (acutally, i've copied the string from the frontend to the comment above).
First, i only had one account and was suspecting to see at least the "Pause all synchronization". however, it did't.
Then i added a second account in order to verify if it only appears on two accounts. however, it didn't. :-(

![Screenshot](https://cloud.githubusercontent.com/assets/6409516/13496388/cf591c46-e147-11e5-92f7-9505410a614b.JPG)
