### ISSUE TITLE
Captive Wifi Portal Certificate Error Option To Reconnect

### ISSUE THREAD

**Issue by johnp12345** [owncloud/client#3861]
Hi,

When connecting to a wifi network with a captive portal that intercepts SSL, owncloud windows gives a security warning when it attempts to connect (Expected Behavior). This allows the user to cancel the connection attempt. 

After authenticating to the portal the only way to begin syncing is to exit and restart the client. 
Reconnect button would get around this issue.

Thanks,

John

**Comment by danimo** [comment]
There's a brainstorming ticket in https://github.com/owncloud/client/issues/3731. Please use that rather than opening a new ticket. Anyway, the way to go is not to show a cert warning during automatic connection attempts (rather than explicit ones).

What you are seeing is a side effect of the current state machine design which was not created with this use case in mind: Usually there is no point in retrying when the user rejected an invalid certificate.

**Comment by danimo** [comment]
Apologies, that's the wrong ticket which discusses a related, but not quite the same issue. The right one is https://github.com/owncloud/client/issues/3120.
