### ISSUE TITLE
[2.0.2] You can create the same user with the same account whenever you want

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3878]
### Steps to reproduce
1. You neww install v2.0.2
2. Configurate two account (e.g user1, user2)
3. Go to oC Icon
4. Click on Settings...
5. Clcik on General
6. Click on Add an Account
7. Introduce the same URL than the user2
8. Click on Next
9. Introduce the same name (e.g User2 and the password)
### Expected behaviour

you can't create the same user with the same account as often as you want
### Actual behaviour

You can create the same user with the same account whenever you want

![screen shot 2015-09-24 at 13 22 44](https://cloud.githubusercontent.com/assets/12032058/10072208/f975bf2c-62bf-11e5-88f3-13cdc431c883.png)

![screen shot 2015-09-24 at 13 27 29](https://cloud.githubusercontent.com/assets/12032058/10072213/1184f9ca-62c0-11e5-8dd1-fd4be41232eb.png)
### Server configuration

Desktop v ownCloud-2.0.2.2740-nightly20150924.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by phil-davis** [comment]
I have done this purposely (while playing and testing). For example:
1) Create account 1 for user1 and sync everything to D:\ownCloudme
2) Create account 2 for user1, then set up various folder sync connections to spread the files all around your computer:
a) Documents to C:\Users\me\Documents
b) Pictures to C:\Users\me\Pictures
c) ImportantStuff to C:\ImportantStuff

Now if I add/change things in any of (a) (b) or (c) the changes sync up to the ownCloud server. Then they sync down again to D:\ownCloudme - it seems to work.
D:\ownCloudme effectively contains a mirror of the stuff spread around C drive.

Maybe D: is a physically separate disk or SSD that provides some hardware failure protection. Maybe the user just wants their stuff to be in multiple places for goodness knows why.

For discussion:
Should this be allowed or not?

**Comment by Dianafg76** [comment]
@phil-davis Thanks

**Comment by dragotin** [comment]
So far I think the only thing that should not be allowed is that two syncs use the same local folder. And I think that is prevented by the sync connection setup wizard. 

But even that could work, as long as two syncs do not run in parallel which they do not currently.

**Comment by dragotin** [comment]
so, bottomline, I am not sure if this is a bug at all. @MTRichards thoughts?

**Comment by ckamm** [comment]
I'll move this out of 2.0.2 since it's not urgent.

@phil-davis If we want to support your usecase, wouldn't it be easier to have a single account but allow setting up folder definitions like that? Maybe it's a good idea to hide this behind 'make a second account' though, to not confuse users...

**Comment by phil-davis** [comment]
My "use case" was just an example of what I have done while playing and testing. I don't think that I want to do it as an "ordinary user". I was just pointing out that the current behavior is flexible and happens to work. If a user wants to add the same account 2 times to the multi-account client and have 2 different sets of folder sync connections, then is there a reason to write extra validation code to stop that?
As @dragotin says, "I am not sure if this is a bug at all."
At the moment you cannot have a single account with multiple overlapping folder sync connections - and the "feature" @Dianafg76 has reported here is a way to achieve that.
I guess the validation of adding folder sync connections could be loosened up so that the user could have multiple overlapping folder sync connections, as long as every folder sync connection had a unique client-side sync folder. But I suspect that doing that will mean we get a lot of users who keep the original "sync everything from the root" folder sync connection and add extra folder sync connections to various specific places. And then they will log issues saying everything on the server is downloading twice.
