### ISSUE TITLE
[Shibboleth] [WebKit] Wrong UserAgent on Client with SSO 

### ISSUE THREAD

**Issue by felixboehm** [owncloud/client#3913]
### Expected behaviour
Sync client should use same User-Agent-String on all requests.
Admins require in some setups to route requests to specific servers based on User-Agent-String.

### Actual behaviour
User-Agent-String of a Client changes from "*mirall*" to "*Safari*" after redirection to IDP login page.

### Steps to reproduce
1. Use Shibboleth auth with Sync Client
2. Look into logfiles:

### Logs

[16/Sep/2015:17:43:01 +0200] xxx.xxx.xxx.xxx: demo.owncloud.local.de "PROPFIND /remote.php/webdav/" 302 834 "-" "Mozilla/5.0 (Windows) mirall/2.0.1"
[16/Sep/2015:17:46:51 +0200] xxx.xxx.xxx.xxx: demo.owncloud.local.de "GET /" 302 830 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) ownCloud Safari/538.1"

**Comment by danimo** [comment]
This is by design. Changing the user agent for the QtWebKit component is not a good idea, because this interferes with a lot of websites that (still) do not discriminate by features, but by user agent. I intentionally did not touch the User Agent of the QtWebKit component, which is resembles Safari's user string (which is actually closest to the truth).

That said, We could snak in the Mirall signature, but I am more than hestinent.


That said, We could snak in the Mirall signature, but I am more than hestinent.

**Comment by felixboehm** [comment]
If an IDP login website would reject certain User-Agents, the SSO mechanism would be useless.
Maybe I do not understand the concerns.

@dragotin

**Comment by bboule** [comment]
@MTRichards this seems like a product discussion, could we discuss this and options? considering @danimo concerns, perhaps there is another way to solve this?  I think the issue here is routing requests based on user agent (request coming from desktop, web, or mobile going to different OC servers) and the potential confusion this might cause to someone who is doing this type of filtering/load balancing and the possibility of misrouting a request based agent string with our current behavior...  Sounds like we could/should talk through this before deciding on action?

**Comment by MTRichards** [comment]
Yep. 
If I understand correctly, since we use webviews to authenticate with Shibboleth and not a native window, the switched user agent is true. 
So when the client is redirected to the IDP to log in, it switches to safari on windows because it uses a webview (and probably default webview for Windows and linux too, which is also different). Then once authenticated, it should switch back. Isn't this normal because it reflects the actual nature of the request?

Why is this an issue for this use case? Why are they routing differently based on different clients? Curious what they are trying to do, and more importantly why. Implementing a native shibboleth login, or implementing a change in the user agent string is a little tougher (remember this can also be customized in ownbrander) - not sure what the best answer is.

**Comment by guruz** [comment]
Why not just _append_ the ```mirall``` or ```ownCloud``` or ```$BRANDNAME``` to the user agent?

**Comment by guruz** [comment]
I have a change that changes from
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) ownCloud Safari/538.1
```
to
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) ownCloud Safari/538.1 Mozilla/5.0 (Macintosh) mirall/2.0.2
```

Shall I push this to 2.0.2? @rperezb @cmonteroluque @MTRichards @dragotin

**Comment by rperezb** [comment]
@guruz from ownbrander *it was* or *it is* transparent taken into account: 
https://github.com/owncloud/client/issues/2818#issuecomment-145900582
not sure how your change will be implemented

**Comment by cmonteroluque** [comment]
@guruz if it's still possible I think it would be fine to push to 2.0.2
