### ISSUE TITLE
Deleting folder on server during client file upload results in odd error message

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3921]
### Steps to reproduce
1.Install v 2.0.2 on the Desktop client
2. Create a new account
3. Right click on the oC icon
4. Go to Open Folder.....
5. Create a New folder (e.g. Folder1)
6. Go in to Folder 1
7. Upload a File
8. Go to the Server Web with the same account
9. Delete the Folder1 

### Expected behaviour
It should look like when you move or rename

### Actual behaviour
On the Desktop Client you can't see the error for the File Locked: "Error downloading https..........-server replied: Not Found ......"

### Server configuration
Desktop v ownCloud-2.0.2.2766-nightly20151005.pkg

Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related #3387

**Comment by ckamm** [comment]
@Dianafg76 I'm not convinced this has got anything to do with file locking. Does "File Locked" actually appear in a log or in the UI somewhere?

When you say "it should look like when you move or rename", you mean that if you did this to "Folder1" while an upload to it is in progress, you get better error messaging?

It feels like this could be moved to 2.1 and downgraded in severity since client behavior is ok and it's just the presentation that could be improved, but I'm not yet sure I fully understand this issue.

**Comment by ckamm** [comment]
This still needs investigation of what the actual problem is.

**Comment by ckamm** [comment]
I've tried this and see the following kind of error message: `Error downloading ... - server replied: Not Found (File with name ... cound not be located)`. That seems correct with the exception of "downloading", which has been a known problem for a while.

@Dianafg76 Do you think something needs to be done here?

**Comment by Dianafg76** [comment]
OK
