### ISSUE TITLE
Syncing small files takes apparently 25.000.000 Years

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#3942]
Just noticed something weird with 2.0.2-nightly20151011 (build 2778) on OSX. I had a folder with about 1800 very small files that had to be deleted. The client said it would take 25.000.000. years and went up to 500.000.000 years after that it said 0 seconds. Here are some screenshots:

![screen shot 2015-10-12 at 22 33 20](https://cloud.githubusercontent.com/assets/2091312/10438255/e2a4e62a-7132-11e5-9a5f-dc2eb2219d83.png)
![screen shot 2015-10-12 at 22 33 48](https://cloud.githubusercontent.com/assets/2091312/10438256/e2a63390-7132-11e5-8020-ebab6b6a29c5.png)

**Comment by dragotin** [comment]
Wow - finally we made epic software :grinning:

**Comment by ckamm** [comment]
I'll check this out, maybe progress for deletes is counted weirdly somehow.

**Comment by ckamm** [comment]
I think the problem is that deletions don't lead to any progress on the speed estimator, so the transfer speed estimate gradually drops to 0. Data that needs to be transfered later on will then appear like it'll need a long time.

We know this is a problem and thus transition to a files/second based estimate if it looks like we're processing many files. But you probably didn't get there (it needs around 10 files/s to be processed to kick in).

**Comment by ckamm** [comment]
@Dianafg76 Test note: This is not perfect. Guessing the remaining time is pretty hard. But you shouldn't see millions of years anymore.

**Comment by Dianafg76** [comment]
I tried this, and it is working fine when I removed 1,600 small files , I can't see millions of years
Desktop v ownCloud-2.1.0.2831-nightly20151027.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed
