### ISSUE TITLE
build-dep for owncloud-client fails on Debian 8.2 with unreasonable message.

### ISSUE THREAD

**Issue by DrDamnit** [owncloud/client#3953]
Not sure if this is a Debian issue or not, but here goes:

When building from source, I get this:

root@d8:/usr/src/owncloud-client/client-build# apt-get build-dep owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages have unmet dependencies:
 qtkeychain-dev : Depends: libqtkeychain0 (= 0.4.0-1) but 0.5 is to be installed
E: Build-dependencies for owncloud-client could not be satisfied.

0.5 is between 0.4 and 1 (thus, the "unreasonable" portion of my issue title").

I don't know if this needs to be fixed in the Debian package for ownCloud Client, or at Debian....

I did not have this issue on Debian 8.1.

>lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie

**Comment by guruz** [comment]
@jnweiger @hefee

**Comment by DrDamnit** [comment]
Odd. I seemed to have resolved the issue by doing this:

apt-get remove libqtkeychain0
apt-get install qtkeychain-dev

Then calling cmake, and it was happy.

So, probably this can be closed unless TPTB want to do something else with this.

**Comment by jnweiger** [comment]
qtkeychain-dev : Depends: libqtkeychain0 (= 0.4.0-1)
means that the exact version 0.4.0 is required. The -1 part is the build release number. Not a range.

**Comment by guruz** [comment]
@jnweiger And 0.5 is not binary compatible?

**Comment by hefee** [comment]
qtkeychain is ABI compatible since 0.3.0 this is not the issue here.
qtkeychain-dev is a development package and that requires an exect version of libqtkeychain0.

All other dependencies are createdy by (>= 0.3.0), to reflect, that it can be used with libqtkeychain from 0.3.0 onwards.

I would expect, that this error is caused, by DrDamnit trying to install qtkeychain-dev from another source than libqtkeychain0. Because qtkeychain-dev and libqtkeychain0 have the same upstream tarball and created together, so the version mismatch should not happen.
```
apt-cache policy libqtkeychain0
apt-cache policy qtkeychain-dev
```
shows the available sources for these packages.

**Comment by DrDamnit** [comment]
While I frequently compile from source for certain applications (most notably PHP and asterisk), I never download random versions of dev packages because I know better. You can break all sorts of things. I only install anything -dev  from the Debian repos.

This was, however, most likely originally downloaded while my box was at Debian 8.0 or 8.1. So, if it required an exact version, that may be the cause of the mismatch.

Regardless, I am pretty sure this can be closed since removing it and allowing it to be reinstalled with apt fixed the issue. Unless a bunch of people can reproduce the issue, it's not worth keeping this open.

**Comment by DrDamnit** [comment]
Does this appear to have anything wrong with it? (It would have been more helpful to have this before I fixed the issue)... but none-the-less... here it is.

michael@d8:~$ apt-cache policy libqtkeychain0
libqtkeychain0:
  Installed: 0.4.0-1
  Candidate: 0.4.0-1
  Version table:
 *** 0.4.0-1 0
        500 http://debian.gtisc.gatech.edu/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
michael@d8:~$ apt-cache policy qtkeychain-dev
qtkeychain-dev:
  Installed: 0.4.0-1
  Candidate: 0.4.0-1
  Version table:
 *** 0.4.0-1 0
        500 http://debian.gtisc.gatech.edu/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
michael@d8:~$

**Comment by hefee** [comment]
That does not explain from where you got the libqtkeychain0 0.5. Well owncloud itself creates that version on there [obs](http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/amd64/). So i think that you have downloaded the deb by hand or add the obs repo and removed it in the meanwhile.

But let's close this issue because it is mostly created by hand.

**Comment by DrDamnit** [comment]
That is true!

You sir, are the winner.

I had, at one point, been using the repo version of owncloud, and followed the owncloud.org instructions for adding that repo. But, because it is stuck at 1.6, and does not work with later versions of owncloud server (always gives a forbidden error) I scrapped it, and decided to compile from source.

This definitely explains why the procedure above worked. While I did remove the obs repo from the sources, I did not uninstall things it had installed... I just assumed they would be compatible.

Well done @hefee !

**Comment by DrDamnit** [comment]
I also didn't know that this was installed from that repo. My earlier statement is still true: when I do apt-get install [anything]-dev, I always get it from Debian when I get it on purpose.

**Comment by hefee** [comment]
On debian: If you have an installed version of something, debian will never downgrade anything to reach a normal user action (like installing a package here qtkeychain-dev). Only if you expicitly say that it will do (via apt-get install qtkeychain-dev libqtkeychain0=0.4.0-1).

This issue is a great example of why it is probematic to add additional repos :)

**Comment by hefee** [comment]
Keep in mind when i added the obs repo you install libqtkeychain0 0.5 and 0.5>0.4.0 that's why apt complains about it.

Btw. you can also use the pacakges from backports, if you want a newer owncloud-client:
https://packages.debian.org/source/stable-backports/owncloud-client

**Comment by DrDamnit** [comment]
I normally don't add additional repos. But, owncloud.org had that in the
instructions at one point. :-)

I prefer to compile from source.
