### ISSUE TITLE
Renaming folder caused deletion of files within

### ISSUE THREAD

**Issue by Skanda42** [owncloud/client#3954]
### Expected behaviour
Files and folders remaining after renaming a folder (both on filesystem and server).

### Actual behaviour
After renaming a few folders consequently using filesystem (MAC Finder), folders and related files were deleted in one of the folders renamed.

Local "recent changes" show the operation. There are no records on the server of deletion.

The folders / files are not in bin, not in deleted files on ownCloud server. :'(
 
### Steps to reproduce
Occurred once only - tried to reproduce and didn't succeed.

### Server configuration
Operating system: Linux crotan 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Web server: Apache/2.4.10 (Ubuntu), Server built:   Jul 24 2015 17:25:18

Database: mysql  Ver 14.14 Distrib 5.6.25, for debian-linux-gnu (x86_64) using EditLine wrapper

PHP version: PHP 5.6.4-4ubuntu6.3 (cli) (built: Sep 29 2015 12:44:47)

ownCloud version: 8.1.3

Storage backend: Azure

### Client configuration
Client version: Version 2.0.1 (build 2694)

Operating system: OS X 10.10.5 (14F27), Kernel Version: Darwin 14.5.0

OS language: EN

Installation path of client: applications/owncloud.app

### Logs (samples only)
10:40:13|736|SCORA/30. Operations|INST_RENAME|Up|1441976823|55f2d1f83766b|0|00016297ocahnflp8axm|4||201|0|0|||INST_NONE|
|0|SCORA/30. Operations/00. Orders|INST_RENAME|Up|1441976823|55f2d1f8428eb|0|00017487ocahnflp8axm|4||0|102|1441976773|||INST_NONE|
|0|SCORA/30. Operations/00. Orders/ISO Standards Batch 1 ver 001.xlsx|INST_RENAME|Up|1441976749|33a5a7b6805e32d7122541325a437c2d|50324|00017491ocahnflp8axm|4||0|50324|1441976749|||INST_NONE|
#=#=#=# Syncrun started 2015-10-15T11:40:30 until 2015-10-15T11:40:36 (5890 msec)
10:40:33|2150|SCORA/40. oRganization|INST_RENAME|Up|1444904816|561f7f727215e|0|00016300ocahnflp8axm|4||201|0|0|||INST_NONE|
|0|SCORA/40. oRganization/00. Recruiting|INST_RENAME|Up|1444218028|561504af2eeee|0|00017534ocahnflp8axm|4||0|170|1444218007|||INST_NONE|
...
#=#=#=# Syncrun started 2015-10-15T11:40:41 until 2015-10-15T11:40:46 (4379 msec)
|0|SCORA/40. oRganization/00. Recruiting|INST_REMOVE|Down|1444218007|561504af2eeee|170||4||0|0|0|||INST_NONE|
|0|SCORA/40. oRganization/00. Recruiting/xxx MM.pdf|INST_REMOVE|Down|1442219493|f4d710d4e6dfe55695c6b4470e4992c5|41031||0||0|0|0|||INST_NONE|
...

**Comment by PVince81** [comment]
Possibly related to https://github.com/owncloud/core/issues/13391.

You should be able to make the files reappear in the list by running `./occ files:scan --all` (or `./occ files:scan userid`) on the CLI on the server.

To avoid this happening again, set "filesystem_check_changes" to 0 in config.php.
Also you can enable the new transactional file locking: https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html but you'll need a redis server.

Note that in 8.2 transactional file locking will be enabled by default and uses the DB backend instead of redis (redis will be optional, but has much better performance).

Hope this helps.

**Comment by Skanda42** [comment]
Server Status:  Transactional File Locking is enabled.

Success!

Files have reappeared ...
