### ISSUE TITLE
Latest Windows Sync Client issue ( 2.0.2 build 5569 )

### ISSUE THREAD

**Issue by StopTrain** [owncloud/client#3998]
Noticed this after reinstalling the client on a new Windows 8.1 Pro installation, did not see these before with other clients.

I've noticed that if I want to sync a particular folder to a machine, that it still syncs any single files within the 'root' of the directory.

For example:

/Home
/Work
/Stuff
file.txt
file.doc
file.jpg

If I select /Work to sync locally with C:\ownCloud, it actually does sync the folder, but also syncs file.txt, file.doc, and file.jpg.

So, I end up with C:\ownCloud\Work  with the three individual files synced as well in C:\ownCloud

The prior behavior I recall was you select the remote folder to sync, point it at the local folder such as C:\ownCloud and the files and sub-directories within the remote folder would sync to the root of C:\ownCloud, not become a sub-directory of it.

**Comment by phil-davis** [comment]
This has been discussed before in other Issues - I am having trouble finding them because I can't think of useful words to search for outside of "folder file sync subfolder...!" which of course matches nearly every issue here :(

If you have a Folder Sync Connection at that top level, then use the "Folders to Sync" to select some subset of the folder tree, then if any sub-folder is selected at [some|any] level the the chain of folders above it has to be created on the client - so that a path to the sub-folder exists.

This means the the folders in the path above are "half-selected" in the Folders to Sync tree.

If you have:
/Stuff/Folder1
/Stuff/Folder2
/Stuff/File1.txt

There is currently no way in the UI to specify what to do at the /Stuff level if /Stuff/Folder1 is unselected for sync. /Stuff shows that things are partly selected. There is not way for the user to say what should happen to files in /Stuff

So the files are synced.

If you make and individual Folder Sync Connection for each of /Home /Work /Stuff then those other files will not be seen or synced.

**Comment by StopTrain** [comment]
I just removed the folder sync and allowed it to completely remove the files.

The "Add Folder Sync Connection" button is grayed out.

**Comment by StopTrain** [comment]
Ah ha... I spoke to soon... I figured it out... appreciate the guidance.  It appears that this is a change in behavior from the older clients that I wasn't quite used to yet.

I have this sorted now... Really appreciate it.  Closing ticket!

**Comment by phil-davis** [comment]
No problem - depending on what is required it can be better to make multiple Folder Sync Connections, or to make a single Folder Sync Connection and then select a subset of Folders to Sync withing that Folder Sync Connection.
