### ISSUE TITLE
After upgrade to 2.0.2.5569: "There are no sync folders configured"

### ISSUE THREAD

**Issue by dexternest** [owncloud/client#4012]
This is a continuation of the closed issue #3747.
Two clients upgraded automatically today to the latest version and both lost their sync directory.
Both computers were win7-64.
On both computers the sync folder resides on a separate drive (not in the initially suggested directory).
The accounts remaind unharmed.

**Comment by guruz** [comment]
If I had heard correctly, only the next-update will have this fixed..

FYI @danimo @ckamm

**Comment by danimo** [comment]
Yes, this was unavoidable to happen for some people in 2.0.2, but is fixed from now on. Sorry.

**Comment by dexternest** [comment]
Thanks.
If it was known and unavoidable some advice at the end of the closed issue #3747 would have been helpful though. Or some message within the update process with advice how to solve the problem.

**Comment by gmonkey2** [comment]
Question?  "but is fixed from now on" referring to "a fix is on the way", or the current desktop app is "fixed"?  If the latter, I just updated my app on two computers (Win7 and Win10), both lost all sync settings on update.

**Comment by phil-davis** [comment]
The code in the existing 2.0 and 2.0.1 is the code that controls the upgrade process. So for people that already have 2.0 or 2.0.1 installed there is nothing that can be done about it. The fix is in 2.0.2 - but the fixed code will only get run when upgrading from 2.0.2 to the subsequent release.
The workaround is for everybody to get themselves to 2.0.2 by doing a manual install of 2.0.2 - avoiding letting 2.0 or 2.0.1 do an automatic upgrade avoids the issue.
Also read comments towards the end of https://github.com/owncloud/client/issues/3747
