### ISSUE TITLE
On upgrade to 2.0.2, lost all selective sync and account info

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#4042]
When I upgrade from 2.0.1 to 2.0.2 with the auto update push today, the client remembered my account in the account tab, but the account folder sync connection just disappeared. I tried restarting, but no change. So, I had to remove the account and re enter the account information, and then also select all of the selective sync all over again - which took quite some time to drop 30 GB from my ownCloud server. 

I would expect a seamless upgrade as usual.

Windows 7, ownCloud 8.2.0, 2.0.2 client upgrading from 2.0.1.

**Comment by phil-davis** [comment]
https://github.com/owncloud/client/issues/3747
But for me, on re-adding the folder sync connections mapped to the existing local folder/s it did not have to download all the files again.

**Comment by MTRichards** [comment]
Folder did remap, but sadly not the selective sync.

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by RealRancor** [comment]
Hi,

I think this is also tracked at this still open issue: https://github.com/owncloud/client/issues/4015

**Comment by dragotin** [comment]
As I explained, there is nothing what we can do to fix this because the bug is in the already installed version. Once 2.0.2 is installed, this wont happen again.

**Comment by MTRichards** [comment]
Ok. Closing this one then.

**Comment by RealRancor** [comment]
@dragotin From my PoV at least disabling the auto-update from 2.0.0/2.0.1 to 2.0.2 and a blogpost/mailinglist post to warn users should be done here.

**Comment by dragotin** [comment]
Hmm, that would be disabling the auto update for all recent versions, as it is not limited to 2.0.0 or 2.0.1. And all those  who do not update manually now (aka who do not read the blog) will face the same problem again once we do the auto update again.

I know its really a strange situation. So far I was of the opinion that the best is to go through that now once forever, especially because the auto update is already active for quite some days, so most of the people will have been hit by that already.

**Comment by RealRancor** [comment]
> Hmm, that would be disabling the auto update for all recent versions, as it is not limited to 2.0.0 or 2.0.1.

Ah, i thought the client is also doing something like http://apps.owncloud.com/updater.php?version=4x90x14x1338030373.1628x1373617342.3379xstablex where it would be possible to hide the update only for those versions.

But i think that it already to late for most of the people, even with an blogpost / mailinglist post.

There is a forums posting about that https://forum.owncloud.org/viewtopic.php?f=14&t=31191 so hopefully some people got that info.

**Comment by brunodegoyrans** [comment]
Hi

I have encountered this issue and client seems to restart an overall sync since the beginning. This is really a pain, I have 1,6Tb to resync! And several of my collaborators have very slow internet.

But the main problem is that sync client shows error messages "connexion closed" and "operation canceled". Then Sync ends. New files or updates are not sync anymore. I'am bloqued.

I have opened a new issue: https://github.com/owncloud/client/issues/4047

**Comment by light** [comment]
You guys really need to communicate with your users when something like that happens. This is not only a bug but a critical failure for the app to complete its function, with possible loss of productivity or data. In my case I noticed by chance that all but one of my shared folders had stopped syncing, and I looked around for info with not much success until I found the forum post mentioned above. A blog post of some kind clearly explaining what's going on and how to fix it would have saved some time and frustration. It's also not "too late" even now since the bug is silent and it can take some time for people to realize the issue.
