### ISSUE TITLE
[Windows] With only TLS 1.2 available, decryption failed or bad record mac, disconnections

### ISSUE THREAD

**Issue by Exagone313** [owncloud/client#4053]
### Expected behaviour
The client keeps connected without any error.

### Actual behaviour
When the client is connected, about after 10 seconds, it looses the connection with the error: owncloud 1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac.
After one minute it reconnects, and over and over.
There isn't a problem on a navigator.

### Steps to reproduce
1) Use this Apache2 configuration:
```
SSLCipherSuite EECDH+AES:+AES128:+AES256:+SHA
SSLHonorCipherOrder on
SSLProtocol TLSv1.2
```
2) **(no impact)** ~~Use an OpenVPN server that receives connection for :443 and redirects unknown connections to another port, used by Apache2 for owncloud.~~
```
port-share 127.0.0.1 4433
```

To correct this problem, I had to use:
```
SSLProtocol +TLSv1 +TLSv1.1 +TLSv1.2
```
And then, it does not disconnect anymore.
It should be allowed to activate only TLS 1.2.
Maybe Apache2 disable some ciphers with this configuration, and these do not work well.
Or, something about OpenVPN.

### Server configuration
Operating system: Ubuntu Server 14.04

Web server: Apache 2.4.7

OpenSSL version: 1.0.1f

(Database: MariaDB)

(PHP version: 5.5.9)

ownCloud version: 8.1.3

Storage backend: ?

### Client configuration
Client version: 2.0.2 (build 5569)

Operating system: Windows 8.1 Pro

OS language: FR

Installation path of client: default (program files x86)

### Logs
owncloud 1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
(?)

**Comment by guruz** [comment]
FYI @danimo @richmoore

**Comment by RealRancor** [comment]
@guruz 
We had a chat with that user yesterday and he planned to test the connection without the port sharing option of OpenVPN. From my PoV this might be the point of failure here.

**Comment by Exagone313** [comment]
I did the test and no, OpenVPN do not cause the problem!

**Comment by guruz** [comment]
@Exagone313 You're 100% confident that when connecting directly to 4433 it also does not work?

**Comment by Exagone313** [comment]
Yes, just tried. connected to https://  ... :4433/

**Comment by NonSecwitter** [comment]
I don't know this project, but for what it's worth I've been having the same problems with a software provider. When attempting to download files we get an error that decryption failed from the remote server. We are suspecting a problem with Windows/IE/Edge In any case, I stumbled across your project while searching for solutions and thought the information might help you.

**Comment by tsumi** [comment]
Hi,
i can confirm the same problem with dektop client for Linux (Mint 17.2) after moving from Debian 7 to Centos 7 as server (with Apache 2.4).
Here too i can solve it enabling TLSv1 and TLSv1.1

**Comment by guruz** [comment]
@tsumi And you are not using the OpenVPN port sharing either?

**Comment by guruz** [comment]
@danimo Didn't you before christmas mention something about the TLS enums in Qt SSL?

**Comment by tsumi** [comment]
@guruz nope, direcy connection trought internet/https

**Comment by Exagone313** [comment]
@guruz OpenVPN has no impact to this problem, I tried without.

**Comment by danimo** [comment]
I've tested this with nginx 1.8 and 1.9 on Debian 8.0 (openssl 1.0.1k), using Windows 10 as the target (the Windows version should not matter, since we're shipping with OpenSSL). I cannot reproduce any problems. This, I'd say this is either a matter of your Apache or OpenSSL version.

We cannot provide extensive support on specific SSL issues here, sorry.

**Comment by Exagone313** [comment]
It cannot be a server problem since a browser that uses OpenSSL like Firefox has no issue with such server. Only with owncloud client.

**Comment by richmoore** [comment]
Firefox doesn't use openssl, it uses nss.

**Comment by Exagone313** [comment]
Ok I don't know so, it does not seem logical. I'll migrate to Nginx to see.

**Comment by guruz** [comment]
Try first to change/remove the ```SSLCipherSuite```

**Comment by brozkeff** [comment]
I experience exactly the same problem now with the latest clients 2.5.1 both on Linux (Mint 17.3) and Windows, after I upgraded server (Ubuntu 14.04) to backported newest Apache, OpenSSL 1.1.1 to support newer crypto suites, TLS1.3, HTTP/2, and to limit connections to TLS1.2+ only with selected suites only to get A+ rating on sslalbs test. Since then the client which connects via TLS1.2 randomly loses connection with the very same error as mentioned by the Exagone313 in 2015. Connection via web browsers is without issues and all SSL tests on the net show no issues as well.Even disabling server-forced honoring order of crypto suites did not help.

**Comment by brozkeff** [comment]
@danimo @richmoore

**Comment by michaelstingl** [comment]
@brozkeff could you open a new issue and provide the information that’s requested in the template? I think too many things changed since 2015.
