### ISSUE TITLE
please update ancient History and Architecture

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/client#4057]
It would be lovely if some nice developer would update this section, which still references ownCloud 4. Yes, really!
https://doc.owncloud.org/desktop/2.0/architecture.html

**Comment by carlaschroder** [comment]
I will proofread & make it pretty.

**Comment by guruz** [comment]
FYI @moscicki

**Comment by RealRancor** [comment]
Some points which could be also fit here as those questions are coming up at the forums quite often (and we mostly can't answer them at the forums):

- What happens if the server is restored to a previous snapshot?
- What happens if there is a data loss on server-side and only the datadir is restored to a previous state but the database is not restores?
- What happens if the data is restored on client-side to a previous state?

**Comment by carlaschroder** [comment]
Closing for lack of response.
