### ISSUE TITLE
[File Firewall] If i have two rules on the Desktop is not working very well

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4070]
### Steps to reproduce
1. Install the v 2.0.1 with 3 diferents users (user1, user2, diana)
2. Go to the Server Web, with user Admin
3. Click on User
4. Create a new 2 diferents groups (one for the user1 and user2, other for the user diana)
5. Click on Admin/administration
6. Select the option File Firewall
7. Create this rules 
![screen shot 2015-11-04 at 10 32 57](https://cloud.githubusercontent.com/assets/12032058/10934325/7600d268-82df-11e5-80f0-a9d420a31b8c.png)
8. Go to the Desktop client with user Diana
9. Upload one file .txt and other file .jpg

### Expected behaviour
It should appear in the .txt file the access  to this resource has been forbidden by a file firewall

### Actual behaviour
The .jpg file the access  to this resource has been forbidden by a file firewall, but the file .txt is uploaded
![screen shot 2015-11-04 at 10 37 58](https://cloud.githubusercontent.com/assets/12032058/10934427/274ab70a-82e0-11e5-9638-5528d647df51.png)

### Server configuration
Desktop v ownCloud-2.1.0.2851-nightly20151104.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related #3490

**Comment by nickvergessen** [comment]
> It should appear in the .txt file the access to this resource has been forbidden by a file firewall

I can't see it being blocked with your rules. Please see the doc-block message above the rules.

> Requests are checked against all rules that are defined below. A request is blocked, when at least one rule matches the request.

You have one rule named "diana", so let's see if that matches:

> A rule matches a request, when all conditions evaluate to true.

Condition 1: mimetype on upload is not text/plain => :x: Does not evaluate to true
=> Not all conditions evaluate to true
=> The rule does not match
=> No rules matches
=> The request is not blocked

Everything working as expected

Uploading a non text file will also work, because:

Condition 2: mimetype on upload is text/plain => :x: Does not evaluate to true
=> Not all conditions evaluate to true
=> The rule does not match
=> No rules matches
=> The request is not blocked

So you just created a rule that will never block anything.

Closing

**Comment by Dianafg76** [comment]
Thank you for the information
