### ISSUE TITLE
[OS X] OS X client lost network, never recovers

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#4097]
Similar problem like in Win https://github.com/owncloud/client/issues/3969 and Linux https://github.com/owncloud/client/issues/4051.
Here with:
OS X 10.9.5
client version 2.0.2 (from git 78d782), Qt 5.4.0

It was set to `system proxy`, but it persist when I change it to `no proxy`. For me it happened for a wifi-network where you have to authorize first.
Restarting the client solves the issue.

Logfile:
````
11-09 14:25:21:390 0x60000001de10 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
11-09 14:25:21:390 0x60000001de10 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
11-09 14:25:21:391 0x600000252f30 OCC::SystemProxyRunnable::run: virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup
11-09 14:25:21:391 0x60000001de10 OCC::ConnectionValidator::systemProxyLookupDone: void OCC::ConnectionValidator::systemProxyLookupDone(const QNetworkProxy &) Setting QNAM proxy to be system proxy "2://:0"
11-09 14:25:21:391 0x60000001de10 OCC::AbstractNetworkuserb::start: !!! OCC::CheckServeruserb created for "https://example.org/owncloud" + "status.php"
11-09 14:25:21:391 0x600000206960 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::HostNotFoundError QSslSocket(0x600000207cf0) QObject(0x0)  0 false 3 1 QAbstractSocket::UnconnectedState
11-09 14:25:21:391 0x600000206960 unknown: ERRORING OTHER QHttpNetworkReply(0x6000006343e0)  QUrl( "https://example.org/owncloud/status.php" ) 
11-09 14:25:53:391 0x60000001de10 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
````
Then network is set to `no proxy`
````
11-09 14:28:22:202 0x60000001de10 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use NO proxy
11-09 14:28:33:396 0x60000001de10 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-09 14:29:05:397 0x60000001de10 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-09 14:29:14:511 0x60000001de10 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
11-09 14:29:37:398 0x60000001de10 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-09 14:30:09:399 0x60000001de10 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-09 14:30:21:400 0x60000001de10 OCC::CheckServeruserb::slotTimeout: TIMEOUT virtual void OCC::CheckServeruserb::slotTimeout()
11-09 14:30:21:401 0x60000001de10 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Status not found" -> "Timeout"
11-09 14:30:21:401 0x60000001de10 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href="https://example.org/owncloud">https://example.org/owncloud</a>.
timeout"
11-09 14:30:21:402 0x60000001de10 OCC::FolderMan::slotAccountStateChanged: Account "user@example.org" disconnected, terminating or descheduling sync folders
11-09 14:30:41:399 0x60000001de10 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
11-09 14:30:41:400 0x60000001de10 OCC::AbstractNetworkuserb::start: !!! OCC::CheckServeruserb created for "https://example.org/owncloud" + "status.php"
11-09 14:30:41:401 0x600000206960 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::HostNotFoundError QSslSocket(0x600000207cf0) QObject(0x0)  0 false 3 1 QAbstractSocket::UnconnectedState
11-09 14:30:41:401 0x600000206960 unknown: ERRORING OTHER QHttpNetworkReply(0x608000635de0)  QUrl( "https://example.org/owncloud/status.php" ) 
11-09 14:30:41:401 0x60000001de10 OCC::AbstractNetworkuserb::slotFinished: void OCC::AbstractNetworkuserb::slotFinished() 3 "Host example.org not found" QVariant(Invalid)
11-09 14:30:41:401 0x60000001de10 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply *) 3 "Host example.org not found"
11-09 14:30:41:401 0x60000001de10 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Timeout" -> "Status not found"
11-09 14:30:41:401 0x60000001de10 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href="https://example.org/owncloud">https://example.org/owncloud</a>.
Host example.org not found"
11-09 14:30:41:403 0x60000001de10 OCC::FolderMan::slotAccountStateChanged: Account "user@example.org" disconnected, terminating or descheduling sync folders
11-09 14:30:41:403 0x60000001de10 OCC::CheckServeruserb::finished: error: status.php replied  0 ""
11-09 14:31:13:402 0x60000001de10 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
11-09 14:31:13:402 0x60000001de10 OCC::AbstractNetworkuserb::start: !!! OCC::CheckServeruserb created for "https://example.org/owncloud" + "status.php"
11-09 14:31:13:402 0x600000206960 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::HostNotFoundError QSslSocket(0x600000207cf0) QObject(0x0)  0 false 3 1 QAbstractSocket::UnconnectedState
11-09 14:31:13:403 0x600000206960 unknown: ERRORING OTHER QHttpNetworkReply(0x60800063ab80)  QUrl( "https://example.org/owncloud/status.php" ) 
11-09 14:31:45:402 0x60000001de10 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
````
Client is stopped and then started again:
````
11-09 14:33:03:575 0x7f9b83f0cda0 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
11-09 14:33:03:598 0x7f9b83f0cda0 OCC::AbstractNetworkuserb::start: !!! OCC::CheckServeruserb created for "https://example.org/owncloud" + "status.php"
11-09 14:33:03:861 0x7f9b83f0cda0 OCC::CheckServeruserb::finished: status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.1.4.2") ) ( "versionstring" ,  QVariant(QString, "8.1.4") ) )    0  Reply:  QNetworkReplyHttpImpl(0x7f9b83f9aa30)
11-09 14:33:03:862 0x7f9b83f0cda0 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:   QUrl( "https://example.org/owncloud/status.php" )   with version  "8.1.4" ( "8.1.4.2" )
11-09 14:33:03:882 0x7f9b83f0cda0 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
11-09 14:33:03:889 0x7f9b83f0cda0 OCC::AbstractNetworkuserb::start: !!! OCC::CheckServeruserb created for "https://example.org/owncloud" + "status.php"
11-09 14:33:03:938 0x7f9b83f0cda0 OCC::CheckServeruserb::finished: status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.1.4.2") ) ( "versionstring" ,  QVariant(QString, "8.1.4") ) )    0  Reply:  QNetworkReplyHttpImpl(0x7f9b83f8f790)
11-09 14:33:03:938 0x7f9b83f0cda0 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:   QUrl( "https://example.org/owncloud/status.php" )   with version  "8.1.4" ( "8.1.4.2" )
11-09 14:33:03:939 0x7f9b83f0cda0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
11-09 14:33:03:939 0x7f9b83f0cda0 OCC::AbstractNetworkuserb::start: !!! OCC::Propfinduserb created for "https://example.org/owncloud" + "/"
11-09 14:33:04:261 0x7f9b83f0cda0 OCC::AbstractNetworkuserb::start: !!! OCC::JsonApiuserb created for "https://example.org/owncloud" + "ocs/v1.php/cloud/capabilities"
11-09 14:33:04:349 0x7f9b83f0cda0 OCC::ConnectionValidator::slotCapabilitiesRecieved: Server capabilities QVariant(QVariantMap, QMap(("core", QVariant(QVariantMap, QMap(("pollinterval", QVariant(qulonglong, 60) ) ) ) ) ( "files" ,  QVariant(QVariantMap, QMap(("bigfilechunking", QVariant(bool, true) ) ( "undelete" ,  QVariant(bool, true) ) ( "versioning" ,  QVariant(bool, true) ) ) ) ) ( "files_sharing" ,  QVariant(QVariantMap, QMap(("public", QVariant(QVariantMap, QMap(("enabled", QVariant(bool, true) ) ( "expire_date" ,  QVariant(QVariantMap, QMap(("enabled", QVariant(bool, false) ) ) ) ) ( "password" ,  QVariant(QVariantMap, QMap(("enforced", QVariant(bool, false) ) ) ) ) ( "send_mail" ,  QVariant(bool, true) ) ) ) ) ( "resharing" ,  QVariant(bool, true) ) ( "user" ,  QVariant(QVariantMap, QMap(("send_mail", QVariant(bool, true) ) ) ) ) ) ) ) ) )
11-09 14:33:04:350 0x7f9b83f0cda0 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Undefined" -> "Connected"
11-09 14:33:04:351 0x7f9b83f0cda0 OCC::AccountState::setState: AccountState state change:  "Disconnected" -> "Connected"
11-09 14:33:04:352 0x7f9b83f0cda0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7f9b83cf5200)  with name  "ownCloud"
11-09 14:33:04:355 0x7f9b83f0cda0 OCC::FolderMan::slotAccountStateChanged: Account "user@example.org" connected, scheduling its folders
11-09 14:33:04:355 0x7f9b83f0cda0 OCC::FolderMan::slotScheduleSync: Schedule folder  "ownCloud"  to sync!
11-09 14:33:04:355 0x7f9b83f0cda0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7f9b83cf5200)  with name  "ownCloud"
11-09 14:33:04:356 0x7f9b83f0cda0 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Not yet Started"
11-09 14:33:04:356 0x7f9b83f0cda0 OCC::FolderMan::startScheduledSyncSoon: Scheduling a sync in 2 seconds
11-09 14:33:06:405 0x7f9b83f0cda0 OCC::FolderMan::slotStartScheduledFolderSync: XX slotScheduleFolderSync: folderQueue size:  1
11-09 14:33:06:406 0x7f9b83f0cda0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7f9b83cf5200)  with name  "ownCloud"
11-09 14:33:06:409 0x7f9b83f0cda0 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "SyncPrepare"
11-09 14:33:06:410 0x7f9b83f0cda0 OCC::Folder::startSync: *** Start syncing  "ownCloud"  - client version 2.0.2 (build 2818)
````

**Comment by guruz** [comment]
(I'd want to wait for confirmation from @robert128 on #3969 before we prepare a build with a rebuilt/updated Qt)

**Comment by guruz** [comment]
http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2885-nightly20151116.pkg
Could you please try? :)

**Comment by tflidd** [comment]
I installed the new nightly version. I wasn't able to reproduce reliably 
this problem, so I will just use it.

**Comment by noliveira87** [comment]
Hello,
I installed the 2.0.2.2885 and after I lost connection to owncloud server and bring it back, the owncloud client connects to the server perfectly.

**Comment by guruz** [comment]
:+1: Thanks

**Comment by noliveira87** [comment]
When you gonna put this version on the website?

**Comment by guruz** [comment]
@noliveira87 Should be in 2.1beta1

**Comment by noliveira87** [comment]
@guruz Many thanks! Let's talk about Windows 8 problem :) See you on the other issue!

**Comment by noliveira87** [comment]
Sorry @guruz but I am having a problem at the client when I connect the client.
I start the computer without connection to the owncloud server. When I connect to the network that I have access to owncloud server the log does not change:

<pre><code>
11-22 00:03:40:210 0x7f88514197e0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-22 00:04:12:209 0x7f88514197e0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-22 00:04:44:207 0x7f88514197e0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-22 00:05:16:206 0x7f88514197e0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-22 00:05:42:228 0x7f88514197e0 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
11-22 00:05:48:203 0x7f88514197e0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-22 00:06:20:204 0x7f88514197e0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-22 00:06:52:203 0x7f88514197e0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-22 00:07:24:200 0x7f88514197e0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
</code></pre>

When I restart the client everything works, but when I change the network, the client stills "Connected" but it is not correct because the client does not have access to the server.

This log are from the time that I disconnect from the network with access to owncloud:

<pre><code>
11-22 00:13:39:308 0x7fc88a9afcd0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fc88a8f1ea0) QObject(0x0)  0 false 3 0
11-22 00:14:00:183 0x7fc88840f480 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 86 s)
11-22 00:14:00:185 0x7fc88840f480 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag
11-22 00:14:00:186 0x7fc88840f480 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://owncloud.domain" + "/"
11-22 00:14:00:348 0x7fc88840f480 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
11-22 00:14:05:376 0x7fc88a9afcd0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fc88a8f1ea0) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
11-22 00:14:05:376 0x7fc88a9afcd0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fc88a8f1ea0) QObject(0x0)  0 false 3 0
11-22 00:14:06:183 0x7fc88840f480 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
11-22 00:14:06:185 0x7fc88840f480 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://owncloud.domain" + "/"
11-22 00:14:06:284 0x7fc88840f480 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 302 "http://www.xxx.com/remote.php/webdav/"
11-22 00:14:11:519 0x7fc88a9afcd0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fc88a8f1ea0) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
11-22 00:14:11:519 0x7fc88a9afcd0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fc88a8f1ea0) QObject(0x0)  0 false 3 0
11-22 00:14:30:184 0x7fc88840f480 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 116 s)
11-22 00:14:30:186 0x7fc88840f480 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag
11-22 00:14:30:187 0x7fc88840f480 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://owncloud.domain" + "/"
11-22 00:14:30:282 0x7fc88840f480 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
11-22 00:14:30:688 0x7fc88840f480 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
11-22 00:14:33:052 0x7fc88840f480 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://owncloud.domain" + "/"
11-22 00:14:33:112 0x7fc88840f480 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 302 "http://www.xxx.com/remote.php/webdav/"
11-22 00:14:38:182 0x7fc88840f480 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-22 00:14:38:245 0x7fc88a9afcd0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fc88a8f1ea0) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
11-22 00:14:38:245 0x7fc88a9afcd0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fc88a8f1ea0) QObject(0x0)  0 false 3 0
11-22 00:15:00:182 0x7fc88840f480 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 146 s)
11-22 00:15:00:183 0x7fc88840f480 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag
11-22 00:15:00:184 0x7fc88840f480 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://owncloud.domain" + "/"
11-22 00:15:00:285 0x7fc88840f480 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
</code></pre>

**Comment by guruz** [comment]
```PROPFIND request *not* successful, http result code is 302```

302 in HTTP is redirected. Is this a network where you are using a website to login to the network? Like at a café or airport?

**Comment by noliveira87** [comment]
No. I have a normal WPA2 Wifi connection that does not have access to Owncloud. To access to Owncloud I have to connect to a L2TP/IPSec VPN.

**Comment by noliveira87** [comment]
Here are more news.

Here is the return code to my owncloud without VPN:

<pre><code>root# curl -o /dev/null --silent --head --write-out '%{http_code}\n’ https://owncloud.domain
302</code></pre>

Without connection to Owncloud server, HTTP redirects to the company website. That's why it returns 302 code.

And the log from Owncloud Client:

<pre><code>11-23 23:17:58:162 0x7fc28ca322f0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fc28a53b150) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
11-23 23:17:58:163 0x7fc28ca322f0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fc28a53b150) QObject(0x0)  0 false 3 0
11-23 23:18:24:369 0x7fc28a52a0f0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring</code></pre>

When I connect the VPN, that I have access to the Owncloud server, here is the HTTP result:

<pre><code></code>root# curl -o /dev/null --silent --head --write-out '%{http_code}\n' https://owncloud.domain
200</pre>

And here is the log of the client:

<pre><code>11-23 23:19:28:366 0x7fc28a52a0f0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-23 23:19:50:948 0x7fc28a52a0f0 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
11-23 23:20:00:365 0x7fc28a52a0f0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-23 23:20:32:363 0x7fc28a52a0f0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring
11-23 23:21:04:362 0x7fc28a52a0f0 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring</code></pre>

If I can you send more information, just ask.

**Comment by tflidd** [comment]
For my part, it is working now (it is disconnected at first but recovers after some time).

**Comment by noliveira87** [comment]
@guruz This is the maximum log that I can get:

<pre><code>11-26 23:02:22:895 0x7f8348413a70 OCC::SparkleUpdater::backgroundCheckForUpdate: virtual void OCC::SparkleUpdater::backgroundCheckForUpdate() launching background check
11-26 23:02:22:924 0x7f8348413a70 -[DelegateObject updaterMayCheckForUpdates:]: -[DelegateObject updaterMayCheckForUpdates:] may check: YES
11-26 23:02:24:366 0x7f8348413a70 -[DelegateObject updaterDidNotFindUpdate:]: -[DelegateObject updaterDidNotFindUpdate:]
11-26 23:02:25:454 0x7f834a9ac710 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7f834aa623f0) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
11-26 23:02:25:455 0x7f834a9ac710 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7f834aa623f0) QObject(0x0)  0 false 3 0
11-26 23:02:51:835 0x7f8348413a70 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring</code></pre>
