### ISSUE TITLE
"You don't have permission to add files in that folder"

### ISSUE THREAD

**Issue by ldesousa** [owncloud/client#4102]
I am using the ownCloud desktop client version 8.1.4-12.1 on Ubuntu 14.04. A week or so ago it stopped synchronising. In the Settings dialogue it shows this message: "Not allowed because you don't have permission to add files in that folder". 

The folder structure the client is using is stored in my home folder and is fully owned by my user. I tried renewing the ownership of the folder but the error remains. I believe I can rule out user error, this must be an issue with the software.
### Expected behaviour

OwnCloud client should synchronise the ownCloud folder in my home folder.
### Actual behaviour

The dash indicator shows a red sign with a white cross and in the Settings dialogue the following message is displayed: "Not allowed because you don't have permission to add files in that folder".
### Steps to reproduce
1. Start up the system
### Client configuration

Client version: 8.1.4-12.1

Operating system: Ubuntu 14.04

OS language: ?

Installation path of client:  /usr/share/owncloud
### Logs
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`: 
   this produces an empty file.
2. Web server error log:
3. ownCloud log (data/owncloud.log): I could not find this file in my system.

**Comment by ckamm** [comment]
@ldesousa I don't know what's going on yet, could you look up a few things?

* The version you give is a server version. Please look for the client version in the "General" tab in the "About" section.
* Click the "Activity" tab. What file shows an error, what's the full error message there?
* Do you still have enough disk space to create new files on your hard disk?
* A client log file would be highly appreciated. To get one:
  * Quit the client.
  * Start it from the console with `owncloud --logfile ~/log.txt`. Let it run until the error is displayed. There will now be a log.txt file in your home directory. Attach it or email it to me at mail@ckamm.de. (note it contains personal information like file names and server address)

**Comment by ldesousa** [comment]
I have been getting some help at the Forum, and already ran onwcloud with the log file option. The relevant part is this:

$ cat ownCloud.log | grep error
11-10 14:43:25:190 0x1709460 Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration")
11-10 14:43:30:061 0x183ec38 oc_module: Error read certificate : Unknown error.
11-10 14:43:34:495 0x1709460 This error is not blacklisted  0
11-10 14:43:34:662 0x1709460   ** error Strings:  ("git/MDDEclipse/.git/objects/0e/f136808399f06e66618765c2388ec662b8339e: Not allowed because you don't have permission to add files in that folder")
11-10 14:43:34:662 0x1709460     * owncloud csync thread finished with error
11-10 14:44:24:972 0x24703b8 oc_module: Error read certificate : Unknown error.
11-10 14:44:27:472 0x1709460 This error is not blacklisted  0
11-10 14:44:27:551 0x1709460   ** error Strings:  ("git/MDDEclipse/.git/objects/0e/f136808399f06e66618765c2388ec662b8339e: Not allowed because you don't have permission to add files in that folder")
11-10 14:44:27:551 0x1709460     * owncloud csync thread finished with error
11-10 14:45:24:970 0x276ecd8 oc_module: Error read certificate : Unknown error.
11-10 14:45:27:267 0x1709460 This error is not blacklisted  0
11-10 14:45:27:312 0x1709460   ** error Strings:  ("git/MDDEclipse/.git/objects/0e/f136808399f06e66618765c2388ec662b8339e: Not allowed because you don't have permission to add files in that folder")
11-10 14:45:27:312 0x1709460     * owncloud csync thread finished with error 

Apparently, owncloud is trying to open a git metadata file as if it was a folder. Naturally, this can not work.

Indeed, in the General tab I get a different version from that reported by apt, in the GUI it is 2.0.2.

**Comment by ldesousa** [comment]
I contacted the OwnDrive support this morning, inquiring for alternative ways to synchronise my files. They soon answered back instructing me to go to "Settings" -> "General" -> "Edit Ignored Files" and turn on the option "Sync hidden files".

OwnCloud is now functionally properly again, but I will leave this issue open in any case. I believe the error I was getting should not be happening.

**Comment by ldesousa** [comment]
I contacted the OwnDrive support this morning, inquiring for alternative ways to synchronise my files. They soon answered back instructing me to go to "Settings" -> "General" -> "Edit Ignored Files" and turn on the option "Sync hidden files".

OwnCloud is now functionally properly again, but I will leave this issue open in any case. I believe the error I was getting should not be happening.

**Comment by e-alfred** [comment]
I have the same problem with Git repositories in a folder synced with Owncloud.

The error log summary says the following:

11-23 15:49:03:200 0x1b0f310   ** error Strings:  ("git/gitit/.git/FETCH_HEAD: Not allowed because you don't have permission to add files in that folder", "git/gitit/.git/ORIG_HEAD: Not allowed because you don't have permission to add files in that folder", "git/gitit/.git/index: Not allowed because you don't have permission to add files in that folder", "git/gitit/.git/logs: Not allowed because you don't have permission to add subfolders to that folder", "git/gitit/.git/logs/HEAD: Not allowed because you don't have permission to add parent folder", "git/gitit/.git/logs/refs: Not allowed because you don't have permission to add parent folder", "git/gitit/.git/logs/refs/heads: Not allowed because you don't have permission to add parent folder", "git/gitit/.git/logs/refs/heads/master: Not allowed because you don't have permission to add parent folder", "git/gitit/.git/logs/refs/remotes: Not allowed because you don't have permission to add parent folder", "git/gitit/.git/logs/refs/remotes/origin: Not allowed because you don't have permission to add parent folder", "git/gitit/.git/logs/refs/remotes/origin/HEAD: Not allowed because you don't have permission to add parent folder", "git/gitit/.git/objects/pack/pack-ecdd0d6384864eb5f16a22d6bd230fb7b63106a3.idx: Not allowed because you don't have permission to add files in that folder", "git/gitit/.git/objects/pack/pack-ecdd0d6384864eb5f16a22d6bd230fb7b63106a3.pack: Not allowed because you don't have permission to add files in that folder", "git/gitit/.git/packed-refs: Not allowed because you don't have permission to add files in that folder", "git/gitit/.git/refs/heads/master: Not allowed because you don't have permission to add files in that folder", "git/gitit/.git/refs/remotes: Not allowed because you don't have permission to add subfolders to that folder", "git/gitit/.git/refs/remotes/origin: Not allowed because you don't have permission to add parent folder", "git/gitit/.git/refs/remotes/origin/HEAD: Not allowed because you don't have permission to add parent folder") 

I am running Owncloud 8.2 on Debian 8 as a server and 2.0.2 on a client machine.

**Comment by ckamm** [comment]
@e-alfred I've tried to reproduce the problem with the repository you linked. It works fine for me with "sync hidden files" and without it - on 2.1.0. Could I ask you to try to reproduce with the RC1 or a nightly to verify that the problem has been fixed?

@ldesousa I'm glad that enabling "Sync hidden files" made sync work correctly for you. It's surprising that the client tried to do something in a ".git" folder with that option disabled.

**Comment by ckamm** [comment]
Please reopen if the problem still occurs.

**Comment by hanyadel** [comment]
I followed the above steps and still have error in permissions

**Comment by ckamm** [comment]
@hanyadel Can you briefly describe your issue? Whatever is happening, detailed logs (with `--logfile mylog.txt --logdebug`) would be helpful for seeing what's going on. Feel free to mail to mail at ckamm de. (logs can contain confidential data like server urls and file names)
