### ISSUE TITLE
[Activity View] On Activity option/Sync Protocol you can't see the button (Sync repeat)

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4165]
### Steps to reproduce
1. Open your ownCloud desktop client with the new v2.1.0
2. Right click to the oC icon
3. Click on Settings
4. Clikc on Activity option
5. Click on Sync Protocol

### Actual behaviour
If you see the issue #4083, you can see the button: Sync repeat
But with this version you can't see the button
![screen shot 2015-11-19 at 10 44 32](https://cloud.githubusercontent.com/assets/12032058/11267276/b6c86af0-8eaa-11e5-8512-36e1fe977797.png)

### Server configuration
Desktop 2.1.0 (build 2889)
Server v {"installed":true,"maintenance":false,"version":"9.0.0.2","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Comment by guruz** [comment]
@dragotin Is it only visible when there are blacklist items? Maybe it should be visible inactive?

**Comment by dragotin** [comment]
The button is not here because I am not sure if we still really need it. The blacklist items are retried to be synced after a certain time other than in former times, where we had that button.

**Comment by ckamm** [comment]
Closing since @dragotin removed the button on purpose.

**Comment by DavidShepherdson** [comment]
I recently moved my ownCloud installation to a different server, and in the process ended up with some misconfigurations on the new server for a while that resulted in some files being blacklisted in some of my clients.

Without the Retry Sync button, my only options to get things working again were to wait 24 hours for the blacklisted entries to automatically try again, or to manually remove the entries from the blacklist using SQLite. The latter is what I did, since I (eventually) found out that this was possible, and am comfortable manipulating an SQLite database. But the 'average' end user wouldn't be likely to fall into that category.

At first, I went looking for the Retry Sync button, both because I remembered it from the past and because the documentation still refers to it.

If the button were still there, the end user would still have a way to recover from server-related issues like this without having to resort to database manipulation or waiting up to 24 hours.
