### ISSUE TITLE
Move/Add the Log out and Log in for an account to the Settings Screen -- Call Change Password

### ISSUE THREAD

**Issue by gig13** [owncloud/client#4193]
When a user needs to change the password for a sync client, it is not intuitive on finding how to accomplish this without removing and adding the account. Can we add a small section in the Settings that can be used/named to Change the Password?

@bboule @MTRichards @MorrisJobke

**Comment by danimo** [comment]
@gig13 As soon as the password needs changing, the client will show a message. Why would the user initiate a password change on the client?

The only use case I can see is a user who wants to update the password right away and not wait for the session to time out. The real fix to the problem is coming in one of the next server releases (Matt: in below issue: "no later than 9.1, but unconfirmed"), with the server being able to terminate sessions right after the password is changed. This will pop up the dialog right away, ending all confusion.

I'd hate add a hack when the real fix is on the way. Would that be acceptable?

Related: https://github.com/owncloud/core/issues/18410

**Comment by gig13** [comment]
@danimo 
The problem is there is no wording anywhere for "Change password". The standard user will right click the owncloud icon and click Settings completely overlooking the "Log in/out". 

Are you saying that If the LDAP password is changed, then the expected behavior is that the sync client will pop up the Log In dialog box so the user can re-enter the username/password?

**Comment by danimo** [comment]
@gig13 "Expected" in the sense of "that's our goal". However, the necessary changes are not implemented yet, see the core bug report in my comment above.

**Comment by ogoffart** [comment]
Core issue was closed.
