### ISSUE TITLE
Sync client retry count when password changes

### ISSUE THREAD

**Issue by gig13** [owncloud/client#4194]
When the password is changed for an ownCloud user, whether using internal ownCloud users or LDAP/AD users, does the sync client automatically retry connecting with the old password?

If the sync client is retrying, is there a setting or configuration for the maximum number of retries?

For example, an AD is setup with policies for users to reset their passwords every 90 days. When the password changes, will the sync client restart (after a reboot or sleep) with the cached credentials?

**Comment by danimo** [comment]
> If the sync client is retrying

@gig13 Yes, but we will not retry too often. See https://github.com/owncloud/client/issues/2186.

> is there a setting or configuration for the maximum number of retries?

No, but the client currently is robust if the server allows >=3 retries before locking.

**Comment by MTRichards** [comment]
>No, but the client currently is robust if the server allows >=3 retries before locking.

This means it won't try again until the password is changed by the user?

@gig13 What client are they using?

**Comment by danimo** [comment]
> This means it won't try again until the password is changed by the user?

@MTRichards yes. That's the expected behavior at least.

**Comment by gig13** [comment]
@MTRichards 
The Windows desktop client

**Comment by MTRichards** [comment]
Yeah, which one?

**Comment by MTRichards** [comment]
And which ownCloud version?

**Comment by gig13** [comment]
OC 8.1.4 with the latest 2.0.2 desktop client

**Comment by ckamm** [comment]
@gig13 I just ran the following test:

* Connect to an account, sync, have the client running
* Change the account password on the server
  * The client will be able to continue to sync (because the session cookie is still valid)
* After a client restart:
  * the client tries with the session cookie, fails
  * the client tries with the auth data, fails
  * the account gets put into 'signed out' state and no more server requests are made unless the user explicitly selects "Log in..."

That means that the client will only try logging in with bad auth data once in this scenario.

It could be different if the cookie expires while the client is running a sync operation. Since it sends the auth data with each PROPFIND, there could easily be several bad login attempts in this case? @guruz

**Comment by bboule** [comment]
@gig13 can we close this out?  Sounds like there must be another reason for what is happening with this user!!

**Comment by gig13** [comment]
Closing out. The user has been unresponsive.
