### ISSUE TITLE
owncloud reverts files while no one else is modifying them

### ISSUE THREAD

**Issue by mortee** [owncloud/client#4222]
My setup is one windows desktop client, and one server which mostly serves as an automated backup (and primitive versioning) for my work files. This also lets me easily migrate my work stuff to another desktop if necessary - but this happens very rarely, and most of the time the _only_ client that accesses the server is my desktop.
### Actual behaviour

Given this setup, I'd expect to _never_ experience conflicts. What happens instead is that in a _lot_ of cases, a conflict arises from reasons involving mostly "Not allowed to upload this file because it is read-only on the server, restoring". This occurs mostly in Eclipse project folders, especially with .classpath files (dunno why), which revert my developments in unpredictable ways.

While I understand that OC is primarily a collaborative tool, I think the below guidelines should be seriously considered, to prevent loss of data/work:
### Expected behaviour

When the local computer is the _only_ source of updates on the server, then the client should never, ever overwrite any local file from the server, in any case whatsoever. How this circumstance can be verified is a separate topic - but I think this outcome should be mandatory.

When there's a conflict, then the local file should be left unchanged, the server version downloaded into a tagged filename, and the user _notified_.

Especially if the conflict is caused by a failure to sync, like when the client thinks the file is read-only on the server.

(How can a file become read-only on the server, when it's uploaded from a local, non-read-only file, and there are no other sources of updates on the server?)

The local file should never be overwritten/reverted if it's been changed locally since the last sync. Even in a collaborative environment this implies "I know you've been working on this file, but the server version is obviously more important than your work, so I set yours aside".

Actually, it should _only_ be overwritten from the server when the local version has already been successfully synced/uploaded, it has been changed on the server since then, _and_ the local file does _not_ have local changes. If it does, it should be treated as a conflict, and handled as written above.
### Steps to reproduce

I _think_ the only-client-and-still-conflicting behavior might be triggered by a large shared folder which takes long to even discover, and local changes which happen on a much faster pace than the client can keep up.

So I'd reproduce it by setting up a server with only one client accessing it, sharing a big folder with lots of files, putting an Eclipse workspace inside, starting to do work on it, and then watching the project settings and possibly source files being reverted.
### Server configuration

Operating system: NetBSD
Web server: Apache 2.2.31
Database: MySQL 5.5.45
PHP version: 5.4.45
ownCloud version: 8.1.3 (stable)
### Client configuration

Client version: 2.0.2
Operating system: Windows 8.1

**Comment by tps800** [comment]
Seeing this too. Maybe these bugs are related: #4272 files get "readonly" on server, but without any idea why, because there is only one client. The chance seeing this bug is high if you change the file locally fast. Idealy while the client was in a sync cycle and before the client starts to sync this particular file. Looks like there is a time window between checking if a file has to be synced and the file really being synced. Changing the file within this window seems to disturb syncing and make the file "read only" on the server until something further happens, resetting the "read only" state.

**Comment by ogoffart** [comment]
So the client belieave that the directory and files are read only.
There could be because of a bug in the client which would understand the permissions wrong,  or a bug in the server which would report the wrong permission. I tend to think this is the later.
The client log should tell use what are the permission sent by the server.  

So i believe this is a server bug.
May also be related to https://github.com/owncloud/core/issues/20426

**Comment by ogoffart** [comment]
Closing this old issue.
Maybe it is a duplicate of #5106
