### ISSUE TITLE
Display when unlimited quota is displayed

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#4345]
Not certain if this is server only (and we just display the result of an api call) or client side too.

When selecting unlimited storage quota it should be configurable to display "unlimited"

The client needs to say the following in the quota panel:

>176MB of the available unlimited quota. (client side)

Linked from server issue
https://github.com/owncloud/core/issues/19988

**Comment by ogoffart** [comment]
This was changed in 2.1 for #3940
 The current string for the client when the quota is unknown or unlimited is:

> 176MB in use

Is this issue a request to change the string to mention that the quota is unlimited when it is unlimited?   

and what does the `(client side)`  means?  Because the value that is shown is the used space on the server.

**Comment by ogoffart** [comment]
@MTRichards  ?

**Comment by MTRichards** [comment]
Ok, good that it was partly changed for 2.1 though not quite as the customer had asked. Regardless, this is close enough for now, no need to change it.

What I was going for was an implementation of #19988 above in the desktop sync client quota part, but I think you simplified it.

**Comment by ogoffart** [comment]
So I assume i can close this bug then :-)
