### ISSUE TITLE
Feedback required when no sharee is found

### ISSUE THREAD

**Issue by rullzer** [owncloud/client#4348]
When doing user/group sharing we should also display feedback if no user/group to share with is found.

See https://github.com/owncloud/enterprise/issues/1006

Assigning to myself so I don't forget.

**Comment by MorrisJobke** [comment]
00004525

**Comment by guruz** [comment]
@ogoffart started working on that yesterday

**Comment by rullzer** [comment]
Ah even better :)

**Comment by davitol** [comment]
https://github.com/owncloud/core/issues/22319

**Comment by MorrisJobke** [comment]
> owncloud/core#22319

https://github.com/owncloud/core/issues/17408

**Comment by Dianafg76** [comment]
@rullzer @ogoffart 
### Steps to reproduce
1. In share dialog, write down a username pattern that doesn't fit with any user

### Expected behaviour

The dropdown should show a message related to 'no users where found'

### Actual behaviour

you can see this: 
![screen shot 2016-02-12 at 10 16 20](https://cloud.githubusercontent.com/assets/12032058/13002836/dbd96a38-d171-11e5-9833-c1a3fcb453b0.png)

but not No dropdown is shown .

### Server configuration
Desktop v ownCloud-2.2.0.3112-nightly20160211.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related https://github.com/owncloud/client/issues/4205

**Comment by ogoffart** [comment]
The way the server does with puting the error in the dropdown does not really work for a native app IMHO. 
I agree that the current way is not realy pretty.
@jancborchardt  what do you think?

**Comment by jancborchardt** [comment]
An improvement to the current situation would be to move the message »No results for 'blabla'« directly below the input field. Also, the wording should be more concrete: »No users or groups found for 'blabla'«.

Those are quick fixes (I assume) which do a lot to improve the experience already, and no fancy dropdowns needed. :)

**Comment by ogoffart** [comment]
The error strings come from the server, so this should be a core issue if we want to change the wording.

But moving the label is quite easy.  New screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/959326/13821388/ac91753c-eba1-11e5-9ad6-e6bd295f6305.png)

**Comment by rullzer** [comment]
@ogoffart yeah those repsonses are not translated. But in this case we can actually also do a custom message on the client. Since we know that there are no sharees to be found (if we just get an empty list).

**Comment by guruz** [comment]
@michaelstingl Do you want to test and close this?

**Comment by michaelstingl** [comment]
As I understood, @pako81 already tested in https://github.com/owncloud/enterprise/issues/1006#issuecomment-176150574 .

**Comment by pako81** [comment]
@michaelstingl in that case, the issue was that an _existing _user was not properly returned from the Desktop sharing dialog.
This case is to return a proper feedback when no user/group to share with is found..not sure is completely related..
