### ISSUE TITLE
Disable share permission checkboxes that are unavailable when resharing

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4383]
In #4357 #4358 we fixed the problem of resharing being impossible when some permissions had been revoked. Now it works, but users can still try to enable the unavailable permissions manually. Since the client knows which permissions are available, we should disable the permission checkboxes that are forbidden.

To reproduce:
* Share user1's folder/ with user2, give only 'reshare' permission
* As user2, try to share folder/ with user3 using the desktop client
* Notice the 'edit'/'change'/'delete' etc permission checkboxes can be toggled, but won't work

**Comment by rullzer** [comment]
I see no clean way to be able to do this properly for the current API. But if we get something like https://github.com/owncloud/core/pull/22834 in at the server side then we could easily make this happen.

**Comment by rullzer** [comment]
https://github.com/owncloud/core/pull/22834 will only be in 9.1. However we can already start with implementing this in the client. So that once 9.1 is out this will work directly.

I'll prepare a patch that makes this happen soonish.

**Comment by rullzer** [comment]
https://github.com/owncloud/core/pull/22834 is in. So this will be available in 9.1.

This introduces a new webdav property. `share-permissions`. All clients could already query this property now but it would just return a 404 (and then we fall back to the current crappy behaviour). But if the property is there we can do much better.

**Comment by ckamm** [comment]
Pull request: #4673

**Comment by mcastroSG** [comment]
Hi hi:

**Steps executed**

1. user1 shares a folder with user2 giving just reshare privilege.
2. user2 shares the same folder to user3 with "Share with ownCloud" option and choosing user3

**Result**
 
![screen shot 2016-04-19 at 18 03 24](https://cloud.githubusercontent.com/assets/18436398/14646258/18b27366-0659-11e6-8cbb-2cd6906ffee4.png)

The checkbox are shown. In case we check any of them we obtain:

![screen shot 2016-04-19 at 18 13 14](https://cloud.githubusercontent.com/assets/18436398/14646627/76d8e816-065a-11e6-9a67-14c196edd7fe.png)

So after that we could just close the window.

**MacOS**
Client Version: Version 2.2.0-nightly20160419 (build 3282)
Client OS: MacOS X El Capitan 10.11.4
Server Version: 9.0.1
Server OS: Ubuntu

**Windows**
Unable to test due to [https://github.com/owncloud/client/issues/4701](url)

**LOGS**

`04-19 18:21:35:187 0x7fbd605150b0 OCC::SocketApi::command_SHARE: void OCC::SocketApi::command_SHARE(const QString &, QIODevice *) “/Users/******/testpilotcloud/Testing3222 (2)”
04-19 18:21:35:188 0x7fbd605150b0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  “SHARE:OK:/Users/mcastro/testpilotcloud/Testing3222 (2)”
04-19 18:21:35:189 0x7fbd605150b0 OCC::ownCloudGui::slotShowShareDialog: void OCC::ownCloudGui::slotShowShareDialog(const QString &, const QString &, bool) Opening share dialog “/Testing3222 (2)” “/Users/mcastro/testpilotcloud/Testing3222 (2)” QFlags(0x1|0x2|0x4|0x8|0x10)
04-19 18:21:35:191 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for “http://*************” + “/Testing3222 (2)” “”
04-19 18:21:35:342 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for “http://*************” + “ocs/v1.php/apps/files_sharing/api/v1/shares” “”
04-19 18:21:35:344 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for “http://*************” + “ocs/v1.php/apps/files_sharing/api/v1/shares” “”
04-19 18:21:35:482 0x7fbd605150b0 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) “9.0.1.3” Fetched 0 shares
04-19 18:21:35:482 0x7fbd605150b0 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) Sending  0 shares
04-19 18:21:35:559 0x7fbd605150b0 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) “9.0.1.3” Fetched 0 shares
04-19 18:21:35:559 0x7fbd605150b0 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) Sending  0 shares
04-19 18:21:35:560 0x7fbd605150b0 OCC::ShareLinkWidget::slotSharesFetched: void OCC::ShareLinkWidget::slotSharesFetched(const QList<QSharedPointer<OCC::Share> > &) “9.0.1.3” Fetched 0 shares
04-19 18:21:38:107 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareeJob created for “http://*************” + “ocs/v1.php/apps/files_sharing/api/v1/sharees” “”
04-19 18:21:39:443 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for “http://*************” + “ocs/v1.php/apps/files_sharing/api/v1/shares” “”
04-19 18:21:39:596 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for “http://*************” + “ocs/v1.php/apps/files_sharing/api/v1/shares” “”
04-19 18:21:39:790 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for “http://*************” + “ocs/v1.php/apps/files_sharing/api/v1/shares” “”
04-19 18:21:39:927 0x7fbd605150b0 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) “9.0.1.3” Fetched 1 shares
04-19 18:21:39:928 0x7fbd605150b0 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) Sending  1 shares
04-19 18:21:42:506 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for “http://*************” + “ocs/v1.php/apps/files_sharing/api/v1/shares/11” “”
04-19 18:21:42:641 0x7fbd605150b0 OCC::OcsJob::finished: Reply to “PUT”  QUrl( “http://*************:56693/ocs/v1.php/apps/files_sharing/api/v1/shares/11” )  (QPair(“permissions”,”31”)) has unexpected status code: 404 “{“ocs”:{“meta”:{“status”:”failure”,”statuscode”:404,”message”:”Cannot increase permissions”},”data”:[]}}”
04-19 18:21:52:078 0x7fbd605150b0 OCC::Folder::slotRunEtagJob: * Trying to check “http://*************:56693/remote.php/webdav/“ for changes via ETag check. (time since last sync: 205 s)
04-19 18:21:52:079 0x7fbd605150b0 OCC::FolderMan::slotRunOneEtagJob: Scheduling “http://*************:56693/remote.php/webdav/“ to check remote ETag
04-19 18:21:52:079 0x7fbd605150b0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for “http://*************” + “/“ “OCC::Folder”`

Regards

**Comment by ckamm** [comment]
@mcastroSG The new feature only works with server >= 9.1.0, I was using a development snapshot for my tests.

**Comment by mcastroSG** [comment]
Hi hi:

### Internal Share Enhancement

##OS X

Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0beta1 (build 3297)

<br>
 
Test Case ID | Test case     | Steps   | Expected behavior | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Internal Share Enhancement - "can share" hierarchy | 1.- As user1 share a file with a user2 granting "can share"<br>2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can share" checkbox is available | ✅ 
2 | Internal Share Enhancement - "can share" and "can edit" hierarchy | 1.- As user1 share a file with a user2 granting "can share" and "can edit" <br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can share" and "can edit" checkbox is available | ✅ 
3 | Internal Share Enhancement - "can edit" hierarchy | 1.- As user1 share a file with a user2 granting "can edit" <br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | An error message appears because you are not able to reshare the file | ✅ 
4 | Internal Share Enhancement - "can share" Link hierarchy | 1.- As user1 share a file with a user2 granting "can share"<br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> 5.- Enable "Share Link" | Link, Password Protect and Set expiration date checkbox is shown |✅ 
5 | Internal Share Enhancement - "can Share" and "can edit" > "change" hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Change <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "change" checkbox is available |✅ 
6 | Internal Share Enhancement - "can share" and "can edit" > "create" hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Create <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "create" checkbox is available |  ✅ 
7 | Internal Share Enhancement - "can share" and "can edit" > "delete" hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Delete <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "delete" checkbox is available |  ✅  
<br>

##OS W

Client OS: W10
Client Version: Version 2.2.0beta1 (build 3297)

<br>
 
Test Case ID | Test case     | Steps   | Expected behavior | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Internal Share Enhancement - "can share" hierarchy | 1.- As user1 share a file with a user2 granting "can share"<br>2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can share" checkbox is available | 🚧 
2 | Internal Share Enhancement - "can share" and "can edit" hierarchy | 1.- As user1 share a file with a user2 granting "can share" and "can edit" <br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can share" and "can edit" checkbox is available | 🚧 
3 | Internal Share Enhancement - "can edit" hierarchy | 1.- As user1 share a file with a user2 granting "can edit" <br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | An error message appears because you are not able to reshare the file | 🚧 
4 | Internal Share Enhancement - "can share" hierarchy Link| 1.- As user1 share a file with a user2 granting "can share"<br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> 5.- Enable "Share Link" | Link, Password Protect checkbox and Set expiration date is shown | 🚧 
5 | Internal Share Enhancement - "can Share" and "can edit" > "change" hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Change <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "change" checkbox is available |🚧 
6 | Internal Share Enhancement - "can share" and "can edit" > create hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Create <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "create" checkbox is available |  🚧 
7 | Internal Share Enhancement - "can share" and "can edit" > "delete" hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Delete <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "delete" checkbox is available |  🚧 

##OS Ubuntu


<br>
 
Test Case ID | Test case     | Steps   | Expected behavior | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Internal Share Enhancement - "can share" hierarchy | 1.- As user1 share a file with a user2 granting "can share"<br>2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can share" checkbox is available | 🚧 
2 | Internal Share Enhancement - "can share" and "can edit" hierarchy | 1.- As user1 share a file with a user2 granting "can share" and "can edit" <br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can share" and "can edit" checkbox is available | 🚧 
3 | Internal Share Enhancement - "can edit" hierarchy | 1.- As user1 share a file with a user2 granting "can edit" <br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | An error message appears because you are not able to reshare the file | 🚧 
4 | Internal Share Enhancement - "can share" hierarchy Link| 1.- As user1 share a file with a user2 granting "can share"<br> 2.- As user2 right-click on shared file <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> 5.- Enable "Share Link" | Link, Password Protect checkbox and Set expiration date is shown | 🚧 
5 | Internal Share Enhancement - "can Share" and "can edit" > "change" hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Change <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "change" checkbox is available | 🚧 
6 | Internal Share Enhancement - "can share" and "can edit" > create hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Create <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "create" checkbox is available |  🚧 
7 | Internal Share Enhancement - "can share" and "can edit" > "delete" hierarchy | 1.- As user1 share a folder with a user2 granting "can edit" > Delete <br> 2.- As user2 right-click on shared folder <br> 3.- Select "Share with ownCloud" option <br> 4.- Fill user field with user3 and select <br> | "can edit" > "delete" checkbox is available |  🚧
