### ISSUE TITLE
Choose what to sync: Do not remove unchecked folders from the filesystem

### ISSUE THREAD

**Issue by mark-orion** [owncloud/client#4406]
Current behaviour:
Unchecked folders will not be synced and deleted from the local file system.
It should be up to the user if the folder gets deleted or not.

Expected behaviour:
Unchecking a folder in the list will make Owncloud Client ignore it during the sync process and nothing else will happen.

**Comment by blackm** [comment]
I like the current behaviour and would not change it.

I normally exclude a folder from being synced because I want to save disk space on the client site. Not removing an unchecked folder is opposite of want my intention is.

Why would you like to keep the folder on the disk?

I think if you keep the files, it is very likely that you run into file conflicted later when you add the folder for sync again.

**Comment by dragotin** [comment]
@blackm names it exactly. That was our design idea when we decided to do so. Thanks for that, and sorry @mark-orion
