### ISSUE TITLE
Owncloud.exe error

### ISSUE THREAD

**Issue by K4nape** [owncloud/client#4407]
Hello guys, how can i fix it ?

I use windows 8.1
Web host - wamp Php 5.5 / apache 2.4.9
Web - owncloud 8.0
owncloud dekstop sync - 2.1 latest

![screenshot 2016-01-29 15 58 50](https://cloud.githubusercontent.com/assets/10292911/12677441/c17b8930-c6a1-11e5-845f-d60bb445f41a.png)

**Comment by danimo** [comment]
This is a server issue, which is not related to the client. As such, this should go to the core component.

That being said, Running the server on Windows is no longer supported, and was deprecated for the version you are currently running. See https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/ for alternatives, such as the ownCloud appliance which you can run as a virtual machine. Try this rather than wasting your time with a WAMP setup.

**Comment by K4nape** [comment]
i have only windows server ...  what can i do?

**Comment by danimo** [comment]
@K4nape virtualization with HyperV or VMWare.
