### ISSUE TITLE
Update to new QtKeychain version for Windows Vault support

### ISSUE THREAD

**Issue by danimo** [owncloud/client#4429]
We should use the Windows Credential Manager API (now branded Vault) to store the credentials. QtKeyChain can do this, but there is no released stable version. Once that's done (https://github.com/frankosterfeld/qtkeychain/issues/64), we should update, which is hopefully in time for 2.2.

**Comment by guruz** [comment]
@danimo @ @felixboehm Will this also help us for roaming profiles? (which are in the 2.2 roadmap)

https://technet.microsoft.com/en-us/library/cc770797.aspx

**Comment by MTRichards** [comment]
Well, we are still on the problem of which roaming profile issue. The question remains open on what the problem is - usually it is paths that are the problem on roaming profiles, but we still don't have the details we agreed to seek.

@cdamken can you help get us something to talk to on the issue of roaming profiles?

**Comment by cdamken** [comment]
The explanation for the roaming profiles is here:

https://github.com/owncloud/enterprise/issues/995

**Comment by guruz** [comment]
FYI There is a new tag https://github.com/frankosterfeld/qtkeychain/releases/tag/v0.6.0

**Comment by danimo** [comment]
0.6.2 will be part of all forthcoming Windows and OS X builds.

**Comment by dragotin** [comment]
All done.
