### ISSUE TITLE
ownCloud client 2.1.1.5837 breaks explorer (again) on Windows if installed side-by-side with an older branded version

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4595]
I have just had a report from a user about the very same symptoms as already reported in https://github.com/owncloud/client/issues/3320 

Platform Win7 64 bit. Upstream owncloud client build: 2.1.1.5837

The system is outside of the domain (standalone).

Is this a known issue? Is there a workaround? Is there any piece of system information I can send you in order to help understanding this problem?

**Comment by guruz** [comment]
Does a reboot help?
Can you describe more of the symptopms?
Is this an auto update of the client? Normal update? Not an update?

**Comment by jturcotte** [comment]
If this is the same issue, it was an installation problem (incompatible DLLs were loaded by explorer).
In that case, this should fix the issue: Uninstalling, rebooting (all extension DLLs should normally be uninstalled), reinstalling, rebooting

The interesting part then is: if so, is is easy to reproduce?

If it's a different issue (the extension didn't change for a few releases now, it would be a rare issue), loading explorer in WinDBG or visual studio to get a stack trace of the crash would then be very helpful.

**Comment by moscicki** [comment]
I am afraid reinstalling and rebooting does not help. Uninstalling and rebooting does help but that's not what we want ;-)

We just reproduced it. Here is the workflow which fails:

1. cernbox 1.7.2 is installed on the box
2. owncloud 2.1.1.5837 is installed previously WITHOUT explorer extensions (the system booted normally)
3. we launch owncloud 2.1.1.5837 installer in order to reinstall owncloud WITH explorer extensions
4. during the reinstallation process we have been asked to remove the previous owncloud installation (same 2.1.1 version) which we did
5. the explorer extensions (overlay icons) are not immediately visible upon successful installation and launch of owncloud 2.1.1.5837
6. when we reboot the box we end up with the blue screen -- the Explorer does not start and there is no GUI
7. Ctrl-Alt-Del, running cmd.exe and uninstall.exe in owncloud 2.1.1 folder: this fixes the problem and the reboot works fine

**Comment by guruz** [comment]
@moscicki Sounds troublesome :-(

Note that DLLs in use by explorer can only be removed upon reboot..

(Just for the record: master/2.2.0 is doing a forced uninstall when being silently updated.)

**Comment by moscicki** [comment]
Could you point me to the list of DLLs which should be updated by the reinstallation process? Is it possible that there are some stray DLLs from previous owncloud or cernbox versions which are also loaded when 2.1.1 is reinstalled with extensions?

How do I load explorer in WinDBG or Visual Studio if the system does not boot (hangs with blue screen after user login). Could you please point me to a recipe?

**Comment by jturcotte** [comment]
@moscicki I tried your steps on my Win10 machine and I didn't see the issue (at least the #3320 one), which would previously be triggered by having two different, incompatible versions of `C:\Program Files (x86)\ownCloud\shellext\OCContextMenu_x64.dll` and `C:\Program Files (x86)\ownCloud\shellext\OCUtil_x64.dll`. So reinstalling the same client version can't cause that one specific issue.

As for the debugger, it's a bit touchy since explorer is usually assisting with the just-in-time debugging settings for crashed processes. What you need to do is probably to start explorer inside the debugger instead of on its own to catch the exception when it happens. Maybe you could do this by starting the debugger manually through cmd.exe (instead of running the uninstaller like you did) and manually start explorer.exe through the debugger's run menu?

The stack trace might not be complete, if you want the debug symbols for our DLLs you can download them from https://github.com/owncloud/owncloud-client-binary/tree/master/shell_integration/windows/Release/x64 and point VisualStudio to the path where you downloaded them, but even an incomplete stack trace would probably help us identify the issue or give us info on how to reproduce it.

Some questions:
- I'll try to find a Win7 VM somewhere, if you have a different Win7 machine available it would be nice to know if you can also reproduce it there. It's possible that something else on that machine is causing problems together with the ownCloud's extensions which would mean that you wouldn't be able to reproduce it on a clean machine.
- Maybe you could find a short description of the explorer crash and the DLL causing the issue in the Event Viewer's System logs?

**Comment by moscicki** [comment]
We compared the registry before and after the crash and there are duplicate entries which refer to old and new DLLs:

C:\Program Files (x86)\CERNBox\shellext\OCOverlays_x64.dll
C:\Program Files (x86)\ownCloud\shellext\OCOverlays_x64.dll
 
So it lt looks like CERNBox DLL takes for some reason precedence over the newer one from ownCloud, and that quite surely the new client is not binary compatible with old DLL (the explorer problems reported before #3320 were pre-dating version 1.8.0 — which matches completely this theory).

The puzzling issue is that overlay icons seems not working on 1.7.2 but the DLL is there.

Also, in case of branded and non-branded clients installed on the same system: how to avoid such clashes in the future?

**Comment by jturcotte** [comment]
Ahh, that could explain it, we don't check at all which ownCloud version opens the local pipe to talk with the explorer extension.The last extension to be installed will overwrite the GUIDs to point to its own DLL path on disk, and then both CERNBox and the newer ownCloud would try to talk with the latest installed version.

That means that if CERNBox is running, it will talk to the newer extension but using the old protocol, it could be that something isn't rock-solid on that side, it could be why it crashes.
- We'd need to use the branding in the pipe name. The problem at the moment is that we can't compile the explorer extension as part of the build since we can't use MinGW to build it, we'd need to manually compile a different version for all branding flavor for each update and this doesn't scale.
- We could maybe do a version check very early in the process, and abort if it's known to be problematic, but this is also bug-prone
- The simplest solution, if this is really the issue, would probably be to make the extension more robust to unexpected protocol use, and at least make sure that it doesn't make the user's computer completely unusable. That would however not help unless we also make the older CERNBox extension version robust as well, in case where that one is the one installed last on the computer.

It's also possible that this is similar to #3320, but this is only going to happen if OCOverlays_x64.dll is trying to dynamically link to an older/newer OCUtils_x64.dll, which is probably going to be picked from the same directory unless the PATH variable or something like that is pointing to the CERNBox version (sounds unlikely, but not impossible).

**Comment by moscicki** [comment]
Since the 1.7.2 does not seem to handle overlay icons on windows correctly, would it be possible to disable this functionality at runtime completely for 1.7.2? Is there a registry setting or a config option to disable it?

As per protocol for extensions in the future: I think there should be care to maintain backwards compatibility of the protocol, such that any older client version would not be affected by an update of the extension DLL. I would maybe consider to introduce the protocol version number (say 1 to start with) and make sure that if the protocol changes then the version changes as well. In other words, if I have a branded client talking protocol v1 and a newer upstream client also implementing v1 but replacing DLL with a bugfix version -- all should work fine. If a newer version of the client introduced the protocol change v2 then it would register it with a different GUID and the older one would not be affected.

**Comment by jturcotte** [comment]
Unfortunately no, the only way to disable the SocketApi is to not install the extension.

As for the protocol, we should make it robust enough not to crash across versions if we want to support branded clients to live side-by-side the OEM version, but since this protocol isn't public, trying to maintain backward compatibility (and forward compatibility if the branded client is newer) isn't worth the cost. We officially only support matching implementations on both sides of the pipe.

The cleanest solution I think would be to have a different pipe name for each branding (which make it behave like if the extension isn't installed when another client overwrites its registration), but we can't go there unless we completely change our building infrastructure to build on windows and MSVC, which currently uses MinGW through cross-compilation on Linux.

A more hackish way would be to do a version+branding check at runtime through the pipe, and disconnect or ignore every subsequent message if it doesn't. This could possibly cause mass reconnect or other subtle issues in some cases though.

**Comment by jturcotte** [comment]
I'm currently trying the 2.1.1 shell extension with the ownCloud 1.7.1 client, and also tried the 1.7.1 shell extension with the 2.1.1 client and none are crashing on my Win10 machine (which shouldn't matter unless we're crashing by feeding invalid data to Win32, which Win10 would handle better).

So we probably need a stack trace or a way to reproduce the crash before we can assume what a good solution would be.

**Comment by moscicki** [comment]
Hello,

For your reference, here is the dump of the registry. Please note that the different registry keys are not treated in the same way:

OCContextMenuHandler Class : one GUID with the new DLL version form ownCloud
OC Overlay Handler: several consecutive GUIDs with the mix of old and new DLL (ownCloud/CERNBox)

```
Windows Registry Editor Version 5.00
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AllFilesystemObjects\shellex\ContextMenuHandlers\OCContextMenuHandler]
@="{841A0AAD-AA11-4B50-84D9-7F8E727D77D7}"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F090-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F090-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files (x86)\\ownCloud\\shellext\\OCOverlays_x64.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F091-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F091-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files (x86)\\CERNBox\\shellext\\OCOverlays_x64.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F092-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F092-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files (x86)\\ownCloud\\shellext\\OCOverlays_x64.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F093-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F093-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files (x86)\\ownCloud\\shellext\\OCOverlays_x64.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F094-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F094-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files (x86)\\ownCloud\\shellext\\OCOverlays_x64.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F095-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F095-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files (x86)\\CERNBox\\shellext\\OCOverlays_x64.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F096-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F096-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files (x86)\\ownCloud\\shellext\\OCOverlays_x64.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F097-F328-48A3-B746-276B1E3C3722}]
@="OC Overlay Handler"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{0960F097-F328-48A3-B746-276B1E3C3722}\InprocServer32]
@="C:\\Program Files (x86)\\CERNBox\\shellext\\OCOverlays_x64.dll"
"ThreadingModel"="Apartment"
"Version"="1.0"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{841A0AAD-AA11-4B50-84D9-7F8E727D77D7}]
@="OCContextMenuHandler Class"
 
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\CLSID\{841A0AAD-AA11-4B50-84D9-7F8E727D77D7}\InprocServer32]
@="C:\\Program Files (x86)\\ownCloud\\shellext\\OCContextMenu_x64.dll"
"ThreadingModel"="Apartment"
```

**Comment by jturcotte** [comment]
Humm we removed some CLSIDs in 2.1 since we remove sharing icons for error status, so those won't be overwritten, and this might lead to both DLLs being loaded in explorer (with each their OCUtil_x64.dll). I have to test this.

**Comment by jturcotte** [comment]
Yes so that was the issue:

- Install branded 1.7 with shell extensions
- Install ownCloud 2.1 with shell extensions without uninstalling the <2.1 branded client
- Restart Windows (explorer crashes)

I pushed a patch for 2.2 that will make sure to unregister previous pre-2.1 CLSIDs when we regsvr32 the shell extension during the 2.2 installation, to make sure that we don't leave any CLSID pointing to the old DLL. Meanwhile for 2.1, you have to make sure that you don't install shell extensions for either the branded or non-branded client in order to avoid both incompatible DLLs being loaded at the same time by explorer. 

Even with the patch, both version will still try to communicate with any available extension version through the socket API (even if disabled in the installer) and this seems to cause wrong icons from time to time (I'm not sure if this was caused by my icon cache needing reseting), but at least explorer won't crash. If we want both to fully work side-by-side on Windows we'll need much more work than this.

**Comment by davitol** [comment]
Tested and works fine :+1: 
Win10; branded oC 1.7 and ownCloud-2.2.0.5855

**Comment by guruz** [comment]
@moscicki Would you also confirm this? Thank you

**Comment by moscicki** [comment]
Where do I get this client version from, please? (ownCloud-2.2.0.5855)

On Fri, Apr 8, 2016 at 1:54 PM, Markus Goetz <notifications@github.com>
wrote:

> @moscicki <https://github.com/moscicki> Would you also confirm this?
> Thank you
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/4595#issuecomment-207399082>
>



-- 
---
Best regards,
Kuba

**Comment by davitol** [comment]
@moscicki https://download.owncloud.com/desktop/daily/

**Comment by moscicki** [comment]
This version does not exit.

Shall I take one of these?

[image: [ ]]
<https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5971-nightly20160405-setup.exe>
ownCloud-2.2.0.5971-nightly20160405-setup.exe
<https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5971-nightly20160405-setup.exe>
2016-04-05
01:25 38M
[image: [ ]]
<https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5973-nightly20160406-setup.exe>
ownCloud-2.2.0.5973-nightly20160406-setup.exe
<https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5973-nightly20160406-setup.exe>
2016-04-06
01:26 38M
[image: [ ]]
<https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5976-nightly20160407-setup.exe>
ownCloud-2.2.0.5976-nightly20160407-setup.exe
<https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5976-nightly20160407-setup.exe>
2016-04-07
01:31 38M
[image: [ ]]
<https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5980-nightly20160408-setup.exe>
ownCloud-2.2.0.5980-nightly20160408-setup.exe
<https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5980-nightly20160408-setup.exe>
2016-04-08
01:31 38M


On Fri, Apr 8, 2016 at 2:56 PM, David Toledo <notifications@github.com>
wrote:

> @moscicki <https://github.com/moscicki>
> https://download.owncloud.com/desktop/daily/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/4595#issuecomment-207421809>
>



-- 
---
Best regards,
Kuba

**Comment by dragotin** [comment]
@moscicki yes, please the latest one, ie. https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5980-nightly20160408-setup.exe
