### ISSUE TITLE
the client can not login

### ISSUE THREAD

**Issue by junkings** [owncloud/client#4610]
I change the steps of owncloudsetupwizard, and make it become OwncloudSetupPage, Page_ShibbolethCreds, OwncloudAdvancedSetupPage, and OwncloudWizardResultPage.

According to the steps mentioned above, the Synchronization Client is created. But there is not UserID. 

Now, after I exit the program, the client can not login again.

**Comment by danimo** [comment]
Tha'ts because with Shibboleth, there is no hardcoded userid. That's the idea behind Shibboleth (unless used with ECP, which we do not support), and you cannot just rearrange wizard pages to change that, Or do you mean the user id that gets passed on from the IdP?

Anyway, please note that this issue tracker is reserved for actual bugs, not development issues. Please use #owncloud-client-dev on freenode or subscribe to devel@owncloud.org at https://mailman.owncloud.org/mailman/listinfo/devel for development related questions. Please describe _exactly_ what you want to achieve, and what exact steps you pursued, ideally with on a branch if you can make it public.
