### ISSUE TITLE
Usability proposal: undo instead of confirmation!

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/client#4619]
The client has a great function: warn you if a LOT of data is deleted server-side.
![screenshot_20160328_181658](https://cloud.githubusercontent.com/assets/551757/14122321/92a1df72-f5fb-11e5-8ded-07d52f55cd2c.png)

A suggestion from social was: why don't you make it 'undo'able? Keep the files locally but hide them and, next time that the user opens the client, let them undo it. I guess that'll be the first thing they do when they find out the files are gone, so... ;-)

Also, you can keep them and if the user undoes the change on the server the files don't have to be downloaded.

@jancborchardt what do you think? Idea?

**Comment by danimo** [comment]
@jospoortvliet The problem is that "undo" does not really work on the client. 

* It's what the user least expects because it's "still" wasting space
* It's least what an admin expects because they may want a wipe (which is why we had a lot of requests to just remove the box)
* Restart is a bad action to depends this on because a lot of people barely restart the client.
* The client is not really visible to the user, unless an actionable task or a notification happens. You could passive-notify about this, but we still have not found a good solution for passive notifications. This needs to be solved first (and is actually a task for 2.2, because a user needs to be able to e.g. accept shares).

**Comment by jancborchardt** [comment]
Yeah, I have to agree with @danimo in this case here. Usually I’m all with undo (as you know) but in this scenario a popup seems like a better solution for the consequences.

**Comment by jospoortvliet** [comment]
fair enough, it doesn't seem viable. Closing ;-)
