### ISSUE TITLE
[Windows] overlay icons incorrect since 2.2 nightly

### ISSUE THREAD

**Issue by calis2002** [owncloud/client#4631]
I noticed that the overlay icons are incorrect since a few days.
Can't really say when it started but now all files and folders are marked with the red icon. Only the .csync_journal.db* and .owncloudsync.log files are marked with the blue "syncing" icon.

EDIT: Noticed that a folder someone shared with me has a green icon.
![2016-04-01__13_15_41](https://cloud.githubusercontent.com/assets/4539953/14205559/5fa6f37e-f80c-11e5-8af8-01027aeade24.png)

Client and Server Logs are all fine and doesn't show any errors

### Client configuration
Client version: Version 2.2.0-nightly20160401 (build 5961)

Operating system: Windows 10 Enterprise with latest Updates

OS language: German

**Comment by guruz** [comment]
If you say it only regressed with the version of 1st of April then I'd blame https://github.com/owncloud/client/pull/4615
@ckamm @ogoffart @jturcotte

**Comment by jturcotte** [comment]
It might actually be caused by 5989a07339b30946b96cdad02a1bf223e06f5694. I noticed that my visual studio setup got messed up and my change to the .RC file wasn't properly committed. Doing a clean build and fixing that file was necessary to fix it but I wasn't sure if the binaries were broken as well.

**Comment by jturcotte** [comment]
If you dont have time to redo the build before I come back from vacation, a way to quickly fix it could be to revert the binary submodule to its parent commit so that the builds use the version before 5989a07. At least this would allow testing #4615 on windows, since right now this bug can hide any other bug.

**Comment by guruz** [comment]
@jturcotte Don't worry, @danimo and @ogoffart should also have the MSVC setup to rebuild those binaries. Let's keep the refactor branch in and see.

**Comment by danimo** [comment]
I'm on it.

**Comment by danimo** [comment]
@jturcotte 

```
Error	1	error RC2135: file not found: ico\Error_Shared.ico	E:\client\shell_integration\windows\OCOverlays\OCOverlay.rc	55	1	OCOverlays
Error	2	error RC2135: file not found: ico\Sync_Shared.ico	E:\client\shell_integration\windows\OCOverlays\OCOverlay.rc	59	1	OCOverlays
Error	3	error RC2135: file not found: ico\Warning_Shared.ico	E:\client\shell_integration\windows\OCOverlays\OCOverlay.rc	61	1	OCOverlays
```

Forgot to check in assets?

**Comment by jturcotte** [comment]
Cool, fixing the .rc file was only making sure that it doesn't list files that were actually removed (I think the shared version of the error, warning and sync icons), and include them in the binary. The current bug looks like there's a mismatch between the resources contents and their name caused by a stale build target.

**Comment by danimo** [comment]
@jturcotte so I can remove them from the rc file?

**Comment by jturcotte** [comment]
@danimo Yes exactly, those resources aren't used by the code anymore.

**Comment by danimo** [comment]
Ok, resources have been updated.

**Comment by guruz** [comment]
@calis2002 Would you try the new nightly and report back? http://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5976-nightly20160407-setup.exe

**Comment by calis2002** [comment]
Looks good. Thank you.
![07-04-_2016_15-56-05](https://cloud.githubusercontent.com/assets/4539953/14353658/40da4f9a-fcda-11e5-9c8e-8dad4cfac46d.png)
