### ISSUE TITLE
Handle errors of database transactions

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4632]
### Expected behaviour

It can happen that even if the sync journal was opened successfully, that subsequent interactions fail. For that we need to check the return value of low level SyncJournal methods like `setFileRecord` and others.

If for example `setFileRecord` fails, we need to bail out with a critical error.

### Actual behaviour

The return values are widely not checked because we assumed that if the db was opened successfully all is good.

Version where we found that: 2.1.1 and 2.2.0pre

**Comment by guruz** [comment]
Also make sure the asserts are real problems, not a problem in debug mode for 5 developers.
https://github.com/owncloud/client/issues/3906#issuecomment-151871922

**Comment by dragotin** [comment]
After some more debugging we found out the root cause: The user is syncing to a removable disk. Later the user hibernates the machine and removes the removable disk. When he starts the computer again, the disk is still not connected, he does it seconds later once the machine is up and running again. 

If the sync is running when the machine is hibernated, especially the database file is open. If it wakes up from hibernation but the external disk is not yet connected, the database file is lost for the sync process, and that is why sql commands fails.

In that case the client needs to bail out with an error and restart the sync.

**Comment by dragotin** [comment]
Some more pull requests to this:
- https://github.com/owncloud/client/pull/4656
- https://github.com/owncloud/client/pull/4645

Setting this to ready to test. 

@owncloud/qa you find testing instructions [here](https://github.com/owncloud/client/wiki/Testing-Scenarios-2.2)
@msrex for your info, please try nightly builds starting tomorrow.

**Comment by mcastroSG** [comment]
Hi Hi:

## TEST1

**Steps Executed**

1. Add a new account setting as Sync Shared Folder a USB
2. Pause Sync 
3. Copy a big amount of data to the USB
4. Restart Sync
5. Pause Sync
6. Hibernate PC
7. Unplug USB
8. Come out of hibernation

**Results**

An error related to the db fail is shown.  USB gets corrupted during the process so we need to review and repair it with a tool included at W10. After that just Unpause Sync and a sync starts without problem.

![img_05052016_090129](https://cloud.githubusercontent.com/assets/18436398/15038200/034c44ca-12a2-11e6-8da8-71ed5a6f860b.png)

At snapshot attached appears the pause sync icon due to we tried to pause sync before hibernate but it does not work in this way, sync is atomic and in case we try to pause during sync it continues.

##TEST2

**Steps Executed**

1. Add a new account setting as Sync Shared Folder a USB
2. Copy a big amount of data to the USB
3. While Sync Hibernate PC
4. Unplug USB
5. Come out of hibernation

**Results**

There were no error related to DB, just an error that informs about there is no Shared Folder mounted. It seems that detects there is no USB mounted and shows just that error. After that and plug in again the USB  it begans to work.

@dragotin could we consider these results as valid ?

**Comment by mcastroSG** [comment]
@msrex your input is appreciated too, are the results ok?

**Comment by dragotin** [comment]
I think these tests are fine. The important bits are:
- There is a error message about the problem (happens as we see)
- once the problem is resolved but repair or remount, the sync continues without up- or download or delete all the files again.

**Comment by rperezb** [comment]
great, @mcastroSG time for us to close this?

**Comment by mcastroSG** [comment]
sure 😄
