### ISSUE TITLE
[Windows] Right-click menu on tray icon travels below the screen

### ISSUE THREAD

**Issue by onlineth** [owncloud/client#4772]
### Expected behaviour

Menu appears within the screen
### Actual behaviour

Menu travels below the screen
### Steps to reproduce
1. Right-click on the Windows ownCloud Client icon in the notification center
### Server configuration

_Not necessary_
### Client configuration

Client version: 2.1.1

Operating system: Windows 10 64bit

OS language: English

Installation path of client: `C:\Program Files (x86)\ownCloud`
### Screenshot

[![Screenshot](http://i.stack.imgur.com/3NWP9.png)](http://i.stack.imgur.com/3NWP9.png)

**Comment by r2evans** [comment]
I'm getting the same behavior. I've attributed it to having multiple desktops (though I don't know for certain). If it helps, the layout (via Windows' *"Display settings > Customize your display"* is left-to-right (mimicking the physical placement of my monitors, so not aligned on top or bottom either), my laptop is a hires screen, and the other monitor (1 or 2 others) are not hires.

Periodically the client window itself is halfway off the screen (to the bottom, similar to the menu above), though it's easier to mitigate since I can grab the title bar and move it to within view.

Currently: win10_64 pro, client 2.2.3 (build 6307), English, default installation path.

**Comment by guruz** [comment]
Would be interesting if you find this on https://bugreports.qt.io/browse/QTBUG/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel (as open or closed bug) so we see which Qt version this potentially has fixed

**Comment by hodyroff** [comment]
@onlineth @r2evans please retest with 2.3

**Comment by SamuAlfageme** [comment]
I'm not seeing it reproduced with 2.3.1 and multi-display setups, the menu always stays on-screen. Probably the Qt version switch did the trick. 🎉

**Comment by r2evans** [comment]
I haven't seen it in 2.3.0 and didn't know 2.3.1 was released ... sorry for not responding earlier, I had wanted to test it for a few days but lost track of time to respond to you. I've not seen any problems since upgrading to 2.3, so it appears to be resolved. Thanks!
