### ISSUE TITLE
New feature--Allow selecting subfolders for sync, but do not auto-sync new folders in the root folder

### ISSUE THREAD

**Issue by kozmikyak** [owncloud/client#4795]
### Expected behaviour
Have the ability to deselect a root folder containing other folders, while selecting subfolders under that root.

### Actual behaviour
If one selects all _current_ subfolders for syncing, undreneath a root folder, the root folder is also selected for sync; there is no way to uncheck the root folder while keeping the _current_ subfolders checked.

As a result, whenever someone adds new subfolders of the root, they get auto-downloaded by the client, and it gets checked as a folder to keep synced.

This is not always desirable for organizational purposes.

### Steps to reproduce
1. Create a folder on the ownCloud server, with two subfolders
2. Set up an ownCloud client on a workstation (WIndows) and select the two subfolders of the root for sync
3.  See that if you try to click on the root folder's checkbox to deselect it and only sync the two subfolders, it won't let you; whenever all subfolders are checked, it automatically checks the root
4.  Make sure to re-check both subfolders to continue testing
5. Add a new subfolder of the root folder from a web browser logged in to the ownCloud server
6.  Observe that it will sync the new folder to the workstation

This is operating as designed, however from two posts on the forums I see that a few others desire this new functionality.

I see an easy interface way of specifying the new desired behavior without breaking the UI:  Allow one to uncheck the root folder when all its subfolders are checked.  The default can still be to automatically leave it checked, but allow the user to uncheck it manually.

Of course implementation is another matter entirely.

### Server configuration
Operating system: Ubuntu 16.04 LTS 64-bit

Web server: Apache 2.4

Database: MySQL

PHP version: 5.6

ownCloud version: 9.0

Storage backend: NFS mount

### Client configuration
Client version: 2.1 and 2.2 beta

Operating system: Windows 10 Pro

OS language: English

Installation path of client:

**Comment by MTRichards** [comment]
This is by design. When using selective sync, the option is set up to emulate the behavior of other commercial offerings, which also pull down the root folder and all of its contents, and then also the sub folder and all of those contents with selective sync. If you check to sync only a deep folder in ownCloud, all of the parent folders will be synced. The idea is that you can either sync parent content or not, and there is no good answer - some want it one way, some another. Thus we chose to emulate selective sync in an already accepted meme. Possibly an option will help a user decide, but then we run into the issue of cluttering the interface with options.

However, there may be a solution for your problem. You can instead remove the current syncing root folder, which will remove all synced folders. Then you should see nothing in your sync client, but you will still be connected to the server. Then you can just add the sub folders you want to sync with the desktop using the little "add folder sync connection" and connect each individual folder. This gives you the ultimate flexibility there, and you can even choose folders from anywhere to sync.

I am not sure of your use case specifically, but it may help you do what you want.

**Comment by kozmikyak** [comment]
That would indeed be a solution that I'd want to use.  However, I'm not
quite clear on what is meant by removing the current syncing root
folder--do I delete the ownCloud directory from my home directory (Windows
or Mac), or do I uncheck all the synced folders in the client, or something
else?  In experimenting with this I'm unable to get the "Add Folder Sync
Connection" button un-greyed.

A pointer to documentation, or a clearer description, would be welcome.

**Comment by kozmikyak** [comment]
Nevermind, I found out what the option is.  It's "Remove folder sync
connection" in the little dotted button to the right of the connection, in
the client.

**Comment by MTRichards** [comment]
Great!

**Comment by kozmikyak** [comment]
And, that option works perfectly for me.  Thank you for answering, this can
be closed.

**Comment by MTRichards** [comment]
Cool, glad to be able to help.

**Comment by dragotin** [comment]
.o0( how can we make this option easier to understand and use? ) @kozmikyak any ideas?

**Comment by jessicajaclyn** [comment]
This feature would be very useful for our use-case. We have a large marketing company, and they need to have access to many folders at many levels, but do not want to sync new folders added at higher levels automatically - leads to HUGE bloat on their devices.

Or if someone could write an extension that added this option. It's not feasible to create 5 to 27 individual syncs for each user (30+ users).

**Comment by michaelstingl** [comment]
@jessicajaclyn sounds like a use case for Spaces in ownCloud Infinite Scale.

**Comment by jessicajaclyn** [comment]
Hi Michael,

Thanks for the quick reply.

Spaces is interesting, but how does it work via sync in the desktop app?

The big problem we have is that virtual files/folders for Mac is horrible at current.

In trying to even set up the virtual files, it never finishes because there are over 400,000 files and folders for it to scan through first time. I left it going for 2+ days and it never finishes initial sync.

Does Spaces alleviate this? We don’t want each user (of say their ‘Studio Team’) to have to sync all of that team’s data to their individual devices. 3+ TB of data.

Thanks,




Jessica Reimer, Systems Administrator (she, her, hers)
[Garnet Research Corp]<https://support.garnet.ca/kb>


We block .XLS and .DOC attachments. Please use .XLSX and .DOCX or .PDF instead.

**Comment by michaelstingl** [comment]
> Spaces is interesting, but how does it work via sync in the desktop app?

Each team should have an own Space. Each Space is a separate sync connection. Users can easily choose what the want to sync or not sync.

Docs:
- https://doc.owncloud.com/desktop/4.2/using.html#spaces
- Screenshots: https://doc.owncloud.com/desktop/4.2/using.html#using-an-account-that-connects-to-infinite-scale

**Comment by jessicajaclyn** [comment]
Ahh, that’s what I figured.

So, even within their own ‘spaces’ if they are syncing a folder 3 levels down from their root and add a folder 1 level down from root (say via the web interface), that’s still going to get automatically added to their sync.



Jessica Reimer, Systems Administrator (she, her, hers)
[Garnet Research Corp]<https://support.garnet.ca/kb>


We block .XLS and .DOC attachments. Please use .XLSX and .DOCX or .PDF instead.
