### ISSUE TITLE
[Linux] Overlay icon is not shown for folder that were created while desktop client is not running

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4799]
### Expected behaviour

In case we create some folders at Shared sync folder and Desktop Client is not running, once we start desktop client an overlay icon should be shown.

### Actual behaviour

Any folder we create while desktop client is not running, once we start it does not have overlay icon. Executing 'nautilus -q' and opening Shared sync folder again the problem is solved.

### Steps to reproduce
1. Shutdown Desktop Client
2. Create at Shared sync folder several folders
3. Start Desktop Client

### Server configuration

Sever OS: Ubuntu
Sever Version: 9.1.0 Alpha

### Client configuration

Client OS: Ubuntu 14.04 LTE
Client Version: Version 2.2.0nightly201654 (build 1587)

**Comment by guruz** [comment]
FYI @jturcotte @dragotin

**Comment by ckamm** [comment]
I think a similar thing happens when you have nautilus open on any sync folder and then start the desktop client. Nautilus will connect to the socket api, but does not actively retrieve information about all the files unless one refreshes with F5.

**Comment by jturcotte** [comment]
Opening the socket should trigger an automatic REGISTER_PATH with all existing Folders, this is what triggers (or should) a refresh in other plugins.

**Comment by ckamm** [comment]
The nautilus plugin does get the REGISTER_PATH message, but can't do anything with it because it discards file items that are not inside a registered path and with no client running that meant all files got filtered. We might need to remove that filtering.

**Comment by ckamm** [comment]
I've looked at it in detail and don't think there's a good way to fix this from the nautilus plugin's point of view.

We could put *every* file we get from nautilus into the nautilusVFSFile_table dict. But if the user browses a couple of large folders it will easily fill up with a large number of entries that are never going to be useful. We'd be wasting a lot of resources even when users aren't looking at owncloud folders at all.

There seems to be no way to tell whether a FileInfo is still being viewed (is_gone always returned true in my tests) so we can't even manually prune unnecessary entries.

The problem only happens if one starts the ownCloud client when nautilus is already opened and viewing an ownCloud sync folder. And refreshing the view in nautilus will make the icons appear. I'd recommend against wasting resources to fix this corner case.
