### ISSUE TITLE
Default to *Server Activity* if there are notifications

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4805]
### Expected behaviour
In case there are notifications from the server, the tab widget should become visible with the activity-tab in front rather than the sync protocol.

### Actual behaviour
If user clicks on Activity, the sync protocol is active, even if there are notifications available.

### Steps to reproduce
1. Have notifications available for the user
2. Open the settings dialog
3. Click on Activity tab.
4. See that "Sync Protocol" is the active tab.

**Comment by guruz** [comment]
* [ ] OS X
* [ ] Linux and Windows

**Comment by ckamm** [comment]
@guruz You say this already works on OS X? How so?

**Comment by ckamm** [comment]
Pull request: #4827

**Comment by ckamm** [comment]
The pull request was reviewed, but I needed to retarget this to master. I merged it directly.

**Comment by mcastroSG** [comment]
Hi hi:

**Steps Executed**

1.- Share a file using federated sharing with another user
2.- Wait till sync ends 
3.- Once notifications has arrived click on Activity tab

**Results**

Server Activity tab is shown instead of Sync Protocol

ServerOS : Ubuntu
Server Version: 9.1.0 Alpha

Client OS: OSX El capitán 10.11.4
Client Version: Version 2.3.0-nightly20160523 (build 3391)

Client OS: W81
Client Version: Version 2.3.0-nightly20160524 (build 6111)

Tested on master branch.
