### ISSUE TITLE
Use tokens on client

### ISSUE THREAD

**Issue by rullzer** [owncloud/client#4877]
We want to support tokens in the client.
Users logs in and the client gets a token from the server. And uses that.

This should be in the 9.1 server. We will know more details on monday.

**Comment by ChristophWurst** [comment]
related https://github.com/owncloud/core/issues/24763

**Comment by mcastroSG** [comment]
Hi hi:

I´ve made some test and have find something that does not fit, we are providing a link to token section but you have to be logged on default browser previous to click on link to get there. In other case you´ll be redirected to login window and after login you are not redirected to token section. Is this the expected behaviour ¿?

**Comment by ogoffart** [comment]
No: The expected behaviour is that you are redirected to the token section even if you were not loged in before. This was fixed last week in the server. What version of the server were you using for the testing?

**Comment by mcastroSG** [comment]
@ogoffart, you are right, I´ve tested it on a docker with 9.1.0 RC1 and you are redirected to login window and in case of proper username and password you are redirected to token section. Thanks a lot!!

**Comment by rperezb** [comment]
@SamuAlfageme fyi we were talking about this one in Nuremberg
