### ISSUE TITLE
[Ubuntu] [2.2.1rc1] File names too long

### ISSUE THREAD

**Issue by 553755** [owncloud/client#4928]
### Expected behaviour

Normal Sync
### Actual behaviour

22 unsync files because of too long file names
### Steps to reproduce
1. Try to sync files with long file names
2. 
3. 
### Client configuration

Client version: 2.2.1rc1

Operating system: Ubuntu 16.04

OS language: German

Server configuration
Operating system: Debian 8
Web server: Apache
Database: Mysql
ownCloud version: ownCloud 9.0.2 (stable)

I already sync two Ubuntu 14.04 Computers without any problem for a while, both clients are stable and sync all files. Now I've setup a third Ubuntu 16.04 with the owncloud client, but it doesn't want to sync all files because of to long file names. Well, if they would be too long, other client's shouldn't be able to sync them, too. As I use encfs to encrypt all files, filenames really get a little long.
Also get the message "Backup detected This sync would reset the files to an erlier time in the sync folder" and I can choose between Normal Sync and Keep local files as conflict. But both options doesn't help.

**Comment by ogoffart** [comment]
I guess the error message say it all.
How long are the file names?  What's the file system?
Maybe just a restriction of that file system.

**Comment by 553755** [comment]
The working and the not working system use both ext4. Only difference is that the not working new system use a SSD instead of a HDD in the old system and it use Ubuntu 16.04 instead of 14.04.
Most file names are 199 characters long, but also some shorter doesn't sync. This is a part of the logfile:

```
   01.06.16 17:25:53,64RqaMguObTmEmrTNT2RtNFdD3Mlcn1ahIuUIsZbyRpgBaEC3-XwoesZnccx1EK2BI0zJrem4l2UYR3TKCaifD-5QDW2joc7Zf25tigwBTcYids62rr039Fpf1T4DUp39qLylIHRx1qcckOnZDXttQ0o,                     cloud_enc,Der Dateiname ist zu lang
   01.06.16 17:25:53,4X9pVfEQVpDqJeV5yciwy8v6/rVap9O,rcsK2UI4zSPNX-siPVRLvIp8foZAZS-wr,Y0ZSmaZ9E1KMku1YhF7mylGnZxnTtUKKsL8,aSBDdGCpKxZo,nXRZSgcaoGqx7Amnb1T9nlcT6pqZPaWBtp6pVkmHv3QzQ4gcgQrvrG0fgSYB3s,                     cloud_enc,Der Dateiname ist zu lang
```

**Comment by ogoffart** [comment]
Can you start the client with the `--logfile`  option and  check the few lines before or after the error.
Maybe also related to the depth of the file in the hierarchy?

**Comment by 553755** [comment]
I would, if you tell me how I can start the client in terminal.

**Comment by guruz** [comment]
@553755 https://help.ubuntu.com/community/UsingTheTerminal

**Comment by proto-chris** [comment]
I have the same error on (X)Ubuntu 14.04 with OwnCloud client 2.2.4 QT 4.8.6
A Windows 2.2.4 client has no problem downloading the same file.

The only info in the log that differs from other downloads:

```
11-13 19:21:04:511 0x1bfa300 virtual void OCC::PropagateDownloadFileQNAM::start() "Pictures/KanColle/yande.re 308584 akatsuki_(kancolle) hibiki_(kancolle) ikazuchi_(kancolle)   inazuma_(kancolle) japanese_clothes kantai_collection kimono shima_(shima_je).png" 0

11-13 19:21:04:511 0x1bfa300 This error is not blacklisted  0 false

11-13 19:21:04:511 0x1bfa300 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Pictures/KanColle/yande.re 308584 akatsuki_(kancolle) hibiki_(kancolle) ikazuchi_(kancolle) inazuma_(kancolle) japanese_clothes kantai_collection kimono shima_(shima_je).png" INSTRUCTION_NEW 2 "File name too long"
 ```

**Comment by proto-chris** [comment]
Ok, I recently tried to manually copy the files via dav-mount and ran into the same issue. It gave me an error that the file name was too long trying to copy from dav to local.

**Comment by christian-rauch** [comment]
I get the same error when trying to sync from the server to a client B, after syncing from client A to the server with ownCloud client version 2.4.1.
In the log of client B:
`[ warning sync.propagator ]:	Could not complete propagation of <relative file path> by OCC::PropagateDownloadFile(0x556391639c90) with status 2 and error: "File name too long"`

The file with the same relative path was successfully uploaded with client A (Ubuntu 14.04, ext4) to the server. However, I cannot sync it back to client B (Ubuntu 16.04, ext4 with encrypted home folder). The error message is misguiding since I can successfully sync between server and client A; hence the filename is obviously not too long.

The `relative file path` in the log has 179 characters. What is the maximum filename length allowed for syncing? And why should this be an issue when downloading to client B after having it already uploaded on the server?

**Comment by ogoffart** [comment]
This error comes from glibc, and correspond to the ENAMETOOLONG  error.
There is AFAIK no limit in owncloud.  It is the file system that does not support such files:

I guess the probleme is because of the absolute file path. 

Anyway, the client is behaving as expected giving the error message from the system.

**Comment by guruz** [comment]
> What is the maximum filename length allowed for syncing? 

I guess it's related to how you encrypt your home folder on that machine..
