### ISSUE TITLE
macOS: owncloud popup window asking for password is misleading

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4940]
On OSX the popup asking for password has a misleading layout.

This layout that makes it look as if the window is in the foreground (*), and any typed text would end up there. Unfortunately this is not the case, and the password will instead appear in clear text in any document or app that was in the foreground before the owncloud password window popped up. This may expose the password of the user.

(*) it has the blue band around the text field when the window pops up, and which is one of the indicators that this field is active.

When I switch back and forth the popup window and other app -- the blue band behaviour becomes correct. But first impression is not correct.

![image](https://cloud.githubusercontent.com/assets/621965/15752935/b2e1e20a-28f0-11e6-9dcb-c5bb90655e78.png)

**Comment by michaelstingl** [comment]
@dragotin @guruz Could you have a look? /cc @felixboehm 

00005591

**Comment by dragotin** [comment]
The problem AFAIK is that the password window is not modal, that's why it allows users to enter something in another window. If it was modal, it would steal the focus from other apps immediately, which is also bad if that comes unexpected.

As far as I know, this dialog nowadays only appears after the user clicked "log in" in the tray menu and not any longer unexpected. So we probably should do it modal.

@jturcotte @guruz ?

**Comment by jturcotte** [comment]
The change that makes it appear only by pressing log in was reverted. This would be the solution by itself in the end since it would get the focus right away, but people were used to get a popup and they wanted it back.

Isn't a modal dialog per application only too?

With people used to see their popup and not wanting anything to change, I'm not sure what is the solution beside maybe adding an option for branding that want it the "old way" and have the rest of the world have the re-login needing an action from the user before showing a dialog.

**Comment by ckamm** [comment]
I've tried just calling `clearFocus()` on the line edit if the application isn't currently in the foreground. But that didn't really help with the problem at hand on Linux, because a blinking cursor is still displayed. Maybe something like this could be made to work to avoid the issue on osx though.

**Comment by Kawohl** [comment]
any update her @ckamm ?

**Comment by ckamm** [comment]
@Kawohl No. The problem on Linux seemed more mild and I couldn't get the workaround to work. Someone on OSX would have to check the situation and possibility of workarounds there. 

If we must retain the password dialogs that pop up out of the blue (see @jturcotte's points), the only non-workaroundy solution I see is designing the dialogs in a way that requires an explicit click before typing passwords is possible. But that's highly unusual.

**Comment by michaelstingl** [comment]
There are more smaller focus glitches in the UI for macOS. @SamuAlfageme Could you collect a list with action items?

The thing that irritates me most:
In the screenshot in the initial post, the window on top is not in focus, but the input field has the blue outline. This is not usual in other macOS software. I  think other applications remove input field focus if the window itself looses focus.

**Comment by guruz** [comment]
I remember @ogoffart mentioned this is a Qt bug?

**Comment by michaelstingl** [comment]
@guruz @ogoffart focus behaviour improved in Qt 5.10.1 ?

**Comment by guruz** [comment]
@moscicki @michaelstingl Feel free to try..  https://download.owncloud.com/desktop/testing/ownCloud-qt5.10.1-2.4.2.951824.pkg

**Comment by dragotin** [comment]
I heard MacOSX has such a cool notification system, maybe it is possible to ask for the Password directly in the notification? That would save the lost little input dialog that you hardly can find on the huuuuge Mac display?! Maybe.... (My linux desktop is far away from that...)

**Comment by felixboehm** [comment]
@guruz what is needed to cleanup the behavior here?

**Comment by guruz** [comment]
If this is a Qt bug, then @moscicki can re-evaluate with a newer build using Qt 5.10.1 that he just downloaded for testing another issue. (@moscicki did you download the one with 5.10.1 in filename, not 5.6.2?)

Otherwise I'll then add this for 2.6.0 milestone.

> I heard MacOSX has such a cool notification system, maybe it is possible to ask for the Password directly in the notification? 

This would be the ideal solution. Although apple claims:
> Don’t use notifications to display error messages. People generally expect notifications to be informational and deferrable. If you need to display an error message, an alert has greater impact than a notification. See Alerts.
https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/notifications/

**Comment by TheOneRing** [comment]
Should be fixed with the modal dialogs in 2.7
