### ISSUE TITLE
[Overlay][MultiOS]"Red cross" overlay icon is not shown in case of bad renaming file

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4978]
### Expected behaviour
In case there is an error on any folder or file at my Shared sync folder a "red cross" overlay icon is supposed to be shown.

### Actual behaviour
In case of error  "blue sync" overlay icon is shown

### Steps to reproduce
1. Generate an error over a file or folder (i.e. rename a folder to 🌗  ) 

### Server configuration
Server OS: Ubuntu 14.04
Server Version : 9.1.0 RC1

### Client configuration
Client OS: OSX El capitán 10.11
Client version:  Version 2.2.1-nightly20160617 (build 3456)  and also tested with 2.2.1 official

Client OS: W10
Client Version: Versión 2.2.1 (build 6146) (aka 2.2.1 official)

**Comment by guruz** [comment]
I think this way of producing an error is currently not handled properly because of the way we tell the file managers that there is an error on a file (and since they see the file with a different name they can't show it at all).

Do you have another way to produce an error?
E.g. by hacking the server PHP or activating the file firewall or so on a file?

**Comment by guruz** [comment]
https://en.wikipedia.org/wiki/Emblems_of_the_International_Red_Cross_and_Red_Crescent_Movement

**Comment by mcastroSG** [comment]
Somebody has to take care of my injured files 😄

**Comment by mcastroSG** [comment]
closing
