### ISSUE TITLE
Improve error messages if limited permissions don't allow some actions

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#5059]
### Steps to reproduce

1. User A shares folder with user B without permissions to delete things
2. User B uses Win Explorer to move folder from outside into shared folder

### Actual behaviour

In Win Explorer, moved folder is in shared folder, but on the server, the new folder never arrived.

<img width="506" alt="01_ie11_-_win8_1_2" src="https://cloud.githubusercontent.com/assets/214010/16852122/027e08b6-4a07-11e6-8f08-26f605969b56.png">
<img width="364" alt="02_ie11_-_win8_1_3" src="https://cloud.githubusercontent.com/assets/214010/16852104/e5d9d0be-4a06-11e6-81a3-d4f0332bc987.png">

I need to open the settings to get an idea what went wrong.

<img width="829" alt="03_ie11_-_win8_1_1" src="https://cloud.githubusercontent.com/assets/214010/16852106/e5dc2ada-4a06-11e6-87e6-63f2ec7178f5.png">
<img width="831" alt="03_ie11_-_win8_1" src="https://cloud.githubusercontent.com/assets/214010/16852107/e5dc5c08-4a06-11e6-9aa9-387d8a6ec564.png">

### Expected behaviour

**Could the error messages be improved?**
- A user may not know that or why he has limited permissions
- The error messages should suggest how to solve the problem and need to be displayed as quick and as accessible as possible after the failed user interaction

**Example:**
`Please contact $OWNER_OF_SHARE to get permissions to upload the files`

### Server configuration

ownCloud version:
8.2.6

### Client configuration

Client version:
2.2.2

Operating system:
Win 8.1

OS language:
EN

@dragotin @owncloud/designers What do you think?

00005773

**Comment by ckamm** [comment]
Improving these messages sounds good to me. I've investigated our current error messages for various missing permissions:

When deleting a file in a shared folder where I don't have the necessary permissions I get a very generic "Error downloading http://localhost/.../foo.txt - server replied: Forbidden" that users will have a hard time figuring out.

When creating a file without having creation permissions, the error "Not allowed because you don't have permission to add files in that folder" at least says what's going on.

When editing a file without having change permissions, the error is "Not allowed to upload this file because it is read-only on the server, restoring", undoes the change and moves the local change to a conflict file.

**Comment by ogoffart** [comment]
> When deleting a file in a shared folder where I don't have the necessary permissions

That's strange.  Maybe the client did not had time to fetch the permissions.

But other thn that, there is little we can do. We can change the wording, but IMHO it's explicit enough.  We don't know who is the $OWNER_OF_SHARE at this point.

Perhaps what's confusing is that we get red errors for all sub items. so we could change that.  
Maye if the folder is shared we can ask a generic.  "Ask the owner of the share to grant you the approriate rights" if we detect a folder with the "S" permission.

**Comment by ogoffart** [comment]
Is it better now that only one error is there?

**Comment by ogoffart** [comment]
@michaelstingl  Is it better now that there is only one error?  (but it's still the same error)
