### ISSUE TITLE
Don't retry in less than < 1min for 503 failed downloads?

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5087]
I feel a bit flooded by OS X desktop notifications.
And it does not seem to end. `OCC::Folder::slotSyncFinished: the last 23 syncs failed`

```
07-28 13:53:35:256 0x7ff381617ce0 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "https://.../remote.php/webdav/"
...
07-28 13:54:26:933 0x7ff381617ce0 OCC::Folder::startSync: *** Start syncing  "https://.../remote.php/webdav/"  - client version 2.2.3beta1 (build 3556)
```

**Comment by ckamm** [comment]
Currently we intentionally cap the maximum delay between scheduled syncs at 1 minute because we only have a single queue that we never rearrange and with multiple sync folders it'd be bad if a repeatedly failing folder blocked other folders from syncing.

I think we ought to have delays per-folder and then schedule the folder from the queue with the delay that expires soonest. Then we could have consecutive-failing-sync delays that are longer without harming other use cases.

**Comment by guruz** [comment]
The problem is that I'm flooded with the same desktop notification every 1 min :/

**Comment by ckamm** [comment]
@guruz Are these per-file notifications? Maybe we need to do something in addition to triggering the sync less often.

**Comment by guruz** [comment]
(With 2.4/master I don't get notifications for directories, I have not checked files)

**Comment by ckamm** [comment]
It is unclear what exactly to do here. If we had a way of saying: "sync this folder again, but not before 5min have passed" that might do it?

**Comment by fmoc** [comment]
This issue has not seen any updates in years and it is unclear whether this still is a problem. Please don't hesitate to reopen if the issue persists.
