### ISSUE TITLE
OS X: Client notifies about untrusted self-signed certificate even though the certificate is in my keychain

### ISSUE THREAD

**Issue by georgehrke** [owncloud/client#510]
### Expected behaviour

The desktop client should not ask if the certificate is trustworthy if the certificate is saved in the system keychain (and every property is set to "Always trust"). It should just continue without asking.
### Actual behaviour

The desktop client asks if the self-signed certificate is trustworthy even though it's saved in the system keychain.
### Steps to reproduce
1. Host your ownCloud with a self-signed certificate
2. Add the certificate to the OS X system keychain
   (2.1. change every property to always trust)
3. setup syncing with the ownCloud client
4. the client will ask you if the certificate is trustworthy
### Server configuration

Operating system:
Debian GNU/Linux

Web server: 
Apache/2.2.16
mod_ssl/2.2.16
OpenSSL/0.9.8o

Database:
SQLite

PHP version:
5.3.3-7+squeeze15

ownCloud version:
5.0.3
### Client configuration

Client version:
1.2.3

Operating system:
OS X 10.8.3

OS language:
(US)English

Installation path of client:
/Application/owncloud

**Comment by petrindade** [comment]
Hi all!

Some issue here!
I installed a self signed root CA that signs an intermediate cert that in turn signs the final own cloud cert. This goes well on Safari and Chrome.

On owncloud client I too also get the warning about the intermediate and root certs. I can accept and have no more trouble but it should not be the case since they are in the keychain.

ownCloud: 8
client: 1.7.1 build 1655
OSX: 10.10.2 (the latest)

Best regards
