### ISSUE TITLE
Avoid file locking

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/client#5140]
I use the client 2.2.3 for Win7/64-bit.

The problem is, that if I am using Picasa from Google, there are many ini files which are modified quite often. Whenever that happens, ownCloud start the sync. But in that time it's not possible for Picasa to write changes to that file again. That results in not saved changes and corrupt database <> ini file comparison. So changes are visible in Picasa but in reality not saved in the ini files.

Is there any way to avoid file locking by ownCloud?

**Comment by ckamm** [comment]
@scriptPilot The ownCloud client already opens files with the most permissive share mode (SHARE_READ, SHARE_WRITE, SHARE_DELETE). Possibly Picasa opens the file without a share mode at all, which I think means requesting exclusive access, and that's why it fails. I don't think there's anything the client can do regarding file locking, unfortunately.

The problem would probably be less apparent if files were synchronized less often. But for now you'd need to manually pause sync while using Picasa and resume it afterwards to do something like that.
