### ISSUE TITLE
File Watcher: sync is triggered when files/directories under hidden directories are edited.

### ISSUE THREAD

**Issue by pfoo** [owncloud/client#5163]
### Expected behaviour

owncloud client should not trigger a sync check when a hidden directory or any of its subfiles/subdirectories is modified when "sync hidden files" is unchecked.
### Actual behaviour

owncloud client seems to be triggering a sync check when a directory inside a hidden directory is modified even if "sync hidden files" is unchecked.
This is not happenning when adding ".*" to sync-exclude.lst
### Steps to reproduce
1. sync your home folder (~), uncheck sync hidden files, do not add .\* to sync-exclude.lst
2. launch firefox
3. wait for firefox to change something in its profile (launching firefox itself does, creating new tabs also works)

This is also triggering it :
touch .local/share/klipper/test
touch .local/share/test

this is however not triggering it :
touch .local/test
### Client configuration

Client version: 2.2.3

Operating system: linux ubuntu 16.04 4.4.0-36-generic
### Logs

```
09-09 14:51:38:159 15058 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("/home/pfoo/.mozilla/firefox/1mtnhnyr.default/xulstore.json.tmp")
09-09 14:51:38:160 15058 OCC::FolderMan::slotScheduleSync: Schedule folder  "pfoo"  to sync!
[...]
09-09 15:13:29:857 16490 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("/home/pfoo/.local/share/klipper/history2.lst.TJ3570")
09-09 15:13:29:858 16490 OCC::FolderMan::slotScheduleSync: Schedule folder  "pfoo"  to sync!
```

**Comment by ckamm** [comment]
I can reproduce the problem.

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5173

**Comment by SamuAlfageme** [comment]
@ckamm Seems to be fixed (tried in OS X, Ubuntu and Windows with OC Client 2.3.0~nightly20161111) and it's not happening anymore. Although I found a minor bug somehow related with windows special hidden files I've logged in #5309 and a small detail that came up while selecting `$HOME` as local dir to sync, the relative path is cropped and shows `Open folder ''` under Managed Folders, instead of showing 'Open folder /User/<username>`:

![relative path os x](https://cloud.githubusercontent.com/assets/2644445/20211375/86ab5166-a7fe-11e6-9034-b47b75bb9da6.png)

**Comment by ckamm** [comment]
@SamuAlfageme Nice catch, feel free to make another ticket about the remaining issue.
