### ISSUE TITLE
[Windows 10][Client] Sync client cannot rename download temporary file

### ISSUE THREAD

**Issue by marcoesch** [owncloud/client#5234]
Hello,
I am using an Linux owncloud server with 2 Windows 10 laptops.
Both laptops (A,B) have the latest Windows client installed (V2.2.4.6408) and I have a folder that gets synched to both laptops.
If I upload a file to the server via the webinterface, the files gets synched to both laptops. On the A the synch is correct on the other B the synched file is broken. The file has the correct size but the name is wrong (hidden temporary filename).
The same happens when I drop a file from the laptop A into the synched folder, synching to B occurs but the file remains with the temp filename but having the correct size.
If I drop a file to the synch folder from A all is ok - interestingly I can rename the file from the webinterface and the filename is corrrectly renamed on both A and B.
I use different Virus scanners on both machines. But after disabling and even uninstalling the VS from B the problem persists.
Please advice,
Thanks,
Marc
### Server configuration

Operating system: Open Suse

Web server: Apache

Database: MySQL
### Client configuration

Client version: Version 2.2.4 (build 6408)

Operating system: Windows 10 (both with anniversary update)

OS language: Eng

Installation path of client: Standard
### Expected behaviour

The files should have the correct Name after synching
### Client Log:
# =#=#=# Syncrun started  until  (0 msec)

|0|DB/DB.kdbx|INST_NEW|Down|1476092488|2847c47aebd455d141162913dea4408e|910606|00000113oc7bqbud6aer|3|Access is denied.

|0|0|0|||INST_NONE|
|0|DB/ManuelMercator-V.pdf|INST_NEW|Down|1475667044|d48b4d9950d3d6e5b1b149c4e221dd2b|872543|00002700oc7bqbud6aer|3|Access is denied.

|0|0|0|||INST_NONE|
|0|DB/ProblèmeFactures.pdf|INST_NEW|Down|1469182050|5622f5c59d6d9578da14ac17feb06339|1644736|00002701oc7bqbud6aer|3|Access is denied.

|0|0|0|||INST_NONE|
|0|IMG_20160918_205325.jpg|INST_NEW|Down|1474224929|5b8ee62d6ba71ac0619fdd3eb4e4e5cc|1658342|00002141oc7bqbud6aer|3|Access is denied.

|0|0|0|||INST_NONE|
|0|NA-SalesProdByArtIdAndDate.sql|INST_NEW|Down|1476097442|6fe7f84830ba1595dee26a62efd28b51|2090|00005688oc7bqbud6aer|3|Access is denied.

|0|0|0|||INST_NONE|
|0|OwnCloudIssue.txt|INST_NEW|Down|1475844668|47d976049584384eb69eb7abecc4223f|1272|00002732oc7bqbud6aer|3|Access is denied.

|0|0|0|||INST_NONE|
|0|ownCloud Manual.pdf|INST_NEW|Down|1475442626|0691b0b7061591a7db4a1bbf25a7692d|4041918|00002672oc7bqbud6aer|3|Access is denied.

|0|0|0|||INST_NONE|

**Comment by ckamm** [comment]
@marcoesch It looks like on computer B the client get an "Access denied." error when trying to rename the download temporary to the correct target filename. That's weird, because I assume a file with that name doesn't exist yet - and creating the download temporary did not run into problems.

Currently I have no idea for why that would happen, here are some ideas:
* What's the full path to the target folder on machine B? Maybe something's up with that path?
* You could try re-setting up the client sync account on machine B - use a very simple target folder that you created specifically for this purpose.
* Maybe more information is found in the client log files (but I doubt it). You can run the client with `--logfile mylog.txt` to produce a log. (it contains a bunch of private data, all the lines that mention a file that failed to be properly synced would be sufficient)
* Is there any other setup difference between machines A and B?

**Comment by ckamm** [comment]
@marcoesch Feel free to reopen if you have more information.

**Comment by marcoesch** [comment]
Hello,
Found a solution - at least it worked for me, because I still cannot find the reason.
I guess there is something wrong with my windows profile. Just for fun I created a new profile, configured owncloud and all is ok now - files are correctly synched.
