### ISSUE TITLE
read-only share: locally modified file mutliple times should create multiple conflict files (?)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5273]
ownCloud 2.2.4 on MacOSX.

In read-only share I modified a file b.txt which was fully synchronized initially. I had to add the write-bit because it was read-only. The system tried to revert the file but since it found a modification it created a conflict file. The sync was green at the end. That's all expected.

```
%ls -l
   -r--r--r--  1 moscicki  staff  23 Aug 23 16:11 b.txt
   -rw-r--r--  1 moscicki  staff   2 Oct 25 13:23 b_conflict-20160823-161149.txt
```

![image](https://cloud.githubusercontent.com/assets/621965/19684312/d0ca99a0-9ab6-11e6-8e05-515781dfcdc8.png)

When I then again modified file b.txt the system did not create the second conflict file as it should. Instead it left the b.txt modified locally. The resulting log was this:

![image](https://cloud.githubusercontent.com/assets/621965/19684239/734ecad0-9ab6-11e6-846d-d5c1b548c7f3.png)

When I subsequently removed the conflict file b.txt was restored from the server and a new conflict file created. 

Should it create multiple conflict files in this cases to have consistent behaviour?

**Comment by ckamm** [comment]
@moscicki Yes, I agree there should be multiple conflict files.

**Comment by ckamm** [comment]
@dragotin @ogoffart @guruz What's the reason we use the server's timestamp during conflict file name creation? Wouldn't the local mtime work just as well? I'm wondering whether I should change this generally, and not just for restorations.

**Comment by ogoffart** [comment]
Yes, i suppose using the local time is actually better.

**Comment by ckamm** [comment]
Pull request including change and test: https://github.com/owncloud/client/pull/5300

**Comment by SamuAlfageme** [comment]
@ckamm Yup, now the conflict files are created with the local timestamp (`<file>_conflict-yyyyMMdd-HHmmss.<ext>`) and the original file is restored, there are some overlay-related issues though:

* The ones in the conflict files are initially in 🔁 Syncing status until you close the folder and reopen it.
* The original file appears with the ⚠️ overlay as it's not being correctly synced (instead of the original shared green one). This one is kept even when you reopen the folder.

![conflict_overlay](https://cloud.githubusercontent.com/assets/2644445/20751951/f02db69c-b6fe-11e6-8ef9-3f2e8a271bd2.gif)

And then, one question. When I create a new file/folder in a read-only folder, it generates a Sync error (which btw, removes the previous conflict entry in the "Not synced" tab and replaces it by the one about the new sync error) - but this is **semantically the same as adding a conflict file** (that doesn't cause a sync error).

**Comment by ckamm** [comment]
@SamuAlfageme Conflict messages are currently not persistent, i.e. they are removed when the next sync is triggered and won't show up again. Since conflicts should almost always be resolved quickly by the user, that seems like a usability problem we'll want to address. (I'll make a ticket)

Adding a new file to a read-only folder and creating a conflict file inside it aren't equivalent, because conflict files are never synced, so by not syncing the conflict file no user expectations (that the file should be transfered to the sever) are violated.

The overlay issues you mention I'll move to a separate ticket since they're unrelated to this issue (nice catch!).
