### ISSUE TITLE
[Feature] Share relative path of oc file

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#5350]
When collaborating with workmates I often want to send them links to files I just uploaded. E.g. "What do you think about ``Development\Documentation\My idea.pdf``?

Currently I have to build that path my self: First copy folder path, then copy file name.

The best solution would be: https://github.com/owncloud/client/issues/2596
But since it seems to be very complex it might suffice to have a context menu ``Copy relative file path to clipboard`` when right clicking the file in the file explorer.

Note: I didn't quite understand what  `Copy ownCloud Link` from https://github.com/owncloud/client/issues/5023 is about but it sound related.

**Comment by SamuAlfageme** [comment]
From what I understand, you want to copy the absolute path in your disk of a file you are sharing through an owncloud folder with your mates. This is tricky, since they can set a different Folder Sync Connection (meaning, they can select a different local path on their computers to sync the same remote folder) 

You can rely on some OS native features to achieve this: e.g. if you are in OS X, you can hold the alt (⌥ / option) key while in the context menu to show the `Copy <file> as Pathname` option that will copy in your clipboard the absolute path of the selected file. Similarly you can do this in Linux and with some workarounds in Windows.

![pathname](https://cloud.githubusercontent.com/assets/2644445/20834745/1ff99d7a-b897-11e6-960f-335a7b3ee0d1.gif)

And yes, I'm with you on both features #2596 and #5023 being interesting for the desktop client. Best you can do is leave a 👍 in those to show your support to their development.

Thanks!
