### ISSUE TITLE
Add account server address field has no https default text

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#5412]
### Expected behaviour
When I do Account->Add New, the Server Address filed should be pre-populated with "https://" ready for the user to type the rest of the server URL.

### Actual behaviour
The Server Address field is empty.

### Steps to reproduce
1. Have oC client running with at least 1 account sync connection already set up.
2. Select Account->Add New
3. The Server Address field is empty

### Server configuration
N/A
### Client configuration
Client version:
2.3.0-nightly20161212 (build 6562) and 2.2.*

Operating system:
Windows10

OS language:
English

### Notes
When first setting up oC Client making the first sync connection, the Server Address field is pre-populated with "https://" - this is nice to save having to remember to put that at the front of the URL. So it would be even nicer if the same happened when adding more accounts.

**Comment by SamuAlfageme** [comment]
@phil-davis hm, that's rather weird and funny behavior. There's actually no difference between the first sync connection wizard and the following: 

![url](https://cloud.githubusercontent.com/assets/2644445/21420483/4804e9f4-c82e-11e6-80f9-b08e2cda1725.gif)

What is happening under the hood is that the Server Address input field gains cursor focus right when the wizard is launched and if no URL hint has been set (https://github.com/owncloud/client/blob/master/src/libsync/theme.cpp#L472-L475) that field is empty. 

But when you remove the focus from it, the wizard assumes you've finished entering the URL and this happens: https://github.com/owncloud/client/blob/master/src/gui/wizard/owncloudsetuppage.cpp#L144 as there's no scheme set in the URL (because the user didn't write anything), the `https://` is prepended to the URL, appearing only then.

So the question here is whether if the URL hint would be better set to `https://` instead of empty, right?

**Comment by phil-davis** [comment]
So somehow on starting the first time, the code thinks that the user has been in the field and jumped out of it (or whatever) and is nice enough to put "https://" there. I found that handy.
If all (or 99.99%) of use cases have a server address starting with "https://" then it would be nice to always start with that string to save the user having to know to type it.

**Comment by ckamm** [comment]
@phil-davis Thanks for bringing this up! I think we intended to leave the field empty initially to make sure the placeholder text is shown (if set in a theme). The current behavior is new, probably a bug and I'll fix it.

Pasting a url is also a large usecase, and then prefilled text can be in the way. But I expect this is mostly about the placeholder text.
