### ISSUE TITLE
PropagateDirectory: Investigate if _subJobs should be pre-allocated (reserve()) or squeeze()

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5454]

**Comment by ckamm** [comment]
@ogoffart I'd say we can squeeze() _subJobs in directories when we're done with them in `OwncloudPropagator::start`, do you agree?

**Comment by jturcotte** [comment]
I think that this is solved by #5400 as the whole PropagateDirectory job is now destroyed by its parent when it's finished.

**Comment by guruz** [comment]
@jturcotte I mean the pre-running peak. If you squeeze() or reserve() it won't take so much space in memory _BEFORE_ running. (directly after constructing).

@jturcotte @ckamm  Agree to reopen?

See @ckamm 's comment above..

**Comment by jturcotte** [comment]
I interpret "when we're done with them" as "when the job if finished".

`reserve()` is to prevent reallocating the vector as you fill it if you know the size already, but we don't know it since we iterate over the vector of SyncFileItem until we hit a different parent directory. It doesn't reduce the used memory.

`squeeze()` is the other way around, when you're removing objects from the vector, it won't reallocate immediately to avoid `memcpy`ing to a new location. What I meant is that it won't bring us anything to do this at the end of the PropagateDirectory job, since the whole job (and its vector) will be destroyed immediately after. We could do squeeze after each subjob is done, but this means that we'll reallocate the whole vector each time, only to save a bit of extra memory for the duration of the PropagateDirectory and not reducing the peak, so I'm not sure if it's worth it.

**Comment by jturcotte** [comment]
Ahh you guys mean to remove the extra capacity that append might reserve, yes that might help save a few KBytes.

**Comment by guruz** [comment]
Exactly!

**Comment by jturcotte** [comment]
You can only do this at the end of `OwncloudPropagator::start` after the foreach, so you'll already have created all the subjobs and reached the peak at that point, but could keep things tidy with #5451

**Comment by ckamm** [comment]
This has been resolved through #5451. During setup we only build a `QVector<SyncFileItemPtr>` now. We could squeeze that but it'd be a marginal gain.
