### ISSUE TITLE
Windows clients not syncing reliably between each other. 

### ISSUE THREAD

**Issue by arjones85** [owncloud/client#5520]
I am testing the latest Nextcloud 11 between a Windows 10 and a Windows 7 machine, with a CentOS 6 server. It's my understanding that Client issues should still be posted here. Please let me know if this is not the case.

If I add a small text file on one Windows machine, it will sync almost instantly to the server (as I would expect). The file shows up in the web GUI without an issue.

However it will not download on the other Windows machine without some prompting. If I open up the Activity tab on the other machine my file upload shows up in the activity tab, but the file won't download onto that client unless I do something inside the Nextcloud folder, such as adding another file. At that point the problematic file will download.

Am I missing something in the setup?

Thanks!

### Expected behaviour
When adding a file to Windows client 1's directory, it should be synced to Windows client 2 without any action needed first on Windows client 2.

### Actual behaviour
While the file is uploaded to the server immediately, and shows in the Web GUI properly, the file does not get downloaded to Windows client 2 without first interacting with Windows client 2's folder in some way.

### Steps to reproduce
1. Install desktop sync on Windows client 1, Windows client 2, and server on CentOS 6
2. Add file to Windows client 1's folder. Wait for it to finish syncing
3. File never syncs back down to Windows client 2. It does show in the "Activity" tab on Windows client 2, but the file never downloads.

### Server configuration
Operating system: CentOS 6

Web server: Apache

Database: MySQL

PHP version: 5.6

ownCloud version: Nextcloud 11 server

Storage backend (external storage): Local disk

### Client configuration
Client version: 2.2.4

Operating system: Windows 7 and Windows 10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

This is from a client that has an outstanding file that it has not picked up from the server:

02-07 11:42:35:199 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:42:35:199 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:42:51:064 0x7fe0a0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (The specified procedure could not be found.)
02-07 11:42:51:064 0x7fe0a0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

02-07 11:42:51:064 0x7fe0a0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
02-07 11:43:07:209 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:43:07:209 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:43:39:219 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:43:39:219 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:44:11:234 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:44:11:234 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:44:43:244 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:44:43:244 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:45:15:254 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:45:15:254 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:45:47:266 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:45:47:266 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:46:19:276 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:46:19:276 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:46:19:886 0x7fe0a0 OCC::ActivityListModel::startFetchJob: void OCC::ActivityListModel::startFetchJob(OCC::AccountState*) Start fetching activities for  "russell@cloud.eggycrew.com"
02-07 11:46:19:886 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::JsonApiJob created for "https://cloud.eggycrew.com" + "ocs/v1.php/cloud/activity" "OCC::ActivityListModel"
02-07 11:46:19:886 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::JsonApiJob created for "https://cloud.eggycrew.com" + "ocs/v2.php/apps/notifications/api/v1/notifications" "OCC::ServerNotificationHandler"
02-07 11:46:20:351 0x7fe0a0 OCC::ActivityWidget::slotBuildNotificationDisplay: void OCC::ActivityWidget::slotBuildNotificationDisplay(const ActivityList&) Activity in blacklist, skip
02-07 11:46:51:288 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:46:51:288 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"
02-07 11:47:14:269 0x7fe0a0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (The specified procedure could not be found.)
02-07 11:47:14:269 0x7fe0a0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

02-07 11:47:14:269 0x7fe0a0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
02-07 11:47:23:299 0x7fe0a0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
02-07 11:47:23:299 0x7fe0a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://cloud.eggycrew.com" + "/" "OCC::ConnectionValidator"

2. Web server error log: Empty

3. Server logfile: ownCloud log (data/owncloud.log):

{"reqId":"JeulwKcx7vcM0rgk4+HE","remoteAddr":"66.195.111.246","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-02-07T16:36:59+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--","version":"11.0.1.2"}

**Comment by hodyroff** [comment]
Can't reproduce this. Please try with ownCloud 9.1.4. ideally oC Client 2.3 from daily.
Of course the server to desktop syncing works in a pull mechanism, but after the first such pull the file lands perfectly on desktop 2.

**Comment by szakitibi** [comment]
Encountered sync issues with Windows clients too.

sync error 1.
A folder with some content was shared to five users. All five of them were using Windows desktop client. One of them cut-pasted (moved) a sub-folder inside the shared folder, which did not sync the way as expected.

sync error 2.
I created a test server with ownCloud version 9.1.0 with two users (User1, User2) using desktop clients, to test if I can reproduce the cut-paste issue before reporting it. In fact I was not able to reproduce the original issue. Cut-paste did sync properly for both users, but instead I encountered another sync error, where a newly created folder was not synced by one of the desktop clients.

### Expected behaviour
1. Based on [documentation](https://doc.owncloud.org/desktop/2.2/architecture.html#the-synchronization-process) cut-pasted folder should be removed on its original location and show up in its new location in the folder tree for all five users using the desktop application.
2. Newly created folders and files by User1 should sync for User2 using the desktop application.

### Actual behaviour
1. The cut folder was showing up on its new location for all five users on their PC, but the original was not removed. Basically it did copy-paste the folder instead of cut-paste.
2. User1 created on his PC a new folder with a dummy file in it, and it was not synced by User2's desktop client.
It was properly uploaded to the server, so if User2 logged in the browser, he saw the new folder on the server.
We tried to pause-restart sync, restarted the client, checked testfolder as not synced, then re-enabled sync, waited a day, restarted server ... The folder was ignored by User2's desktop client while its parent folder said it is synced.
Eventually it did sync, when the problematic newly created folder was renamed...

### Steps to reproduce
Seems like these reliability issues randomly occur. I was not able to reproduce the original issue (sorry no log files for that). The second was on a test setup, so I have the log files - see bellow - but was not able to reproduce it with a second try.

### Server configuration
Operating system: Ubuntu 14.04 LTS 64-bit

Web server: 

Database: MySQL - 5.5.54-0ubuntu0.14.04.1 - (Ubuntu)

PHP version: PHP 5.5.9-1ubuntu4.20

ownCloud version: ownCloud 9.1.0

Storage backend (external storage): Apache/2.4.7 (Ubuntu)

### Client configuration
Client version:  2.4.0

Operating system: windows

OS language: en

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:/Program Files (x86)/ownCloud

### Logs
As I mentioned I have the log files for my tests only, where 2 users were used for tests. In the log file you can find the logs about the problematic folder "nerw" and file "moj prazni fajl"  created by User1 and which did not want to sync for User2 until it was renamed to "nerw rn".

1. Client logfiles: [User2 log file](https://gist.github.com/szakitibi/637b5cb7206477506c814ebecfe7844f#file-owncloudsync-log) |  [User1 log file](https://gist.github.com/szakitibi/77a39bcfba782fef4da9ea361968b22b)

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):  [owncloud.log](https://gist.github.com/szakitibi/f6796e1e704b1273c824843d38326779)

I had a bit of problem setting up the trusted domains for tests done locally, but still I hope the log files can help to figure out what causes these glitches in the sync process for windows client.

**Comment by arjones85** [comment]
Last night I ditched my Nextcloud installation and installed Owncloud 9 with Owncloud clients, and my syncing issues have been resolved so far.

Thanks!

**Comment by hodyroff** [comment]
@szakitibi if its not reproduceable I think we have to close for now. When you have something which can be reproduced we'll happily look at the details. Please always use the newest for reproduction 9.1.4 is already released.
@arjones85 Thanks for the update! Tell the world.

**Comment by secure11** [comment]
Having the same problem with NextCloud 11 latest release on CentOS 7, php 7.0, Apache 2.4.x. NextCloud client version 2.2.4 build 2 on Windows 7 Pro. User 1 in web interface changes name of picture nut.jpg to nut1.jpg. Never syncs to Windows client user 2. User 2 changes the name of another file in the local D:\nextcloud folder, changes hummingbird.jpg to hummingbird-change.jpg. User 2 in the web interface sees this change almost immediately. User 2 in the web interface or in the synced folder DOES NOT see the User 1 file name change from nut.jpg to nut1.jpg - ever... User 1 when logged into the web interface NEVER sees the changed name hummingbird-change.jpg that User 2 renamed. What and where are the log files I can provide you, also this is a test environment, I can provide you access to test?

**Comment by hodyroff** [comment]
Please reproduce with 2.3 beta and ownCloud 9.1.4. 
@rullzer maybe you want to triage.
