### ISSUE TITLE
Owncloud Windows desktop client and resuming interrupted uploads

### ISSUE THREAD

**Issue by arjones85** [owncloud/client#5524]
Hi,

What is the expected behavior for the Windows desktop clients and resuming interrupted uploads?

I was syncing 20 gigs of data last night (split across four 5 gig files) and my internet connection had a blip it in for a minute or so. After it came back and the client reconnected, it started completely over (after having done 13 gigs or so of it) instead of resuming from where it left off.

The cache chunks were there on the server, so I do not understand why it had to start over.

Is this expected behavior? Just want to know what my expectations should be for how the client handles interrupted uploads.

Thanks!

**Comment by hodyroff** [comment]
Expectation is that as the clients are using chunking it should resume. However the Windows Client is still 32bit and might have some special issues with large files. We are trying to get a 64bit client out right after the QT 5.6.2 update and 2.3 release. A complete over is strange as if a full file was transfered it should not repeat.

**Comment by guruz** [comment]
@hodyroff The issue with 32bit was about a large amount of files, not large files itself:) Large amount is highly improved on 2.3 because of lower memory usage, so we don't actually need 64bit client anymore.

@arjones85 Your intuition is correct, it should just resume from those chunks. Do you have any log information etc that can help us? Which client version are you using, which server version? The client should be able to sync 5 GB files.

**Comment by arjones85** [comment]
Stable 2.2.4 Windows client, 9.1.4 Linux server.

The logs have already been rotated out unfortunately, so I am unable to provide any more info than what I already have. Sorry :(

**Comment by guruz** [comment]
It could very well be that we (correctly or not?) interpret one of the things received from the network in a way that would us decide to delete the chunks and retry. Hm.
