### ISSUE TITLE
Cursor flickers and typing/mouse clicking is interrupted while syncing

### ISSUE THREAD

**Issue by davidak** [owncloud/client#5534]
### Expected behaviour
oc-client should run in the background and let me do my work :)

### Actual behaviour
while the client is running, periodically the cursor flickers and typing on the keyboard or clicking the mouse/touchpad is interrupted.

that is a really annoying behavior since written text or commands are fucked up.
I need to quit the client to work with my system like writing this bugreport.

i use this system about half a year now and always had this problem.

### Steps to reproduce
1. start oc-client
2. try to work
3. ???
4. typed characters don't appear on the screen

see this video: https://youtu.be/HRJV0dvj3sg

### Server configuration
Operating system: Ubuntu GNU/Linux

Web server: Apache 2.4.7

Database: MySQL

PHP version: PHP/5.5.9-1ubuntu4.19

ownCloud version: ownCloud 8.1.3 (stable)

Storage backend (external storage):

### Client configuration
Client version: 2.2.4-10.1 (official Ubuntu package xenial)

Operating system: elementary OS 0.4 (Ubuntu 16.04 based)

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): Gebaut von der GIT-Revision eaeed0 auf Feb 3 2017, 13:11:47 verwendet Qt 5.5.1, OpenSSL 1.0.2g-fips 1 Mar 2016

Client package (From ownCloud or distro) (Linux only): APT-Sources: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  Packages

Installation path of client: /usr/bin/owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

https://gist.github.com/davidak/e7173fef1d37c781019c1a44361fc066

2. Web server error log: i don't have access to it

3. Server logfile: ownCloud log (data/owncloud.log): i'm just a user here

**Comment by guruz** [comment]
Sorry, I haven't watched your video in full because it's quite long.
Of course the sync client should not influence the cursor like this.

We have some possible related issues: https://github.com/owncloud/client/search?utf8=%E2%9C%93&q=%22elementary+OS%22&type=Issues

Before we dig deeper do you want to try the 2.3 beta1? Thanks.
https://owncloud.org/changelog/desktop/

**Comment by davidak** [comment]
It is exactly this problem: https://github.com/owncloud/client/issues/5389

I'm happy to help by testing the beta!

**Comment by guruz** [comment]
@davidak ok.. please do =)

**Comment by davidak** [comment]
It's better. Like @fotastisch said in the linked issue, it happens every 30 seconds.

With 2.3 beta1 only very short, so when you are continously typing, every 30 seconds one character is lost.

Still not usable.

**Comment by guruz** [comment]
Please  report this upstream at the distro. :/

**Comment by davidak** [comment]
@guruz like @fotastisch said it also happens in other distros. it's coused by your app. don't happen when it is not running.

**Comment by fotastisch** [comment]
Hi!
Sorry, I was not yet able to test the beta, but would like to confirm that it's also happening in xubuntu. Not as bad, no characters are lost, but flickering occurs in the notification area. This behaviour does not occur when the owncloud client is not running.

**Comment by ogoffart** [comment]
Can it also be reproduced if  you set the environment variable OWNCLOUD_MINIMAL_TRAY_MENU to 1?

**Comment by davidak** [comment]
I started it using `OWNCLOUD_MINIMAL_TRAY_MENU=1 owncloud` and can't reproduce the problem anymore.

**Comment by ckamm** [comment]
@davidak Thanks for reporting your tests with the beta!

If this happens every 30s, then this is very likely caused by the qdbusmenu workaround that's active for Qt versions <5.6.0. It de- and re-registers the tray icon when the menu needs updates, up two every 30 seconds. (it's a workaround for a not-showing and not-updating tray icon...)

Could you try what happens with `OWNCLOUD_FORCE_QDBUS_TRAY_WORKAROUND=0`? I assume that gets rid of the stuttering? Unfortunately disabling this workaround is very likely to break the tray icon in some configurations. Does it continue working for your setup? (does clicking entries do something? does the "Recent" menu update? Do submenus work?)

Tray icons are extremely finicky, it's so frustrating. Maybe it would make sense to just have a list of broken configurations in the client and then start out with the minimal tray icon for those. We could have a "Enable full tray icon (unsupported, use at your own risk)" button, that pops up another warning dialog and enables the full tray. (/sarcasm)

@ogoffart Yes, this is probably pre-Qt 5.6.0-only.

**Comment by davidak** [comment]
>Could you try what happens with OWNCLOUD_FORCE_QDBUS_TRAY_WORKAROUND=0?

sure

>I assume that gets rid of the stuttering?

yes

>does clicking entries do something? does the "Recent" menu update? Do submenus work?

Clicking entrys and the "Recent changes" submenu works. When clicking on the tray icon it is empty sometimes.

![img_20170221_160009](https://cloud.githubusercontent.com/assets/91113/23170543/d41af068-f84f-11e6-91b0-443f735cdbd1.jpg)

>Tray icons are extremely finicky, it's so frustrating.

I see :(

What API do you use for the tray icons?

elementary has some recommendations about this topic: http://elementaryos.stackexchange.com/a/4227/115

>Do you see "Enabled QDBusPlatformMenu workaround" in the logs with 2.3.0beta1?
No

Everything is also true when i don't set this VAR. So maybe it is fixed in the latest build. I will let it run for some time and report back if i see any problem.

Currently i have the latest version 2.3.0~rc1-1.1 (build 2237)

> Gebaut von der GIT-Revision 639548 auf Feb 21 2017, 10:26:50 verwendet Qt 5.5.1, OpenSSL 1.0.2g-fips 1 Mar 2016
