### ISSUE TITLE
FRQ: Protection from depleting server when local storage is unmounted

### ISSUE THREAD

**Issue by daniel-hmc** [owncloud/client#5543]
For people like me who have the local file repository of owncloud on a removable drive (RAID system...), it would be good to have an option in the client similar to the existing option "Confirm if folders > X MB are downloaded":
"Confirm, if more than X files / X MB will be deleted on server".
Usecase:
If, for some reason, the removable drive is not available and owncloud client doesn't see its local repository anymore, it will probably (not tested!) delete everything on the server, too, as it probably assumes that all local files have been deleted.

**Comment by hodyroff** [comment]
Please test, such a warning is actually build in. If not yet perfect, please let us know in relation to the current warning. Warning is triggered if all files on the server or an external storage or all files on the desktop are deleted ...

**Comment by SamuAlfageme** [comment]
Hi @daniel-hmc! no worries! Since the unmount operation is not seen by the client as a deletion there's no chance it's commited to the server as so.

You can experience the same behavior if you move any of your local sync folders to another location since the client stops to track it's contents; in the future the possibility to point to a new  location will be available too: https://github.com/owncloud/client/issues/5387, e.g. to change a mounting point or move it to a bigger drive without downloading everything again.

[Version 2.3 (that you can try already)](https://owncloud.org/changelog/desktop/) would also bring the option to re-include folders that were unmounted after they're back online (see https://github.com/owncloud/client/issues/5317), so the behavior in this use case is smoother. 

Closing here, don't hesitate to reopen if you find a weird behavior on this operation. Thanks for reporting!
