### ISSUE TITLE
Use .gitignore files for sync ignore lists

### ISSUE THREAD

**Issue by TT44bb** [owncloud/client#5567]
So there is  #1558 for per folder ignore lists, but what I would like much more is if I could have the client read my .gitignore files. I already have ignore lists for stuff which shouldn't be synced, so why not use them? This would need to be a config setting, probably best not globally but per git repo.

**Comment by hodyroff** [comment]
Hm, what is the use case/benefit of using git and ownCloud Client in combination?! Trying to understand this generally as it seems somewhat mutually exclusive on first sight ...

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/2097

**Comment by TT44bb** [comment]
Oh, sorry, my search skills seem to be rusty.

@hodyroff Usecase is that personally I prefer git over owncloud sync, mostly because I'm often without good internet and git works decentrally (so when I sync my laptop with my desktop, I don't need to go over the server). But the university where I study offers free owncloud storage and I like to sync my work there just to have an additional backup copy.
Also, git isn't just for syncing but for version control, I like to be able to roll back...

**Comment by borisceranic** [comment]
Another use case: I keep all of my work folders checked out under ownCloud sync root (or, currently, under Dropbox sync root). I do this as a first level of "protection" against data loss. Files are synced pretty much instantly as soon as I edit them, so that I can recover latest version of files if things go south.

Git is used on top of ownCloud/Dropbox, because I am versioning files normally.

Automatic ignoring via `.gitignore` would be useful to me so that I don't have to specify folders to ignore in two separate places. I do not want to sync i.e. `node_modules/**`, `vendors/**`, `cache/**`, `var/**`, and so on, and all of these are already laid out in my `.gitignore` file.
