### ISSUE TITLE
Some HTML entities are not correctly displayed in Activity tab

### ISSUE THREAD

**Issue by ldmpub** [owncloud/client#5576]
The original file name is "Nom de l'applicationjpg.jpg" but in the activity tab, the ' character is not correctly displayed ;-(

![nom de l applicationjpg](https://cloud.githubusercontent.com/assets/1452146/23522330/cf0740a6-ff82-11e6-8f43-54e8bf0be9f5.jpg)

**Comment by SamuAlfageme** [comment]
Yeah, we discussed this some time ago but I can't find the original issue:

![html_entities](https://cloud.githubusercontent.com/assets/2644445/23542541/1b2b775c-ffee-11e6-9d5b-0555eae45310.png)

Server probably involved since I believe those file names are sent from there escaped when they shouldn't and I have seen problems with HTML entities there before.

**Comment by ogoffart** [comment]
They are HTML escaped in the JSON.  cc @PVince81 

We could workaround it by unescaping them anyway.

**Comment by ogoffart** [comment]
The subject of the activity is xml escaped from `ocs/v1.php/cloud/activity?format=json` is xml-escaped.  (When removing format=json, then it is escaped twice)

@DeepDiver1975  Is that how is it supposed to be? Should the client un-escape it?

**Comment by guruz** [comment]
@DeepDiver1975 ping..

**Comment by ogoffart** [comment]
Reported to the activity app as https://github.com/owncloud/activity/issues/614
