### ISSUE TITLE
Ubuntu package for owncloud-client-cmd has excessive dependencies

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5607]
We use QT-code also for the network stack. This pulls a certain list of QT dependencies.

But we should review why e.g. qtwebkit4 is pulled in. I believe this is unneeded in this case: 
See: https://twitter.com/thepanta82/status/841222975726735360 for a screenshot.

**Comment by panta82** [comment]
I guess I should have opened an issue like a big boy instead of whining on twitter :/

Some more information:

Here's my apt-cache policy for the `owncloud-client-cmd` package:

```
  Installed: (none)
  Candidate: 1.7.0~beta1+really1.6.4+dfsg-1+deb8u1
  Version table:
     2.2.4+dfsg-1~bpo8+1 0
        100 http://ftp.debian.org/debian/ jessie-backports/main amd64 Packages
     1.7.0~beta1+really1.6.4+dfsg-1+deb8u1 0
        500 http://ftp.us.debian.org/debian/ jessie/main amd64 Packages
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
```

I eventually installed the `owncloud-client` package from the owncloud repos:

```
  Installed: 2.3.0-1.1
  Candidate: 2.3.0-1.1
  Version table:
 *** 2.3.0-1.1 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/  Packages
        100 /var/lib/dpkg/status
     2.2.4+dfsg-1~bpo8+1 0
        100 http://ftp.debian.org/debian/ jessie-backports/main amd64 Packages
     1.7.0~beta1+really1.6.4+dfsg-1+deb8u1 0
        500 http://ftp.us.debian.org/debian/ jessie/main amd64 Packages
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
```

This one seemed to have less dependencies, although it still installed parts of X that I didn't feel I needed for pure CLI usage.
