### ISSUE TITLE
[owncloudcmd] the command-line client ignores the keychain entries

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5609]
This is a follow-up of the thread started on [central](https://central.owncloud.org): https://central.owncloud.org/t/owncloudcmd-on-macos-does-not-authenticate-automatically/6349 about a potential regression or just outdated docs. 

### Expected behavior
According to the ["*Credential handling*" section of the docs](https://doc.owncloud.org/desktop/2.3/advancedusage.html#credential-handling):

> `owncloudcmd` uses the credentials of the GUI synchronization client. If no client is configured

### Actual behavior
The client always asks for user/password combination, regardless of what was set on the GUI / present on the keychain.

### Steps to reproduce
1. Set up an account on the GUI
2. Try to sync the same account URL(*) from the command-line client.

*: *as after multi-account support, it's the only way to indicate the client which account we are referring to*

**Comment by phil-davis** [comment]
And you can have sync connections to different user names on the same server (URL) - I have that set up. So just the URL cannot (always) uniquely identify the sync connection to choose.
e.g. I have a "family" account that has all the "master" files for the family and share needed folders of that to appropriate family members. Since I am one the family also, the folders that I personally use a lot I have shared to account "phil". So "family" (the master copy of everything) and "phil" are both synced to my laptop.

**Comment by ogoffart** [comment]
owncloudcmd does not attempt to read from the keychain. The docs are just wrong. I don't think it ever did.
