### ISSUE TITLE
[Windows] [HiDPi] [Windows 10] Auto-Scaling broken

### ISSUE THREAD

**Issue by blizzard4591** [owncloud/client#5620]
### Expected behaviour
The owncloud client settings window and its content should scale with respect to the scale settings set in Windows 10 per monitor.

### Actual behaviour
The owncloud client settings window and its content do not scale correctly.

### Steps to reproduce
1. In my setup, two monitors are connected to the system. One has 3840x2160 pixels and is set to a 250% Scaling factor. The other monitor has 1920x1200 pixels and is set to a 100% Scaling factor.
2. Open the owncloud client settings window.
3. See that even when it first opens on the 4k display, the content is too small to read.
4. Move it to the smaller display. See that scaling changes, but not for the better.

See the attached Screenshots for better illustration. Notice the owncloud Desktop Icon on the (cropped) 4k screenshot. The taskbar is included in both pictures as a reference for the minimum required/expected font-size.

![owncloudbroken1920x1200](https://cloud.githubusercontent.com/assets/130480/23992672/19e32070-0a3e-11e7-98f4-079d652f4da3.png)

![owncloudbroken3840x2160](https://cloud.githubusercontent.com/assets/130480/23992543/9428bf8a-0a3d-11e7-9bed-e21fa4c87926.png)

### Client configuration
Client version: 2.3.0 (build 6780)

Operating system: Microsoft Windows [Version 10.0.14393]

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Not relevant.

**Comment by ogoffart** [comment]
I could not reproduce that problem on my VM.  I have tried opening onwlouc on both the 250% scaling or the 100%  and the behavior is the same, ownCloud is scaled appropriately.

It looks like Qt is taking the wrong default (not scaled) DPI. I guess in this case, https://codereview.qt-project.org/157173/ might help.

**Comment by blizzard4591** [comment]
Maybe the key issue here is the two different scalings being present, which would explain why replicating it failed for you?

**Comment by ogoffart** [comment]
I was trying with different scaling as well, but I was not able to reproduce.

It sounds like a Qt issue anyway that would need to be fixed upstream.

**Comment by raimund-schluessler** [comment]
It did work with older versions. Sadly I cannot say when it broke.

**Comment by miicha** [comment]
There is another way to produce a maybe similar font size problem:
I have the owncloud client running on a windows pc with two full HD monitors. Ich I connect via remotedesktop from a PC with a 4K monitor I get a lot of strange font sizes and scaling problems:

1. the table view shows a small font size when the whole name fits but when its too long, the font size increases and part of the name is clipped.

![owncloud client fontsize bug](https://user-images.githubusercontent.com/3731697/36917946-863738e0-1e58-11e8-9f38-d6d8c6ecb21d.PNG)

2. Fonts are partly to big for the container (actually they have the right size to read them comfortably) and are therefore cut off. On the other hand there is text that is much smaller and fits into the element but is hard to read.

![owncloud client fontsize bug3](https://user-images.githubusercontent.com/3731697/36917957-929058ce-1e58-11e8-8fc0-f093c77c54b9.PNG)
![owncloud client fontsize bug2](https://user-images.githubusercontent.com/3731697/36917941-8352ca7c-1e58-11e8-8bcb-f569e1e81c37.PNG)

Hopefully this behaviour points in the right direction... (otherwise I can also create a new issue)

**Comment by guruz** [comment]
We have a 2.5 daily build (=testing quality) at http://download.owncloud.com/desktop/daily/ownCloud-2.5.0-daily20180328.MSVC.106.msi .. this has a new Qt version that might fix it.
Please note that 2.5 is unreleased to far, so use at your own risk!

**Comment by miicha** [comment]
Tried ownCloud-2.5.0.9426-daily20180408-setup.exe and font size / scaling looks good now
Thanks
