### ISSUE TITLE
offer dl-link when sharing

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#5627]
When sharing a file with the desktop-client it would be nice to have also links with /download generated. A good option would be an extra button like the "copy link" button

See Screenshot:
![sc](https://i.imgur.com/XOINQHf.png)

**Comment by hodyroff** [comment]
hm, on first sight it sounds like an extra button which we need to explain to normal users while for the experts they can just append /download nd be done. Whom would this feature help for what pupose?

**Comment by MegaV0lt** [comment]
Make it optional, so normal user do not get bothered with it. Adding the /download manualy is just awful

**Comment by hodyroff** [comment]
Maybe a button on the left where you can click like the other two would work better? We could call it "enable direct download" but it makes only sense for files, or? And does it make sense in the Web Frontend and Mobile as well?!

**Comment by SamuAlfageme** [comment]
I agree having a shortcut for the direct download link is quite convenient for a super-common use-case (in fact @stkjj requested it also a couple of weeks ago). And having it on the web UI will be just as useful. It even works for whole folders, since appending `/download` to the sharing link will download the `.tar` contents.

**Comment by guruz** [comment]
Instead of the 2 current buttons we could have 1 button that opens a drop-down menu?

* E-Mail link
* E-Mail link  (direct file download)
* Copy link to clipboard
* Copu link to clipboard (direct file download)

**Comment by ckamm** [comment]
@guruz Sounds good to me. And the text on the button would be something like "Send link..."?

**Comment by hodyroff** [comment]
Related: https://github.com/owncloud/client/issues/5023
One dialog or seperate right clicks? Which one is easier to understand?

**Comment by guruz** [comment]
@hodyroff Right click? I mean a menu which opens on left click of a normal button.

**Comment by ckamm** [comment]
@hodyroff As far as I understand the "local link" doesn't belong into the "link share" section, because it's not about sharing externally by link. I think it belongs into the "share with users and groups" section of the share dialog?

This will probably confuse users. Maybe enabling and parameters of "share by link"/"share with users" and "copy/mail that link" should be decoupled? 

As far as I can tell we get the following options for the latter:

1. Copy link (accessible by local users only)
2. Copy link (accessible by local users only) with /download
3. Copy link (externally accessible)
4. Copy link (externally accessible) with /download
5. Mail link (accessible by local users only)
6. Mail link (accessible by local users only) with /download
7. Mail link (externally accessible)
8. Mail link (externally accessible) with /download

There are three binary choices:
1. "With local users" / "With everyone who has the link"
2. "oC website" / "Direct download"
3. "By email" / "Copy to clipboard"

**Comment by ckamm** [comment]
Here's a design change attempt:
![sharedialog](https://cloud.githubusercontent.com/assets/833306/24353827/b6dfafba-12ef-11e7-96f2-209631eb57d0.png)

Only small changes and cleanups. The list view is a placeholder for the current user/permission editing widget.

Clicking the link would bring up a dropdown with options "Open link in browser..." / "Copy link to clipboard" / "Copy direct download link to clipboard" / "Send link by email..." / "Send direct download link by email...". Since this is a bit surprising there should still be a push button (maybe slimmed down to a "..." button?) next to the link: that's not included in the image.

**Comment by SamuAlfageme** [comment]
@ckamm all those changes to simplify the dialog make a lot of sense, I left some more notes on the dialog redesign on https://github.com/owncloud/client/issues/5655, but maybe it's a bit _unrelated_ since it aims to the multiple sharing links integration.

**Comment by ckamm** [comment]
@SamuAlfageme Thanks for the note about there being multiple link-shares in the future. It makes a lot of sense to include that in the layout considerations. That said, I might make some incremental changes already.

**Comment by ckamm** [comment]
@SamuAlfageme @MegaV0lt @hodyroff If we really want to add this option, it could look like this:
![foo](https://cloud.githubusercontent.com/assets/833306/25435128/56b63a20-2a8f-11e7-8975-0221836d3d61.png)

Any comments?

**Comment by MegaV0lt** [comment]
For me it looks good

**Comment by ckamm** [comment]
Pull: https://github.com/owncloud/client/pull/5740
