### ISSUE TITLE
Share "local link" from the file explorer desktop menu

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5653]
Implement server permalink feature (https://github.com/owncloud/core/pull/24434) via context menu shortcut.

### Scenario: 

There's a file an user wants to point at to a colleague he's already sharing the parent directory with. Instead of generating a new shared link for the individual file, he can use a permalink to point to any file in the shared folder hierarchy: e.g.

`https://<server>/index.php/f/29` will always point to the same file on both accounts no matter if it's displaced within any of the file trees. 

An entry in the file explorer's context menu could be used as shortcut to directly:

* **Copy the permalink to the clipboard**: ("`Copy permalink`") 
* Open file in the containing folder context (file's row highlighted) ("`Open <server> in browser`")
    * Ideally for this, the automatic login (#633) should also be implemented for a better UX.

The permalink is available for both shared and non-shared files so should be available for both use cases.

**Comment by ckamm** [comment]
This topic was also mentioned in https://github.com/owncloud/client/issues/5627 .

The main complication I see is: How do we make clear that this "permalink" is something that is only useful for people who the file or directory is already shared with? I think that if we added the feature as suggested, people would try to give this link to other people and then be confused because it doesn't work.

**Comment by SamuAlfageme** [comment]
@ckamm oh, just saw https://github.com/owncloud/client/issues/5023 linked there, which means this is a duplicate 😓, will dump my input there and close here. 

And yes, the other day we discussed the same issue about the name of the feature. Different wording and placing sharing always before permalink could be some ways to point to the most common and less _power-userish_ use-case.
