### ISSUE TITLE
When syncing only a specific location, the content of the main folder is also synced

### ISSUE THREAD

**Issue by unalignedcoder** [owncloud/client#5656]
### Expected behaviour
If on first run I select on the cloud: main folder > folder-to-sync (removing the tick from the main folder)
and on the local computer I select: main hd > folder-to-sync
After syncing I expect the content of the two folders to be identical

### Actual behaviour
inside hd > folder-to-sync I find:
1) all the files (not the folders) in the main folder on the cloud
2) another folder named folder-to-sync with the content I wanted to sync

The only workaround is to remove the sync connection created at first run, and make a new one.

**Comment by SamuAlfageme** [comment]
@unalignedcoder Yup, this has been reported quite a few times already and IMO needs to be fixed. You can +1 on https://github.com/owncloud/client/issues/3664 and refer to https://github.com/owncloud/client/issues/3664#issuecomment-133367256 for the workaround to avoid this behavior. 

Closing here as duplicate. Thanks for reporting!

**Comment by phil-davis** [comment]
And if you have a good idea for my comment a little further down:
"If you/someone can think of good words to put in the "Skip folders configuration" button text that will help users to understand that they need to choose this if they want to sync various server folders to various places on the client, and that they add those syncs one-by-one after the wizard finishes, then great!"

because putting some (succinct) words on the wizard that could help people find their way would be useful.

The challenge is not to have those words confuse 90% of users who just want to click through the wizard and "sync all".
