### ISSUE TITLE
[Sparkle] After updating progress bar dialog doesn't close until main install dialog is closed.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#5768]
### Steps to reproduce

1. Install Macos desktop client.
2. When an update is suggested, update it.
3. Follow the default steps.

### Expected behaviour

Progress bar dialog closes automatically when finishing. Installation dialog remains open to be closed manually.

### Observed behaviour

Progress bar is around open until install dialog is closed manually. Feeling quite annoying because the little dialog cannot be closed manually and you need to look for the install one.

![screen shot 2017-05-12 at 10 08 19](https://cloud.githubusercontent.com/assets/9048796/25989414/4ea44ad8-36fc-11e7-9bd1-e4fcd0181b21.png)

Environment:
Macos El Capitan 10.1

**Comment by guruz** [comment]
How is the rest of the wizard during auto update?
Does it do things automatically?

**Comment by SamuAlfageme** [comment]
I think this happens with most `.pkg`s installed with Sparkle (need to find an app shipped that way tho) - the progress bar is there since the installer has not yet returned. 

There's also an option to run Sparkle on quiet mode: https://github.com/sparkle-project/Sparkle/issues/162 - might be handy, but not sure.

**Comment by TheOneRing** [comment]
No update in years.
I assume it is no longer an issue.
