### ISSUE TITLE
[2.3.3] [Linux] crashes when no X11 display can be opened

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5806]
https://software.opensuse.org//download.html?project=isv%3AownCloud%3Atestpilot%3Anightly&package=testpilotcloud-client
tested on Ubuntu 16.04

<pre>
$ env DISPLAY=BANG testpilotcloud
QXcbConnection: Could not connect to display BANG
Aborted (core dumped)
</pre>

I'd prefer a simple error message in instead of a core dump.

**Comment by ogoffart** [comment]
Anything that uses a QApplication will crash this way[1].  There is no way an application can work around that. (Unless we would use XLib ourself to try to connect to the server. But I don't think it's worth it.)

[1] https://code.woboq.org/qt5/qtbase/src/plugins/platforms/xcb/qxcbconnection.cpp.html#557


If anything, this needs to be fixed upstream in Qt.  (It could call exit(), instead of qFatal)

But People should not be running without an XServer anyway and so I don't think it's worth to spend time in improving this error
