### ISSUE TITLE
Elementary OS Loki 0.4 update to client 2.3.2 indicator icon missing, qt-4.8.7

### ISSUE THREAD

**Issue by DroWnThePoor** [owncloud/client#5807]
Title says it all, this is an issue I battled back on Freya as well, and was able to fix in various ways.
If anyone knows a way to make this work even with an older client, I'll gladly try it.

### Expected behaviour
Tell us what should happen

owncloud client should run with the indicator icon in the panel.

### Actual behaviour
Tell us what happens instead

client runs, without an indicator

### Steps to reproduce
1. Update to version 2.3.2
2. Run client
3. 

### Server configuration
Operating system: Ubuntu 14.04 lTS HWE stack

Web server: Apache2.4

Database: MySQL 5.5

PHP version: PHP 5.5.9 Zend Engine 2.5.0

ownCloud version: 8.1

Storage backend (external storage): N/A

### Client configuration
Client version: 2.3.2

Operating system: Elementary OS 0.4 Loki

OS language:

Qt version used by client package (Linux only, see also Settings dialog):Using Qt 4.8.7, built against Qt 4.8.7

Client package (From ownCloud or distro) (Linux only): ???

Installation path of client: /usr/owncloud-client

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

**Comment by SamuAlfageme** [comment]
Hey @DroWnThePoor, we've had many reports of this kind in the past due to broken or buggy packages from the distros. All those were the reason behind the Qt5 switch we did for https://github.com/owncloud/client/issues/5470. Now, in 2.3.3, we're packing our self-built version of Qt with the client and distributing those.

You can give a try to the first nightly releases for 2.3.3 from the links in https://github.com/owncloud/client/issues/5470#issuecomment-301756093 (If you want to preserve your settings and do it without interfering with your current ownCloud client you can always try the testpilotcloud edition). Hope this helps! 

Feel free to reopen if the problem persists.

**Comment by DroWnThePoor** [comment]
@SamuAlfageme I followed the link to the nightly repos, my concern is at the bottom of the page there are binaries and they show the version to be 2.3.2. Added the repo to my sources and all I got was and updated to owncloud-client-l10n launched OC and still no icon in panel.

**Comment by SamuAlfageme** [comment]
@DroWnThePoor here: https://gitlab.com/alfageme/client-linux-tests/builds/17491066 you can see how this repo: https://software.opensuse.org/download.html?project=isv%3AownCloud%3Atestpilot%3Anightly&package=testpilotcloud-client installs 2.3.3 version from git on current [`2.3`](https://github.com/owncloud/client/tree/2.3) branch on an Ubuntu 16.04. Don't worry about the versions that appear on the output of `apt-get` since we're reworking the build system and the schema might not be right.  

I've just tried to install that package on an elementary 0.4 Loki (64bit) and I can see it's using Qt5.6.2 and displaying the tray icon.

![screenshot 2017-06-01 10 26 55](https://cloud.githubusercontent.com/assets/2644445/26671188/e34cc774-46b4-11e7-83af-b1ea5ca779f2.png)

If you still can't get it to work I'd suggest performing a clean install, in case some qt4 is still being naughty there:
```
# apt-get purge testpilotcloud-client
# apt-get autoremove
# apt-get autoclean
# apt-get install testpilotcloud-client
```

**Comment by DroWnThePoor** [comment]
Okay so I want to install testpiloutcloud-client not owncloud-desktop-client? When you mentioned that package before it sounded like some kind of a test package that would leave my current client alone.

**Comment by SamuAlfageme** [comment]
@DroWnThePoor in practical terms, both packages are the same. Just the theming changes and respects your current ownCloud installation. But of course you can try as well the packages in https://software.opensuse.org//download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client to get the original theme. ^^

**Comment by DroWnThePoor** [comment]
@SamuAlfageme So I realize I'm very late to reply, but the testpilotcloud-client is now missing from that link, but I found this one https://software.opensuse.org/package/testpilotcloud-client, went ahead and downloaded 2.3.1 for 16.04 gonna purge and then install, Will report back. Also, when will I be able to move to a stable repository though?
