### ISSUE TITLE
Illegal instruction: 4 on older Mac hardware

### ISSUE THREAD

**Issue by gsberre** [owncloud/client#5808]
After building the 2.4.0 Mac Client on an iMac Intel Core i5 with Mac OS X 10.10.5 everything seems to work fine.
Except if I run this Mac client on older hardware configurations.
It crashes right after the setup fase on an Intel Core i3 and other older Macs.
So the crash occurs just before the actual syncing should take place.

The error is:
Illegal instruction: 4

On Intel Core i5 and higher everything works fine.

Any idea on what could be causing this?
Is there some build setting I should adapt?

**Comment by SamuAlfageme** [comment]
Hey @gsberre for such specific problems on the build, I'll recommend you to head over https://central.owncloud.org/ to ask the community. 

However you can always complement this issue with the crash report or stack trace of the program. And also, compare the library versions you've built the binary with and the ones loaded in those legacy systems. Retro-compatibility reasons are most likely the problem here.
