### ISSUE TITLE
 Cosing the connection wizard does not close the app

### ISSUE THREAD

**Issue by caco3** [owncloud/client#5817]
When you have a new installation (or no nextcloud.cfg), the client (2.3.1) will show a connection wizard.
When you close this client (top right x), the window gets closed, but the client continues running (there is still an icon in the systray).

I would suggest that in such case the app gets closed.
Else point 4 in https://help.nextcloud.com/t/how-to-migrate-your-owncloud-desktop-client-to-nextcloud/6808 will not work as expected!

Tested with the Nextcloud client 2.3.1 from http://repo.morph027.de/#nextcloud-client using Kbuntu

See also https://github.com/nextcloud/client_theming/issues/53

**Comment by SamuAlfageme** [comment]
Hey @caco3, the client running minimized in the sistray is, indeed, expected behavior. Imagine the scenario where the user wants to modify the client settings (e.g. proxy, excluded files and folders, bandwidth...) even before establishing a connection. 

> I would suggest that in such case the app gets closed. Else point 4 in https://help.nextcloud.com/t/how-to-migrate-your-owncloud-desktop-client-to-nextcloud/6808 will not work as expected!

That's an unsupported workaround to migrate accounts. I'm sure people in that post value your heads up 😉
