### ISSUE TITLE
Daily rebuilds of owncloud-client on OBS Debian_9.0 + Debian_9.0_update

### ISSUE THREAD

**Issue by kdslkdsaldsal** [owncloud/client#5836]
Seems there is something really strange going on the following OBS repositories of the sync client:

http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0_update/

Those packages are daily rebuild and have already reached ``2.3.2-1.20`` (note the 20). On each update the following is just updated in the ``/usr/share/doc/owncloud-client/changelog.Debian.gz``:

```
owncloud-client (2.3.2-1.20) stable; urgency=low

  * version number update by debtransform

 -- debtransform <build@opensuse.org>  Mon, 12 Jun 2017 03:22:43 +0000
```

I guess nineteen rebuilds since the initial release of 2.3.2 is not the expected behavior?

**Comment by michaelstingl** [comment]
@SamuAlfageme @jnweiger Please check.

**Comment by jnweiger** [comment]
The 2.3.2 codebase and all the build scripts in https://build.opensuse.org/package/show/isv:ownCloud:desktop/owncloud-client are unchanged for ca one month now. 
No rebuilds were trigggered from our side. What you see is automatic rebuilds triggered by the openBuildService, probably due to dependency updates or configuration changes. 
(the 20 rebuilds only happened for Debian_9 and Debian_9_update, all others remained are at first rebuild)
I have disabled rebuilding for now. @michaelstingl  please add a checklist item "Enable build in OBS" so that we don't forget to re-enable :-)

**Comment by guruz** [comment]
@jnweiger Close then?

**Comment by guruz** [comment]
@jnweiger @crrodriguez Is there still anything to do here?

**Comment by jnweiger** [comment]
Debian_9.0_update can trigger many rebuilds, whenever they add more updates. We have blocked rebuilds to avoid confusion. Closing.
