### ISSUE TITLE
[OAuth2] Integration with the branding options

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5914]
I'm currently collecting all the cases in the desktop client OAuth2 support testplan for: https://github.com/owncloud/oauth2/issues/63 and thought in opening a ticket for the branding integration with the alternative OAuth wizard:

> Some branding options alter the normal wizard flow, **skipping some pages or auto-filling some fields**. These have to be considered when using OAuth as authentication method.

So far, I think these are all:

- [ ] Authentication method: `Theme::forceConfigAuthType()`
    - Force http on OAuth2 server (normally is the opposite). - _Is even worth to consider?_
- [x] Server URL: `Theme::overrideServerUrl()`
    - Disable "Back" button on "Login in your browser" wizard's page.
- [ ] ~~User: `Theme::customUserID()`~~
    - ~~Send the branding-defined username on the auth. requests (ref. https://github.com/owncloud/oauth2/issues/48).~~

| Case | Expected Behavior | Actual Behavior |
|------|-------------------|-----------------|
| `Theme::forceConfigAuthType()` set to `http` | If the server offers both OAuth and basic http auth methods, the client chooses the one set | OAuth has always preference (?) |
| `Theme::overrideServerUrl()` set | Disable "Back" button on "Login in your browser" wizard's page. | ✅ "Back" Button disabled |
| ~~`Theme::customUserID()` set~~ | ~~Send the branding-defined username on the auth. requests~~ | ~~No username is set in all requests~~ |

Is there any more options that could collide with the new wizard workflow?  cc/ @ogoffart

**Comment by ogoffart** [comment]
@SamuAlfageme  the `Theme::customUserID`  is not the username, it is the "label" that is shown next to username field. eg, it replaces the string "Username".  That's usefull for branding to set another string such as "Email" or "ACME ID" instead. But is irrelevant as far as oauth2 is concerned, because that string should be on the theming of the server.

As for `forceConfigAuthType` to force http instead of oauth is worth considering. Altough this field is only used to force the config. So that means that if an organization wants to upgrade from shibboleth to oauth, they'd set "http" in there so we would switch away from shibboleth when upgrading the account.
So if we want to force http, we would need another theming option. But i'm wondering if that's any usefull for the theme to set that. If they don't want oauth, they can disable it on their server.  But there is already issue https://github.com/owncloud/client/issues/5848 to discuss that.

**Comment by SamuAlfageme** [comment]
Agreed, closing here in favor of #5848
