### ISSUE TITLE
Add context menu action to "open file in browser" to sync protocol and server activity

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6121]
Follow up from #5023.

What hasn't yet been implemented is to use private links to navigate from the sync protocol or server activity pane of the client to the web user interface.

Users should be able to right-click file entries in these views to get access to a "Open in browser" action.

There were also other tickets that suggested adding a context menu to the sync protocol view: #5982

**Comment by SamuAlfageme** [comment]
@ckamm we need to update https://github.com/owncloud/owncloud-client-binary right?

**Comment by ckamm** [comment]
Not yet, we'll need to do that when we're done with the shell integration additions of the same function for #5903

**Comment by guruz** [comment]
Works for me in protocol.
I guess it can't work in server activity as this is a text-only activity log with no real references to files..

**Comment by SamuAlfageme** [comment]
It's about time to close this one as well 👍 this works great now.

**Comment by jnweiger** [comment]
@guruz Improvement idea:
In the sync protocol view, double click on a File  brings up the file browser. A right click opens a menu with one entry. 'Open in browser'.
But for some files no clicking whatsoever works. It is not apparent when and why.

I suggest to make both 'open in local file browser' and 'open in web browser' part of the right click context menu. Would be much clearer which is which.
Files that were deleted currently do not react to neither double click nor right click. The context menu should also open for them, with grayed out entries, so that the user knows the right click itself is reliable.
Files in the 'not synced' tab could have the same context menu for consistency, but with either the local or remote entry grayed out as appropriate.

**Comment by guruz** [comment]
@jnweiger I agree with you about the graying out etc. Maybe create a new issue?
Which operation though would the double click be if there is no operation? Just no operation like currently?

**Comment by ckamm** [comment]
@jnweiger That makes a lot of sense, I'll move it to an issue!
