### ISSUE TITLE
Enhancement: sync each top-level directory to a different location

### ISSUE THREAD

**Issue by vivia** [owncloud/client#6143]
Hi,

I have two separate directories I want to sync with NextCloud and they have to reside in different partitions. However, the desktop client only allows me to select one folder that will be synced. Given that symlinks don't work either (I won't argue about that, I see there are good reasons for symlinks to not work), I'd like to suggest an alternative solution: For each top-level directory (like the built-in ones Documents and Photos) I'd like to be able to select a different local path.

**Comment by SamuAlfageme** [comment]
Hey @vivia thanks for your request! 

Actually, syncing multiple folders ("Folder Sync Connection") is possible with the sync client for a while now. However, the option happened to be disabled in the UI when using the default wizard config (caused by https://github.com/owncloud/client/issues/3664). This has been solved in the upcoming 2.4 release (see https://github.com/owncloud/client/pull/6032) - But you can also get it working on previous clients by doing: 

1. On the account wizard, select `Skip folder configuration`
2. Click on `Add Folder Sync Connection` and configure one local destination per remote folder 

See e.g. 2 different folders configured in 2 different partitions/drives: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/32502769-eed2cc8e-c3db-11e7-974d-ed0ba3bc5fa6.png"/>
</p>

**Comment by vivia** [comment]
Perfect, thanks for your quick reply! That's exactly what I needed! :)
