### ISSUE TITLE
OwnCloud Client Invalidating App Password

### ISSUE THREAD

**Issue by AdamDunn** [owncloud/client#6167]
I am using the Windows ownCloud client on a few machines along with ownCloud running on my own server. I have generated a unique app password for each client computer and entered them into the client programs. When I do this I can see in the Windows Credential Vault there are three entries created:
user:https://owncloud.mydomain.ca/:0
user_clientCertificatePEM:https://owncloud.mydomain.ca/:0
user_clientKeyPEM:https://owncloud.mydomain.ca/:0

For each of these, when viewing in the WinCredVault, the username field appears blank, the password is obscured dots, and the persistence is local machine.

This will work fine for some days or weeks (about a month is the max), and then suddenly ownCloud will pop up a message asking for a password, the user:https://.... credential will be gone, and the "App Password" entry for that computer on the web interface will be missing. I've suspected some kind of faulty interaction related to Windows Update, since it seems to happen overnight when Windows Update has been run automatically, though with Microsoft pushing out updates seemingly any day of the week/month, it's been hard to verify a correlation. No other password or credential that is stored in WinCredVault (such as MS Office 365 credentials or Visual Studio git credentials) will be invalidated, only the ownCloud credential.

I'm not sure where the password gets invalidated first: is it on the client, which fails to authenticate and then the server decides to wipe out that app password? Or does it invalidate on the server and when the client can't connect it decides to wipe out what was saved? Since they seem to happen at the same time, I'm not sure which comes first.

I've tried looking through the source code to figure out what's going wrong, but I'm not familiar with the code, or with Qt.

### Expected behaviour
An app password that is entered into the client program and then stored in the Windows Credential Vault should remain valid and used in perpetuity until the app password is revoked by an admin (me).

### Actual behaviour
An app password will be used for several days or weeks but then will suddenly disappear from the Windows Credential Vault and the app entry will disappear from the server, and a new one needs to be generated and entered.

### Steps to reproduce
1. Generate an app password and put it on a Windows client
2. Wait several days or weeks
3. Wake up to find the client asking for a password

### Server configuration
ESX appliance for ownCloud version 9.1.4

Storage backend (external storage): local

### Client configuration
Client version: 2.3.0

Operating system: Windows 7 64-bit

OS language: English

Installation path of client: c:\program files (x86)\ownCloud

### Logs
I don't have log files because I'm unable to pin down an exact time or reproduce at an exact time.

**Comment by SamuAlfageme** [comment]
Hey @AdamDunn thanks a bunch for reporting! Let's see:

> For each of these, when viewing in the WinCredVault, **the username field appears blank**, the password is obscured dots, and the persistence is local machine. 

Don't worry about the username being empty; I think that's a known behavior of the interface to the CredentialStore https://github.com/frankosterfeld/qtkeychain provides and does not have collateral effects. And since you mentioned:

> the "App Password" entry for that computer on the web interface will be missing

Your second guess:

> Or does it invalidate on the server and when the client can't connect it decides to wipe out what was saved?

Seems right, since there's no way to remove such password in the server **from the client itself**. It's more likely that the server is doing it so, forcing the client to ask for re-authentication (same as it happens when you change your password and restart). So question here remains about what can trigger an undesired app-password deletion. Maybe some cleanup cronjob? cc/ @PVince81

**Comment by xyGZen** [comment]
I have the same issue - happy to provide details but I see nothing in the logs.

**Comment by ogoffart** [comment]
Please reproduce the problem on the server bug tracker. (core components)
I don't discard the possibility that a bug in the client could cause it to forget the password. But if it dieapear from the server, it means it is the server removing it.  (And the client asks for the password because the server tells him that the password is wrong)

**Comment by guruz** [comment]
@xyGZen @AdamDunn Are you using any special authentication backends on the server?

Maybe @akallabeth has an idea if QtKeychain could somehow "forget" entries.

**Comment by ogoffart** [comment]
@guruz 
> [...] if QtKeychain could somehow "forget" entries.

Even if it did, that's not the problem here, since the entries are missing on the server.

**Comment by guruz** [comment]
> since the entries are missing on the server.

Oh.
Can https://github.com/owncloud/core/issues/26731 be related?

CC @PVince81
