### ISSUE TITLE
[FR] Better naming of description and extension name in OCOverlays_x64.dll

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6204]
Starting from https://github.com/owncloud/client/issues/6203
Installing ``ShExtView``, looking for ownCloud

![image](https://user-images.githubusercontent.com/3321281/33437142-4f182540-d5e7-11e7-92fe-01c12acdd33f.png)

![image](https://user-images.githubusercontent.com/3321281/33437149-537660c0-d5e7-11e7-9d88-38037982a702.png)

**Feature Request:**

The Extension Name should change from:
``Windows Shell Overlay Icon Handler`` to ``ownCloud Shell extension``

The Description should change from:
``OC Overlay Handler`` to ``ownCloud overlay Handler``

Not a big thing, but helpful when searching...

**Comment by mmattel** [comment]
To be found in:
shell_integration/windows/OCOverlays/OverlayConstants.h
shell_integration/windows/OCOverlays/OCOverlay.rc

**Comment by michaelstingl** [comment]
@mmattel At the moment those blurry names are intentional, because they aren’t fully branded yet. Imagine a sync client with the name „MyAwesomeCompanyCloudClient“, then it looks weird if regular users find „ownCloud“ there. 

As I understood, it would be necessary to build the Win client in MSVC on Windows to make the shell extensions fully brandable.

Related: https://github.com/owncloud/client/issues/2717

**Comment by mmattel** [comment]
@michaelstingl THB, the refrenced issue #2717 was updated a year ago... 
And https://github.com/owncloud/client/issues/5237 10 months ago.
IMHO the thing is that this will take another long time to be done. It is easier, because we are in deep debugging, to get the wording right and add a comment reminding for conditional compiling when addressing MSVC.

**Comment by guruz** [comment]
thanks for contributing
