### ISSUE TITLE
Not space enough for uploads, but server and user 200GB free and inodes 1% 

### ISSUE THREAD

**Issue by abkrim** [owncloud/client#6302]
### Expected behaviour
Sync files from cliente mac to server 9,1,4,2

### Actual behaviour
Stop working desktop client after latest update 2.4.0 build 8836 for MacOs  10.13.2 (17C88)

Not space enough for uploads

### Steps to reproduce
1. Update my client.
2. Stop working

### Server configuration
Operating system: Ubuntu 16.04.1 LTS

Web server: Server version: Apache/2.4.18 (Ubuntu)

Database:  10.0.31-MariaDB-0ubuntu0.16.04.2

PHP version: PHP 7.0.22-0ubuntu0.16.04.1

ownCloud version: 9.1.4.2

Storage backend (external storage): No

### Client configuration
Client version:   2.4.0 build 8836 

Operating system: MacOs  10.13.2 (17C88)

OS language: Spanish

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From ownCloud or distro) (Linux only):

Installation path of client: Default

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1.[ Client logfile: ](https://gist.github.com/abkrim/c27a3105877ea6ab6d59643d0e58049d.js)

3. Server logfile: [ownCloud log (data/owncloud.log)](https://gist.github.com/abkrim/7d03326d06632faa40dd1dc72fcda3cb.js)

NOTE: If upload files from browser any problem.

**Comment by abkrim** [comment]
Update server to 10.0.4
Same problem.

**Comment by SamuAlfageme** [comment]
Hey @abkrim thanks for reporting! By checking your client logs, I can see that you're trying to upload several `.htaccess` files; which the server does not support (see https://github.com/owncloud/core/blob/v10.0.4/apps/files/lib/Capabilities.php#L62) as they can pose a security threat for the server. 

Client behavior (reporting 507: insufficient storage) is explained in https://github.com/owncloud/client/pull/5748#issuecomment-299451865 and comes from the server. Will open a request issue on the core repo and link here. 

In order to get your client to continue syncing (by ignoring the 507 error code coming from the server) you can manually add `.htaccess` among the ignored files patterns on your settings.

**Comment by SamuAlfageme** [comment]
Core issue: https://github.com/owncloud/core/issues/30136

**Comment by ckamm** [comment]
@SamuAlfageme Great debugging! Unfortunately there's nothing the client can do when it sees the 507 but assume there's not enough storage. The core bug you linked should be sufficient to track this issue. Do you think this is severe enough to warrant reverting #5701 until the server issue is fixed?

**Comment by SamuAlfageme** [comment]
@ckamm yeah, 😕 I don't really know which is the best compromise solution to pick here; quoting (and backing) @ogoffart:

> Personally, i think it makes sense to remove it from the client's ignore list, and let the server reject it with an appropriate error.

There's no "appropriate error" from the server just yet. I don't know if the scope of https://github.com/owncloud/core/issues/30136 would be hard to implement; if that can happen before next client release (2.4.1) we may be able to hold the revert. cc/ @DeepDiver1975 and @PVince81 for their input.

**Comment by ckamm** [comment]
Currently there's confusing messaging for users with `.htaccess` files. I'm considering to add a special case for that for servers before 11.

**Comment by ckamm** [comment]
I'm seeing a 403 error with owncloud 10.0.3.
