### ISSUE TITLE
client side folder sync selection list, not updating after local and server side deletion

### ISSUE THREAD

**Issue by julesmoretti** [owncloud/client#6337]
### Expected behavior
Once server-side folders are deleted, the owncloud Client folder selection menu should update.

![screen shot 2018-01-26 at 10 25 45 am](https://user-images.githubusercontent.com/744300/35454862-9af5bd82-0284-11e8-8c42-f6d81d8b17dc.png)

### Actual behavior
The old folders are still listed even though both source and destination folders no longer exists

### Steps to reproduce
1. Create a series of folders on your desktop
2. Allow them to sync
3. open up the drop down to reveal folder list
4. delete the folders from your computer and check if drop down still has the old folder listed

### Server configuration
Operating system:
Not sure Drobo 5N version 2 Probably DroboAccess

Web server: Apache

Database: MySQL

PHP version: not sure

ownCloud version: 2.4.0

Storage backend (external storage): Drobo 5N

### Client configuration
Client version: 2.4.0

Operating system: Mac osX 10.13.2

OS language: Mac

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

**Comment by ckamm** [comment]
Indeed, the folder list is supposed to refresh on sync.

**Comment by julesmoretti** [comment]
Thank you @ckamm

**Comment by SamuAlfageme** [comment]
See it working as expected now; have to check a couple of state machines more (specially after the work in https://github.com/owncloud/client/issues/5809) and how they affect this view, but in general this looks bright.

**Comment by guruz** [comment]
2.5.0 beta1 is out :-)
https://central.owncloud.org/t/desktop-sync-client-2-5-0-beta1-released/14667
Everyone, please comment here if we can close this issue. Thank you.

**Comment by jnweiger** [comment]
### Linux Mint 19 aka Ubuntu 18.04

testpilotcloud version 2.5.0daily20180801 (build 9974)

let sync with demo.owncloud.org
using selective sync on all folders, then remove one folder on the server,
check if it disappers in the list.
OK

remove one folder on the client,
check if it disappears in the list.
OK

Move an enabled folder into another enabled folder
OK

Revert the hierarchy of two enabled folders **slowly**
 - web interface: create an empty folder in Documents called Empty.
 - owncloud client: Enable only Documents/Empty
 - mv Documents/Empty . ; sleep 10; mv Documents Empty  # sufficient sleep so that a sync run completes.
OK.
BUT: the new Empty toplevel folder is reported with (0B), which is no longer correct. the Empty/Documents folder contains ca
 35Kb)

Revert the hierarchy of two enabled folders **quickly**
 - Enable only Documents/Empty
 - mv Documents/Empty . ; mv Documents Empty

BAD: Stuck in an error state: See  https://github.com/owncloud/client/issues/6694
