### ISSUE TITLE
Import and Debug 

### ISSUE THREAD

**Issue by NguyenVanVuong** [owncloud/client#6432]
I can't not find the code to send user:pass to server !
Anybody cant help me find the code or import and build in QT Creater

**Comment by SamuAlfageme** [comment]
@NguyenVanVuong thank you for your report! It does seem like a question about the codebase rather than an issue with the client itself, please refer to [central.owncloud.org](https://central.owncloud.org/c/desktop-client) for community support and questions! 

We're also hanging out in IRC on freenode: #owncloud-client-dev
