### ISSUE TITLE
Local DELETE on server-locked resource 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6513]
@jvillafanez just showed me an _edgy_ case on which **the sync journal and local FS stay inconsistent**. It requires the file to be "locked" at the storage layer (e.g. **Windows applying a lock on a WND mounted storage**) - but IIRC it's the same as _erasing a file locally on a read-only share/mount_. 

### Expected behavior
I'd say the expectations would be to either:
- **Recreate the file on the local sync folder**: this is annoying for users that willingly want to delete the file locally: i.e. "ignore it" but keep the rest of the folder (so selective sync does not apply) -> server wins 
- **Blacklist the file**: so server-side ETAG changes on it do not trigger a re-download on the sync client since the entry is stale on the sync journal. (This would apply for read-only scenarios) -> client "wins"
- (Current situation) - Keep the DELETE instruction "queued" to be applied once the resource is unlocked. 

I'm tagging this as "Discussion" as I'm not completely sure which is desirable. 

### Actual behavior
403 on DELETE logged on the Not Synced tab. 

### Steps to reproduce
1. On the external storage WND run`notepad >filetolock`
2. Delete `filetolock` on the local sync folder
3. Observe the `Activity > Not Synced` tab

**Comment by guruz** [comment]
> 403 on DELETE logged on the Not Synced tab.

For something temporary, we'd better get 503?

> so server-side ETAG changes on it do not trigger a re-download

Why would the ETAG change? Or you mean for legitimate reason?

(I havent read the linked issues)

**Comment by ogoffart** [comment]
I don't understand the problem here, on the client side.
If the server tells that it is impossible to remove the file, we should indeed show that as an error to the client.

Or you think error to remove should be hidden?

**Comment by jvillafanez** [comment]
I think the problem is that the file is deleted in the desktop. Neither the deletion isn't prevented nor the file is restored after the deletion. In the long run, the user has a missing file in the desktop; the file is still showing in the server and can be accessed normally form the web UI or other clients.

**Comment by SamuAlfageme** [comment]
cc/ @DeepDiver1975 since he's doing `LOCK`-ing shenanigans lately and this will need to be handled eventually

**Comment by ogoffart** [comment]
If the rights of the file (as reported by the server) are set so deleting is forbidden, the client should restore the file.

**Comment by ogoffart** [comment]
I don't think there is anything a can do on the client side.
Should this issue be moved to the server repository instead?

**Comment by jvillafanez** [comment]
I think the global interaction is something like:
1. User deletes the file in his computer
2. Desktop sends the delete request to ownCloud
3. ownCloud forwards the delete request to the backend
4. The delete request fails in the backend because the file is locked
5. 403 HTTP error is sent from ownCloud to the client.

The question is what the desktop client should do in this scenario. Note that ownCloud allows the deletion.

If we consider that it's a temporary error (the file will be eventually unlocked), queuing the request could be fine, so no action needs to be done on the client's side.
My worry is that we don't really know how much time the file will be locked, it could take 5 second or 1 hour. While the request is queued, the user just see the file deleted locally but it's still accesible from the web UI.
Maybe the desktop should fail the request after X attempts and restore the file?

**Comment by guruz** [comment]
This sounds similar to the AMD-stuff that @DeepDiver1975 @butonic @ogoffart are working on. The client could get a reply that the operation is queued on the server and then polls if it succeeded.
https://github.com/owncloud/core/pull/31851

**Comment by ogoffart** [comment]
> Maybe the desktop should fail the request after X attempts and restore the file?

That does not sound like a good idea.  We would just be undoing changes the user did. And the user might not even realize.

While it is true we already do it for folder we do not have the permissions to remove, I think the situation here is different.

**Comment by ogoffart** [comment]
Closing old issue. This is just a server issue.
