### ISSUE TITLE
Increase chunked upload finalization timeout

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6527]
See https://github.com/owncloud/enterprise/issues/2480

Some server setups regularly hit the 5min timeout on the final MOVE or PUT. We don't like the large timeouts, but increasing it based on the size of the uploaded document seems like a required workaround until the processing is sped up on the server or, preferably, an asynchronous API is introduced.

Concretely: 5min + 3min/gb ? This is entirely made up and should be checked against data (@SamuAlfageme)

**Comment by SamuAlfageme** [comment]
@ckamm looks like a plan; as for the exact figures; I might poke some server devs. to benchmark the assembly step and determine some sort of estimate.

**Comment by SamuAlfageme** [comment]
I was just having a discussion with @butonic and he's also trying to come up with a solution for this at some level. Let's hold our horses - his solution might make way more sense wo/ going **full** https://github.com/owncloud/core/issues/12097

**Comment by SamuAlfageme** [comment]
Re-labeled since the patch has proved to be useful for the large file file scenario - but far from a complete compromise solution. 

Like @ogoffart points out in https://github.com/owncloud/client/issues/6527#issuecomment-389235016, it's sane to try keep the timeout reasonable. Thus the 30 min limit; if there's additional assembly delays (i.e. I/O load on the server, antivirus processing the assembled file before MOVE gets replied, etc.). 

Server support for server-to-client communication (e.g. https://github.com/owncloud/client/pull/6195) for async. ops. is required to get a reliable solution. I'll close here as the workaround does its job 👍
