### ISSUE TITLE
Don't sync lock and temporaly files

### ISSUE THREAD

**Issue by Matthias84** [owncloud/client#66]
OC currently even publishs .ext~ temporaly files and lock files. Please add a filter to avoid syncing this files, as they will change rapitly and spam the sync folder

**Comment by jnweiger** [comment]
Modern wopi installations introduce a lock visible in the owncloud server, while the file is being edited in e.g. office online.
This new type of lock is not a separate .$* lock file, but an attribute on the docx file itself.

IMO, clients should propagate the locked state properly. 

I neither see the occasional stale locks (due to networks separation or editor crashs) nor slow locks as blockers for this feature.
The first one is a false positive (err on the safe side, which is good) and should invoke some user interaction.
The latter one is a short lived false negative, that could bite on a very quick load-edit-save cycle -- as soon as the server notices two different locks from two different clients, it could inform the conflicting parties. 

A decent implementation would also notify to any editing client that e.g. the "ownCloud network locking manager" granted an exclusive edit token and will block other edits...
