### ISSUE TITLE
Sync client (1.2.5) ignores symlink files?

### ISSUE THREAD

**Issue by cthielen** [owncloud/client#665]
I have a ~/todo.txt that I symlinked to ~/owncloud/todo.txt but the sync client doesn't pick it up.

I did a touch ~/owncloud/test just to ensure the sync client was working and that file did sync.

**Comment by Morganlej** [comment]
+1 for symlinks. By dereferencing at client side. As it seem everybody here assume it should in the first place.  As said links are much used feature for people that really use *nix.  This is a reason we still use dropbox even for in-house files.

Use example: i want a current project shared to my laptop or a customer. I then just drag a link from that folder to the owncloud shared folder, done.  Easily done on several projects.  When i remove that link, content get deleted on wherever it was shared.

Now withoput this feature i need to move that folder with content to OC shared folder and symlink it back to where it really belongs (so local programs etc stil use files in the original place) then remember to move back.

**Comment by microchip8** [comment]
+1 for symlinks! :)

**Comment by vliegeois** [comment]
From what I see of ownCloud, this option is not needed since ownCloud is more powerful than Dropbox.
Indeed, you are not required to sync the root folder and to have it appear as a local folder.
So for instance, you are not obliged to have a ownCloud folder. This is the default but it's not obligatory.
Instead, remove the sync of the root folder and add manually the sync of some specific folders like the Documents folder. The name of this folder on the cloud can be different from the name on your machine.
Now, whenever you add a file to your Documents folder, it will be synchronised and you don't have to see that on the cloud this Documents folder is stored with another name in the ownCloud root.

**Comment by rolandixor** [comment]
This is a pretty critical feature, especially in cases where you have a defined structure on the client that would need to be duplicated just to sync it.

**Comment by eBug** [comment]
+1

**Comment by r00t23** [comment]
+1 for symlinks!

**Comment by captoriginal** [comment]
+1 for symlinks, too!

**Comment by rolandixor** [comment]
I wonder if Nextcloud will support Symlinks. Either way, they've done us a disservice, because now we must migrate :/

**Comment by dragotin** [comment]
ladies and gents.... please think again about the symlink thing. It makes things more complicated, more fragile, because link targets can vanish, loop and such, and as https://github.com/owncloud/client/issues/665#issuecomment-119616309 says, there are other options.

@rolandixor must migrate to what? Where is the client download button for nextcloud? We should not go this way in the bugtracker tough, rather let the socmedia peepz go on ranting...

**Comment by Morganlej** [comment]
For us who are used to symlinks the benefits are obvious.
We who use symlinks on ana daily basis use them because they solve a lot, easily, and we know how to use them.
As always, there are ways to foul up even without symlinks.
Symlinks is widely used, have been for long, time, and to say that specifically owncloud users can not handle that is not nice!

**Comment by danimo** [comment]
@Morganlej This is not an insult, but a result of a careful weighing of usability concerns. We're more than happy for a design document that proposes how to support symlinks in a non-confusing way for everyone, or at least "power users". So far we hadn't had any convincing suggestions, but I'm not saying they do not exist.

**Comment by nickmdowson** [comment]
Hi,
I would suggest one option, although it wouldn't solve everything that users after here, would be to allow users to select an individual file to be synced to the folder, for use cases where users don't want to move the file into a synced folder.

**Comment by scolebrook** [comment]
@Morganlej I use ownCloud to sync my ~/.ssh directory between multiple computers. Not just for keys but for the config file that defines shortcuts for all the servers I manage. I have two accounts setup in the ownCloud app. One syncs my entire account in the regular way, but I use selective sync to not sync the ssh folder from the server.

Then I have a second account setup in the client, but it's the same username and password so the same account server side. It just pairs the ssh folder in my account on the server with ~/.ssh. This is an alternative to using a symlink to to link ~/.ssh into my ~/ownCloud folder.

To me, it's cleaner. I don't need the symlink to tell ownCloud to sync a given local folder with a given server folder. That functionality is already built into ownCloud. But this is only a helpful solution if that's the only reason why you have a symlink. If you need symlinks in your file system for other software then this probably won't help you. But perhaps it might help others.

Keep in mind that in order for ownCloud to support symlinks, it has to be intuitive and simple to people who don't know what a file system is (99% of computer users despite using one every day) let alone what symlinks are. That's the challenge here, to make something that doesn't set up for failure those who are less skilled.

**Comment by codethief** [comment]
@scolebrook Why would those 99% of computer users use symlinks in the first place? I don't see the problem here. Just introduce the option to follow symlinks for power users that know what they're doing.

**Comment by scolebrook** [comment]
@codethief In light of the fact that ownCloud can already achieve the same functionality without the need for symlinks at all, there's the question of why spend the time to develop and maintain an additional option that achieves the same result via the filesystem rather than the settings window.

I'm not saying that there isn't a good reason to develop the feature in addition to what's already there. I'm just saying that in a project like this with limited resources there needs to be a good reason to take resources away from other features. If those features have a bigger benefit for more people then they should be developed first. Or vice versa.

And if it's determined that this needs to be developed ahead of other things then there are the considerations of exactly how to implement it. It's not a case of simply saying "just introduce the option". How will it work? How will it look in the ui? How will ownCloud detect and avoid loops of links? Will there be a limit on how deep the traversal of links should go? What happens if a target of a link disappears? Should ownCloud delete all files from the server that were behind that symlink? How will ownCloud handle symlinks to targets within the synced local ownCloud directory? What if a link target it removed due to selective sync on one computer, but still exists on another?

Symlinks work on one computer and they solve that problem well. ownCloud works across multiple computers and devices with multiple accounts on multiple servers and there are some fundamental differences here and every single one of them needs careful consideration and thorough testing. That's a lot of time to take away from other features to duplicate functionality that can be achieved with a couple of mouse clicks.

As @danimo said, this really starts with a design document. So someone who wants this feature developed needs to take some time to think through these scenarios and put together how they think this feature could work. Then as a community we can work through what if's and iterate on that design until something solid is produced. Only then have we reached square one and can consider actual implementation.

**Comment by codethief** [comment]
@scolebrook Thanks for your response! I understand a lot better now.

**Comment by doits** [comment]
I'm using owncloud to store a lot of my files and also program data. Some of those programs use (relative) symlinks, so I'd be happy if those were synced, too.

I'm sorry if it has been brought up like the following already (didn't find it in this thread though), but why not introduce symlinks - having in mind that only "power users" need them and "normal users" (99 %) will never have any symbolic links - like this:

- general:
    - store information on server that this file is a symlink with it's target (e.g. relative or absolute path)
- sync clients:
    - detect symlinks, do not dereference them for syncing
    - when syncing to a file system that does not support symlinks, simply do not sync them (ignore them, file is missing)
        - when a new file is created with the same name like an existing symlink on server, display a sync error telling "file exists on server as a symlink" and do not sync that new file
    - when syncing to a file system that does support symlinks, sync them and restore them exactly like they were (relative or absolute)
- in webui:
    - display a link with a different icon and it's target (relative or absolute)
    - that's it, you cannot click on it or so, it is just displayed, never dereferenced
- webdav: ❓ 
    - is there any spec how symbolic links should be handled in webdav?

By not dereferencing them it should be easier to implement this (but still hard, I know). Dereferencing is done on file system level by client using those files.

Of course with that solution you cannot simply drop a symlink into your owncloud folder and it will sync the linked object (only the symlink itself), but in my opinion the sync client should always sync exactly what I drop into the folder and not manipulate it in any way (e.g. on one device it is a symlink and on the other a regular file/folder which was dereferenced).

Was this way thought of already?
