### ISSUE TITLE
selective sync "Apply" stuck if another sync folder has error (missing)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#6675]
MacOSX, client 2.4.1.

I have several sync folders. One of them is "broken" because it is missing completely (let's call it folder X).

![image](https://user-images.githubusercontent.com/621965/43327979-2d221f4e-91bd-11e8-929a-13adf5f9fd51.png)

However, another folder is OK (just some unresolved conflicts):
![image](https://user-images.githubusercontent.com/621965/43328014-3f9764cc-91bd-11e8-8e96-aa40ce543271.png)

When I try to use selective sync on my OK folder I am not able to because "Apply" button seems to be stuck:

![image](https://user-images.githubusercontent.com/621965/43328080-67127910-91bd-11e8-84a2-f88ed2e2eeca.png)

Whenever I click "Apply" I see these error messages (related to the "broken" folder X).
So there is some negative interaction for Selective Sync between the two under the hood:

```
07-27 16:47:34:198 [ warning sync.database.sql ]:	Error: "unable to open database file" for "/.../X/._sync_b2f43b5ea209.db"
07-27 16:47:34:198 [ warning sync.database.sql ]:	CANTOPEN extended errcode:  14
07-27 16:47:34:199 [ warning sync.database.sql ]:	CANTOPEN system errno:  2
07-27 16:47:34:199 [ warning sync.database ]:	Error opening the db:  "unable to open database file"
07-27 16:47:34:199 [ warning gui.folder.model ]:	Could not read selective sync list from db.
```

**Comment by guruz** [comment]
@moscicki You can test this in a recent macOS 2.5.0 nightly.
E.g. https://download.owncloud.com/desktop/daily/ownCloud-qt5.10.1-2.5.0.10395-daily20180817.pkg

**Comment by jnweiger** [comment]
### testing macos 10.14 Mojave

ownCloud-2.5.1.10814rc2.pkg

connect one account to demo.owncloud.com -> sync folder ownCloud
connect another account to demo.owncloud.org -> sync folder ownCloud2

use a shell to `rm -rf ~/ownCloud2`

force sync on the second account, the red error message `unable to find local sync folder` appears as expected.

* click open the folder tree on the other account, 
* deselect e.g. the Documents folder. 
* Click `Apply`.
-> The subfolder `Documents` gets removed. -> OK

The bug seems to be fixed. 
However, after a few minutes the client crashes. 
![image](https://user-images.githubusercontent.com/1108546/48074562-7a447c80-e1e1-11e8-88d1-24334d61fb2a.png)

@guruz @ogoffart can we check if the crash is related?

**Comment by guruz** [comment]
@jnweiger will do tomorrow morning when crash log is parsed.

**Comment by guruz** [comment]
I can't find the crash yet. Did I mistype?
https://sentry.io/owncloud/desktop-win-and-mac/?query=d1ffff282634302915aede872181106

**Comment by guruz** [comment]
@ogoffart Why is this issue marked as resolved in sentry? https://sentry.io/owncloud/desktop-win-and-mac/issues/649245901/

**Comment by guruz** [comment]
@jnweiger FYI see @ogoffart 's edit. It's a Qt bug that is fixed in later versions. (because you asked about this issue in the call)
