### ISSUE TITLE
Don't rely on instance id oc prefix when parsing file id

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#6745]
See https://github.com/owncloud/client/issues/6742#issuecomment-416513772

In general the client could use the newer "oc:fileid" property and store it separately from the instance id.

If the instance id is needed, we could expose it as well in the capabilities if not already.

**Comment by ogoffart** [comment]
The client does only try to extract the fileid as a fallback, if the PROPFIND fails. or if the server do not support oc:fileid.  

Since what version of the server can we assume there exist oc:fileid?

https://github.com/owncloud/client/pull/5763#issuecomment-303646670  Discuss that we could use oc:fileid instead of oc:id in the database itself.

**Comment by PVince81** [comment]
The "oc" prefix exists since OC 6.

Any install that was setup before that, like mine, still have the old instance id as we don't regenerate it automatically as it could cause side effects.

**Comment by ogoffart** [comment]
But ince when do the properties `http://owncloud.org/ns:fileid` and `http://owncloud.org/ns:privatelink` exist?  Can we assume they are there on every supported server?

**Comment by ckamm** [comment]
The fileid is only extracted from the full id in this way if `fileid` and `privatelink` aren't available. (due to network errors or old servers). What we could do is use the first 8 bytes, instead of `^[0-9]*`

**Comment by PVince81** [comment]
using the first bytes could become unreliable once the fileid becomes longer, see https://github.com/owncloud/core/issues/26901

**Comment by ckamm** [comment]
This is only for the legacy codepath so I think it's low urgency. Nevertheless I will improve the heuristic for extracting the fileid from the id for the legacy case in 2.5.0.

In the future we should indeed think about migrating to just using the fileid instead of the id. This will likely need to be done over a long time period to ensure database interoperability: first start storing the numeric id as well in a separate field, then later drop the id. Currently there's no urgent need for it.

**Comment by PVince81** [comment]
Agreed about low prio. If the 404 is solved in 2.5.0 (I need to test it), then the problem will likely disappear

**Comment by TheOneRing** [comment]
Legacy private links where removed in 2.7
