### ISSUE TITLE
[v2.5.0 rc1] [Windows] Always build two MSis, one English, one Multilingual

### ISSUE THREAD

**Issue by mreichh** [owncloud/client#6769]
### Expected behaviour
* MSI should install via Group Policy without any further ado

### Actual behaviour
* MSI installation during boot is aborted (error code: %%1605)
* MSI of Owncloud version 2.5.0 beta2 works like a charme

### Steps to reproduce
1. Create new GPO and add MSI via _Computer Configuration -> Policies -> Software Settings -> Software installation_
2. Connect GPO to an Organisational Unit which contains a test client
3. run "gpupdate /force" within test client's CMD
4. restart test client
4. verify that Owncloud did not get installed on the test client and check Admin Events in Event Log for the error code named above

### Client configuration
Client version: v2.5.0 rc1

Operating system: Windows 10

OS language: German

Installation path of client: default

**Comment by guruz** [comment]
@dschmidt AFAIK the beta2 MSI didn't contain translations. The rc1 does. Does this play a role? I can't imagine other differences between the MSIs right now
(Can't verify this right now).

**Comment by dschmidt** [comment]
Hey @mreichh,

thanks for your valuable feedback.
There was indeed a slight difference in the way the rc1 was built. Due to a bug in the build scripts the beta msi did not contain the crash reporter, which was added back for rc1. The code path adding the crashreporter which was disabled before contained the bad conditional string shown by ORCA. I just triggered a new daily build that should have it fixed:
https://download.owncloud.com/desktop/daily/ownCloud-2.5.0.10550.10584-daily20180911.msi

(This build has no translations because they take a rather long time to build and I wanted to get out a fresh build to you as quickly as possible, as soon as a new build with translations finishes, I will replace the link)

**Comment by dschmidt** [comment]
If it doesn't fix your issue:

Was beta installation a fresh installation and rc an upgrade?

**Comment by mreichh** [comment]
perfect - the new build works like a charm, even for upgrading the previous beta. Thanks for that!

**Comment by guruz** [comment]
Superb :)
thank you @mreichh @dschmidt

**Comment by ingogoeppert** [comment]
I have the same problem (error 1605) with the released version ownCloud-2.5.0.10598.msi.
This version shows "Spanish" as language in the GPO.

The daily build, for example https://download.owncloud.com/desktop/daily/ownCloud-2.5.0.10680.10625-daily20180921.msi, installes per GPO without problems. This build shows English as language in the GPO. I don't know why, but it looks like multi-langiage MSIs can not be installed by GPO. If this ist the root cause, is it possible to provide a single language build to install per GPO?

**Comment by guruz** [comment]
@ingogoeppert Do you have more info like log output?

**Comment by ingogoeppert** [comment]
I enabled the debug log for the msi installer. I also have to set "Ignore the language", otherwise the GPO/Software is completly ignored on a Windows 8.1 x64 System with German language setting.

Here are the three logfiles I got:
[MSI668c.LOG](https://github.com/owncloud/client/files/2405899/MSI668c.LOG)
[MSI668e.LOG](https://github.com/owncloud/client/files/2405902/MSI668e.LOG)
[MSI668f.LOG](https://github.com/owncloud/client/files/2405903/MSI668f.LOG)

**Comment by mreichh** [comment]
actually optional German would be important for us.

**Comment by michaelstingl** [comment]
How do other projects handle this? Do they build 50+ installers?

**Comment by mreichh** [comment]
well, I'm not familiar with MSI technology in detail so I don't know. For ownCloud-2.5.0.10550.10584-daily20180911.msi German UI worked though.

**Comment by ingogoeppert** [comment]
>  How do other projects handle this? Do they build 50+ installers?
No. For example Kopano provides a english-only installer for GPO-installation and a multilingual installer for manual installation. This installer works also in a german Windows installation, no need to provide different installers. The software it self is multilingual in all installers.

**Comment by dschmidt** [comment]
https://download.owncloud.com/desktop/daily/ownCloud-2.5.1.10821.10745-daily20181016.msi
https://download.owncloud.com/desktop/daily/ownCloud-2.5.1.10821.10745-daily20181016.en-US.msi

https://download.owncloud.com/desktop/daily/ownCloud-2.6.0.10820.10744-daily20181016.msi
https://download.owncloud.com/desktop/daily/ownCloud-2.6.0.10820.10743-daily20181016.en-US.msi

**Comment by ingogoeppert** [comment]
Testet with https://download.owncloud.com/desktop/daily/ownCloud-2.5.1.10821.10745-daily20181016.en-US.msi. Works in our environment as expected :+1:

**Comment by jnweiger** [comment]
=== Tested by looking at the download mirrors
@dschmidt yesterday the daily build generated both daily20181016.msi and daily20181016.en-US.msi
today only daily-20181017.en-US.msi was generated.
-> FAIL

**Comment by dschmidt** [comment]
pfff...

FTR: that's because dailies had no translations enabled. That's also why daily builds could be installed via GPO before already. 
You enabled msi translations in dailies now and we should see both msis being built again.
(What I posted yesterday was triggered manually with translations enabled)

**Comment by michaelstingl** [comment]
> actually optional German would be important for us.

@mreichh Could you elaborate on your use case for a German-only MSI installer? Your non-English-speaking end users should never see/use the English-only MSI installer with automated GPO deployment. The client itself is always multi-language, also in the English-only MSI installer.

**Comment by mreichh** [comment]
sorry for replying so sluggishly, just havent found time to test the new builds till now! 

For GPO deployment https://download.owncloud.com/desktop/stable/ownCloud-2.5.3.11470.11300.en-US.msi now works like a charme, though the German MSI https://download.owncloud.com/desktop/stable/ownCloud-2.5.3.11470.11300.msi still does not. For me going with the English version is completely ok as after installation the Owncloud UI is in German resp. adapts to German OS environment.

Maybe I didn't really get the difference between both MSIs. Is it just the installer language? If so I think this really does not matter with regards to the silent GPO-based installation. Anyway, I'm now really fine with https://download.owncloud.com/desktop/stable/ownCloud-2.5.3.11470.11300.en-US.msi, many thanks for that!

**Comment by michaelstingl** [comment]
> Is it just the installer language?

@mreichh Yes, only the installer is EN-only. And in automated deployments, users will never have to read inside the *.MSI.

**Comment by guruz** [comment]
@michaelstingl @dschmidt Can we have a better name for the en-US MSI? something with "GPO" without "en-US"?

**Comment by michaelstingl** [comment]
I have no strong opinion. @guruz suggestions?
