### ISSUE TITLE
Failed to register module OCContextMenu.dll. HRESULT - 2147024770

### ISSUE THREAD

**Issue by rubenqo** [owncloud/client#6799]
### Expected behaviour
Installation of owncloud client

### Actual behaviour
Error message. Installation fails

### Steps to reproduce
1. Remove previous version of owncloud client
2. Download latest version and execute installer
3. Watch error message

### Server configuration
Operating system: 

Web server: 

Database:

PHP version:

ownCloud version: 

Storage backend (external storage):

### Client configuration
Client version: 2.5.0.10598

Operating system: Windows 8.1 Pro

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
> Remove previous version of owncloud client

Just curious, why did you go this route instead of letting the 2.5.0 installer call the previous versionuninstaller?

> Download latest version and execute installer

Does it work if you use the EXE based installer instead of the MSI?
https://download.owncloud.com/desktop/stable/ownCloud-2.5.0.10359-setup.exe

Does it work if you reboot after uninstalling the previous version?

**Comment by guruz** [comment]
CC @voroyam

**Comment by voroyam** [comment]
central topic:

https://central.owncloud.org/t/fail-to-reinstall-owncloud-error-messages-occur-applicatio-doesnt-start-propely/15766/8?u=dmitry

**Comment by dschmidt** [comment]
> Does it work if you use the EXE based installer instead of the MSI?
> https://download.owncloud.com/desktop/stable/ownCloud-2.5.0.10359-setup.exe

Yes, it would work. It uses the old build of shell extensions which was built using VS2012 (or something) which did not have the dependency on UCRT yet (and installs vcredist, more on that later).

> Does it work if you reboot after uninstalling the previous version?

Completely unrelated, different vs runtime, no ucrt involved.

> @dschmidt Just wondering.. you are writing:
> 
> > for the application itself we can ship it in the app directory, but it doesn't work for the explorer extension ... hence the error
> 
> Isn't this a OS-level installation? Can't we have the MSI somehow (remotely?) depend on this, have it download it from microsoft so it is done BEFORE the MSi attempts to install the explorer extension?

I couldn't even find a way to mark a certain Windows update a requirement for the MSI. 

There used to be so called merge modules for shipping the MSVC CRT but they seemed unsupported for some time, but they are apparently still a thing. IIRC I could not use them because we ship a 32bit MSI (although the shell extension is and needs to be 64bit) and the merge modules can only be used with their respective architecture. I was also reluctant to install vcredist as in the past it was claimed to cause trouble ... https://github.com/owncloud/client/issues/5632
The approach that would certainly work would be to wrap the .msi in a so called bootstrapper .exe file. But that's a lot of complexity for supporting outdated insecure systems :-\

I want to stress again: If your system is properly updated (and I'm not talking about the latest and greatest update that might eat your files), which you should *always* take care of, there is no issue. This only happens for utterly outdated system without the above mentioned updates, which are around for *years*.

**Comment by guruz** [comment]
@ogoffart @dschmidt FYI I thought why not link that MSVC CRT stuff **statically** in the shell extension instead of requiring the DLLs to be present?
As I don't see anything in shell_integration/windows/*/CMakeLists.txt this comes via the compiler... however:

https://msdn.microsoft.com/en-US/library/abx4dbyh.aspx
But this leads to other problems so we probably can't do it:
> if you have more than one DLL or EXE, then you may have more than one CRT, whether or not you are using different versions of Visual C++. For example, statically linking the CRT into multiple DLLs can present the same problem. [...] If your program is using more than one version of the CRT, some care is needed when passing certain CRT objects (such as file handles, locales and environment variables) across DLL boundaries. 

(We have 3 DLLs)

**Comment by dschmidt** [comment]
We could indeed try to statically link the ucrt into the shell extensions at least... will give this a spin.

**Comment by guruz** [comment]
@dschmidt If I read those Microsoft docs directly they recommend against it. If we pass any shared resources between the DLLs this might not work? (e.g. OCUtil and OCOverlays)..

**Comment by dschmidt** [comment]
@guruz yeah, not really recommended.
We could make ocutil also static and link it all together in two dlls: contextmenu and overlayicons.

It's not nice but it could help with the poor user experience right now...

**Comment by guruz** [comment]
```
shell_integration/windows/OCContextMenu/OCClientInterface.cpp:#include "CommunicationSocket.h"
shell_integration/windows/OCOverlays/stdafx.h:#include "CommunicationSocket.h"
```
But the function returning a HANDLE is only used from OCUtil.. good.

```
shell_integration/windows/OCOverlays/stdafx.h:#include "FileUtil.h"
```
FileUtil Doesn't return crt resources.

```
shell_integration/windows/OCOverlays/OCOverlay.cpp:#include "RegistryUtil.h"
shell_integration/windows/OCOverlays/stdafx.h:#include "RegistryUtil.h"
```
RegistryUtil Doesn't return crt resources.

```
shell_integration/windows/OCOverlays/OCOverlay.cpp:#include "RemotePathChecker.h"
```
RemotePathChecker Doesn't return crt resources.

```
shell_integration/windows/OCContextMenu/OCClientInterface.cpp:#include "StringUtil.h"
shell_integration/windows/OCContextMenu/OCContextMenu.cpp:#include <StringUtil.h>
shell_integration/windows/OCOverlays/OCOverlay.cpp:#include "StringUtil.h"
```
StringUtil Doesn't return crt resources.

But @dschmidt just mentioned that it's also about memory allocation (different heaps)..
I didn't see anything with this regard yet.

**Comment by guruz** [comment]
>  We could make ocutil also static and link it all together in two dlls: contextmenu and overlayicons.

@ogoffart Is there any reason it was decided to have a different file OCUtil.dll instead of just linking it as a lib statically or linking the .cpps into ContextMenu and OverlayIcons?

**Comment by ogoffart** [comment]
I don't know, this was not done by me.  I think statically inking should be fine.

**Comment by dschmidt** [comment]
Here is a test build: https://download.owncloud.com/desktop/testing/ownCloud-2.5.1.10932.10816-staticucrt.en-US.msi

**Comment by dschmidt** [comment]
Fix is merged for 2.5 and 2.6 master.

**Comment by guruz** [comment]
> Here is a test build:

@rubenqo Would you be willing to uninstall the Microsoft CRT/UCRT again and try the test build?

**Comment by dschmidt** [comment]
I assume this is fixed, at least we had no further reports since.
