### ISSUE TITLE
Assert/enforce don't trigger windows crash handler

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6823]
We'd like for asserts to produce stack traces for us, particularly ENFORCE in release builds, but currently I don't think they do.

**Comment by dschmidt** [comment]
Changing this is a bit tricky. Right now I don't think there's a really nice solution to this. 

The problem is that qFail calls [`qt_message_fatal`](https://code.woboq.org/qt5/qtbase/src/corelib/global/qlogging.cpp.html#_ZL16qt_message_fatal9QtMsgTypeRK18QMessageLogContextRK7QString) which in turn uses ``__fastfail`` if available to exit the application. We cannot catch that.

What we could do to prevent that is crash/abort/whatever in `mirallLogCatcher` like this for example:
```
static void mirallLogCatcher(QtMsgType type, const QMessageLogContext &ctx, const QString &message)
{
    auto logger = Logger::instance();
    if (!logger->isNoop()) {
        logger->doLog(qFormatLogMessage(type, ctx, message));
    }

    if(isFatal(type)) {
        Utility::crash();
    }
}
``` 
[``isFatal``](https://code.woboq.org/qt5/qtbase/src/corelib/global/qlogging.cpp.html#_ZL7isFatal9QtMsgType) is unfortunately private in ``qlogging.cpp``, that's why we'd need to copy that function to catch every possible `qFail()`, not sure that's worth it.

**Comment by guruz** [comment]
> not sure that's worth it.

I think we should definitely have that. We need them stacktraces!

**Comment by dschmidt** [comment]
Hehehehe, I meant copying isFatal completely .. but I don't care, we can do it.

**Comment by guruz** [comment]
`qFatal` on macOS triggers the crash reporter for me:
```
 void Application::slotCrash()
 {
-    Utility::crash();
+    qFatal("reason");
+    //Utility::crash();
 }
```

```
10-30 19:19:50:591 [ fatal default ]:	reason
m_crashReporterWChar: owncloud_crash_reporterDump file was written to: /var/folders/2h/s_3y89yd0677xfhfnzj5dg640000gn/T/738DCA9E-D525-4723-867C-5B00F8565403.dmp
```

**Comment by dschmidt** [comment]
Cool, thanks for investigating. Then the custom qFatal code can be ifdeffed for Windows only...

**Comment by ckamm** [comment]
By @dschmidt  in #6852

**Comment by jnweiger** [comment]
Do we know a nice way to trigger a fatal crash without modifying the code?
Signals, DLL poisoning, etc?

That'd be nice for testing the crash reporter behaviour.

**Comment by dschmidt** [comment]
We can add a menuitem just like the crash one...

**Comment by guruz** [comment]
Tested: We can see in sentry it works. Although that's very ugly to see Utility::crash.
Can we somehow "crash directly" in the frame before calling qFatal?
Or maybe we'd need to modify this directly in sentry-process-dump.py?
