### ISSUE TITLE
Already delted files on external storage , but the file still exist on local host

### ISSUE THREAD

**Issue by YTS85205107** [owncloud/client#6874]
**Expected behaviour**

I need to upload files to owncloud external storage and sync to others hosts , so that I can use files on different host.

When I delete file on folder of external storage , this file should be deteled on my local host.

**Actual behaviour**

When I deleted file on folder of external storage , after I use forced synchronization , this file still exist on my local host.

**Steps to reproduce**

But when I check and refresh my folder of external storage on owncloud website , 
I use forced synchronization again on my owncloud client , bounce out a window and ask me whether this file should be removed.

I checked many times , if I don't check or refresh my folder of owncloud website , this file always still exist on my local host.

**Server configuration**

Ubuntu 16.04
Owncloud 10.0.10

**Client configuration**

Owncloud client 2.5.1

**Other comments:**
Normally, a window will pop up asking if you want to remove the file , but the window not pop up , even if I use force synchronization , finally I refresh my folder of external storage on owncloud website , and use force synchronzation again , the window pop up asking if I want to keep or remove files.

Can you check why window can't popup , when I deleted files on external storage?

Thanks in advance.

**Comment by japerki** [comment]
Fraudulent emails


Sent from my iPhone

On Nov 11, 2018, at 10:27 PM, YTS85205107 <notifications@github.com<mailto:notifications@github.com>> wrote:


Expected behaviour

I need to upload files to owncloud external storage and sync to others hosts , so that I can use files on different host.

When I delete file on folder of external storage , this file should be deteled on my local host.

Actual behaviour

When I deleted file on folder of external storage , after I use forced synchronization , this file still exist on my local host.

Steps to reproduce

But when I check and refresh my folder of external storage on owncloud website ,
I use forced synchronization again on my owncloud client , bounce out a window and ask me whether this file should be removed.

I checked many times , if I don't check or refresh my folder of owncloud website , this file always still exist on my local host.

Server configuration

Ubuntu 16.04
Owncloud 10.0.10

Client configuration

Owncloud client 2.5.1

Other comments:
Normally, a window will pop up asking if you want to remove the file , but the window not pop up , even if I use force synchronization , finally I refresh my folder of external storage on owncloud website , and use force synchronzation again , the window pop up asking if I want to keep or remove files.

Can you check why window can't popup , when I deleted files on external storage?

Thanks in advance.

**Comment by ogoffart** [comment]
It looks like a server error which does not propagate the etags properly.

What external storage are you using?
Are you syncing the whole content of your owncloud, or only partial content?
What do you mean exactly by "forced synchronization"?

Also the client log files would be usefull.

> a window and ask me whether this file should be removed.

A window asking if a single file should be removed? I'm not aware of that. Perhaps are you talking about the popup that is shown when everything is removed.
Could you perhaps provide a screenshot?


> Can you check why window can't popup , when I deleted files on external storage?

The popup is only there if all files in the sync directory are removed or changed. If the external storage is a subdirectory, there will not be any popup.

**Comment by YTS85205107** [comment]
Hi , ogoffart

Thanks for your reply first.

My owncloud server information as below:
owncloud client (my computer in the office)
owncloud server (server in the office)
external storage (server room)

I setting external storage SFTP on owncloud , and I just only need to sync files , like html , excel ...etc.

When I delelted files from sftp server of server room , and I choose sync on owncloud client , then owncloud client display sync completely , but I still can find files on my computer , normally , files should be deleted from my computer , right?

> A window asking if a single file should be removed? I'm not aware of that. Perhaps are you talking about the popup that is shown when everything is removed.
> Could you perhaps provide a screenshot?
![owncloud problem](https://user-images.githubusercontent.com/32276008/48385241-a5225980-e728-11e8-89f7-bb09cc25a87d.png)

**Comment by michaelstingl** [comment]
The ownCloud server has to actively scan for changes on the external storages. See the docs: https://doc.owncloud.com/server/10.0/admin_manual/configuration/files/external_storage_configuration_gui.html#detecting-files-added-to-external-storages

**Comment by YTS85205107** [comment]
Hi , michaelstingl

Thanks your reply , I have already enabled this plugin , so that I can use external storage to sync files.

But my problem is files has delete from external storage , my computer still has this files , then a window popup asking me whether files will keep or remove until I login owncloud website and refresh external storage folder.

**Comment by michaelstingl** [comment]
I have no idea about the popup window, but to see changes you not only need the plugin enabled, you also need to regularly scan the data on the external storage.

**From the docs:**

> You might need to setup a cron job that runs sudo -u www-data php occ files:scan --all (or replace “–all” with the user name, see also Using occ core commands) to trigger a rescan of the user’s files periodically (for example every 15 minutes), which includes the mounted external storage.

**Comment by YTS85205107** [comment]
Hi , michaelstingl

Thanks your reply , After I set up crontab to scan occ, the deleted files can be automatically removed from local PC.

Thanks michaelstingl  and  ogoffart  !!!
