### ISSUE TITLE
Safely access and modify OwnCloud files from the server hosting the OwnCloud instance? 

### ISSUE THREAD

**Issue by MasonProtter** [owncloud/client#6886]
So I have a small OwnCloud instance hosted on a DigitalOcean droplet and I sometimes ssh into that droplet for computing on the go.

Ideally, I'd like to be able to open a file that's stored in the owncloud, modify it and have those changes be synced to my other computers.

What's the best way to do this? I'm uncomfortable just using root privileges to modify files inside ownclud/data directly (this also has the problem in that it seems to not sync new files created) but I also would ideally not want a full copy of the owncloud storage living in my home directory as that would double my storage needs.

Any suggestions appreciated.

The server hosting the owncloud instance is running Ubuntu 18.04 and has no desktop. It's a headless server.

**Comment by ogoffart** [comment]
Hi,

This is a bug tracker for the owncloud client,and is not a place for questions.
Please go to the forum instead:  https://owncloud.org/help/

To answer your question you can synchronize only part of your account with the owncloud client.  You could also use the web interface. Otherwise, owncloud uses the wedav protocol and you can access the owncloud content with any webdav client.
