### ISSUE TITLE
macOS Mojave with Dark Mode

### ISSUE THREAD

**Issue by btamas86** [owncloud/client#7025]
I upgrade client from 2.5.1 to 2.5.3 and UI is bad.
I use macOS Mojave 10.14.2 with Dark Mode.

My problem this:
![image](https://user-images.githubusercontent.com/4123828/52554831-62842200-2de8-11e9-948a-6811ffbe5bb4.png)
![image](https://user-images.githubusercontent.com/4123828/52555151-3321e500-2de9-11e9-9e23-1c8ef49447f5.png)

Fix please.
Thank You!

**Comment by ChrisEdS** [comment]
https://github.com/owncloud/enterprise/issues/3138

**Comment by guruz** [comment]
@michaelstingl @dschmidt This is maybe because you changed the macOS builder between 2.5.3 and 2.5.4 to compile with 10.14 SDK (new build machine>
Ref: https://bugreports.qt.io/browse/QTBUG-68850?focusedCommentId=408457&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-408457
> Once you do rebuild the app with the 10.14+ SDK, Qt will pick up the dark mode theme and look something like this: 

I guess the way forward would be to asap get Qt 5.12.1 for 2.5.4 and check that out.
(Currently 2.6.0 is on 5.12.0.. we should get 5.12.1 (ONE) though for 2.5.4)

**Comment by guruz** [comment]
@btamas86 Please try https://download.owncloud.com/desktop/daily/ownCloud-2.5.4.11337-daily20190219.pkg and report back

**Comment by guruz** [comment]
Please join discussion in https://github.com/owncloud/client/issues/7043#issuecomment-465448121 instead

**Comment by btamas86** [comment]
> @btamas86 Please try https://download.owncloud.com/desktop/daily/ownCloud-2.5.4.11337-daily20190219.pkg and report back

@guruz The main screen is now good, but top bar item title not perfect.

<img width="798" alt="kepernyofoto 2019-02-24 - 16 38 35" src="https://user-images.githubusercontent.com/4123828/53301412-d398f000-3852-11e9-90d6-39de369a1db6.png">
