### ISSUE TITLE
[Linux] Move + overwrite does upload + delete instead of server MOVE

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#7077]
### Steps

1. Create a file "b.txt" with contents
1. Wait for sync
1. Create a file "a.txt" with contents
1. Wait for sync
1. `mv a.txt b.txt`
1. Wait for sync
1. Check activity

### Expected result
Server MOVE

### Actual result
~~The file "b.txt" is first uploaded, and then "a.txt" is deleted instead of MOVE.~~
First "a.txt" is deleted and then "b.txt" is uploaded, instead of MOVE.

### Version
Observed on 2.5.1 by me and on 2.5.4 daily by @jnweiger 

### Env
My env is openSUSE Tumbleweed 20190126 with owncloud-client-2.5.1.10973-1.1.x86_64

Note: I don't think it's a problem with inotify as I only have about 1300 entries in my local folder.

@guruz

**Comment by jnweiger** [comment]
Reproduced with 2.6.0 master on ubuntu 18.10
using demo.owncloud.com with only its default set of files present. (certainly not exhausting inotify limits) - 100 % reproducable within 3 re-tests.


    sleep 100; cp Photos/Squirrel.jpg another.pdf
    sleep 100; mv ownCloud\ Manual.pdf another.pdf
    sleep 100; mv another.pdf nondestructive_mv.pdf

I am watching the F12 log to make sure the sleep 100 are sufficient delay for all sync activity to finish.
Result:
 * the fist mv results in upload and delete, as described by @PVince81 above
 * te second mv results in a rename, as expected.

![grafik](https://user-images.githubusercontent.com/1108546/54038426-d683d100-41c0-11e9-8249-32a28e1b4a57.png)

**Comment by guruz** [comment]
Is that because the FileId is not known yet?
The server used to reply the OC-FileId as header..
But if there is a sync in between, actually we should know the file ID from the sync. Maybe still a client bug then when messing around with SyncFileItem?

**Comment by jnweiger** [comment]
The client can easily detect that the file was moved by looking at the inode number, which remains the same despite the new name.

**Comment by jnweiger** [comment]
Also reproduced with client-2.4.2 ion Ubuntu 18.04

**Comment by ogoffart** [comment]
This has always been like that. We do the move detection only for new file.
I don't know why it is like that since this was designed before my time.

It is true that now, with the hashes on the DB, we could more reliably detect copies and move and that we could consider changing that in 2.6 by also doing the rename detection in this case.

**Comment by ckamm** [comment]
@ogoffart Do you see a reason we shouldn't trigger move detection if the local file's inode is different from the one in the database? I currently don't see why we shouldn't detect moves onto files that already exist.

**Comment by ogoffart** [comment]
No, i don't know the reason. Maybe it was simpler for Klaas to implement at the time with the old csync engine. 
But this could trivially be done now.

**Comment by joholm2** [comment]
Has anything changed since a year ago? We still have this problem.

I would expect for most users, this would be a critical issue.

If I rename a folder containing 2 GB of files the last thing I want OwnCLoud to do is upload them all again to a new folder and then delete the old folder; when all it has to do is a simple move.

But it more often does upload then delete everything in a folder if I rename it. Even worse the otehr clients ten get to download the files all over again into the "new" folder.

Below a simple description and our configuratoin details.

**Expected behaviour**
In Windows explorer I do any of the following in a synchronized folder…

Rename a folder
Rename a file
Move a file from one directory to another
All of these can be accomplished by a simple move operation.

**Actual behaviour**
Sometimes a “move” is used
More often files are deleted on the server and re-uploaded.
I see no obvious pattern in how it chooses what method to use.

I thought maybe it depended on file size, but even moving a large (500 MB file) into a sub-folder and later back resulted in a “move” on the sever (Ok) and later a totally unnecessary server “delete/re-upload” on returning to the original folder.

I also tried renaming a folder containing a large number of files amounting to 500 MB.It spent 20 minutes uploading them all, then deleted the ones already on the server.

This is very inefficient and there is no obvious reason for it

**Steps to reproduce**
Select a file in Windows Explorer
Drag to a sub-folder, observe Sync log and wait until idle
Select same file again and drag and drop back to original place, observe sync log
Repeat or vary file or folder until delete/upload is used

**Server configuration**
Operating system:Ubuntu 18.04

Web server: Apache/2.4.29 (Ubuntu)

Database: mySQL Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP Version 7.3.15-1+ubuntu18.04.1+deb.sury.org+1

ownCloud version: 10.3.2.2

Storage backend (external storage): SMB attached drive

**Client configuration**
Client version: 2.6.0

Operating system:Windows 10

**Comment by jnweiger** [comment]
@joholm2 your scenario is different. This issue is about a 100% reproducable misbehaviour triggered on linux. 
Your scenario is on windows, and -- at least for me -- hard to reproduce.
I was toying around with windows explorer as per your instructions and get reliable moves.
![image](https://user-images.githubusercontent.com/1108546/75073930-d2001780-54fa-11ea-8b35-ff6baaf7c187.png)

Please file a new issue. We have to understand your scenario in more detail, and also the scenario described here earlier. Mixing the two does not help.

**Comment by joholm2** [comment]
Sorry, it was the nearest match I could find. I deleted my post and will start again in a new one.

**Comment by TheOneRing** [comment]
The issue needs retesting

**Comment by TheOneRing** [comment]
Could that be the inode issue you recently rediscovered?
