### ISSUE TITLE
enabling permanent logging has no effect

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7146]
## tested ownCloud-2.6.0.11775.11588-daily20190411.GPO.msi with vfs enabled on win10

Press F12 or CTRL-L should open a log window. Instead we get

![grafik](https://user-images.githubusercontent.com/1108546/56049169-2bc77b00-5d49-11e9-859e-ea0a28efb814.png)

The folder remains empty even after repeated attempts of disconnet reconnect. 
Killing the client and restarting produces some fresh (and unrelated) logs though.

**Comment by guruz** [comment]
@jnweiger Can you also click "Schließen" for the dialog to have an effect?
@ckamm Maybe it should be modal then?

**Comment by ckamm** [comment]
@jnweiger The log window is intentionally gone. Were you using any command-line options to the client?

**Comment by jnweiger** [comment]
No command line options. Client started with double click. 
Without further info, users must regard the removal of the log window as a regression. I currently do, as it hinders QA.

**Comment by ckamm** [comment]
@jnweiger Could you elaborate on how it makes QA harder? 

The discussion around removing it went like this: We have this log window, but the live log view really doesn't work: Logs scroll by way too quickly, and when people copy&paste logs from there into issues we nearly always don't get the information we need because it doesn't keep enough history. Let's just drop it and make it easier for users to get full and useful log files without having to drop to the command line.

**Comment by guruz** [comment]
The only probable bug here is 

> The folder remains empty even after repeated attempts of disconnet reconnect.

**Comment by ckamm** [comment]
I've tested the following on windows and linux:
- Start owncloud without command line args, open log window
- Go to log dir, confirm it's empty / nonexistant
- Enable permanent logging
- Trigger a sync
- Confirm a log appears in the sync folder

It works for me. Could you double-check?

**Comment by ckamm** [comment]
Ah, it'd be good if it started logging without waiting for a sync run to trigger the next log file. Can fix that.

**Comment by HanaGemela** [comment]
Tested with 2.6.0alpha1 (build 11573) on Windows - logs are saved immediately after checking 'Enable logging' checkbox
