### ISSUE TITLE
Add "try again" option to windows updater dialog

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7217]
See https://github.com/owncloud/enterprise/issues/3278: if the updating process fails the users see a dialog and are redirected to the installation website. In many cases they just want to reattempt the update with the downloaded installer.

Previously the dialog would offer "Skip this version" / "Skip this time" / "Get update". After the change it would offer "Skip this version" / "Ask again later" / "Restart and update" / "Update manually".

**Comment by ckamm** [comment]
QA: See https://github.com/owncloud/client/pull/7218#issuecomment-500766596.

**Comment by HanaGemela** [comment]
1. no available update: no questions asked. - OK
2. available update, but no download url in update info: popup window to notify the update, allowing skipping, or going to the website with the update - FAILED ❌  currently it says you're up-to-date!

I'll continue testing tomorrow

**Comment by ckamm** [comment]
@HanaGemela The osx and linux updater implementations didn't seem to have a dialog like this (and I'm unaware of how exactly the SparkleUpdater works), so I thought this was only applicable to windows.

**Comment by michaelstingl** [comment]
Win updater and macOS updater are totally different, there's nothing shared between them. From what I know, the problem happened only on Win.

The Linux client doesn't have an update feature. It can only notify you, an update is available.

**Comment by HanaGemela** [comment]
Windows 10
Client 2.6.0alpha2 (build 12097)

1. no available update: no questions asked. ✅ 
2. available update, but no download url in update info: popup window to notify the update, allowing skipping, or going to the website with the update :x: it says no updates available
3. available update with download url: 

- updater is downloaded in the background (check AppData\Roaming\ownCloud) ✅ 
- notification about update on restart is seen
- on restart, updater is started :x: Updater says failed even though the new version has been installed 

If the updater is aborted, the new "updater failure" dialog comes up on the next start: :x: the message doesn't show what has been downloaded
![image](https://user-images.githubusercontent.com/49001702/61958773-4523c880-afc2-11e9-8b61-cc3a2f9316a7.png)

a) on "restart and update" the updater is started again ✅ yes, it has been started again :x: but the update in the end says FAILED even though the new version has been installed 
b) on "ask again" the "updater failure" dialog will come up again on restart ✅ 
c) on "skip" the update won't be mentioned anymore, the updater file is deleted :x: when I skip a version, the message in the client is 'you're
d) on "update manually" , the update url is opened - otherwise acts like "skip". ❓ What is the update url? https://owncloud.org/download/ so they can choose what they want? Or a direct link that will download the version users need?

**Comment by ckamm** [comment]
Thanks for the in-depth test @HanaGemela .

1. I'll attempt to reproduce "available update, but no download url in update info: popup window to notify the update, allowing skipping, or going to the website with the update x it says no updates available"
2. On "on restart, updater is started x Updater says failed even though the new version has been installed" what exactly says "failed"? Really the updater? Then it would be an updater bug unrelated to this change.
3. "the message doesn't show what has been downloaded" - I can figure this one out.
4. "x but the update in the end says FAILED even though the new version has been installed" - This sounds like it's the same as 2. right?
5. " x when I skip a version, the message in the client is 'you're" - I assume you mean "you're up to date". This is something this patch didn't touch and unrelated to this issue. We could indeed improve the wording there. Needs a new issue.
6. "on "update manually" , the update url is opened - otherwise acts like "skip". question" - There's indeed an inconsistency between "Update manually" (in update error dialog) and "Get update" (in update available dialog): Only the former behaves like "skip". The specific url is provided in the update info's "web" field and controlled by the admin.
  I'd propose to make "Update manually" open the url and behave like "Ask again later" otherwise.

**Comment by ckamm** [comment]
Okay,
1. I've tried again, it works for me. If I send `<downloadurl></downloadurl>` then the no-download dialog comes up for me. Can you try again, and then describe exactly how I can reproduce?
3. I've found the problem, there'll be a PR.
6. I've prepared a patch to remove the "skip" part of the button, will be in PR.

**Comment by HanaGemela** [comment]
@ckamm 
1. I've tried again and I got the update dialog. The options are Skip this version, Skip this time and Get update. Is that OK?
2.,4. Yes, I'll raise a new issue if it still happens with the next version
5. I'll raise a new issue
6. Thanks, I see where the url is from

**Comment by ckamm** [comment]
1.: Yes, that's the expected behavior (unchanged by this issue).

**Comment by HanaGemela** [comment]
@ckamm Updater is not working any more. I'm getting "unexpected character" error

**Comment by HanaGemela** [comment]
@ckamm @TheOneRing  There are still some issues with the online updater, see below

1. no available update: no questions asked. ✅ 
2. available update, but no download url in update info: popup window to notify the update, allowing skipping, or going to the website with the update ✅  ❓ are we happy with the wording 'Skip this time' and 'Skip this version'? 
3. available update with download url:

- updater is downloaded in the background (check AppData\Roaming\ownCloud) ✅ 
- notification about update on restart is seen
- on restart, updater is started ✅ 

❌ But the update shows 'Update failed' message even though it has succeeded 

If the updater is aborted, the new "updater failure" dialog comes up on the next start:
a) on "restart and update" the updater is started again ✅ 
b) on "ask again" the "updater failure" dialog will come up again on restart ✅ 
c) on "skip" the update won't be mentioned anymore, the updater file is deleted ❌ 'Update about to be installed' after next restart
d) on "update manually" , the update url is opened - otherwise acts like "skip". ❌  nothing opened when button clicked quickly

**Comment by HanaGemela** [comment]
@ckamm to make the requirement clear - there are two different dialogs. 'Update failed' is shown when the download url is wrong and then the new options are shown. When the download url is missing, I still see the old options. Is that right?

**Comment by HanaGemela** [comment]
When the download URL is wrong, it seems like I'm getting the 'Update failed' error because the file is downloaded in the background. So before the user even knows that there is a new version available and before they decide if they want to update or not, they get an error message that the update failed.

**Comment by ckamm** [comment]
@HanaGemela 
> are we happy with the wording 'Skip this time' and 'Skip this version'?

Not related to this issue.

> What notification? Update available? Update installed? Failed?

Once the updater has been downloaded a systray notification about the update should be seen. Something like "%1 available. Restart application to start the update."

>  But the update shows 'Update failed' message even though it has succeeded - I've raised a separate issue for this #7388
> nothing opened when button clicked quickly - separate issue #7389

Thanks!

**Comment by ckamm** [comment]
Correct, there atwo different dialogs. One is shown when there's no update download url, and the other is shown on update failure.

**Comment by ckamm** [comment]
@HanaGemela What exactly is still needed for completion of this issue? Do you want it to track #7388 #7389, #7390 ?

**Comment by HanaGemela** [comment]
"Try again" option has been added
Tested on Windows 20, client 2.6.0 beta1
There are many related issues that will be resolved in separate tickets
