### ISSUE TITLE
big folder warning appears only for small folders

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7252]
Done like this:
* In the general tab, set [x] Ask for confirmation before synchronizing folders lager than 10MB
* my syncfolder is /emco, it has a 1k text file, two PDF files and one subfolder images with 1.6GB of data
* wait until sync finishes.
* uncheck the selective sync button on the subfolder images. -> apply.
* it deletes 1.6GB from the disk. GOOD.
* check the selective sync button on the subfolder images. -> apply.
* it starts downloading the 1.6GB. No quesitons asked. Should'nt it?

While that download is running, I use the client's file manager to
* create a subfolder pdf in /emco, 
* move the PDF files into that folders.

When the sync finishes, I am presented with this screen:

![image](https://user-images.githubusercontent.com/1108546/59608259-433e2e00-9115-11e9-95d6-3fc48917678d.png)

Apparently it is asking me about the small 14MB, but did not ask about the 1.6GB ?

**Comment by ckamm** [comment]
How did you create and move the files to pdf/? In the server ui, on a different client connected to the same server or locally in the sync folder while the sync was running? I'm assuming it was one of the first two.

I think the idea was that the big folder warning appears for folders that are new on the remote. It does not apply to folders that the user explicitly opted in to in the selective sync settings. That's why you get asked about the new pdf/ folder (I assume it was a folder that the client saw on the server that wasn't local yet) and not for the images/ folder (you just clicked the checkmark next to "images (1.6 GB)" after all).

**Comment by TheOneRing** [comment]
@jnweiger could you answer the question above?

**Comment by TheOneRing** [comment]
Removed in https://github.com/owncloud/client/pull/11517
