### ISSUE TITLE
Inconsistent behaviour when deleting the only file in a folder

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7332]
Client: 2.6.0alpha2 (build 12128)
macOS: 10.14.5
Server: 10.2.1 (stable)

Steps to recreate:
1) Sync a new account
2) Delete everything apart from e.g. Photos/Paris. jpg
3) Delete Paris.jpg (note that user deletes a file inside a folder)
4) Select 'Keep' in pop-up message "All files in the sync folder 'ownCloud' folder were deleted on the server....".
4) Delete Paris.jpg again

Actual result: For the second time Paris.jpg gets deleted without warning. User has to delete also the folder Photos to get the pop-up message. 
The confirmation message is shown every time when deleting a file in the root directory.

Expected result: User is asked for confirmation if the last file should be deleted every time

**Comment by ogoffart** [comment]
I am having a hard time reproducing this.
For me the popup never appear if you leave an empty folder.

**Comment by ogoffart** [comment]
Ah, i can reproduce.

(This happen when the directory has CSYNC_INSTRUCTION_UPDATE_METADATA)

I could make this consistent by never counting the directory to count the amount of not changed files  (and always show the message)

However, I think in this case, if the user explicitly removed the last file, we should not show that message.  That message was mostly to prevent dataloss if ALL files got removed because the server was reset or something wrong happened on the file system.
This is heuristics based and has some false positive. But hiding the message would mean we could miss real case of problem.
So i think we should actually not fix this.

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/issues/7332#issuecomment-542246808
