### ISSUE TITLE
Windows - Remove virtual files options from owncloud submenu

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7400]
<img width="539" alt="Screenshot 2019-08-16 at 14 00 16" src="https://user-images.githubusercontent.com/49001702/63166705-7e82ad80-c02f-11e9-8e3d-fd6d74cf6b0d.png">

Current status and options to free up space and make always available locally in the owncloud submenu are redundant on Windows 
Please remove them 

Steps to recreate:
1) Right click on a file in File Explorer
2) Select owncloud submenu

**Comment by ckamm** [comment]
Please discuss with @jnweiger, he made convincing consistency arguments to bring them back. The flag `Vfs::socketApiPinStateActionsShown()` controls whether they appear or not for a vfs plugin.

**Comment by ckamm** [comment]
I don't think this should block 2.6.0.

**Comment by HanaGemela** [comment]
The reason to include this in 2.6.0 is not to disappoint users if we remove it later when they are already used to it. @jnweiger please approve the change :)

**Comment by michaelstingl** [comment]
I'm interested in the user feedback. I users miss it, we can bring it back anytime.

**Comment by ckamm** [comment]
A key point was that it's easier to document and explain and debug when all users see these options.

**Comment by jnweiger** [comment]
Consistency is an evil beast.

* Linux and Mac must have the vfs entries there, because the operating system does not provide any.
  On windows, users may ask, "why are the vfs missing from the owncloud submenue on this
   machine?" (Q1)  -- I'd like to avoid this question.
 
* iCloud and onedrive don't have the vfs entries in submenues, they rely on windows.
* Windows7 or any machine, where we fall back to placeholder: then we again need the vfs entries in the owncloud sub menu.
* having the vfs entries twice, can lead to users asking "what is the difference?" (Q2), even if they are identical and close together. -- Also something I'd like to avoid.

So we cannot be consistent in all dimensions simultaneously. 
What makes it worse: We are prone to language inconsistencies, as soon as we have the vfs entries in both the main windows menue, and the owncloud submenue. Our translations must be absolutely in sync with Microsoft translations, or users will ask "What is the difference"(Q3) - is is in my view worse than being inconsistent with ourselves.

When trying to avoiding these questions, for me Q3 has even higher prio than Q2 or Q1.
(Q1 would be higher prio than Q2, that is what I had discussed with @ckamm earler).

(So, sorry I am changing my mind because of Q3, which I had not thought of before.)
I'd vote for removing the vfs entries in the owncloud sub menu, if

* we know 100% that the operating system presents the same functionality in a nearby menue.
* we add some indicator to our submenu ( e.g. a small gray  "vfs integration active" ) instead.

**Comment by michaelstingl** [comment]
> * Mac must have the vfs entries there

macOS will have own native VFS implementation soon. Let's see how it looks there…

**Comment by ckamm** [comment]
I have flipped the switch that disables the ownCloud submenu entries for the winvfs plugin again. Is there consensus that there should be a "Vfs integration active" disabled context menu action instead?

**Comment by michaelstingl** [comment]
> Is there consensus that there should be a "Vfs integration active" disabled context menu action instead?

Could you post a screenshot? (I doubt this is something regular users will understand)

**Comment by ckamm** [comment]
@michaelstingl No. @jnweiger proposed "we add some indicator to our submenu ( e.g. a small gray "vfs integration active" ) instead." that replaces the "Currently...", "Make available locally" etc options.

**Comment by michaelstingl** [comment]
> ( e.g. a small gray "vfs integration active" ) instead.

I was thinking about making such a line more useful for users. Maybe add "Learn more…" at the end, and make it a link to the docs?

**Comment by ogoffart** [comment]
Is this fixed?

**Comment by HanaGemela** [comment]
Removed in 2.6.0daily20191011 (build 12493), Windows 10
