### ISSUE TITLE
Deal with unsyncable items

### ISSUE THREAD

**Issue by danimo** [owncloud/client#742]
This task tries to collect all reports related to unsyncable items trouble

Possible Approaches:
- Report unsyncable items
- If possible, exclude them from syncing

Related reports: 
- #60 (Loop in sync windows client when encounters files with path longer than MAX_PATH)
- #432 (File is put into a folder synced with 'Shared/'
- #474 (Folder whose names include ? character are not sync)
- #519 Adding file in read-only shares makes Mirall try to sync it indefinitely
- #520 Endlessly trying to sync data put in sync of /Shared

Possibly others.

**Comment by johansolve** [comment]
Filenames with forward slash on MacOS X is not at all unusual among regular users. It's problematic to not allow what the OS allows. The slash is transparently stored as colon ":" and displayed as / in the Finder. Conversely, the Finder doesn't allow ":" in filenames and has never done since that's the historical path delimiter in older (pre X) Mac OS. 
Why can't Owncloud simply sync files as they are stored, so "/" becomes ":" internally? That's what Dropbox does for example. It seems that the main problem is that Owncloud doesn't allow ":" in filenames. Maybe that is configurable.

**Comment by danimo** [comment]
@johansolve no problem, the 'real' character (at API level) is the ':', not the '/'. '/' is just what finder shows. We're dealing with it at API level.

**Comment by johansolve** [comment]
Excellent. Can the filename characer blacklist be configured @danimo ?

**Comment by LukasReschke** [comment]
Will be possible in a future release once https://github.com/owncloud/core/pull/14346 is available. In that case the server can support more characters when running on Linux. (and not Windows or some other OS that has some more forbidden characters)

**Comment by johansolve** [comment]
We can't go live with owncloud until we make it so that ":" (shown as "/" in Finder) is accepted in filenames. Just in my own set of project folders I have several "/" in folder names. Also other trivial characters like "?" and ">" are problematic to have excluded. Any pointers on how to change the filename blacklist?
