### ISSUE TITLE
Implement dynamic roles for server 10.3+ and oCIS

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7487]
Background is here https://github.com/owncloud/enterprise/issues/3473

Steps to recreate:
1) Connected to server 10.3+ and oCIS
2) Right click on a resource
3) Select Share from ownCloud submenu
4) Select Public links

Expected result: Roles are displayed instead of permissions

**Comment by pmaier1** [comment]
> Expected result: Roles are displayed instead of permissions

One clarification: It is expected that the client makes use of the new (10.3) roles API (if the capability is present) in order to fetch the available permissions/roles (for public links and user/group sharing) from the server and to display them dynamically.

The main reasons that the roles API was implemented are
- We added a new role for public links. Clients can't implement it statically because it's availability depends on the server they connect to (https://github.com/owncloud/enterprise/issues/3464).
- Since we have "Advanced Sharing Permissions" (10.2) server extensions may add permissions to user/group sharing. Implementing those in the clients has the same challenges as above.

This is also necessary for Android and iOS.

**Comment by michaelstingl** [comment]
"Hybrid approach" would be still a viable alternative:

- https://github.com/owncloud/client/issues/633
- https://github.com/owncloud/core/issues/5453

**Comment by ogoffart** [comment]
Note that there is a POC for the hybrid approach:
https://github.com/owncloud/client/pull/7564

**Comment by michaelstingl** [comment]
Replaced by:
- https://github.com/owncloud/client/pull/10241
