### ISSUE TITLE
Implement SSO for Windows (SSPI)

### ISSUE THREAD

**Issue by lmu-zz** [owncloud/client#750]
Hi,

It will be very helpfull to have a possibility from the sync client to use the Windows credential/password? (single sign on)

As example, I use Owncloud with the ldap feature (AD), the main objective is to have the same password for windows and Owncloud and also to change my password every 30 days. 

It’s quite a mess to have to change at the same time the password for Windows and for the client every time. It make sense to reuse the windows password as soon as we use ldap feature ….

Regards,
Laurent

**Comment by jekader** [comment]
It's actually quite trivial to make Apache HTTPD authenticate users using NTLM information (IE and Chrome on windows can pass NTLM auth to web pages in the same domain). I can document the process if you'd like so that we can see how this can be done on the desktop client. Pretty sure it can use the same Windows APIs that IE/Chrome use to achieve this.

I've successfully used this method to authenticate users in Nagios, Cacti, TeamPass and all sorts of other web apps. The only thing needed is to have an app that respects the REMOTE_USER variable passed by Apache. The app then queries AD via LDAP against this username to figure out access rights and voila: the user just opens a page and can see what he is allowed to see. No usernames or passwords to enter.

The basic steps for setting up Apache to get NTLM data from the client and pass REMOTE_USER var to the app are described here for example:
http://bloke.org/linux/ntlm-authentication-active-directory-on-apache-linux/

**Comment by danimo** [comment]
@jekader yes, but authentication for the webdav route (remote.php/webdav) is performed by ownCloud. You would need to create an AD backend that leaves the authentication to the web server.

**Comment by jekader** [comment]
@danimo Thank you for sharing the details. Indeed, this means the back-end must be adjusted first before any work can be done with the desktop client.

**Comment by TheOneRing** [comment]
We now support oauth with sso on the server side.
