### ISSUE TITLE
Please enable Debian 10 builds

### ISSUE THREAD

**Issue by wiene** [owncloud/client#7515]
On http://download.opensuse.org/repositories/isv:/ownCloud:/desktop a repository for Debian 10 is missing. Could you please enable builds for Debian 10. Thanks!

**Comment by olifre** [comment]
We'd also love to see this, Debian 10 is now out since quite a while, and OBS also supports it since quite some time. 
However, strangely, almost all owncloud client repos seem to be disabled on OBS, including Debian 9.0 - is this really intentional, or is the project migrating away from OBS? OBS usually takes care of rebuilding packages if core packages of the distro change AFAICT, by disabling the builds for repos, this automatic rebuilding is broken...

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Is there any new development here?

**Comment by michaelstingl** [comment]
2.6.0 RC's available for Debian 10:
https://github.com/owncloud/client/releases

Please test and provide feedback.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
There is still a dependency to `gnome-keyring`. There is no technical reason for this.

Please remove this dependency.

The problem is that if `gnome-keyring` is installed it asked me everytime for the master password when ownCloud starts. But I do not use this keyring for any application.

**Comment by michaelstingl** [comment]
> There is still a dependency to `gnome-keyring`. There is no technical reason for this.

Please open a new issue for this. Thanks!

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> Please open a new issue for this. Thanks!

https://github.com/owncloud/client/issues/7578
