### ISSUE TITLE
Add Folder Sync Connection - virtual files and selective sync available at the same time

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7553]
Client: 2.6.0rc2 (build 12577)
Server: 10.3.0 stable
macOS 10.15

Steps to recreate:
1) Go to Account tab
2) Click Add Folder Sync Connection
3) Click Continue
4) Select a folder with some subfolders and Continue 
5) Unselect some subfolders and tick 'Use virtual files'
6) Click 'Add Sync Connection' 

Actual result: All subfolders have been synced as Virtual files even though some were not selected to be synced in selective sync
Expected result: Until https://github.com/owncloud/client/issues/7320 is resolved, when ticking 'Virtual files', all subfolders should be automatically ticked as everything will be synced 

<img width="554" alt="Screenshot 2019-10-24 at 17 07 07" src="https://user-images.githubusercontent.com/49001702/67501137-09ad9e80-f684-11e9-83fa-6eb1fdb17ce9.png">

**Comment by ogoffart** [comment]
The meaning of the UI being disabled means it has no effect.
Virtual file ans selective sync are mutually exclusive.
So it is expected that everything get  sync'ed as virtual files.

Is the problem that the UI still show "unchecked" items?
Should we hide completely the Selective sync UI instead of disabling it?  Maybe we could collapse the root folder.  Or we could put the checkbox on the previous screen of the wizard.

**Comment by michaelstingl** [comment]
cosmetic issue, no priority
