### ISSUE TITLE
Data loss when switching on VFS for .owncloud files

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7557]
Similar to https://github.com/owncloud/client/issues/6953

Client: 2.6.0rc2 (build 12577)
Server: 10.3.0 stable
macOS 10.15

Steps to recreate:

1) upload the below files on the server 

```
test
test.owncloud
test.owncloud.owncloud
```

2) sync them to the client
3) turn on VFS
4) Account tab -> three dots menu -> availability -> free up local space 
5) Force sync

Actual files: One file is gone from the client, one file has lost its content, the third file test.owncloud.owncloud remain the same
Expected result: No data loss

**Comment by ogoffart** [comment]
I wouldn't call that as data loss since the data is still on the server and you get the data back if you turn off VFS again

**Comment by ogoffart** [comment]
When having files on the server named with the VFS extention, they are not properly synchronized to the client when using VFS. I'd say it is an expected limitation. I'm not sure what to do. I guess it should at least appear in the "not sinchronized"

**Comment by jnweiger** [comment]
https://github.com/owncloud/client/issues/7556 has a reproducer for the data-loss. We start with three files, then we have two files. I don't think that switching off VFS afterwards can recreate the third file.

**Comment by ogoffart** [comment]
So what should we do?

Suggestion:

1. If we detect such case, abort the sync and tell the user that virtual files cannot be enabled because there are files that ends with `.owncloud` in the sync directory.

2. Immediatly remove all the files that ends with `.owncloud`, as they are bining ignored from now on.

3. Leave it as is: the `.owncloud` files are no longer synchronized, but they are also ignored.  They can also be overwritten by an actual placeholder, which could be considered a dataloss if the file is not on the server.

4. Leave it almost as it, but do not overwrite existing file with a placeholder. Dehydrating or creating new placeholder for files with content would result as an error.

**Comment by HanaGemela** [comment]
Suggestion number 1 is the most user friendly as it explains to the user what is going on and there are no surprises or wrong assumptions what will happen to .owncloud files.
Basically I like the idea of having a message telling the user what turning on VFS means for .owncloud files

**Comment by ogoffart** [comment]
I actually went for option 4. in https://github.com/owncloud/client/pull/7562
There is still an error message that explains the problem in the not sync'ed dialog.

**Comment by HanaGemela** [comment]
Files are not deleted but they are ignored now in 2.6.1sprint2 (build 12978), macOS 10.15.2

<img width="1206" alt="Screenshot 2020-01-09 at 11 23 13" src="https://user-images.githubusercontent.com/49001702/72059551-8985f500-32d2-11ea-9ed0-6b788e5da8f7.png">

**Comment by HanaGemela** [comment]
@TheOneRing

**Comment by jnweiger** [comment]
Ignored is good in this case. That is in sync with the fix we have for #7556 !
