### ISSUE TITLE
VFS Windows - data loss when moving a file 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7558]
Windows 10
Client: 2.6.0rc2 (build 12524)
Server: 10.3. 0 stable

Steps to recreate:
1) Turn on VFS
2) Make a folder 'Always available on this device'
3) Make a file 'Available when online'
4) Move that file into 'Always available on this device' folder

Actual result: Sync in progress but it will never finish. When VFS are disabled, the file is gone 
Expected result: File has been moved and downloaded (got pin state from the parent folder)

**Comment by HanaGemela** [comment]
Logs shared

**Comment by HanaGemela** [comment]
Similar behaviour when adding a brand new file into Online only folder

**Comment by ogoffart** [comment]
Is it using the suffix VFS, or the windows integration?

I could not reproduced the bug with the windows integration.

**Comment by HanaGemela** [comment]
Windows integration

**Comment by ogoffart** [comment]
I tried many times to move files or directories around and i found nothing wrong.

However, analysing the log, i see something like 

```
10-28 14:12:26:019 [ info sync.discovery ]:     Processing "Photos/Squirrel.jpg" | valid: false/true/db | mtime: 0/1572253177/0 | size: 0/233724/0 | etag: ""//"" | 
checksum: ""//"" | perm: // | fileid: ""//"" | inode: 0/84871/ | type: 3/5/0
10-28 14:12:26:019 [ info sync.discovery ]:     Discovered "Photos/Squirrel.jpg" INSTRUCTION_CONFLICT OCC::SyncFileItem::None 5
```

(Is seems that Squirrel.jpg is being moved locally to Photos/Squirrel.jpg)

The conflict is strange. It seems that the problem comes from the fact that new local file is considered as download virtual file in `ProcessDirectoryJob::processFile`

https://github.com/owncloud/client/blob/318b6b00d8f3755639e2c199cc05524a91ae5258/src/libsync/discovery.cpp#L329-L340

Then later serverModified is probably set to true.
I believe that's where the bug is: it shouldn't be set to true if the server entry don't exist.

https://github.com/owncloud/client/blob/318b6b00d8f3755639e2c199cc05524a91ae5258/src/libsync/discovery.cpp#L627-L628

Which then trigger the conflict.

https://github.com/owncloud/client/blob/318b6b00d8f3755639e2c199cc05524a91ae5258/src/libsync/discovery.cpp#L806-L807

**Comment by ogoffart** [comment]
I made a PR but i was not able to test if it fixes the problem since i couldn't reproduce it myself.

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0daily20191030 (build 12597), Windows 10
