### ISSUE TITLE
Cannot update to Ubuntu 19.10

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7622]
Client: 2.6.0rc4 (build 1679)
Ubuntu 19.04

Steps to recreate:
1) Update to Ubuntu 19.10

Actual result:
<img width="643" alt="Screenshot 2019-12-02 at 16 58 33" src="https://user-images.githubusercontent.com/49001702/69974389-6f176980-1525-11ea-8b26-ef89529a253f.png">

Expected result:
Ubuntu has been updated

**Comment by jnweiger** [comment]
This is a dist upgrade from 19.04 to 19.10. 
It correctly complains about third software being not upgradable.

Background: SUSE OBS has distinct repositories per distribution and version.
Fixing this requires a change in repo-layout, so that multiple ubuntu versions share the same repo, and the installer can choose the one that matches.

We cannot change that on SUSE OBS, it would mean invistigate how to exactly create such an ubuntu repo.  This may or may not be possible for other systems besides ubuntu. Investigation also needed there.

**Comment by TheOneRing** [comment]
@HanaGemela @jnweiger I think this issue was fixed?

**Comment by HanaGemela** [comment]
Not fixed. Investigation needed if worth the effort

**Comment by TheOneRing** [comment]
Gone with 2.7?

**Comment by jnweiger** [comment]
Idea: For some Linux platform it is possible to put the current platform version as a variable in the .repo file. If we can uses this mechanism, then the client could update itself automatically to the new platform, when the platform gets updated...

**Comment by TheOneRing** [comment]
@dschmidt can we do something like that?

**Comment by fmoc** [comment]
There is no real "fix" for this issue, other than perhaps @jnweiger's suggestion. Upgrades of distributions like Ubuntu typically should disable all private repositories. I'm not sure this was done by the upgrade script here.

In any case, I'd consider this issue resolved for two reasons. First, AppImages are coming up as an official Linux distribution channel (see #5951). Second, Ubuntu 19.04 and 19.10 are long EOL now. We might try to reproduce the issue with an upgrade between, say, 20.10 and the upcoming 21.04, but I don't think it's worth the effort.
