### ISSUE TITLE
[2.6] Linux owncloud-client does not save password when restarted "unkwown error"

### ISSUE THREAD

**Issue by OlivierRaulin** [owncloud/client#7638]
Hi,
I just updated owncloud-client 2.6.0 on Debian Buster and am facing a very annoying issue which I think I found the cause (tl;dr libgnome-keyring)

At each start of the application, it tells me to enter password / application password for every of my account set up.

The error messays says "Error while accessing keyring : 'unknown error'" (I translated the first part from French, might not be exactly be the same in English)

When searching for similar bugs, I found some topics about ligbnome-keyring ... which has been removed from Buster.
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892359
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941821

I guess this might be the cause, but I cannot find a solution myself at the time.

### Expected behaviour
Owncloud client should have my passwords saved.

### Actual behaviour
Owncloud client asks me for my password at each start.

### Steps to reproduce
1. Install Debian Buster
2. Install owncloud-client
3. Configure an account and restart owncloud-client

### Server configuration (is not involved)
Operating system: 
Debian Buster 10.2

Web server: 
nginx + php-fpm

Database: 
mysql / mariadb

PHP version: 
7.3

ownCloud version: 
10.3.1-1+2.1

Storage backend (external storage):

### Client configuration
Client version:
2.6.0

Operating system: 
Debian Buster

OS language: 
French

Qt version used by client package (Linux only, see also Settings dialog): 
Cannot find it.

Client package (From ownCloud or distro) (Linux only): 
ownCloud

Installation path of client:
default

### Logs
[ info sync.credentials.http ]:	Backend unavailable (yet?) Retrying in a few seconds. "Unknown error"

[ info gui.account.state ]:	Fetched credentials for "https://[redacted]" attempting to connect

[ info gui.account.state ]:	AccountState connection status change:  OCC::ConnectionValidator::Undefined -> OCC::ConnectionValidator::CredentialsNotReady
[ info gui.account.state ]:	Invalid credentials for "https://[redacted]" asking user

**Comment by knight-of-ni** [comment]
According to Debian bug 892359 mentioned above, libgnome-keyring has been deprecated in favor of libsecret. Building the ownclient against libscret is the long term fix.

For those interested in a short term fix, you can manually download and install libgnome-keyring from the previous version of your Debian based distro. 

Since I am running Ubuntu 19.10, I downloaded these deb files from Ubuntu 19.04 and installed them from the command line:
```
libgnome-keyring0_3.12.0-1build1_amd64.deb 
libgnome-keyring-common_3.12.0-1build1_all.deb
multiarch-support_2.29-0ubuntu2_amd64.deb 
```

NOTE: libgnome-keyring-common and multarch-support packages only contain documentation files and are installed merely to keep the libgnome-keyring0 package from complaining about dependencies during installation.

Once the packages are installed, reboot (or logout). After login, you will be asked for your owncloud password one more time. The password will be saved in your keyring (verify using seahorse). You will not be bothered for your owncloud password again.

**Comment by OlivierRaulin** [comment]
Thank you for the advice, the problem was indeed solved by installing manually those 3 packages taken from Ubuntu repositories.

**Comment by knight-of-ni** [comment]
Yes, that's the short term fix. 

However, the real fix requires the owncloud developers to build against the libsecret library, or come up with another solution that does not rely on libgnome-keyring, since it is no longer available.  

IMO, this issue should remain open.

**Comment by michaelstingl** [comment]
2.6.0 should not have libgnome-keyring as a direct dependency. (see https://github.com/owncloud/client/issues/7578#issuecomment-550245556)

Related:
- https://github.com/owncloud/client/issues/7014
- https://github.com/owncloud/client/issues/7578

**Comment by knight-of-ni** [comment]
Excellent. Thanks @michaelstingl

**Comment by SpacyNG** [comment]
2.6.0 still produces this bug even without libgnome-keyring, but it seems to be fixed in the testing repo.
`http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing/Ubuntu_19.10`
Current version at the time of this writing is 2.6.1~sprint2+oc-1994 and this works nicely.
