### ISSUE TITLE
Potential data loss found in formal verification

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7658]
Although this paper focusses on dropbox, they also include a chapter on owncloud:
https://www.cis.upenn.edu/~bcpierce/papers/mysteriesofdropbox.pdf

They find a behaviour, where the client fails to detect a content change, as both mtime and size are identical.

Do  we know if this is fixed meanwile?

**Comment by ogoffart** [comment]
The paper does not mention what version of the client or sever was used.

They mention that the problem is the following:

> The ownCloud client uses a simple test for when a file has been changed and
> needs to be uploaded to the server: it checks whether either the
> file’s modification time or its length are different from their
> last seen values. But modification times are recorded in the
> filesystem with a 1-second granularity. So if the file is written
> twice in quick succession (i.e., during the same second) and
> the new contents is the same length as the old one, no change
> will be detected.

That's true, and this is why we wait for at least two seconds before synchronizing files. 
From 2.5 (i think) we check also the file's checksum if the server has it. (but if the server does not have a checksum, we indeed tends to resolve the conflicts if we detect a conflict and the size and mtime are the same as on the server.)
It could be that this was tried with an older version of the client, or the server, which did not do the checksum check.

---

They also mention another problem:

> (1) On the host, delete all the left-over
> directories from previous tests. (2) On each virtual machine,
> wait for the left-over directories to disappear. (3) On the
> host, create several hundred ‘fresh’ directories for the first
> few hundred test cases to use. (4) On each virtual machine,
> wait for all these new directories to appear. To our surprise,
> when using ownCloud as the synchronizer, step (4) often failed
> to terminate. On checking progress, we found that not only
> had the test directories not appeared on the virtual machines,
> but they had been deleted from the host! 

I don't explain that issue. We would have to try to reproduce it, but i can't think of a reason why this should happen.
