### ISSUE TITLE
Error message : don’t support NC version 18.0.1.3

### ISSUE THREAD

**Issue by F3000** [owncloud/client#7778]
does the windows client show this for all Nextclouds servers or is only the Nextcloud 18 version not supported until now ?

**Comment by michaelstingl** [comment]
Only ownCloud servers 10+ are supported. Older ownCloud servers or other backends weren't tested and can't be supported from ownCloud team. Also some security features like checksums for file integrity are missing. That's why the warning is shown. The error message could be more specific about the problems.

**Comment by F3000** [comment]
Ok thanks
