### ISSUE TITLE
Alias name unnecessary

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#783]
The »Directory alias name« for syncs is not really necessary and kind of confusing because it’s really just a label. But the important parts are already there: The remote path (or »syncing all your files« for simple sync) and the local folder.

Hence, the alias function should be removed altogether.

**Comment by guruz** [comment]
@jancborchardt @ogoffart @dragotin Please re-evalute/close this in context with the multi-account discussion
#43

**Comment by jancborchardt** [comment]
We’ll remove the alias when we also transform the »Add folder« wizard into  a simple dialog as discussed in https://github.com/owncloud/client/issues/2619

The alias can be abolished in favor of just showing the folder name (or path).

**Comment by guruz** [comment]
(Internal note: Beware that we so far expected aliases to be unique across everything (FolderMan, .cfg file etc) so we need to evaluate what to do there)

**Comment by jancborchardt** [comment]
Well, the folder path is also unique, isn’t it?

**Comment by ckamm** [comment]
I think a minimal version would look something like
* use the full path or some other unique string as the internal alias name
* introduce a folder display name that's automatically generated from the path (and considers the other folder paths to make it as useful as possible)
* show the display name instead of the alias name everywhere

That seems doable for 2.1.

**Comment by phil-davis** [comment]
Being fairly new to ownCloud I'll just say that I was confused by the ownCloud, ownCloud1, ownCloud2 thing also when I fired up the 2.0 client and had 4 accounts. For a while I went looking for where I could edit that so that something useful to me was displayed in that screen space. Eventually I found out that it is just a sequentially numbered thing that can't be edited. It therefore seemed odd to me to show such a thing to the user at all.
@ckamm suggestion above seems good. If there is some technical reason to keep something designated as "internal alias name" (e.g. because it would be a lot of work to get rid of whatever it is used for internally) then sure, keep such a thing - and maybe you do not even need to change that "internal alias name" at all. It can stay being ownCloud1, ownCloud2... Only techos will ever see it in config files, logs...
Generate the "folder display name" from the path in some sensible way that trades off short vs. useful. That can happen directly from the path without having to go through the "internal alias name" at all.

**Comment by jancborchardt** [comment]
Cool – great proposal @ckamm. Additionally we should remove all means of adding or editing an "alias" from the interface.

**Comment by guruz** [comment]
Some things done in 2.0 already: https://github.com/owncloud/client/issues/3576#issuecomment-130573468

**Comment by jancborchardt** [comment]
Great, thanks! :)

**Comment by guruz** [comment]
Closing this for now.. we did most parts of this which will be in 2.0.2
