### ISSUE TITLE
Deleted virtual file on macOS will never work

### ISSUE THREAD

**Issue by rsun-thoughtworks** [owncloud/client#8292]
**Notice** Android ownCloudv2.15.3 release 13511f58e works fine about delete virtual files.

### Expected behaviour
When I delete a virtual file in Finder, it will never show up again.

### Actual behaviour
When I delete a virtual file in Finder, it will show up again a few seconds after it was deleted.
### Steps to reproduce
1. Free space of a file to make it a virtual file.
2. Delete the virtual file
3. Wait for a few seconds

### Server configuration
Operating system:
Docker
Web server: 
owncloud/server:10.5
Database:
webhippie/mariadb:latest
PHP version:
owncloud/server:10.5
ownCloud version:
owncloud/server:10.5
Storage backend (external storage):

### Client configuration
Client version:
Version 2.7.2(build 2626) for macOS
Operating system:
macOS Big Sur Version 11.0.1
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):
-
Client package (From ownCloud or distro) (Linux only):
-
Installation path of client:
-
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by luan007** [comment]
Same here, OSX,
user hits delete on virtual files (intention = removal on server)
after sync the virtual file pops back.

Thanks!

**Comment by michaelstingl** [comment]
Current suffix based VFS on Linux and macOS has experimental status with some known flaws. The approached turned out to be a dead end, so it won't see any improvement. Can be done nicer in a macOS native VFS implementation, based on the FileProvider API. Sadly, no ETA yet.

Related:
- https://github.com/owncloud/client/issues/4341#issuecomment-521591814
- https://github.com/owncloud/client/issues/7859#issuecomment-626308898

Tracked here:
- https://github.com/owncloud/enterprise/issues/4676
- https://github.com/owncloud/enterprise/issues/4751
