### ISSUE TITLE
Fully disable conflict files?

### ISSUE THREAD

**Issue by racerxdl** [owncloud/client#8462]
I wonder if there is anyway I can fully disable file conflict and let the client *always* sync the local file to the server.

I'm using the owncloud mainly for backup, with a single user sending data to the server, to a single account.

**Comment by michaelstingl** [comment]
> I wonder if there is anyway I can fully disable file conflict and let the client _always_ sync the local file to the server.

What is the real-world problem you’re trying to solve? Please elaborate on your use case. I don’t get where the conflict files come from if there’s only a single user.

**Comment by racerxdl** [comment]
It does create conflicts with a single user. Specially with files that are being edited. I still not being sure why, but its a single instance of Owncloud client running on a file server machine, some times it gets a conflict file (looks like when the file is being used), its really annoying since no one edits the file in the owncloud server.

I primarily use this for backuping data "real time" for my customers server. More than half of them has at least one conflicted file per day.

Also one thing that's not very intuctive: It prioritize the **server side copy** of the file, not the local one. So the renamed file is always the local one. It would solve the issue if the conflicted copy file is the server one and not the local (since then I could just tell them to erase the files)

**Comment by jnweiger** [comment]
Yes, currently "server priority" is hardcoded with conflict resolution.
A client_conflict_polity setting would be nice, indeed!

But I am curious to learn more how users create conflicts with themselves.
I know one scenario: 
* client machine A gets restored from backup without setting the timestamps correctly into the past.
* client machine B is happily syncing edits to the server, until machine A connects to the server and propagates new files that are actually old.

**Comment by racerxdl** [comment]
I would say it might be a race-condition. Some applications (like office) can trigger some filesystem race conditions if the lockfile is ignored (which owncloud does). That's why the lockfile exists at all. I noticed is always in a excel, word or anything from office package that gets conflicted. Never in images, zip files or so. Even with customers that does edit images and hit Ctrl + S like crazy.

**Comment by TheOneRing** [comment]
> 
> 
> I would say it might be a race-condition. Some applications (like office) can trigger some filesystem race conditions if the lockfile is ignored (which owncloud does). That's why the lockfile exists at all. I noticed is always in a excel, word or anything from office package that gets conflicted. Never in images, zip files or so. Even with customers that does edit images and hit Ctrl + S like crazy.

So I assume you are on a unix system because on windows file locking works.
Please fill in some information about your system.

**Comment by racerxdl** [comment]
@TheOneRing nope, its a Windows Server 2012 R2. The owncloud server runs on a linux instance, but not the client. The client is a windows server (some of them are Windows 10, but the problem happens the same).

It is just a standard NTFS system. The windows file locking works for writing, but you can read it anytime you want.

**Comment by racerxdl** [comment]
Also just a thing to mention: The Filesystem Watcher from windows reports everytime a file is saved, even if that file is locked.

**Comment by TheOneRing** [comment]
Your right we read most locked files. Depends on the kind of locking used.... (if shared read is allowed we do so).

We should generate a script to reproduce your race condition to see whether we can improve the behavior.

**Comment by mdaeron** [comment]
This exact issue regularly bites me, with potentially ugly consequences (silently erasing large chunks of a manuscript draft). For context:

+ ownCloud 3.2.1.10355 [9724d6]
+ Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
+ Using virtual files plugin: suffix
+ osx-21.4.0

When I'm writing a scientific paper using LaTeX + Python code, frequently switching between different branches, for whatever reason I often realize that some sync conflict has happened (perhaps as a result of alternating online/offline work) at some point in the past. I only have one OwnCloud client running on a laptop because it gives me online access to my files from everywhere if needed, so I *always* want to keep the local copy in case of conflict, because it is always the latest version, with text/code that I just spent time working on. What happens is always the opposite (server copy silently replaces local copy), for the implementation reasons explained above.

When I'm lucky, I realize what has happened soon after the sync conflict and I simply waste half an hour `diff`-ing my way back to productive work. When I'm not, I have to start over from scratch, after hopefully identifying the missing bits.

What would really help users like me is more customizable sync conflict resolution defaults ("always trust local copy" would be hugely useful). That alone would remove a huge amount of friction from OwnCloud in my experience.
