### ISSUE TITLE
Desktop Sync Client forced reboot with uninstall exit code 1641 when using SCCM Application

### ISSUE THREAD

**Issue by codaamok** [owncloud/client#8497]
### Expected behaviour
Uninstall without a forced reboot when uninstalling using SCCM

### Actual behaviour
If initiating an uninstall using an [SCCM Application](https://docs.microsoft.com/en-us/mem/configmgr/apps/get-started/create-and-deploy-an-application), the system immediately reboots without prompt or warning. 

I believe this is because the exit code is 1641.

The SCCM client, using the Application model, seems to react to 1641 with an immediate reboot. May I recommend it be changed to 3010? 3010 is the return code after installing the desktop client.

3010 would make more sense, too, because the prompt after manually uninstalling or installing asks for a reboot, which is the definition of the 3010 exit code. i.e. reboot requested. Whereas the definition for 1641 means reboot initiated.

### Steps to reproduce
1. Install ownCloud-2.7.6.3261.x64.GPO.msi
2. Create an SCCM application where the uninstall string is: 
```
msiexec /x ownCloud-2.7.6.3261.x64.GPO.msi REBOOT=ReallySuppress /qn
```

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: 2.7.6.3261

Operating system: Windows 10 20H2

OS language: en-us

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\Program Files

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by BerndBeutner** [comment]
We checked this problem.
With manual installation/removal, the Exitcode ist 3010 (as expected and designed).

In an SCCM environment, the MSI exitcode is 1641 due to an Error in SCCM / MSIEXEC.

Microsoft classified this problem as a known error (version 1906 and up). The problem will be adressed in a future patch... 20xx..

There is no solution to this problem by changing the OwnCloud MSI.

Possible workarounds:
- Use a wrapper, to track the exitcodes in SCCM
- Define a exception rule in Configuration Manager to handle the exitcode.

Please check further information in different discussions like:
- https://social.technet.microsoft.com/Forums/en-US/8f2eddab-c9cc-4405-841d-91bd8c47efed/msiexec-return-code-3010-becomes-1641?forum=configmanagerapps
- https://stackoverflow.com/questions/61089313/my-installer-package-throws-3010-or-1641-when-run-from-sccm-works-fine-if-i-run

**Comment by codaamok** [comment]
To clarify, you believe this will be fixed in a future release of SCCM or it has already been addressed in a 20xx release? If the latter, I disagree because I can reproduce this in a 2010 environment with latest HFRU. However if you mean the former, and instead should have said 21xx, then great thank you for the update.

**Comment by BerndBeutner** [comment]
Sorry, i don't know which SCCM release will correct this problem. I quoted an comment in MS Technet.
But when you can reproduce the problem in 2010 - so it will be 21xx earliest...

**Comment by michaelstingl** [comment]
@codaamok thank you very much for your feedback! Let us know if there's anything else we could improve to make automated deployments smoother.
