### ISSUE TITLE
Don't raise settings window when the client is invoced a second time without "--show-settings" (depends on #8377)

### ISSUE THREAD

**Issue by pulkin** [owncloud/client#8590]
... while there is no reason for it to behave like that. I remember this consistently happening across versions and distros for 4 years or so. I am mostly using Gnome.

**Comment by dragotin** [comment]
Same on KDE Plasma with version 2.7.6

**Comment by gabi18** [comment]
I see the 'Syn Activity Notifications' popping up after autostart of the client (openSUSE Leap 15.2, KDE Plasma 5.18.6).
 
Is this meant here or which window pops up?

**Comment by pulkin** [comment]
I see a full-blown window with buttons and account lists each time I start my machines.

**Comment by gabi18** [comment]
I cannot confirm this on my openSUSE 15.2 system.

Do you use Ubuntu 20.04?

**Comment by pulkin** [comment]
Currently Fedora 33 and 34.

**Comment by TheOneRing** [comment]
Might be multiple invocations caused by auto start and session restore.
https://github.com/owncloud/client/blob/master/src/gui/application.cpp#L554

**Comment by pulkin** [comment]
I vaguely remember a discussion about window popping up in case `owncloud` is invoked multiple times after login. But I was never able to confirm it. Currently, removing the autostart checkbox in the client will make the client not start up automatically, as expected.

**Comment by jnweiger** [comment]
Tested on Ubuntu 20.10, autostart includes the ownCloud desktop client, I cannot confirm either:

![image](https://user-images.githubusercontent.com/1108546/116885000-ae208180-ac27-11eb-8984-fd89fe41e4e2.png)

On a reboot, the desktop client comes up, but only the small tray icon. The full blown settings window is not shown unless I click the icon, or trigger the client manually.
Tested with both ownCloud client 2.7.1 and 2.8.0RC1

**Comment by jnweiger** [comment]
On a Fedora 33, I have ownCloud client 2.7.2 in autostart. I can confirm the issue:
Upon logout/login, or reboot/login the client opens its settings window.

**Comment by TheOneRing** [comment]
I guess ubuntu != gnome

**Comment by jnweiger** [comment]
> I guess ubuntu != gnome

Both my Ubuntu 20.10 and my Fedora 33 run Gnome 3.38.x

**Comment by fmoc** [comment]
Can either of you please provide a screenshot for reference?

**Comment by fmoc** [comment]
Reproducible in a Fedora 34 VM with 2.7.6 (Fedora 33 package):

![grafik](https://user-images.githubusercontent.com/80399010/118294302-1b56d100-b4ca-11eb-8fe6-ec11bd3bf139.png)

Just logged out and logged in again.

The issue is not limited to autostart, you can also just close the client and open it again. The main UI is always shown then. This makes sense, as the desktop entry in `~/.config/autostart` also just calls `/opt/ownCloud/ownCloud/bin/owncloud`. It's almost like `_showSettings` was set to `true`. This makes little sense, as on `2.7` (like in `master`), its initial value is set to `false`, and is only overwritten if `--showsettings` is passed. Also, I am relatively sure the settings dialog isn't triggered via the socket API, as there's a 10 seconds period after the startup in which such requests are ignored.

Looking explicitly for calls to `showSettingsDialog`, I found the most likely issue: the system tray is not available on GNOME, and the existing filter only checks for Ubuntu, not Fedora. In this case, `main` force-shows the settings dialog. This same code still exists in `master` (which I have not tried yet).

https://github.com/owncloud/client/blob/38ba32c380f750ea9ca7093ec885aaad444a14f0/src/gui/main.cpp#L152-L160

Related issues: https://github.com/owncloud/client/issues/6518 https://github.com/owncloud/client/issues/4693 https://github.com/owncloud/client/pull/4747

Commits related to workaround:
- https://github.com/owncloud/client/blame/0da2adcbe02eb9499e90622ca60a726ba75d0188
- https://github.com/owncloud/client/commit/3169833cd78335d23d2b5f08d8a0ca852998e070 (regression was likely introduced here)
- https://github.com/owncloud/client/blame/a2b817f0c0ec00ce7755092a2d562e5535940fbf
- https://github.com/owncloud/client/commit/5639572ef3979413d6b78a5e1779f5a8e522e975
- https://github.com/owncloud/client/commit/18a58f73de4f566ae65e6ba20586364419696f45 (filter originally introduced to work around missing system tray on Unity)


This issue has been around for many, many years already. I don't think adding additional filtering on distros/DEs is a good idea. We have to re-engineer the system tray handling. I am relatively sure the issue exists on all GNOME(-based) desktops, regardless of the distribution.

**Comment by TheOneRing** [comment]
Yes that sounds pretty reasonable.
As you can nowadays use the desktop entry actions or just reinvoke the client there is no reason to force show the window.

**Comment by TheOneRing** [comment]
I think we should remove that behaviour once we implemented https://github.com/owncloud/client/issues/8377
