### ISSUE TITLE
Don't set locale if we use system default language

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8608]
When not specifying the language we should keep the systm locale.

@michaelstingl

**Comment by fmoc** [comment]
That's already the case, isn't it? The order is: `--language`, config, theme, system.
 
Can you provide an example when this is not working?

**Comment by TheOneRing** [comment]
The system locale settings are German, the default language is Englisch and we set locale to eng.

**Comment by fmoc** [comment]
I can't reproduce this on my host. My system locale is `de_DE`, thus `QLocale::system().uiLanguages()` yields `de-DE`. As I have not set `--language`, the language is set to "use default" in the settings and the default theme doesn't set a default locale either, the list of choices is `de-DE`. Therefore, the `de` translation is loaded in the end.

I need more information. Version/commit, OS (including version), config screenshot.

**Comment by michaelstingl** [comment]
`ownCloud-2.9.0-daily20210506.4074.pkg` on macOS Big Sur 11.3.1

On my system, I use English language with German region:

![CleanShot 2021-05-06 at 18 36 14@2x](https://user-images.githubusercontent.com/214010/117334186-fb0b8e80-ae99-11eb-95f2-8d85ab8fb3e7.png)

![CleanShot 2021-05-06 at 18 36 46](https://user-images.githubusercontent.com/214010/117334236-0a8ad780-ae9a-11eb-9afe-32cf1e23e5dd.png)

![CleanShot 2021-05-06 at 18 37 09](https://user-images.githubusercontent.com/214010/117334374-360dc200-ae9a-11eb-8b71-fc164065e4b7.png)

**Comment by TheOneRing** [comment]
We must skip https://github.com/owncloud/client/blob/master/src/gui/application.cpp#L768 in case we use default locale.
Maybe we should also note that changing the langugage affects the locale?

**Comment by fmoc** [comment]
I'm not sure Qt makes a difference between the language and region. It likely depends on how the region is encoded into the locale that Qt receives, I suppose. We'd have to have a look at the value of `QLocale::system()`.

The issue might arise from us force-creating a fresh locale from `QLocale::system().uiLanguages()`. Perhaps we can just use `QLocale::system()` directly? I suppose this needs some thorough testing, because we still need to find the right translation file. I guess we just have to make sure to call `QLocale::setDefault` when we deviate from the system locale.

**Comment by fmoc** [comment]
Looking into `QLocale`, I think we might just be able to use `QLocale::system().country()` when constructing the `QLocale`.

By the way: @TheOneRing suggested we might need a region/country setting in the future.
