### ISSUE TITLE
[FEATURE REQUEST] Debian 11 build

### ISSUE THREAD

**Issue by ddellarocca** [owncloud/client#8773]
Are there any plans for a debian 11 build?
Atm i'm not able to use desktop client in my pc.

**Comment by michaelstingl** [comment]
Debian 11 wasn't released yet:
https://wiki.debian.org/DebianReleases

Starting with 2.9, ownCloud will provide additional AppImage builds. You can already test them and provide feedback:
https://download.owncloud.com/desktop/ownCloud/daily/2.9/linux-appimage/?sort=time&order=desc

**Comment by ddellarocca** [comment]
Yes, debian 11 isn't released yet but most of debian users are running the testing version, and for debian 11 freezing began in january, maybe i can try to build it myself, i don't really like appimage package.

**Comment by fmoc** [comment]
> most of debian users are running the testing version

I would challenge that claim. `testing` is only used by a small subset of users, the ones who are generally more tech-savvy and/or need newer versions than available in `stable`.

You can build the client yourself of course, I think `testing` ships with Qt 5.15 at the moment. But using the AppImage is significantly less effort.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Debian 11 "Bullseye" is was in developend arround 2 years and the deadlines are communicated open and early enough. You had time to create a ownCloud Debian 11 client (and its repo) at the time when "Bullseye" becomes stable (last weekend). This is frustrating. You should spent more love to Debian users. ;)

AppImages are never a choice for Debian users because of security reasons.

It is acceptable if you are not willing to pay your own debian repo maintainer and simply offer your own deb-repo. But there is none.

So Bullseye is out and stable. What is your timeplan?

**Comment by michaelstingl** [comment]
> So Bullseye is out and stable. What is your timeplan?

Maybe we can add it later this week…

**Comment by fmoc** [comment]
> AppImages are never a choice for Debian users because of security reasons.

Do you have real arguments to found this claim? The AppImages ship the exactly same binaries, built on the exactly same systems. In fact, the opposite is true.

Let me give you an example: By adding our Debian repository, you allow our repository to install any kind of packages. What if we added a malicious kernel to our Debian repository? `apt` would install that just fine. With AppImages, this can't happen, for instance. But that's just the first and most obvious difference.

The AppImages we provide are in no way less secure than the Debian packages we provide. You have to trust a third party anyway. At least AppImages don't require `root` access and modifications on your system. They just work.

> You had time to create a ownCloud Debian 11 client (and its repo) at the time when "Bullseye" becomes stable (last weekend).

We are working on this, but we use other projects (e.g., openSUSE build service), which just recently added the new version. There has been no ownCloud client release since the Debian 11 release. We are working on adding support for the new Debian release already.

> It is acceptable if you are not willing to pay your own debian repo maintainer and simply offer your own deb-repo. But there is none.

You don't seem to know how Debian package maintenance really works...

> So Bullseye is out and stable. What is your timeplan?

Soon client 2.9.0 will be released. We are going to support Debian 11 by then.

**Comment by olifre** [comment]
> Do you have real arguments to found this claim? The AppImages ship the exactly same binaries, built on the exactly same systems. In fact, the opposite is true.

I doubt this bugtracker and this bug is the best place to discuss AppImage vs. classical packaging. But at least let me add one comment to your reply, that also helps to keep Mr. stale-bot at bay. 


> The AppImages we provide are in no way less secure than the Debian packages we provide. You have to trust a third party anyway. At least AppImages don't require `root` access and modifications on your system. They just work.

This is very true, you have to trust an additional third party. But leaving trust aside, AppImages are similar to the [modern packager's security nightmare](https://blogs.gentoo.org/mgorny/2021/02/19/the-modern-packagers-security-nightmare/) for a different reason: They bundle dependencies. If there's a CVE e.g. affecting OpenSSL, I can not rest assured that my system is patched after running `apt` to get it updated. I also have to update any AppImage, and in addition trust all these third parties to include the newest binaries. 

From your reply, I read that you always built against the latest libraries shipped with Debian. But keeping two versions of libraries often affected by security issues on a system increases the attack surface (and resource usage). 

> Soon client 2.9.0 will be released. We are going to support Debian 11 by then.

Thanks, that's great to hear!

**Comment by TheOneRing** [comment]
> 
> 
> > Do you have real arguments to found this claim? The AppImages ship the exactly same binaries, built on the exactly same systems. In fact, the opposite is true.
> 
> I doubt this bugtracker and this bug is the best place to discuss AppImage vs. classical packaging. But at least let me add one comment to your reply, that also helps to keep Mr. stale-bot at bay.
> 
> > The AppImages we provide are in no way less secure than the Debian packages we provide. You have to trust a third party anyway. At least AppImages don't require `root` access and modifications on your system. They just work.
> 
> This is very true, you have to trust an additional third party. But leaving trust aside, AppImages are similar to the [modern packager's security nightmare](https://blogs.gentoo.org/mgorny/2021/02/19/the-modern-packagers-security-nightmare/) for a different reason: They bundle dependencies. If there's a CVE e.g. affecting OpenSSL, I can not rest assured that my system is patched after running `apt` to get it updated. I also have to update any AppImage, and in addition trust all these third parties to include the newest binaries.

We already provide our own 3rd party libraries as we require a decent version of Qt, nothing you can take for granted on lets say a centos.

Yes, our app image provide openssl, but is our openssl from last month really worse than an openssl from 2017 (again centos).

> 
> From your reply, I read that you always built against the latest libraries shipped with Debian. But keeping two versions of libraries often affected by security issues on a system increases the attack surface (and resource usage).
> 
> > Soon client 2.9.0 will be released. We are going to support Debian 11 by then.
> 
> Thanks, that's great to hear!

**Comment by TheOneRing** [comment]
And if you ask linus we should link everything statically as shared libraries are bad in his opinion, I'd stick with appimages.
If you don't trust us, please ask your distros maintainers to provide a decent ownCloud version with your system libs.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> You don't seem to know how Debian package maintenance really works...

I do. You (as upstream) can "maintain" your own package if you have a mentor/patron doing the "sensible stuff" for you.

It is not up to the Debian core devs to create a Debian stable package for you. It is just up to you. If you do not show interest in this topic then they won't show interest in you.

**Comment by olifre** [comment]
> We already provide our own 3rd party libraries as we require a decent version of Qt, nothing you can take for granted on lets say a centos.
> 
> Yes, our app image provide openssl, but is our openssl from last month really worse than an openssl from 2017 (again centos).

My point was not about the release date of the libraries — a more recent OpenSSL release is not necessarily affected by less security issues than an older one which has received security patches backported by distribution maintainers. 
My comment was about "having two OpenSSL libraries on your system increases the attack surface", and I think that is something we can all agree on. And yes, that means I also disagree with the point that everything should be statically linked (compared to this, AppImages have distinct advantages). 

In any case, getting a recent build for Debian 11 by you on OBS will solve this request, since this will use the system libraries (as far as possible given Qt requirements). An effort to contribute to a Debian package would still be appreciated, but that's naturally also a question of available manpower.

**Comment by fmoc** [comment]
Debian 11 has been added to the daily builds: https://download.owncloud.com/desktop/ownCloud/daily/2.9/linux/Debian_11/

Closing as resolved.
