### ISSUE TITLE
Return boolean in OC_ASSERT and handle the result

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8798]
Our macro OC_ASSERT  behaves line a normal ASSERT in debug builds and only prints an error in production builds.
As the macro is used to validate a state it should return a boolean in production builds as without handling the condition the client will most probably die ungracefully otherwise.

**Comment by dragotin** [comment]
I am not sure. If you "enhance" OC_ASSERT like that, maybe it is better to solve the situation in the concrete code directly and handle the critical situation. For me that sounds like too much for an assert. Not sure.

**Comment by TheOneRing** [comment]
Yes but we use it in a lot of places that never should be reached. Those should be replaced by a real assert I guess as they should just never happen.

**Comment by fmoc** [comment]
Perhaps you should then add a new construct rather than changing the meaning of a debug macro in order to not confuse future readers of the code. I could image adding a macro that just shows an error message and exits (for critical issues), for instance.

The existing `OC_*` macros should probably also log whenever they fail in production, maybe even on a warning/critical level.

**Comment by TheOneRing** [comment]
Thats what the existing macro does, it logs the assert message as critical.
But in most cases we just continue to execute the code which absolutely does not make any sense.

**Comment by fmoc** [comment]
If you really want to tackle that issue, you will have to change that macro into some sort of "crash-with-nice-message". But there is a risk that users, in special cases, will be bombarded with error messages. I'm not sure whether that's better from a UX point of view, even if it's desirable from a developer point of view. Another risk is that developers might tend not to use the macro at all any more then in order not to bug the users.

I'm all in for "crash-with-nice-message", but you can expect at least a week of either fixing the root cause or handling the asserted condition more gracefully. It will be worth the effort, though, because in the end it will result in a better product, and users might not end up in unexpected states any more without noticing, causing undefined behaviour of the client. You can then also distinguish better between true edge cases, "things that need to be handled properly", and (likely) some false positives.

I don't think that just returning the result of an asserted condition makes any sense, though. That would make it opt-in rather than opt-out. In that case, you can also just ignore the macro's existence and implement a normal `if` directly.

As a side note, in some cases I've encountered so far, the macro is used wrongly anyway. One should assert conditions that can be expected to never happen other than edge cases, causing one to not implement specific handling for these, but instead making sure that they will be detected. For that reason, I don't mind having asserts enabled in production builds. But I'm also into Design by Contract, which is heavily based on asserts.

**Comment by TheOneRing** [comment]
What I actually mean is:
```
if(OC_ENSURE(foo)){
    return ERROR;
}
```
I don't care whether its calles `OC_ASSERT` or what ever.
Currently the assert is uses in the wrong way.
If  we reach a point of no return rather use `OC_ENFORCE` to crash with the error message and not 3 lines later with a nullpointer reference.

Use `OC_ENSURE` to handle unwanted edge cases, to crash in development and to warn in production.

**Comment by TheOneRing** [comment]
Please have a look on the poc in https://github.com/owncloud/client/pull/8802

**Comment by TheOneRing** [comment]
We got the new macro and started using it.
