### ISSUE TITLE
Simplify linux install instuctions by retreving the os release version automaticall

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8903]
`/etc/os-release` should provide us with the version needed.

The current list is more complicated than needed.
![image](https://user-images.githubusercontent.com/200626/129697360-a02feea2-0307-47fb-bb65-16364e172d39.png)

@dschmidt  @jnweiger @fmoc

**Comment by jnweiger** [comment]
The Download installer script was an attempt to evaluate /etc/os-release . -- untested.

**Comment by fmoc** [comment]
Distros have failed so far to provide a reliable cross-distro mechanism to let us query such details. `/etc/os-release` might work on many distros (it's a FreeDesktop standard, as far as I know), though.

If we opt to use that file, we should change the repository names to make it easier to use the data within there. We don't want to parse the contents, because that'll easily increase the length of the commands quickly, which can lead to issues as well.

For reference, here's an example file:

```sh
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Putting together a string like `Ubuntu_20.04` requires parsing two values already, and we have to strip the quotes from one of them.

In any case, all commands will require validation on all releases. The `/etc/os-release` has many different keys and they might not be available universally...

**Comment by dschmidt** [comment]
You don't need to parse `/etc/os-release` manually, you can just `source` it.
```bash
docker run -ti ubuntu:20.04 bash -c 'source /etc/os-release && echo "${NAME}_${VERSION_ID}"'             
Ubuntu_20.04
```

**Comment by TheAssassin** [comment]
We probably want to do that in a shell command anyway. Not every user uses the distro's standard shell. By running it like `sh -c '...'`, we make sure the commands are run in a bourne compatible shell.

**Comment by TheOneRing** [comment]
Not planned
