### ISSUE TITLE
"multiple accounts" misleading error message

### ISSUE THREAD

**Issue by thommierother** [owncloud/client#9110]
Client 2.9.0 shows error message about "multiple accounts using the same sharing folder" although there is only one account configured using THIS main folder. Client only has one account configured.

### Expected behaviour
no error message.

### Actual behaviour
misleading error message displayed

### Server configuration
ubuntu server 18.04

Web server: 
apache

Database:
mariadb

PHP version:
7

ownCloud version:
10.8 classic

Storage backend (external storage):

### Client configuration
Client version: 2.9.0

Operating system:
openSUSE Tumbleweed 

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):
ownCloud 2.9.0 Sep 9 2021 00:00:00
Libraries Qt 5.15.2, OpenSSL 1.1.1l 24 Aug 2021
Using virtual files plugin: suffix
opensuse-tumbleweed-5.14.6-1-default
![Screenshot_20211002_100333](https://user-images.githubusercontent.com/6594120/135708902-8e86cefa-9e61-4324-85ec-ab5c611ccb3d.jpg)

**Comment by TheOneRing** [comment]
The issue is caused by a migration bug, at some point the client created a new database, which result in an old db still being present in the folder.
We you the existence of `.sync_XXXXX.db` files as a way to detect the usage of the folder by different clients(ownCloud, testpilotcloud etc).

If you look into your sync root you will have multiple `.sync_XXXX.db` files. You can safely move the one with the oldest modification date to a backup folder.

We are working on a documentation (https://github.com/owncloud/docs-client-desktop/pull/123)  of the issue (and have fixed the migration bug, even so it might be a bit late for most users).

**Comment by thommierother** [comment]
I had an old sync db from 2019:

-rw-r--r--  1 thommie users  5578752  2. Okt 17:47 .sync_9f32efa93320.db
-rw-r--r--  1 thommie users    32768  4. Okt 09:36 .sync_9f32efa93320.db-shm
-rw-r--r--  1 thommie users  4309552  4. Okt 09:36 .sync_9f32efa93320.db-wal
-rw-r--r--  1 thommie users  2412544 24. Nov 2019  ._sync_c90562aaaae8.db

Removing it solved the error msg.
