### ISSUE TITLE
cannot access '/var/lib/apport/coredump/' in drone

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9259]
Backtracking has been implemented in https://github.com/owncloud/client/pull/9235. And while backtracking the AUT crash, we need to locate coredump file. This file is normally inside `/var/lib/apport/coredump/` but we can not locate it in drone. Hence, the backtracking is not functioning properly in drone. 

For more details, see this drone build https://drone.owncloud.com/owncloud/client/9922/5/13

### Screenshot
![Screenshot from 2021-12-07 16-06-11](https://user-images.githubusercontent.com/27364813/145012463-8cc5245f-d1db-4ca2-b53c-814391edff9b.png)

**Comment by TheOneRing** [comment]
https://askubuntu.com/questions/1225821/how-to-get-coredump-from-process-crashed-inside-a-docker-container-using-apport ?

**Comment by Talank** [comment]
The settings required for apport looks good (same as that in my computer) but there is no such folder as `/var/lib/apport` inside docker container. May be, we can mount it to the volume of local machine.

Also, manually creating the missing folder did not work.

**Comment by Talank** [comment]
I tried installing systemd and apport. And also tried starting the apport service as in https://askubuntu.com/questions/1225821/how-to-get-coredump-from-process-crashed-inside-a-docker-container-using-apport.

The  `core_pattern` and the apport's settings at `/etc/init.d/apport` matches to the settings that we have in our local computer. However, the folder `/var/lib/apport` is missing where the coredump is supposed to be. And I could not find any solution.

In fact, we might be completely blocked in this issue, because we need to start docker in privileged mode so that it can write the coredump files.

**Comment by individual-it** [comment]
I cannot get the coredump from crashing oC client but works with other crashing apps
here is what I tried
1. changed squish docker so that squish is installed in the `/tmp` folder https://github.com/owncloud-ci/squish/pull/31/files (that is needed because we want to mount the home folder to the host)
1. build the changed container
1. on host create folder `/tmp/crash`
1. change permission `chmod 777 /tmp/crash`
1. on the host set `kernel.core_pattern` to the setting that is default in drone `sudo sysctl -w kernel.core_pattern=core`
1. inside the client folder on the host create a `crash.c` with the content
   ```
   int main()
    {
    return 1/0;
    }
    ```
1. build `crash.c`by `gcc -o crash crash.c`
1. run docker with `/tmp/crash` mounted to `/home/headless` 
    `docker run -it --rm --network=host -e LICENSEKEY='<squish license server URL>' -e MIDDLEWARE_URL='http://localhost:3000/' -e BACKEND_HOST='http://localhost/owncloud-core/' -e SERVER_INI='/app/test/gui/local/server.ini' -e CLIENT_REPO='/app/' -e SQUISH_PARAMETERS='--retry 1' -e SQUISH_NO_CRASHHANDLER=1  -v ${PWD}:/app -v /tmp/crash:/home/headless/ --name squish <docker container build in step 2>`
1. while the tests are running, run `crash` `docker  exec -it squish /app/crash`
1. on the host I can find a file called `core.<PID>` in `/tmp/crash`

That seems to work

**Comment by TheOneRing** [comment]
We also have a utility to crash https://github.com/owncloud/client/blob/172bed9a4eed5468197626b99fe88892f72a7592/src/common/utility.cpp#L342-L342

@dschmidt any idea why the crash in the client does not create a dump?

**Comment by dschmidt** [comment]
Not really, maybe related to breakpad?

**Comment by TheOneRing** [comment]
we don't build with breakpad when using squish

**Comment by phil-davis** [comment]
@Talank is this still blocked?
Can we write a reason that it is blocked? Or how to progress? Or close if there is no solution?

**Comment by Talank** [comment]
We are still not sure if we could achieve this objective. We shall investigate further about it this week, and we will try to make a decision, even if it can not be solved now.

**Comment by saw-jan** [comment]
Implementation PR merged. Closing!
