### ISSUE TITLE
When password protecting a previously created public link displays password policy error, the checkbox will be unchecked

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#9336]
### Steps to reproduce
1. Enable `Password Policy` app on the server 
2. Set minimum password characters to `8` for public links (from Settings -> Admin -> Security)
3. From desktop-client, open public link sharing dialog for a file and create a public link share
6. Edit previously created public link
7. Enable (check) `Password protect` and enter password `1234` 
8. Click `Set password` 
(throws error `The password is too short...` and the checkbox will get unchecked but password filed can be edited)

### Expected behavior
expected `Password protect` checkbox to be checked

### Actual behavior
`Password protect` checkbox will get unchecked

![pp01](https://user-images.githubusercontent.com/52366632/148367078-c5794ac6-256f-4659-91ca-e1b3405e9603.png)
![pp02](https://user-images.githubusercontent.com/52366632/148367101-d5d4e4a3-d7bc-4bce-aa41-fd197d3f4091.png)

### Client configuration
Client version: `2.10.0rc3.6436`
Operating system: `win10x64`

**Comment by fmoc** [comment]
I tested the dialog a bit. Seems like keeping the checkbox checked and the password field filled with the old value is what we do when creating new shares, too. The only difference there is that we do not (have to?) disable the close button there, since the link just hasn't been created.

I'm actually in favor with moving the editing controls into a secondary dialog. IMO this increases the usability, since with a modal dialog one cannot change to another entry in the list for instance while the other one's changes are sent to the server (IMO a "save"/"commit" button is missing anyway for editing, changes should be done in a "transactional" way). What do you think?

For a short-term fix, I'm evaluating the first option which will be easier to implement. But long-term, I'd like to rework the share dialog.
