### ISSUE TITLE
Qt6: Investigate replacing jhash with qHash

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9352]
In Qt6 qHash is also int64

https://github.com/owncloud/client/blob/bfa988779de6fc08edf905f0d3780dd3db893af2/src/common/syncjournaldb.cpp#L358

**Comment by fmoc** [comment]
Does `qHash` return the same value? It doesn't seem like `qHash`'s algorithm was documented. There are no guarantees made in the docs whether the algorithm is going to be stable (it is implied for `QPair`'s algorithm that it could not use the same algorithm as `QHash`'s because of this, though). It might be easier to use `QCryptographicHash` instead, whose algorithms are standardized and well known.

If it doesn't, we'd have to keep track of the algorithm used to create the has (I think that would be a good idea anyway, and is done in modern password databases, too).

**Comment by TheOneRing** [comment]
Qt5: crc32 https://github.com/qt/qtbase/blob/v5.15.2/src/corelib/tools/qhash.cpp#L213
Qt6: it depends https://github.com/qt/qtbase/blob/dev/src/corelib/tools/qhash.cpp#L769

**Comment by TheOneRing** [comment]
> It bears repeating that the implementation of qHashBits() - like the qHash() overloads offered by Qt - may change at any time. 
> You must not rely on the fact that qHashBits() will give the same results (for the same inputs) across different Qt versions.

**Comment by TheOneRing** [comment]
qHash would not work as its not guaranteed to be stable.
Anyway this is low priority....
