### ISSUE TITLE
can not get GUI test result in both html and json format

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9454]
In squish, we can not get gui test result in both html and json format. While uploading the failed CI result and rendering through web browser, it is nice if we use the the result in html. However, we designed the gui test result parser in according to the json result. I have requested squish for the feature update, but, until it is implemented in squish, we have to disable the `showGuiTestResult` in drone.

we can re-enable it also if we find some other method to reuse the log parser. For instance, the html report stores the necessary data in a js file inside data directory. Although the data is not the same as that of json result, we might be able to fit the test result parser accordingly.

**Comment by TheOneRing** [comment]
Would it be possible that you upload the results anyhow and print the message that usually goes to a comment in the ci?
That way we could check the results also in the nightly run.

**Comment by saw-jan** [comment]
HTML report is sufficient now and also the github comment feature is disabled/removed. PR builds have logging step in the GUI pipeline which tells from where the logs can be accessed. Nightly build notification provides the URLs to the report and other logs whenever there's a test failure. So, I didn't see the need for json report.
Therefore closing the issue here.
