### ISSUE TITLE
GPG sig errors on Ubuntu 20.04

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9476]
![image](https://user-images.githubusercontent.com/214010/156010620-8ca035ff-2809-46d6-bfaf-01f185853b8b.png)

(Source: https://twitter.com/w_mccan/status/1497586282427559941)

**Comment by fmoc** [comment]
The only scenario that could lead to such an issue which I can come up with (without any further information, I can only guess) is the following:

1) user adds repository a couple of years ago (importing the key for the first and only time)
2) user kept using the `latest` repository ever since, and keeps upgrading
3) now, the key imported in 1) has reached its expiration date

The user must have never reimported the key upon new releases. We do (AFAIK) not tell users anywhere that the key expires after X years, and needs to be re-downloaded and re-imported every now and then.

The easiest solution is to rerun the import command from  https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/:

```sh
> wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/Release.key -O - | sudo apt-key add -
```

That'll download the (since extended) key and updates the existing in the user's apt keyring.

Alternatively, the updated key can be fetched from the keyservers:

```sh
> apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0700205DFD41A71A
Executing: /tmp/apt-key-gpghome.sVZkF4CIYm/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 0700205DFD41A71A
gpg: key 0700205DFD41A71A: public key "devel OBS Project <devel@s2.owncloud.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

I recommend the first approach, though.

**Comment by fmoc** [comment]
I think we can close this issue, unless we hear from the reporter.
