### ISSUE TITLE
New Wizard uses wrong FileDilaog

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9688]
When selecting the sync destination the Wrong file dialog is used.
Please use the same as the FolderWizard.

Folder Wizard:
![image](https://user-images.githubusercontent.com/200626/168860266-4bc37948-c02a-4c19-bae1-6e4b71f425aa.png)

Wizard:
![image](https://user-images.githubusercontent.com/200626/168860367-4234c844-6653-4a21-b134-e7d8688a926f.png)

**Comment by fmoc** [comment]
The folder wizard uses `QFileDialog::getExistingDirectory`, which apparently spawns a new event loop. Since we want to avoid that in the future, we create the dialog ourselves in the wizard:

https://github.com/owncloud/client/blob/1b87c9eabc81570fbc41ede6a8b8c930243db9d9/src/gui/newwizard/pages/accountconfiguredwizardpage.cpp#L71-L82

I don't see why this should make such a big difference look wise...
