### ISSUE TITLE
New wizard Branding

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9701]
- [ ] Theme::userIDType
- [ ] ...

**Comment by fmoc** [comment]
The following options are deprecated now:

- `wizardHeaderBanner` (we use a single-color background now; might be revived, but only for the entire wizard content then)
- `wizardHeaderSubTitleColor`
- `wizardHideFolderSizeLimitCheckbox` (we no longer offer this option in the wizard, since it is a global setting)

Might be missing (not sure if we need any of these any more):

- `wizardHideExternalStorageConfirmationCheckbox`

**Comment by fmoc** [comment]
`Theme::instance()->overrideServerUrlV2()` is still missing.

**Comment by gabi18** [comment]
It seems that `wizardUrlHint` is also missing.

There is no hint in the server input field of 3.0.0 (git master from 21.6.2022) btr client despite QString wizardUrlHint() const { return QStringLiteral("https://demo.owncloud.org"); } is set.

![noServerUrlHint](https://user-images.githubusercontent.com/75983861/174790311-b7a59fb6-e99e-4a35-8e32-4ba22e9d0f2e.png)
