### ISSUE TITLE
client 1.4 unnecessarily downloads again those files which are already downloaded

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/client#994]
A user shared with me a folder with about 10 10 GB data (approx. 200 files).

I don't know why, but it's often (not always) finding some new files. Download follows - but unnecessarily: files are absolutely identical (byte comparison); the file on server hasn't been touched for months. So the file hasn't changed.

Following suggestions:
1. Finding and fixing the reason why the client trys to re-download equal files which hasn't been changed/updated in any way
2. Before downloading files: download a hash of the file from server for that file + check if hash can be found in local journal database + if yes: copy the file locally

Local client: 1.4.0 on Win2008 R2 server (and other win systems, too)
Server version: 4.5.7 on Linux

**Comment by seiferflo** [comment]
Hey. I just resumed another folder and it happened again, quite annoying. I've got 3 machines to sync with this afterwards and It scares me now. 
Any idea how I am supposed to this between Windows & a Synology please?

**Comment by seiferflo** [comment]
@inducer Hey. I just resumed another folder and it happened again, quite annoying. I've got 3 machines to sync with this afterwards and It scares me now. 
I've put windows & synology on the same time server to get the same clock. I restarted everything, remove the db and the problem is still there. When you're saying rebuild the cache, is there any other method than deleting the db? Thanks

**Comment by AiYoriAoshi** [comment]
I have the following setup:
C:\ and E:\ Partition on SSD, not synced by owncloud
D:\ RAID5 Partition on Raidcontroller with 3x1.5TB drives completely synced with owncloud

A few days ago I re-installed my windows while the raid controller was not plugged in so no data is touched on the owncloud partition. After the installation I plugged in the raid and then I installed the owncloud client and set it up with my server. Now the client says some 105GB need to be synced and started downloading them from the server. The files it downloaded so far all exist on the disk and have not been touched in years. 

I have no idea which files it actually want's to sync and why. I checked and the time on server and client are perfectly sync. 

Server: 8.0 (just upgraded from 7.0.2 to see if it makes a difference, nope)
Client: 1.7.1 build 4382 Windows 7

**Comment by karlitschek** [comment]
It seems that ownCloud detected your files as changes. This can be cause by a changes timestamp of the files or the mountpoint.

**Comment by RandolfCarter** [comment]
Just happened again to me after upgrading to OC 8.0. Could this be related to https://github.com/owncloud/core/issues/13980 ? I did have to fiddle around in the storage table to get the upgrade working, not sure if I removed the correct entries there...

**Comment by seiferflo** [comment]
And again...
Turned on my Synology after a while with ownCloud 8.0.3. I started windows client 1.8.0, resume my usual folder and it downloads useless stuff that hasn't changed again.
On top of that All files are "Downloaded, renamed conflicting file". 

Both machines are clocked on the same time.nist.gov server. 
I even tried with the 1.8.1RC2 and deleted all temp files from my folders. 

I don't understand and I'm having this problem since I'm using ownCloud 7 and client 1.7.1 everytime.
Same behaviour, it starts by downloading files, 1 to 200 sometimes, then it stops downloading and just upload if any. If nothing to upload, it stops and moves to other folder. Same behaviour for that folder too.
If I keep the client & server on all the times, it will not download again. 
But I turn both off for a bit, to save electricity I guess, then all folders will download a few files. 

Why ownCloud detect the files as changed when they are not? I'm sure of that because I sync the folders on my external HDD using size & time change. 
Have you solved this issue yet? Thanks for your feedback.

**Comment by PVince81** [comment]
@seiferflo it is still not clear why the files are being redownloaded.
What you could try is the following:
1. Wait for the sync client to be stable (no download) like when you keep it on for a long time.
2. Shut down the web server to prevent further access
3. Check the `oc_filecache` table in the database, maybe save the listing of some of the files. Goal is to find out their "etag", "mtime" and "storage_mtime" columns.
4. Check the files in the "data" directory and see what mtime they have, save the listing in a file.
5. Stop the sync client
6. Reboot the Synology
7. Let the web server start (but not the sync client).
8. Check the "data" folder and verify that the mtimes are still the same
9. Check the database again and compare the "etag", "mtime" and "storage_mtime" columns with what you saw before (for a few select files)
10. Start the sync client, stop it after a while (hopefully it will not upload anything yet)
11. Check the database again like at step 8

Goal is to find out if anything causes the "etag" or "mtime" fields in the database after the Synology reboot.

You might also want to try disabling cron jobs and see if it solves the issue. (if yes, the cron job might be a clue).
